import test from 'node:test';
import assert from 'node:assert/strict';
import {BehaviorRuntime,validateBehaviorGraph} from '../src/behaviors.js';
import {createDrawing} from '../src/vector-authoring.js';
const fixture=()=>{const d=createDrawing(),a=d.actors[0],p=d.packs[a.pack],root=p.joints[0].id;p.clips.work={duration:2,loop:true,tracks:{[root+'.x']:[[0,0,'linear'],[2,20]]}};p.clips.fail={duration:1,loop:false,tracks:{[root+'.x']:[[0,0,'linear'],[1,-10]]}};d.actors.push({...structuredClone(a),id:'other'});const recipe={actor:a.id,variants:[{id:'normal',clip:'work',weight:1,speed:{min:1,max:1},offsets:{[root+'.x']:{min:5,max:5}}}],success:{base:1,modifiers:[]},onStart:[{type:'add',variable:'starts',value:1}],onSuccess:[{type:'add',variable:'wins',value:1},{type:'event',event:'done'}],onFailure:[{type:'add',variable:'losses',value:1}]};d.behaviorGraph={seed:17,variables:{starts:0,wins:0,losses:0,fatigue:0},variableBounds:{fatigue:{min:0,max:1}},activities:{work:recipe,other:{...structuredClone(recipe),actor:'other'}},initial:'idle',states:{idle:{actions:[]}},handlers:[{event:'go',actions:[{type:'perform',activity:'work'}]},{event:'other',actions:[{type:'perform',activity:'other'}]}],edges:[]};return {d,actor:a.id,key:root+'.x'};};
const run=r=>{r.dispatch('go');r.tick(0);};
test('activities run independently per actor, ignore busy requests and execute effects once',()=>{
 const {d,actor,key}=fixture(),r=new BehaviorRuntime(d);run(r);run(r);assert.equal(r.variables.starts,1);r.dispatch('other');r.tick(0);assert.equal(r.variables.starts,2);assert.equal(r.actionPose(actor).pose[key],0);r.tick(1);assert.equal(r.actionPose(actor).pose[key],15);r.tick(1);assert.equal(r.actionPose(actor).pose[key],20,'looping source holds final endpoint, not its first frame');assert.equal(r.snapshot().actions[actor].active,false);assert.equal(r.variables.wins,2);r.tick(20);assert.equal(r.variables.wins,2);assert.equal(r.actionPose(actor).pose[key],20);assert.equal(r.cancelActivity(actor),true);assert.equal(r.actionPose(actor),null);assert.ok(r.actionPose('other'));
});
test('seeded choices, speed and offsets are sampled once and reset reproducibly',()=>{
 const {d,actor}=fixture(),v=d.behaviorGraph.activities.work.variants[0];v.speed={min:.5,max:1.5};d.behaviorGraph.activities.work.variants.push({...v,id:'second',weight:3});v.offsets[Object.keys(v.offsets)[0]]={min:-8,max:8};const a=new BehaviorRuntime(d),b=new BehaviorRuntime(d);run(a);run(b);for(let i=0;i<30;i++){a.tick(1/120);b.tick(1/120);assert.deepEqual(a.actionPose(actor),b.actionPose(actor));}const expected=a.actionPose(actor),snap=a.snapshot();a.reset();run(a);for(let i=0;i<30;i++)a.tick(1/120);assert.deepEqual(a.actionPose(actor),expected);assert.deepEqual(a.snapshot(),snap);const pose=a.actionPose(actor);pose.pose[Object.keys(pose.pose)[0]]=999;assert.notDeepEqual(a.actionPose(actor),pose,'callers cannot mutate held runtime pose');
});
test('failure variants use stats before start effects and numeric writes clamp bounds',()=>{
 const {d,actor}=fixture(),recipe=d.behaviorGraph.activities.work;recipe.success={base:1,modifiers:[{variable:'fatigue',weight:-1}]};recipe.failureVariants=[{id:'fail',clip:'fail',weight:1,speed:{min:2,max:2}}];recipe.onStart.push({type:'set',variable:'fatigue',value:-10});d.behaviorGraph.variables.fatigue=5;const r=new BehaviorRuntime(d);assert.equal(r.variables.fatigue,1,'initial numeric values clamp to bounds');r.setVariable('fatigue',100);assert.equal(r.variables.fatigue,1);run(r);assert.equal(r.variables.fatigue,0);assert.equal(r.actionPose(actor).variant,'fail');assert.equal(r.actionPose(actor).success,false);r.tick(.5);assert.equal(r.variables.losses,1);assert.equal(r.variables.wins,0);r.runActions([{type:'add',variable:'fatigue',value:100}],{});assert.equal(r.variables.fatigue,1);r.runActions([{type:'add',variable:'fatigue',value:-100}],{});assert.equal(r.variables.fatigue,0);
});
test('clip windows are finite, finish once, and offsets ease to zero at boundaries',()=>{
 const {d,actor,key}=fixture(),v=d.behaviorGraph.activities.work.variants[0];v.start=.5;v.end=1.5;v.speed={min:2,max:2};const r=new BehaviorRuntime(d);run(r);assert.equal(r.actionPose(actor).pose[key],5);r.tick(.025);assert.ok(Math.abs(r.actionPose(actor).pose[key]-8)<1e-9);r.tick(.475);assert.equal(r.actionPose(actor).clipTime,1.5);assert.equal(r.actionPose(actor).pose[key],15);assert.equal(r.variables.wins,1);assert.equal(r.snapshot().actions[actor].progress,1);
});
test('activity validation rejects references, recursion, malformed ranges and oversized data',()=>{
 const validate=d=>{const errors=[];validateBehaviorGraph(d,(ok,path,message)=>{if(!ok)errors.push(path+message);});return errors;};assert.deepEqual(validate(fixture().d),[]);
 for(const corrupt of [g=>g.activities.work.actor='missing',g=>g.activities.work.variants[0].clip='missing',g=>g.activities.work.variants[0].start=3,g=>g.activities.work.variants[0].end=0,g=>g.activities.work.variants[0].start=null,g=>delete g.activities.work.variants[0].id,g=>g.activities.work.variants[0].speed={min:2,max:1},g=>g.activities.work.variants[0].weight=Infinity,g=>g.activities.work.variants[0].offsets={'bad.x':{min:0,max:1}},g=>g.activities.work.variants=Array(17).fill(g.activities.work.variants[0]),g=>g.activities.work.onStart=[{type:'perform',activity:'work'}],g=>g.activities.work.success.modifiers=[{variable:'missing',weight:1}],g=>g.variableBounds.fatigue={min:1,max:0},g=>g.states.idle.actions=[{type:'perform',activity:'missing'}],g=>g.states.idle.actions=[{type:'add',variable:'missing',value:1}]]){const {d}=fixture();corrupt(d.behaviorGraph);assert.ok(validate(d).length,corrupt.toString());assert.throws(()=>new BehaviorRuntime(d));}
});

test('completion events carry the recipe actor and can schedule another bounded performance',()=>{
 const {d,actor}=fixture();d.behaviorGraph.handlers.push({event:'done',actions:[{type:'perform',activity:'work'}]});const r=new BehaviorRuntime(d);run(r);r.tick(2);assert.equal(r.variables.wins,1);assert.equal(r.variables.starts,2);assert.equal(r.snapshot().actions[actor].active,true);assert.equal(r.actionPose(actor).progress,0);r.tick(0);assert.equal(r.variables.starts,2);r.tick(2);assert.equal(r.variables.wins,2);assert.equal(r.variables.starts,3);
});
