import test from 'node:test';import assert from 'node:assert/strict';
import {ActorBehaviorRuntime,validateActorBehaviors} from '../src/actor-behaviors.js';import {SceneController} from '../src/scene.js';import {IllustrationController} from '../src/illustration.js';import {BehaviorRuntime} from '../src/behaviors.js';import {CampfireEnsemble} from '../src/ensemble.js';import {ScenePointerInteraction} from '../src/pointer-interactions.js';import {applyContacts} from '../src/contacts.js';import {createDrawing} from '../src/vector-authoring.js';import {createCampfire,convertCampfireCooking} from '../examples/campfire.js';import {assertDocument} from '../src/schema.js';
const options={actorBehaviorFactory:ActorBehaviorRuntime,behaviorFactory:BehaviorRuntime,ensembleFactory:CampfireEnsemble,pointerFactory:ScenePointerInteraction,contactSolver:applyContacts,checkpoints:{interval:.5}};
function fixture(){const d=createDrawing();d.packs.drawing.inputs={enabled:{type:'boolean',default:true},level:{type:'number',default:0,min:0,max:2}};d.actors.push({...structuredClone(d.actors[0]),id:'second'});d.requiredFeatures=['actor-behaviors'];d.actorBehaviors=d.actors.map((a,i)=>({id:'scope-'+i,actor:a.id,sensors:[{variable:'enabled',source:'input.enabled'}],outputs:[{variable:'counter',source:'input.level'}],rates:[{variable:'counter',perSecond:.2+i*.1,when:{variable:'enabled',op:'eq',value:true}}],graph:{seed:17+i,variables:{counter:0,enabled:true},variableBounds:{counter:{min:0,max:2}},initial:'idle',states:{idle:{actions:[]},ready:{actions:[]}},edges:[{id:'threshold',from:'idle',to:'ready',after:{min:.1,max:.1},when:{variable:'counter',op:'gte',value:.5},weight:1},{id:'restart',from:'*',to:'idle',event:'again',weight:1}],handlers:[{event:'again',actions:[{type:'set',variable:'counter',value:0}]}]}}));return assertDocument(d);}
test('actor graphs advance concurrently with independent signals, stats and scoped event routing',()=>{const c=new SceneController(fixture());try{c.seek(2);let s=c.frame().actorBehaviors;assert.equal(s[0].state,'idle');assert.equal(s[1].state,'ready');c.setInput('second','enabled',false);c.seek(3);s=c.frame().actorBehaviors;assert.ok(Math.abs(s[0].variables.counter-.6)<1e-8);assert.ok(Math.abs(s[1].variables.counter-.6)<1e-8);c.setActorVariable('character','counter',1.5);assert.equal(c.frame().actors[0].inputs.level,1.5);c.dispatchActor('character','again');c.step(.01);s=c.frame().actorBehaviors;assert.equal(s[0].state,'idle');assert.ok(s[0].variables.counter<.002);assert.equal(s[1].state,'ready');}finally{c.dispose();}});
test('scoped graph states, variable edits and event history reproduce in full/lite cached seeks',()=>{const d=fixture(),full=new SceneController(d,options),lite=new IllustrationController(d,options),uncached=new IllustrationController(d,{...options,checkpoints:false});try{for(const c of[full,lite,uncached]){c.seek(1);c.setActorVariable('character','counter',.8);c.dispatchActor('second','again');}for(const t of[6,2.25,4.4]){const a=full.seek(t),b=lite.seek(t),c=uncached.seek(t);assert.deepEqual(a.actorBehaviors,b.actorBehaviors);assert.deepEqual(b,c);}assert.ok(lite.checkpointStats().hits>=2);assert.ok(lite.checkpointStats().replayedTicks<=61);}finally{for(const c of[full,lite,uncached])c.dispose();}});
test('campfire authored thresholds change the actual cooking decision and heat stops when fire goes out',()=>{const d=createCampfire(),scope=d.actorBehaviors[0];scope.graph.edges.find(e=>e.id==='ready-temperature').when.value=.46;const c=new SceneController(d);try{c.seek(.5);assert.ok(c.ensemble.members[0].stage!==null);assert.ok(c.frame().ensemble.events.some(e=>e.type==='ready'&&e.actors[0]==='camper-0'));c.dispatch('extinguish-fire');const before=c.ensemble.members[1].heat;c.seek(2);assert.equal(c.ensemble.members[1].heat,before);assert.equal(c.frame().actorBehaviors[1].variables.heating,false);}finally{c.dispose();}});
test('campfire actor-targeted burn, cold preview and source document migration are explicit',()=>{const d=createCampfire(),old=structuredClone(d);delete old.actorBehaviors;old.requiredFeatures=old.requiredFeatures.filter(v=>v!=='actor-behaviors');const saved=JSON.stringify(old),converted=convertCampfireCooking(old);assert.equal(JSON.stringify(old),saved);assert.equal(converted.actorBehaviors.length,4);assert.equal(converted.revision,old.revision+1);converted.actorBehaviors[0].rates[0].perSecond=.12;assert.equal(convertCampfireCooking(converted).actorBehaviors[0].rates[0].perSecond,.12);const c=new SceneController(d);try{c.triggerEnsemble('burn',{actor:'camper-2'});c.step(.05);assert.equal(c.ensemble.members[2].burned,true);assert.equal(c.ensemble.members[0].burned,false);assert.equal(c.frame().actorBehaviors[2].variables.heat,1.04);const before=c.frame().actorBehaviors[0].time;c.previewClip('camper-0','campfire',5);c.step(.1);assert.equal(c.frame().actorBehaviors[0].time,before);c.clearPreview('camper-0');c.step(.1);assert.ok(c.frame().actorBehaviors[0].time>before);}finally{c.dispose();}const a=new SceneController(old),b=new SceneController(old,{checkpoints:false});try{a.seek(20);assert.deepEqual(a.seek(8),b.seek(8));assert.equal(a.actorBehaviors,null);}finally{a.dispose();b.dispose();}});
test('scoped graph validation rejects bad signals, bounds, recursive recipes and oversized rates',()=>{const valid=fixture();for(const corrupt of[s=>s.actor='missing',s=>s.outputs[0].source='time',s=>s.outputs[0].variable='missing',s=>s.graph.variableBounds.counter.max=3,s=>s.sensors[0].source='input.missing',s=>s.rates[0].perSecond=Infinity,s=>s.rates[0].variable='enabled',s=>s.graph.activities={},s=>s.rates=Array(17).fill(s.rates[0]),s=>s.graph.states.idle.actions=[{type:'input',actor:'second',input:'enabled',value:false}]]){const d=structuredClone(valid);corrupt(d.actorBehaviors[0]);assert.throws(()=>new ActorBehaviorRuntime(d));}const errors=[];validateActorBehaviors(valid,(ok,path,message)=>{if(!ok)errors.push(path+message);});assert.deepEqual(errors,[]);});

test('malformed actor graph shapes return validation errors without throwing loader TypeErrors',()=>{
 const corruptions=[
  d=>d.actorBehaviors={},d=>d.actorBehaviors=null,d=>d.actorBehaviors=[null],
  d=>d.actorBehaviors[0].outputs={},d=>d.actorBehaviors[0].outputs=null,d=>d.actorBehaviors[0].outputs=false,d=>d.actorBehaviors[0].outputs=[null,2,[]],
  d=>d.actorBehaviors[0].sensors={},d=>d.actorBehaviors[0].sensors=null,d=>d.actorBehaviors[0].sensors=[null,'bad',{}],
  d=>d.actorBehaviors[0].rates={},d=>d.actorBehaviors[0].rates=null,d=>d.actorBehaviors[0].rates=[null,3,[]],d=>d.actorBehaviors[0].rates[0].when=null,
  d=>d.actorBehaviors[0].graph=null,d=>d.actorBehaviors[0].graph.variables=null,d=>d.actorBehaviors[0].graph.variables=[],d=>d.actorBehaviors[0].graph.variables={counter:null},
  d=>d.actorBehaviors[0].graph.states=null,d=>d.actorBehaviors[0].graph.states={idle:null},d=>d.actorBehaviors[0].graph.states.idle.actions=null,
  d=>d.actorBehaviors[0].graph.handlers={},d=>d.actorBehaviors[0].graph.handlers=[null],d=>d.actorBehaviors[0].graph.edges=[null]
 ];
 for(const corrupt of corruptions){const d=fixture();corrupt(d);const errors=[];assert.doesNotThrow(()=>validateActorBehaviors(d,(ok,path,message)=>{if(!ok)errors.push(path+': '+message);}),corrupt.toString());assert.ok(errors.length,corrupt.toString());assert.throws(()=>new ActorBehaviorRuntime(d),error=>error instanceof Error&&!(error instanceof TypeError)&&/actorBehaviors/.test(error.message),corrupt.toString());}
});

test('actor scopes flag missing scene variables after the scene graph is deleted',()=>{const d=fixture();d.behaviorGraph={seed:17,variables:{weather:true},initial:'idle',states:{idle:{actions:[]}},edges:[]};d.actorBehaviors[0].sensors=[{variable:'enabled',source:'scene.weather'}];assertDocument(d);delete d.behaviorGraph;const errors=[];assert.doesNotThrow(()=>validateActorBehaviors(d,(ok,path,message)=>{if(!ok)errors.push(path+': '+message);}));assert.ok(errors.some(e=>e.includes('sensors')));});
