import test from 'node:test';
import assert from 'node:assert/strict';
import {createAnimationPreview,ANIMATION_PREVIEW_LIMITS} from '../src/animation-preview.js';
import {createHandoff} from '../examples/handoff.js';
import {SceneController} from '../src/scene.js';
import {objectGrip} from '../src/scene-objects.js';
import {evaluatedProps} from '../src/scene-attachments.js';
import {spatialKinematics,poseDefaults} from '../src/spatial.js';
import {forwardKinematics} from '../src/index.js';
const near=(a,b)=>assert.ok(Math.hypot(a.x-b.x,a.y-b.y)<1e-8,JSON.stringify({a,b}));
function fixture(){const document=createHandoff(),controller=new SceneController(document);return {document,controller};}

test('authored preview matches a paused Studio clip preview including expression, overrides and receiving contact',()=>{const {document,controller}=fixture();try{const base=controller.seek(3.8),overrides={'head.rotation':7,'eyes.x':1},sampler=createAnimationPreview(document,base,{actor:'recipient',clip:'receive',overrides}),actual=sampler.sample(3.9),studio=controller.previewClip('recipient','receive',3.9,overrides);assert.deepEqual(actual.actors.find(a=>a.id==='recipient').pose,studio.actors.find(a=>a.id==='recipient').pose);assert.deepEqual(actual.objects,studio.objects);assert.ok(actual.contacts.find(c=>c.actor==='recipient').active);assert.equal(actual.actors.find(a=>a.id==='recipient').pose['head.rotation'],4);assert.equal(actual.effectsTime,base.effectsTime);}finally{controller.dispose();}});

test('preview snapshots cannot mutate or advance the source, other actors, events or ownership',()=>{const {document,controller}=fixture();try{const base=controller.seek(4.1),before=JSON.stringify({document,base,log:controller.log}),sampler=createAnimationPreview(document,base,{actor:'recipient',clip:'receive'}),later=sampler.sample(8.5);assert.equal(later.objects[0].owner.actor,'recipient','Preview must not fire the 8s transfer');assert.equal(later.behavior.time,base.behavior.time);assert.deepEqual(later.actors.find(a=>a.id==='giver'),base.actors.find(a=>a.id==='giver'));assert.equal(JSON.stringify({document,base,log:controller.log}),before);const inspected=sampler.sample(5.6);near(inspected.objects[0],objectGrip(document,inspected,inspected.objects[0].owner));near(evaluatedProps(document,inspected).find(p=>p.id==='gift-box'),inspected.objects[0]);assert.ok(Math.abs(inspected.objects[0].x-base.objects[0].x)>10);later.actors[1].pose['head.x']=9000;document.packs.ona.clips.receive.tracks['head.rotation'][0][1]=18;assert.notEqual(sampler.sample(0).actors.find(a=>a.id==='recipient').pose['head.rotation'],15);assert.equal(sampler.sample(8.5).actors[1].pose['head.x'],base.actors[1].pose['head.x']);}finally{controller.dispose();}});

test('boundaries are explicit and deduplicated; paths and ghost work are capped',()=>{const {document,controller}=fixture();try{document.packs.ona.clips.give.loop=true;const frame=controller.frame(),clamped=createAnimationPreview(document,frame,{actor:'giver',clip:'give'}),wrapped=createAnimationPreview(document,frame,{actor:'giver',clip:'give',boundary:'wrap'});assert.equal(clamped.sample(-1).actors[1].clipTime,0);assert.equal(clamped.sample(11).actors[1].clipTime,10);assert.equal(wrapped.sample(-.25).actors[1].clipTime,9.75);assert.equal(wrapped.sample(10).actors[1].clipTime,0);assert.deepEqual(clamped.onion(0,{step:.2,count:3}).map(g=>[g.side,g.time]),[['after',.2],['after',.4],['after',.6000000000000001]]);assert.equal(wrapped.onion(0,{step:.2,count:3}).length,6);assert.equal(clamped.path('rightWrist',{samples:61}).length,61);assert.deepEqual(ANIMATION_PREVIEW_LIMITS,{ghostsPerSide:3,pathPoints:61});for(const work of [()=>clamped.sample(NaN),()=>clamped.onion(1,{count:4}),()=>clamped.onion(1,{step:0}),()=>clamped.path('rightWrist',{samples:62}),()=>clamped.path('rightWrist',{start:3,end:2}),()=>clamped.path('absent')])assert.throws(work);assert.throws(()=>createAnimationPreview(document,frame,{actor:'giver',clip:'give',overrides:{'head.yaw':181}}));}finally{controller.dispose();}});

test('joint paths use depth-aware forward projection and evaluated actor placement',()=>{const {document,controller}=fixture();try{const pack=document.packs.ona;pack.clips.turn={duration:1,loop:false,tracks:{'root.yaw':[[0,60],[1,90]],'root.pitch':[[0,25]],'rightArm.rotation':[[0,-60]],'rightForearm.rotation':[[0,-45]],'rightWrist.z':[[0,12]]}};document.contacts=[];const frame=controller.frame(),actor=frame.actors.find(a=>a.id==='giver');actor.placement={x:230,y:200,rotation:28,scale:1.35};const sampler=createAnimationPreview(document,frame,{actor:'giver',clip:'turn'}),points=sampler.path('rightWrist',{samples:3});for(const p of points){const f=sampler.sample(p.time),pose=f.actors.find(a=>a.id==='giver').pose,j=spatialKinematics(pack,pose).rightWrist,t=actor.placement,r=t.rotation*Math.PI/180;near(p,{x:t.x+(j.x*Math.cos(r)-j.y*Math.sin(r))*t.scale,y:t.y+(j.x*Math.sin(r)+j.y*Math.cos(r))*t.scale});}const f=sampler.sample(.5),pose=f.actors.find(a=>a.id==='giver').pose;assert.ok(Math.abs(spatialKinematics(pack,pose).rightWrist.x-forwardKinematics(pack.joints,pose).rightWrist.x)>5);}finally{controller.dispose();}});

test('hidden actor folders suppress ghosts and paths without changing source visibility',()=>{const {document,controller}=fixture();try{document.groups.find(g=>g.id==='friends').hidden=true;const sampler=createAnimationPreview(document,controller.frame(),{actor:'giver',clip:'give'});assert.deepEqual(sampler.onion(2),[]);assert.deepEqual(sampler.path('rightWrist'),[]);assert.equal(document.groups.find(g=>g.id==='friends').hidden,true);}finally{controller.dispose();}});

test('optimized path samples preserve public contact results and snapshot isolation',()=>{const {document,controller}=fixture();try{const base=controller.seek(3.8),sampler=createAnimationPreview(document,base,{actor:'recipient',clip:'receive'}),before=JSON.stringify(base),points=sampler.path('leftWrist',{start:2.9,end:4.1,samples:31});for(const point of points)near(point,objectGrip(document,sampler.sample(point.time),{actor:'recipient',joint:'leftWrist'}));assert.equal(JSON.stringify(base),before);assert.deepEqual(sampler.path('leftWrist',{start:2.9,end:4.1,samples:31}),points);}finally{controller.dispose();}});
