import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
try{const page=await browser.newPage();await page.goto('http://127.0.0.1:5178/draw.html');const result=await page.evaluate(async()=>{
 const [{createDrawing},{createEmitter},{SceneController},{WorkerSceneController},{mountSVG,renderSVG}]=await Promise.all([import('/src/vector-authoring.js'),import('/src/scene-graph.js'),import('/src/scene.js'),import('/src/worker.js'),import('/src/svg.js')]);
 const d=createDrawing();d.packs.drawing.parts.push({id:'body',joint:'root',d:'M0 0H50V80H0Z',fill:'#aabbcc'});d.packs.drawing.inputs.flag={type:'boolean',default:false};d.emitters=[createEmitter('flame','fire')];d.lighting={enabled:true,emitter:'fire',showSource:true};d.behaviorGraph={seed:1,variables:{},initial:'off',states:{off:{actions:[{type:'emitter',emitter:'fire',enabled:false}]},on:{actions:[{type:'emitter',emitter:'fire',enabled:true},{type:'input',actor:'$actor',input:'flag',value:true}]}},edges:[{id:'ignite',from:'off',to:'on',event:'ignite',weight:1}]};d.interactions=[{id:'click',actor:'character',gesture:'click',response:'event',event:'ignite',resistance:0}];
 const c=new SceneController(d),host=document.createElement('div');document.body.append(host);const mount=mountSVG(host,d,c.frame()),emitter=host.querySelector('[data-emitter="fire"]'),particles=[...emitter.children],before=getComputedStyle(emitter).display,shadowBefore=host.querySelector('[data-floor-strength]').getAttribute('opacity');c.dispatch('ignite',{actor:'character'});mount.update(c.frame());const after=getComputedStyle(emitter).display,shadowAfter=+host.querySelector('[data-floor-strength]').getAttribute('opacity'),sourceVisible=host.querySelector('[data-light-source]').getAttribute('visibility'),stable=particles.every((p,i)=>p===emitter.children[i]);const exported=document.createElement('div');exported.innerHTML=renderSVG(d,c.frame());const visual=root=>[...root.querySelectorAll('[data-particle],[data-floor-strength],[data-wall-strength],[data-light-source]')].map(n=>['transform','opacity','fill','visibility'].map(k=>n.getAttribute(k)));const parity=JSON.stringify(visual(exported))===JSON.stringify(visual(host));
 const worker=new WorkerSceneController(d);await worker.ready;await new Promise((resolve,reject)=>{worker.onFrame=resolve;worker.onError=reject;worker.pointer({binding:'click',phase:'click',x:25,y:30});});const wf=worker.frame();const reference=new SceneController(d);reference.pointer({binding:'click',phase:'click',x:25,y:30});const workerMatches=JSON.stringify(wf)===JSON.stringify(reference.frame());worker.dispose();mount.dispose();return {before,after,shadowBefore,shadowAfter,sourceVisible,stable,parity,workerMatches,state:wf.behavior.state,flag:wf.actors[0].inputs.flag};
});assert.equal(result.before,'none');assert.equal(result.after,'inline');assert.equal(result.shadowBefore,'0');assert.ok(result.shadowAfter>0);assert.equal(result.sourceVisible,'visible');assert.equal(result.stable,true);assert.equal(result.parity,true);assert.equal(result.workerMatches,true);assert.equal(result.state,'on');assert.equal(result.flag,true);console.log('Behavior rendering and worker checks passed',result);}finally{await browser.close();}
