import test from 'node:test';
import assert from 'node:assert/strict';
import {createBottle} from '../examples/bottle.js';
import {assertDocument} from '../src/schema.js';
import {SceneController} from '../src/scene.js';
import {spatialParts} from '../src/spatial.js';
import {renderSVG} from '../src/svg.js';
const project=()=>createBottle();
test('Bottle is a portable editable scene with grouped scenery and three wind performances',()=>{const doc=project();assertDocument(doc);assert.deepEqual(JSON.parse(JSON.stringify(doc)),doc);assert.deepEqual(doc.packs.ship.inputs.action.options,['calm','breeze','gust']);assert.equal(doc.groups.find(g=>g.id==='bottle').parent,'scenery');assert.equal(doc.actors.find(a=>a.id==='ship').group,'sailing');assert.ok(doc.packs.ship.joints.some(j=>j.id==='ship-rock'));assert.ok(doc.packs.ship.joints.some(j=>j.id==='main-sail'));assert.ok(doc.packs.ship.parts.some(p=>p.id==='main-canvas'&&p.spatial.morph));assert.ok(JSON.stringify(doc).length<100000);});
test('Hull straddles the waterline through every wind clip and ship stays within the bottle body',()=>{const doc=project(),controller=new SceneController(doc);for(const action of ['calm','breeze','gust'])for(let t=0;t<=12;t+=.125){controller.previewClip('ship',action,t);const actor=controller.frame().actors.find(a=>a.id==='ship'),view=spatialParts(doc.packs.ship,actor),ship=view.world['ship-rock'],wave=view.world['wave-front'],level=wave.y+293,deck=ship.y-17*ship.m[4],keel=ship.y+33*ship.m[4];assert.ok(deck<level-10,`${action}/${t} deck submerged`);assert.ok(keel>level+10,`${action}/${t} keel leaves water`);for(const [x,y] of [[-119,-39],[150,-47],[-7,-150],[78,33]]){const px=ship.x+ship.m[0]*x+ship.m[1]*y,py=ship.y+ship.m[3]*x+ship.m[4]*y;assert.ok(px>=210&&px<=520&&py>=118&&py<=326,`${action}/${t}: ${px},${py}`);}for(const part of view.parts.values())assert.ok(part.matrix.every(Number.isFinite));}controller.dispose();});
test('Bottle glass follows clipped waves and ship; exported paths remain finite at sampled extremes',()=>{const doc=project(),controller=new SceneController(doc);for(const action of ['calm','breeze','gust'])for(const time of [0,.9,1.2,3.7,7.4,11.9]){controller.previewClip('ship',action,time);const svg=renderSVG(doc,controller.frame());assert.ok(!/NaN|Infinity|undefined/.test(svg));assert.ok(svg.includes('<clipPath'));assert.ok(svg.indexOf('data-actor="ship"')<svg.indexOf('data-actor="glass"'));assert.ok(svg.indexOf('data-actor="stand"')<svg.indexOf('data-actor="ship"'));assert.ok((svg.match(/clip-path=/g)||[]).length>=50);}controller.dispose();});
test('Wind state changes work through public inputs and authored loops join without a jump',()=>{const doc=project(),controller=new SceneController(doc);controller.setInput('ship','action','gust');for(let i=0;i<120;i++)controller.step(1/60);assert.equal(controller.frame().actors.find(a=>a.id==='ship').state,'gust');controller.setInput('ship','action','calm');for(let i=0;i<120;i++)controller.step(1/60);assert.equal(controller.frame().actors.find(a=>a.id==='ship').state,'calm');for(const clip of Object.values(doc.packs.ship.clips))for(const keys of Object.values(clip.tracks)){assert.equal(keys[0][0],0);assert.equal(keys.at(-1)[0],clip.duration);assert.equal(keys[0][1],keys.at(-1)[1]);}controller.dispose();});

test('Live bottle overlays conserve the interior and scale only the ship subtree',()=>{
 const doc=project(),controller=new SceneController(doc),frame=controller.frame();assert.ok(frame.fluid);const before=JSON.stringify(doc),svg=renderSVG(doc,frame,{bones:true});
 assert.ok(svg.includes('scale(0.65)'));assert.ok(svg.includes('data-part="interior-sky"'));assert.ok(svg.includes('d="'+frame.fluid.paths['deep-water']+'"'));assert.ok(Math.abs(frame.fluid.area-frame.fluid.targetArea)<.001);assert.ok(!/NaN|undefined|Infinity/.test(svg));assert.equal(JSON.stringify(doc),before);
 const empty={...frame,fluid:{...frame.fluid,paths:{...frame.fluid.paths,'deep-water':''}}};assert.match(renderSVG(doc,empty),/data-part="deep-water" d=""/);
 controller.previewClip('ship','gust',4);const preview=controller.frame();assert.equal(preview.fluid,undefined);assert.ok(!renderSVG(doc,preview).includes('scale(0.65)'));controller.dispose();
});
