import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser = await chromium.launch({headless:true, ...(process.platform==='win32'?{channel:'msedge'}:{})});
const page = await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.POSECRAFT_URL || 'http://127.0.0.1:5178';
fs.mkdirSync('test-results',{recursive:true});
try {
 await page.goto(base);await page.locator('[data-part]').first().waitFor();
 await page.screenshot({path:'test-results/studio.png',fullPage:true});
 assert.equal(await page.locator('[data-actor="ona"]').count(),1);
 await page.locator('#greet').click();assert.equal(await page.locator('#clip').inputValue(),'wave');await page.locator('#reset').click();
 await page.locator('#actor-name').fill('Ona test');await page.locator('#actor-name').press('Tab');
 await page.locator('#duplicate').click();assert.equal(await page.locator('#art [data-actor]').count(),2);
 await page.locator('#undo').click();assert.equal(await page.locator('#art [data-actor]').count(),1);
 await page.locator('#redo').click();assert.equal(await page.locator('#art [data-actor]').count(),2);
 await page.locator('#clip').selectOption('wave');
 await page.locator('#scrub').fill('0.45');await page.locator('#scrub').dispatchEvent('input');
 await page.locator('#rotation').fill('-100');await page.locator('#rotation').dispatchEvent('input');
 await page.locator('#add-key').click();
 const saved = await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v1')));
 assert.ok(saved.packs.ona.clips.wave.tracks['rightArm.rotation'].some(([t,v])=>t===.45&&v===-100));
 await page.reload();await page.locator('[data-part]').first().waitFor();assert.equal(await page.locator('#art [data-actor]').count(),2);
 await page.locator('#states-tab').click();await page.locator('#blend').fill('0.4');await page.locator('#blend').press('Tab');
 const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;await download.saveAs('test-results/roundtrip.json');
 const exported=JSON.parse(fs.readFileSync('test-results/roundtrip.json'));assert.equal(exported.packs.ona.states.idle.transitions[0].duration,.4);
 await page.locator('#file').setInputFiles('test-results/roundtrip.json');await page.waitForTimeout(200);assert.equal(await page.locator('#art [data-actor]').count(),2);
 await page.locator('#file').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"schemaVersion":99}')});await page.waitForTimeout(100);assert.equal(await page.locator('#art [data-actor]').count(),2);
 await page.goto(base+'/react-demo.html');await page.locator('[data-posecraft] svg').waitFor();
 await page.getByRole('button',{name:'Wave',exact:true}).click();await page.waitForTimeout(400);assert.match(await page.locator('.event-log').textContent(),/idle → wave/);
 const root=page.locator('[data-posecraft] [data-joint="root"]').first();const before=await root.getAttribute('transform');
 const box=await page.locator('.react-modal').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+25);await page.mouse.down();await page.mouse.move(box.x+box.width/2+110,box.y+25,{steps:12});await page.mouse.up();await page.waitForTimeout(100);const after=await root.getAttribute('transform');assert.notEqual(before,after);
 await page.getByRole('button',{name:'Unmount',exact:true}).click();assert.equal(await page.locator('[data-posecraft] svg').count(),0);await page.getByRole('button',{name:'Mount',exact:true}).click();await page.locator('[data-posecraft] svg').waitFor();assert.equal(await page.locator('[data-posecraft] svg').count(),1);
 await page.locator('[aria-label="Container width"]').fill('320');await page.locator('[aria-label="Container width"]').dispatchEvent('input');
 await page.screenshot({path:'test-results/react.png',fullPage:true});
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForTimeout(100);const still=await root.getAttribute('transform');await page.waitForTimeout(300);assert.equal(await root.getAttribute('transform'),still);
 await page.goto(base+'/wwwzard.html');await page.locator('svg').waitFor();await page.getByPlaceholder('Type here and watch his hands...').pressSequentially('hello');await page.screenshot({path:'test-results/wwwzard.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.goto(base);await page.locator('[data-part]').first().waitFor();await page.screenshot({path:'test-results/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'mobile layout has horizontal overflow');
 assert.deepEqual(errors,[]);console.log('Browser checks passed: editor edit/undo/redo, keys, local recovery, export/import, invalid import, React input/events, inertia, remount, resize, reduced motion, wwwzard typing, mobile layout.');
} finally { await browser.close(); }
