import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];
page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
const food=()=>page.locator('#demo-art [data-actor="camper-0"] [data-part="marshmallow"]');
async function seek(time){await page.locator('#demo-scrub').fill(String(time));await page.locator('#demo-scrub').dispatchEvent('input');await page.waitForFunction(t=>Math.abs(Number(document.querySelector('#demo-art svg').dataset.sceneTime)-t)<.1,time);}
try{
 await page.goto(base+'/demos.html#campfire-night');await page.locator('#demo-art svg').waitFor();assert.equal(await page.locator('#demo-art [data-actor^="camper-"]').count(),4);assert.equal(await page.locator('#demo-art [data-wall-shadow]').count(),0);
 const firstCloud=await page.locator('#demo-art [data-part="cloud-0"]').locator('..').getAttribute('transform'),firstFlame=await page.locator('#demo-art [data-part="flame-0"]').locator('..').getAttribute('transform');
 await seek(12.4);assert.ok(+await page.locator('#demo-art [data-actor="camper-0"] [data-part="snack-flame"]').getAttribute('opacity')>.3);await page.screenshot({path:'test-results/campfire-burn.png'});
 await seek(15.52);await page.screenshot({path:'test-results/campfire-brace.png'});await seek(16.72);await page.screenshot({path:'test-results/campfire-slide.png'});await seek(18.2);await page.screenshot({path:'test-results/campfire-eat.png'});const eating=await food().locator('..').getAttribute('transform');await seek(19.52);assert.equal(await food().getAttribute('opacity'),'0');await seek(23);assert.equal(await food().getAttribute('opacity'),'1');assert.notEqual(await food().locator('..').getAttribute('transform'),eating);
 await seek(8.8);assert.ok(+await page.locator('#demo-art [data-part="meteor-0"]').getAttribute('opacity')>.5);assert.notEqual(await page.locator('#demo-art [data-part="cloud-0"]').locator('..').getAttribute('transform'),firstCloud);assert.notEqual(await page.locator('#demo-art [data-part="flame-0"]').locator('..').getAttribute('transform'),firstFlame);await page.screenshot({path:'test-results/campfire-meteor.png'});
 const coverage=await page.locator('#demo-art [data-actor="camper-0"] [data-surface="face-0"] stop').nth(1).getAttribute('offset');const stops=await page.locator('#demo-art [data-actor="camper-0"] [data-surface="face-0"]').innerHTML();await seek(9.32);assert.notEqual(await page.locator('#demo-art [data-actor="camper-0"] [data-surface="face-0"]').innerHTML(),stops,'Fire changes actual character illumination');assert.notEqual(await page.locator('#demo-art [data-actor="camper-0"] [data-surface="face-0"] stop').nth(1).getAttribute('offset'),coverage,'Fire also changes cel coverage');
 const downloadPromise=page.waitForEvent('download');await page.locator('#download-demo').click();await(await downloadPromise).saveAs('test-results/campfire.scene.json');const doc=JSON.parse(fs.readFileSync('test-results/campfire.scene.json','utf8'));assert.equal(doc.actors.filter(a=>!a.layer).length,4);assert.equal(doc.lighting.type,'point');assert.ok(doc.packs.night.clips.loop.tracks['meteor-0.opacity']);
 for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);const footer=await page.locator('.demo-footer').boundingBox(),art=await page.locator('#demo-art').boundingBox();assert.ok(footer.y+footer.height<=size.height+1);assert.ok(art.height>100);await page.screenshot({path:`test-results/campfire-${size.width}.png`});}
 await page.setViewportSize({width:1366,height:768});await page.locator('#edit-demo').click();await page.locator('#art svg').waitFor();assert.equal(await page.locator('#actors').inputValue(),'camper-0');assert.equal(await page.locator('#clip').inputValue(),'campfire');await page.locator('[data-select-joint="food"]').click();await page.locator('#pose-channel').selectOption('opacity');await page.locator('#rotation').fill('0.5');await page.locator('#add-key').click();await page.reload();await page.locator('[data-select-joint="food"]').click();await page.locator('#pose-channel').selectOption('opacity');assert.equal(await page.locator('#rotation').inputValue(),'0.5');await page.goto(base+'/demos.html#light-and-shade');await page.locator('#demo-art svg').waitFor();await page.locator('#demo-light-type').selectOption('point');await page.locator('#demo-art [data-light-source]').waitFor();const light=await page.locator('#demo-art [data-light-source]').getAttribute('transform'),shadow=await page.locator('#demo-art [data-floor-shadow]').first().getAttribute('transform');await page.waitForFunction(before=>document.querySelector('#demo-art [data-light-source]').getAttribute('transform')!==before,light);assert.notEqual(await page.locator('#demo-art [data-floor-shadow]').first().getAttribute('transform'),shadow);
 await page.locator('#demo-play').click();const frozen=await page.locator('#demo-art [data-light-source]').getAttribute('transform');await page.waitForTimeout(180);assert.equal(await page.locator('#demo-art [data-light-source]').getAttribute('transform'),frozen);
 await page.locator('[data-light-control="celThickness"]').fill('0.75');await page.locator('[data-light-control="celIntensity"]').fill('0.25');await page.locator('#edit-demo').click();await page.locator('[data-panel="light"]').click();await page.locator('[data-light-field="celThickness"]').fill('0.75');await page.locator('[data-light-field="celThickness"]').dispatchEvent('change');await page.locator('[data-light-field="celIntensity"]').fill('0.25');await page.locator('[data-light-field="celIntensity"]').dispatchEvent('change');
 await page.locator('[data-light-tab="source"]').click();await page.locator('#lighting-type').selectOption('point');await page.locator('#lighting-pointX').fill('123');await page.locator('#lighting-pointX').press('Tab');await page.locator('#lighting-motion').selectOption('orbit');await page.locator('[data-light-tab="shadows"]').click();await page.locator('#lighting-receiver').selectOption('floor');assert.equal(await page.locator('#art [data-wall-shadow]').count(),0);await page.reload();await page.locator('[data-panel="light"]').click();assert.equal(await page.locator('[data-light-field="celThickness"]').inputValue(),'0.75');assert.equal(await page.locator('[data-light-field="celIntensity"]').inputValue(),'0.25');await page.locator('[data-light-tab="source"]').click();assert.equal(await page.locator('#lighting-pointX').inputValue(),'123');assert.equal(await page.locator('#lighting-motion').inputValue(),'orbit');
 for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<760)await page.locator('#inspector-panel').click();for(const tab of ['surface','source','shadows']){await page.locator(`[data-light-tab="${tab}"]`).click();const last=await page.locator('#inspector input:visible').last().boundingBox(),timeline=await page.locator('.timeline').boundingBox();assert.ok(last.y+last.height<timeline.y,'Light controls fit '+tab+' '+size.width);}await page.screenshot({path:`test-results/campfire-controls-${size.width}.png`});}
 assert.deepEqual(errors,[]);console.log('Campfire checks passed: four looks, cooking/eating/replacement, animated sky/fire, flickering illumination, export, moving point shadows, pause, saved controls and mobile layout.');
}finally{await browser.close();}
