import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];
page.setDefaultTimeout(20000);page.on('pageerror',e=>errors.push(e.message));
async function seek(time){await page.locator('#demo-scrub').fill(String(time));await page.locator('#demo-scrub').dispatchEvent('input');await page.waitForFunction(t=>Math.abs(Number(document.querySelector('#demo-art svg').dataset.sceneTime)-t)<.03,time);}
const food=id=>page.locator(`#demo-art [data-actor="camper-${id}"] [data-part="marshmallow"]`);
const meteor=()=>page.locator('#demo-art [data-part="meteor-0-head"]').locator('..').evaluate(el=>{const m=el.transform.baseVal.consolidate().matrix;return {x:m.e,y:m.f,dx:m.a,dy:m.b};});
async function download(){const pending=page.waitForEvent('download');await page.locator('#download-demo').click();await(await pending).saveAs('test-results/campfire.scene.json');return JSON.parse(fs.readFileSync('test-results/campfire.scene.json','utf8'));}
try{
 await page.goto(base+'/demos.html#campfire-night');await page.locator('#demo-art svg').waitFor();assert.equal(await page.locator('#demo-art [data-actor^="camper-"]').count(),4);assert.equal(await page.locator('#demo-art [data-wall-shadow]').count(),0);await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.includes('4 characters'));
 const y=await page.locator('#demo-art [data-contact]').evaluateAll(nodes=>nodes.map(n=>+n.getAttribute('cy')));assert.ok(Math.max(...y)-Math.min(...y)>90,'Cast stands at different depths around the fire');await page.screenshot({path:'test-results/camp-live-start.png'});
 await seek(4);assert.match(await page.locator('#demo-caption').textContent(),/conversation/);await page.locator('#camp-doze').click();await seek(5.2);assert.match(await page.locator('#demo-caption').textContent(),/dozing/);
 await page.locator('#demo-reset').click();await page.locator('#camp-meteor').click();await seek(.8);const a=await meteor();await seek(1.6);const b=await meteor();assert.ok(Math.abs((b.x-a.x)*b.dy-(b.y-a.y)*b.dx)<.05,'Meteor follows its streak');assert.match(await page.locator('#demo-caption').textContent(),/pointing at meteor/);assert.match(await page.locator('#demo-caption').textContent(),/watching meteor/);assert.ok(+await page.locator('#demo-art [data-part="meteor-0-tail-0"]').getAttribute('opacity')>+await page.locator('#demo-art [data-part="meteor-0-tail-15"]').getAttribute('opacity')*20);assert.equal(await page.locator('#demo-art [data-part="camp-point"][opacity="1"]').count(),1);await page.screenshot({path:'test-results/camp-live-meteor.png'});
 const full=+await page.locator('#demo-art [data-part="meteor-0-head"]').getAttribute('opacity');await seek(3.52);assert.ok(+await page.locator('#demo-art [data-part="meteor-0-head"]').getAttribute('opacity')<full);
 await page.locator('#demo-reset').click();await page.locator('#camp-share').click();await seek(6.88);assert.equal(await food(0).getAttribute('opacity'),'1');assert.equal(await food(1).getAttribute('opacity'),'0');await seek(7.32);assert.equal(await food(0).getAttribute('opacity'),'0');assert.equal(await food(1).getAttribute('opacity'),'1');assert.match(await page.locator('#demo-caption').textContent(),/eating shared/);const points=await page.locator('#demo-art [data-actor="camper-1"]').evaluate(root=>['hold-palm','marshmallow'].map(id=>{const m=root.querySelector(`[data-part="${id}"]`).getCTM();return {x:m.e,y:m.f};}));assert.ok(Math.hypot(points[0].x-points[1].x,points[0].y-points[1].y)<1);await page.screenshot({path:'test-results/camp-live-share.png'});
 const first=await download();assert.equal(first.ensemble.type,'campfire');await page.locator('#camp-new').click();const next=await download();assert.notEqual(next.ensemble.seed,first.ensemble.seed);await seek(1);const stops=await page.locator('#demo-art [data-actor="camper-0"] [data-surface="shirt-0"]').innerHTML();await seek(1.52);assert.notEqual(await page.locator('#demo-art [data-actor="camper-0"] [data-surface="shirt-0"]').innerHTML(),stops);const frozen=await page.locator('#demo-art').innerHTML();await page.waitForTimeout(200);assert.equal(await page.locator('#demo-art').innerHTML(),frozen,'Pause freezes the ensemble');
 for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);const footer=await page.locator('.demo-footer').boundingBox(),art=await page.locator('#demo-art').boundingBox();assert.ok(footer.y+footer.height<=size.height+1);assert.ok(art.height>100);await page.screenshot({path:`test-results/campfire-${size.width}.png`});}
 await page.setViewportSize({width:1366,height:768});await page.locator('#edit-demo').click();await page.locator('#art svg').waitFor();assert.equal(await page.locator('#actors').inputValue(),'camper-0');assert.equal(await page.locator('#clip').inputValue(),'campfire');await page.locator('[data-select-joint="food"]').click();await page.locator('#pose-channel').selectOption('opacity');await page.locator('#rotation').fill('0.5');await page.locator('#add-key').click();await page.reload();await page.locator('[data-select-joint="food"]').click();await page.locator('#pose-channel').selectOption('opacity');assert.equal(await page.locator('#rotation').inputValue(),'0.5');
 await page.locator('[data-select-joint="take-hand"]').click();await page.locator('#pose-channel').selectOption('pitch');const armBefore=await page.locator('#art [data-actor="camper-0"] [data-part="take-skin"]').getAttribute('d');await page.locator('#rotation').fill('70');await page.locator('#rotation').dispatchEvent('input');await page.locator('#add-key').click();assert.notEqual(await page.locator('#art [data-actor="camper-0"] [data-part="take-skin"]').getAttribute('d'),armBefore);const wrist=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2.demo.campfire-night')));assert.ok(Object.values(wrist.packs['camper-0'].clips).some(c=>c.tracks['take-hand.pitch']?.some(k=>k[1]===70)));
 await page.goto(base+'/demos.html#light-and-shade');await page.locator('#demo-art svg').waitFor();await page.locator('#demo-light-type').selectOption('point');await page.locator('#demo-art [data-light-source]').waitFor();const light=await page.locator('#demo-art [data-light-source]').getAttribute('transform'),shadow=await page.locator('#demo-art [data-floor-shadow]').first().getAttribute('transform');await page.waitForFunction(before=>document.querySelector('#demo-art [data-light-source]').getAttribute('transform')!==before,light);assert.notEqual(await page.locator('#demo-art [data-floor-shadow]').first().getAttribute('transform'),shadow);
 await page.locator('#demo-play').click();const frozenLight=await page.locator('#demo-art [data-light-source]').getAttribute('transform');await page.waitForTimeout(180);assert.equal(await page.locator('#demo-art [data-light-source]').getAttribute('transform'),frozenLight);
 await page.locator('[data-light-control="celThickness"]').fill('0.75');await page.locator('[data-light-control="celIntensity"]').fill('0.25');await page.locator('#edit-demo').click();await page.locator('[data-panel="light"]').click();await page.locator('[data-light-field="celThickness"]').fill('0.75');await page.locator('[data-light-field="celThickness"]').dispatchEvent('change');await page.locator('[data-light-field="celIntensity"]').fill('0.25');await page.locator('[data-light-field="celIntensity"]').dispatchEvent('change');
 await page.locator('[data-light-tab="source"]').click();await page.locator('#lighting-type').selectOption('point');await page.locator('#lighting-pointX').fill('123');await page.locator('#lighting-pointX').press('Tab');await page.locator('#lighting-motion').selectOption('orbit');await page.locator('[data-light-tab="shadows"]').click();await page.locator('#lighting-receiver').selectOption('floor');assert.equal(await page.locator('#art [data-wall-shadow]').count(),0);await page.reload();await page.locator('[data-panel="light"]').click();assert.equal(await page.locator('[data-light-field="celThickness"]').inputValue(),'0.75');assert.equal(await page.locator('[data-light-field="celIntensity"]').inputValue(),'0.25');await page.locator('[data-light-tab="source"]').click();assert.equal(await page.locator('#lighting-pointX').inputValue(),'123');assert.equal(await page.locator('#lighting-motion').inputValue(),'orbit');
 for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<760)await page.locator('#inspector-panel').click();for(const tab of ['surface','source','shadows']){await page.locator(`[data-light-tab="${tab}"]`).click();const last=await page.locator('#inspector input:visible').last().boundingBox(),timeline=await page.locator('.timeline').boundingBox();assert.ok(last.y+last.height<timeline.y,'Light controls fit '+tab+' '+size.width);}await page.screenshot({path:`test-results/campfire-controls-${size.width}.png`});}
 assert.deepEqual(errors,[]);console.log('Campfire checks passed: staged cast, live conversation/dozing, aligned fading meteor, shared gaze, handoff ownership/contact, new seeds, pause, export, editable keys, lighting controls and mobile layout.');
}finally{await browser.close();}
