import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {chromium} from '@playwright/test';
import {createServer} from 'vite';
await fs.mkdir('test-results',{recursive:true});await fs.writeFile('test-results/renderer-fixture.html','<!doctype html><html><head><meta charset="utf-8"><title>Renderer parity</title></head><body></body></html>');
const server=await createServer({configFile:false,root:process.cwd(),server:{host:'127.0.0.1',port:5187,strictPort:true,hmr:false},appType:'mpa'});await server.listen();const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
try{const page=await browser.newPage({viewport:{width:1320,height:1050}});await page.goto('http://127.0.0.1:5187/test-results/renderer-fixture.html');const report=await page.evaluate(async()=>{
 const [{rendererFixture,rendererFrame,crossingMeshFixture},{evaluateDrawing},{renderCanvas,pickDrawing,mountCanvas},{renderDepthCanvas},{renderSVG,mountSVG},{SceneController},{createDemo},{createGym}]=await Promise.all([import('/test/fixtures/renderer-scenes.js'),import('/src/render-evaluation.js'),import('/src/canvas.js'),import('/src/canvas-depth.js'),import('/src/svg.js'),import('/src/scene.js'),import('/examples/showcase.js'),import('/examples/gym.js')]);
 document.body.innerHTML='<style>body{margin:16px;background:#eef1f3;color:#263243;font:14px system-ui}main{display:grid;grid-template-columns:repeat(2,1fr);gap:16px}.card{background:white;padding:12px;border-radius:12px}.pair{display:flex;gap:8px}.pair>*{width:50%;height:240px;object-fit:contain}h3{margin:0 0 8px;font-size:15px}</style><h2>Shared evaluated drawing · SVG / Canvas</h2><main></main>';const results=[];
 const compare=async(name,doc,frame)=>{const drawing=evaluateDrawing(doc,frame),canvas=document.createElement('canvas');canvas.width=drawing.width;canvas.height=drawing.height;renderCanvas(canvas.getContext('2d'),drawing);const svg=renderSVG(doc,frame),image=new Image(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});const reference=document.createElement('canvas');reference.width=drawing.width;reference.height=drawing.height;reference.getContext('2d').drawImage(image,0,0,drawing.width,drawing.height);URL.revokeObjectURL(url);const a=reference.getContext('2d').getImageData(0,0,drawing.width,drawing.height).data,b=canvas.getContext('2d').getImageData(0,0,drawing.width,drawing.height).data;let sum=0,large=0;for(let i=0;i<a.length;i+=4){let error=0;for(let c=0;c<4;c++){const delta=Math.abs(a[i+c]-b[i+c]);sum+=delta;error=Math.max(error,delta);}if(error>70)large++;}const entry={name,meanChannelError:sum/a.length,largePixelFraction:large/(a.length/4),paths:drawing.stats.paths};results.push(entry);const card=document.createElement('section');card.className='card';card.innerHTML='<h3>'+name+' · SVG / Canvas</h3><div class="pair"></div>';card.querySelector('.pair').append(reference,canvas);document.querySelector('main').append(card);return {drawing,canvas};};
 const plain=rendererFixture(),plainFrame=rendererFrame(plain,{'root.rotation':25});const base=await compare('Masks, transformed paths, props and shared object',plain,plainFrame),pick=(x,y)=>pickDrawing(base.canvas.getContext('2d'),base.drawing,x,y);if(pick(200,60)?.object!=='ball')throw Error('Object picking failed');if(pick(100,90)?.part!=='accent')throw Error('Top visible part picking failed');if(pick(158,132)!==null)throw Error('Mask failed to exclude clipped pixels from picking');
 for(const shading of ['cel','gradient']){const lit=rendererFixture(true);lit.lighting.shading=shading;await compare(shading+' surface lighting',lit,rendererFrame(lit,{'root.rotation':25}));}
 const pointLight=rendererFixture(true);Object.assign(pointLight.lighting,{type:'point',pointX:240,pointY:40,showSource:true});await compare('Point light source and wash',pointLight,rendererFrame(pointLight));
 const turn=createDemo('turn-and-pose');turn.lighting.enabled=false;const turnController=new SceneController(turn);await compare('Real spatial rigs, masks and folded limbs',turn,turnController.previewClip('ona','idle',0,{'root.yaw':45,'rightForearm.rotation':-90}));turnController.dispose();
 const gym=createGym(),gymController=new SceneController(gym);await compare('Connected mesh / bench42',gym,gymController.previewClip('atlas','full-set',42));gymController.dispose();
 const crossing=crossingMeshFixture(),drawing=evaluateDrawing(crossing,rendererFrame(crossing)),canvas=document.createElement('canvas');canvas.width=140;canvas.height=140;const depth=renderDepthCanvas(canvas.getContext('2d'),drawing),a=canvas.getContext('2d').getImageData(95,30,1,1).data,b=canvas.getContext('2d').getImageData(30,95,1,1).data;if(a[0]<=a[2]||b[2]<=b[0])throw Error('Per-pixel depth did not resolve intersecting triangles');if(depth.pick(95,30)?.part!=='red'||depth.pick(30,95)?.part!=='blue')throw Error('Depth picking disagrees with visible mesh');const card=document.createElement('section');card.className='card';card.innerHTML='<h3>Opaque mesh depth buffer · crossing triangles</h3>';card.append(canvas);document.querySelector('main').append(card);
 const host=document.createElement('div');document.body.append(host);const svg=mountSVG(host,plain,plainFrame),objectNode=host.querySelector('[data-object="ball"]');svg.update({...plainFrame,time:1,objects:[{...plain.objects[0],x:250,y:40,depth:150}]});if(host.querySelector('[data-object="ball"]')!==objectNode||!objectNode.getAttribute('transform').includes('250 40'))throw Error('Mounted shared object was not updated in place');if(host.querySelector('[data-scene-layer="characters"]').lastElementChild!==objectNode)throw Error('Dynamic object scene depth was not reordered');svg.dispose();host.remove();
 const holder=document.createElement('div');document.body.append(holder);const mounted=mountCanvas(holder,plain,plainFrame,{width:600,height:400,pixelRatio:1});if(mounted.pick(400,120)?.object!=='ball')throw Error('Canvas CSS/viewBox picking failed');mounted.update({...plainFrame,time:1,objects:[{...plain.objects[0],x:220,y:50,depth:150}]});if(mounted.pick(440,100)?.object!=='ball')throw Error('Canvas update picking stale');mounted.dispose();mounted.dispose();if(holder.children.length||mounted.pick(1,1)!==null)throw Error('Canvas disposal failed');holder.remove();const bad=rendererFixture(true);bad.lighting.reflection=.2;let rejected=false;try{mountCanvas(document.createElement('div'),bad,rendererFrame(bad));}catch(error){rejected=error.name==='CanvasCapabilityError';}if(!rejected)throw Error('Unsupported reflection silently rendered');
 return {comparisons:results,depth:{triangles:depth.triangles,candidatePixels:depth.candidatePixels},picking:true,objects:true,disposal:true};
 });await page.screenshot({path:'test-results/canvas-parity.png',fullPage:true});await fs.writeFile('test-results/canvas-parity.json',JSON.stringify(report,null,2));for(const entry of report.comparisons){assert.ok(entry.meanChannelError<6,entry.name+' mean error '+entry.meanChannelError);assert.ok(entry.largePixelFraction<.04,entry.name+' differing pixels '+entry.largePixelFraction);}console.log(JSON.stringify(report));}finally{await browser.close();await server.close();}
