import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
// Official MediaPipe test fixtures live only in ignored test-results, never in shipped assets.
const face=fs.readFileSync('test-results/vision-face.jpg').toString('base64');
const page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base)&&!r.url().startsWith('data:'))external.push(r.url());});
await page.addInitScript(({face})=>{
 window.__cameraRequests=0;window.__stopped=0;window.__tilt=0;window.__maxFrames=0;
 const Native=window.Worker;window.Worker=class extends Native{constructor(url,opts){super(url,opts);this.vision=String(url).includes('vision-worker');this.frames=0;this.addEventListener('message',e=>{if(e.data.type==='result')this.frames--;});}postMessage(m,transfer){if(this.vision&&m.type==='frame')window.__maxFrames=Math.max(window.__maxFrames,++this.frames);return super.postMessage(m,transfer);}};
 navigator.mediaDevices.getUserMedia=async options=>{window.__cameraRequests++;if(options.audio!==false)throw Error('Unexpected microphone request');
 const image=new Image();image.src='data:image/jpeg;base64,'+face;await image.decode();const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const ctx=canvas.getContext('2d');const draw=()=>{ctx.fillStyle='#777';ctx.fillRect(0,0,640,480);ctx.save();ctx.translate(320,240);ctx.rotate(window.__tilt*Math.PI/180);const scale=Math.min(640/image.width,480/image.height);ctx.drawImage(image,-image.width*scale/2,-image.height*scale/2,image.width*scale,image.height*scale);ctx.restore();};draw();const timer=setInterval(draw,60),stream=canvas.captureStream(15),track=stream.getVideoTracks()[0],stop=track.stop.bind(track);track.stop=()=>{clearInterval(timer);window.__stopped++;stop();};return stream;
 };
},{face});
try{
 await page.goto(base+'/director.html');await page.locator('[data-camera]').waitFor();await page.locator('[data-panel="perform"]').click();assert.equal(await page.evaluate(()=>window.__cameraRequests),0);
 await page.locator('#camera-start').click();await page.waitForFunction(()=>!document.querySelector('#capture-calibrate').disabled,{},{timeout:45000});await page.locator('#capture-calibrate').click();await page.locator('#capture-record').click();await page.waitForTimeout(700);await page.evaluate(()=>window.__tilt=20);await page.waitForTimeout(1200);await page.locator('#capture-record').click();await page.locator('#camera-stop').click();assert.ok(await page.evaluate(()=>window.__stopped>0));
 const save=page.waitForEvent('download');await page.locator('#take-save').click();await(await save).saveAs('test-results/webcam.take.json');const take=JSON.parse(fs.readFileSync('test-results/webcam.take.json','utf8'));assert.ok(take.duration>1);assert.ok(Math.max(...take.frames.map(f=>f.pose['head.rotation']))-Math.min(...take.frames.map(f=>f.pose['head.rotation']))>3,'real inference recorded a visible head tilt');assert.ok(take.frames.every(f=>!f.faceLandmarks&&!f.image));
 await page.locator('#take-play').click();await page.waitForTimeout(250);await page.locator('#take-play').click();await page.locator('#take-apply').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('posecraft.director.v1'))?.shots[0].actors.ona.pose);const applied=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')));assert.ok(applied.shots[0].actors.ona.expressions.length>0);await page.locator('#undo').click();assert.ok(!(await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')))).shots[0].actors.ona.pose);await page.locator('#redo').click();
 // Verify stepped facial performance survives take import, bake and timeline scrubbing.
 const expressionTake={kind:'performance-take',schemaVersion:1,duration:1,frames:[{time:0,pose:{'head.rotation':0},emotion:'neutral'},{time:.5,pose:{'head.rotation':15},emotion:'happy'},{time:1,pose:{'head.rotation':-10},emotion:'surprised'}]};await page.locator('#take-file').setInputFiles({name:'expressions.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(expressionTake))});await page.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('Loaded'));await page.locator('#take-apply').click();await page.locator('#frame-number').fill('12');await page.locator('#frame-number').press('Tab');await page.waitForTimeout(200);assert.ok((await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')))).shots[0].actors.ona.expressions.some(k=>k[0]===.5&&k[1]==='happy'));
 await page.locator('[data-panel="motion"]').click();await page.locator('#motion-emotion').selectOption('wink');await page.waitForFunction(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')).shots[0].actors.ona.expressions.some(k=>k[0]===.5&&k[1]==='wink'));await page.locator('[data-panel="perform"]').click();
 await page.screenshot({path:'test-results/director-perform.png'});
 // Leaving the panel terminates the stream; no camera resumes on return.
 await page.locator('#camera-start').click();await page.waitForFunction(()=>document.querySelector('#webcam').srcObject);await page.locator('[data-panel="camera"]').click();const count=await page.evaluate(()=>window.__cameraRequests);await page.locator('[data-panel="perform"]').click();assert.equal(await page.evaluate(()=>window.__cameraRequests),count);assert.equal(await page.locator('#webcam').evaluate(v=>v.srcObject),null);assert.equal(await page.evaluate(()=>window.__maxFrames),1);
 for(const size of [{width:1366,height:768},{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<760)await page.locator('#settings-panel').click();const box=await page.locator('#settings').boundingBox(),timeline=await page.locator('.director-timeline').boundingBox();assert.ok(box.y+box.height<=timeline.y+1,'Perform fits '+size.width);}
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 // Denial and cancellation use fake permissions and never open a physical camera.
 const denied=await browser.newPage();await denied.addInitScript(()=>{navigator.mediaDevices.getUserMedia=async()=>{throw new DOMException('Denied','NotAllowedError')};});await denied.goto(base+'/director.html');await denied.locator('[data-panel="perform"]').click();await denied.locator('#camera-start').click();await denied.waitForFunction(()=>document.querySelector('#capture-status').textContent.includes('denied'));assert.equal(await denied.locator('#camera-start').isEnabled(),true);await denied.close();
 const pending=await browser.newPage();await pending.addInitScript(()=>{window.stops=0;navigator.mediaDevices.getUserMedia=()=>new Promise(resolve=>setTimeout(()=>resolve({getTracks:()=>[{stop:()=>window.stops++}]}),300));});await pending.goto(base+'/director.html');await pending.locator('[data-panel="perform"]').click();await pending.locator('#camera-start').click();await pending.locator('#camera-stop').click();await pending.waitForFunction(()=>window.stops===1);assert.equal(await pending.locator('#webcam').evaluate(v=>v.srcObject),null);await pending.close();
 console.log('Webcam checks passed: actual face inference and head-motion recording, local take export/import, expression bake, undo/redo, one frame in flight, stream cleanup, permission denial, compact layouts, no external requests.');
}finally{await browser.close();}
