import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.activeWorkers=0;window.maxWorkers=0;window.cameraRequests=0;const Native=window.Worker;window.Worker=class extends Native{constructor(...args){super(...args);this.alive=true;window.maxWorkers=Math.max(window.maxWorkers,++window.activeWorkers);}terminate(){if(this.alive){this.alive=false;window.activeWorkers--;}super.terminate();}};navigator.mediaDevices.getUserMedia=()=>{window.cameraRequests++;throw Error('No camera in gallery');};});
const choose=async id=>{await page.locator(`[data-demo="${id}"]`).click();await page.waitForTimeout(250);await page.locator('#demo-art svg').waitFor();};
try{
 await page.goto(base+'/demos.html#www-after-hours');await page.locator('#demo-art [data-camera]').waitFor();assert.equal(await page.locator('[data-demo]').count(),15);assert.equal(await page.locator('#demo-art [data-actor]').count(),3);
 await page.locator('#demo-play').click();await page.locator('[data-shot="goodnight"]').click();await page.waitForFunction(()=>document.querySelector('#demo-caption').textContent.includes('last word'));assert.ok((await page.locator('#demo-art [data-camera]').getAttribute('transform')).includes('scale(2.4'));
 await choose('neon-rehearsal');assert.equal(await page.locator('#demo-art [data-actor]').count(),4);await page.locator('[data-shot="curtain-call"]').click();await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.includes('After the show'));
 await choose('rusty-in-the-park');assert.equal(await page.locator('#demo-art [data-actor]').count(),2);await page.locator('[data-shot="a-paw"]').click();
 await choose('drop-lab');const head=page.locator('#demo-art [data-actor="loose"] [data-joint="head"]').first(),before=await head.getAttribute('transform');await page.locator('#drop-cast').click();await page.waitForFunction(value=>document.querySelector('#demo-art [data-actor="loose"] [data-joint="head"]').getAttribute('transform')!==value,before);await page.waitForTimeout(1600);assert.ok((await page.locator('#demo-status').textContent()).startsWith('Live'));await page.locator('#catch-cast').click();await page.locator('#collision-boxes').click();assert.equal(await page.locator('#demo-art [data-collider]').count(),0);
 await choose('zero-gravity');const stage=await page.locator('#demo-stage').boundingBox();await page.mouse.move(stage.x+stage.width/2,stage.y+stage.height/2);await page.mouse.down();await page.mouse.move(stage.x+stage.width/2+45,stage.y+stage.height/2+20,{steps:6});await page.mouse.up();assert.ok((await page.locator('#demo-stage').getAttribute('style')).replaceAll(' ','').includes('translate(45px,20px)'));await page.locator('#nudge-cast').click();await page.locator('#curl-cast').click();await page.locator('#float-cast').click();
 await choose('expression-ensemble');await page.locator('#demo-target').selectOption('ona');await page.locator('#ensemble-emotion').selectOption('wink');await page.waitForFunction(()=>document.querySelector('#demo-art [data-actor="ona"]').dataset.emotion==='wink');assert.equal(await page.locator('#demo-art [data-actor="wwwzard"]').getAttribute('data-emotion'),'neutral');await page.locator('#demo-target').selectOption('all');await page.locator('#ensemble-emotion').selectOption('surprised');await page.waitForFunction(()=>[...document.querySelectorAll('#demo-art [data-actor]')].every(e=>e.dataset.emotion==='surprised'));await page.locator('#dance-cast').click();await page.locator('#demo-sound').click();assert.equal(await page.locator('#demo-sound').getAttribute('aria-label'),'Mute interaction sounds');await page.locator('#pet-cast').click();
 const download=page.waitForEvent('download');await page.locator('#download-demo').click();await(await download).saveAs('test-results/demo.scene.json');assert.equal(JSON.parse(fs.readFileSync('test-results/demo.scene.json','utf8')).actors.length,4);assert.equal(await page.evaluate(()=>window.maxWorkers),1);assert.equal(await page.evaluate(()=>window.cameraRequests),0);
 await page.screenshot({path:'test-results/demos-gallery.png'});
 // Gallery projects have separate storage and never overwrite either regular editor draft.
 await page.evaluate(()=>{localStorage.setItem('posecraft.studio.v2','sentinel-studio');localStorage.setItem('posecraft.director.v1','sentinel-director');});await page.locator('#edit-demo').click();await page.locator('#actors option').nth(3).waitFor({state:'attached'});assert.equal(await page.locator('#actors option').count(),4);await page.locator('#character-workspace').click();await page.locator('#demo-action').selectOption('wave');assert.equal(await page.evaluate(()=>localStorage.getItem('posecraft.studio.v2')),'sentinel-studio');assert.ok(await page.evaluate(()=>localStorage.getItem('posecraft.studio.v2.demo.expression-ensemble')));
 await page.goto(base+'/demos.html#www-after-hours');await page.locator('#edit-demo').click();await page.locator('[data-shot]').nth(2).waitFor();await page.locator('#episode-name').fill('My demo copy');await page.locator('#episode-name').press('Tab');assert.equal(await page.evaluate(()=>localStorage.getItem('posecraft.director.v1')),'sentinel-director');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.director.v1.demo.www-after-hours')).name),'My demo copy');
 await page.goto(base+'/demos.html#www-after-hours');await page.locator('#demo-art svg').waitFor();for(const size of [{width:1366,height:768},{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);for(const id of ['www-after-hours','drop-lab','expression-ensemble','shake-and-settle']){await choose(id);assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1&&document.documentElement.scrollWidth<=innerWidth+1),'No page scrolling '+size.width+' '+id);const footer=await page.locator('.demo-footer').boundingBox();assert.ok(footer.y+footer.height<=size.height+1,'Footer fits '+size.width+' '+id);const art=await page.locator('#demo-art').boundingBox();assert.ok(art.width>200&&art.height>100,'Visible preview');}}await page.screenshot({path:'test-results/demos-mobile.png'});
 assert.deepEqual(errors,[]);console.log('Gallery checks passed: thirteen demos, shot cuts, multi-cast acting, live physics, container drag, scoped expressions, sound opt-in, one active worker, export, isolated editable copies, compact layouts.');
}finally{await browser.close();}
