import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'no-preference'}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')));
const frame=async n=>{await page.locator('#frame-number').fill(String(n));await page.locator('#frame-number').press('Tab');await page.waitForTimeout(80);};
try{
 await page.goto(base+'/director.html');await page.locator('[data-camera]').waitFor();assert.equal(await page.locator('[data-shot]').count(),3);assert.equal(await page.locator('#scene-select option').count(),2);
 await page.screenshot({path:'test-results/director.png'});
 await page.locator('[data-panel="camera"]').click();const film=await page.locator('#film').boundingBox(),initialX=+(await page.locator('#camera-x').inputValue());await page.mouse.move(film.x+40,film.y+40);await page.mouse.down();await page.mouse.move(film.x+60,film.y+40,{steps:5});await page.mouse.up();assert.ok(+(await page.locator('#camera-x').inputValue())<initialX);await page.locator('#camera-zoom').fill('1.4');await page.locator('#camera-zoom').dispatchEvent('input');await page.locator('#camera-key').click();assert.equal((await saved()).shots[0].camera.zoom[0][1],1.4);
 await frame(24);await page.locator('#camera-x').fill('250');await page.locator('#camera-x').dispatchEvent('input');await page.locator('#camera-key').click();assert.ok((await saved()).shots[0].camera.x.some(k=>k[0]===1&&k[1]===250));await page.locator('#undo').click();assert.equal((await saved()).shots[0].camera.x.length,1);await page.locator('#redo').click();
 await page.locator('[data-panel="place"]').click();await page.locator('#place-x').fill('170');await page.locator('#place-key').click();assert.equal((await saved()).shots[0].actors.ona.placement.x[0][1],170);
 await page.locator('[data-panel="motion"]').click();await page.locator('#motion-clip').selectOption('wave');await page.locator('#motion-kind').selectOption('noise');await page.locator('#motion-seed').fill('73');await page.locator('#motion-seed').press('Tab');assert.equal((await saved()).shots[0].actors.ona.motion.seed,73);
 await page.locator('#bake-motion').click();await page.waitForFunction(()=>!JSON.parse(localStorage.getItem('posecraft.director.v1')).shots[0].actors.ona.motion);assert.equal((await saved()).shots[0].actors.ona.pose['head.rotation'].length,73);
 await page.locator('#copy-shot').click();assert.equal(await page.locator('[data-shot]').count(),4);await page.locator('#copy-scene').click();assert.equal(await page.locator('#scene-select option').count(),3);await page.locator('#delete-shot').click();assert.equal(await page.locator('[data-shot]').count(),3);
 await page.locator('[data-shot="inside"]').click();await page.waitForFunction(()=>document.querySelector('#film-caption').textContent.includes('workshop'));
 await page.locator('[data-panel="reference"]').click();
 // Generate an original two-color video in the browser to verify local decoding.
 const media=await page.evaluate(async()=>{const c=document.createElement('canvas');c.width=320;c.height=180;const ctx=c.getContext('2d'),stream=c.captureStream(12),recorder=new MediaRecorder(stream,{mimeType:'video/webm'}),chunks=[];recorder.ondataavailable=e=>chunks.push(e.data);const result=new Promise(resolve=>recorder.onstop=async()=>resolve([...new Uint8Array(await new Blob(chunks).arrayBuffer())]));recorder.start();for(let i=0;i<18;i++){ctx.fillStyle=i<9?'#ea5555':'#3377cc';ctx.fillRect(0,0,320,180);await new Promise(r=>setTimeout(r,85));}recorder.stop();stream.getTracks().forEach(t=>t.stop());return result;});
 await page.locator('#media-file').setInputFiles({name:'original-test.webm',mimeType:'video/webm',buffer:Buffer.from(media)});await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);
 await page.locator('#source-time').fill('1.1');await page.locator('#capture').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('posecraft.director.v1')).shots.find(s=>s.id==='inside').reference);
 await page.locator('#reference-overlay:not(.hidden)').waitFor();await page.locator('#reference-difference').check();assert.equal(await page.locator('#reference-overlay').evaluate(e=>getComputedStyle(e).mixBlendMode),'difference');
 const referenceDownload=page.waitForEvent('download');await page.locator('#download-reference').click();await(await referenceDownload).saveAs('test-results/director-reference.png');
 const pixel=await page.evaluate(async data=>{const image=new Image();image.src='data:image/png;base64,'+data;await image.decode();const c=document.createElement('canvas');c.width=1;c.height=1;const ctx=c.getContext('2d');ctx.drawImage(image,0,0,1,1);return [...ctx.getImageData(0,0,1,1).data];},fs.readFileSync('test-results/director-reference.png').toString('base64'));assert.ok(pixel[2]>170&&pixel[0]<100,'captured the later blue frame, not the earlier red frame');
 await page.screenshot({path:'test-results/director-reference-view.png'});
 const save=page.waitForEvent('download');await page.locator('#save').click();await(await save).saveAs('test-results/director.episode.json');await page.locator('#project-file').setInputFiles('test-results/director.episode.json');await page.locator('[data-camera]').waitFor();
 await page.locator('[data-shot="inside"]').click();await page.locator('#reference-overlay:not(.hidden)').waitFor();
 for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<760)await page.locator('#settings-panel').click();for(const panel of ['shot','camera','motion','place','reference']){await page.locator(`[data-panel="${panel}"]`).click();const settings=await page.locator('#settings').boundingBox(),timeline=await page.locator('.director-timeline').boundingBox();assert.ok(settings.y+settings.height<=timeline.y+1,`${panel} controls fit ${size.width}x${size.height}`);}assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1));}
 assert.deepEqual(errors,[]);console.log('Director checks passed: scenes/shots, camera and placement keys, undo/redo, noise bake, local video capture, reference persistence, export/import, compact layouts.');
}finally{await browser.close();}
