import test from 'node:test';
import assert from 'node:assert/strict';
import {DocumentStore} from '../src/commands.js';
import {createDrawing,shapePath,assignArtwork,movePivot,reparentJoint,jointMatrices,parseTransform,multiply,validatePath} from '../src/vector-authoring.js';
const close=(a,b)=>a.forEach((v,i)=>assert.ok(Math.abs(v-b[i])<1e-6,`${a} != ${b}`));
function drawing(){const doc=createDrawing(),p=doc.packs.drawing;p.joints.push({id:'arm',parent:'root',x:40,y:90,rotation:30,min:-90,max:90,length:30});p.parts.push({id:'hand',joint:'root',d:shapePath('ellipse'),fill:'#acbdef',transform:'translate(10 20)'});return doc;}
const placement=(p)=>{const a=p.parts[0];return multiply(jointMatrices(p)[a.joint],parseTransform(a.transform));};
test('Draw artwork assignment, pivot edits and reparenting preserve world placement',()=>{const doc=drawing(),original=placement(doc.packs.drawing);let p=assignArtwork(doc.packs.drawing,'hand','arm');close(placement(p),original);p=movePivot(p,'arm',100,130);close(placement(p),original);p=reparentJoint(p,'arm',null);close(placement(p),original);assert.throws(()=>reparentJoint(doc.packs.drawing,'root','arm'),/ancestor/);});
test('Draw changes validate atomically and undo/redo restore artwork and rig',()=>{const store=new DocumentStore(drawing());const next=assignArtwork(store.document.packs.drawing,'hand','arm');store.transact([{op:'set',path:['packs','drawing'],value:next}]);assert.equal(store.document.packs.drawing.parts[0].joint,'arm');store.undo();assert.equal(store.document.packs.drawing.parts[0].joint,'root');store.redo();assert.equal(store.document.packs.drawing.parts[0].joint,'arm');const revision=store.document.revision;assert.throws(()=>store.transact([{op:'set',path:['packs','drawing','parts',0,'fill'],value:'url(https://bad)'}]));assert.equal(store.document.revision,revision);});
test('Pivot changes keep descendants in place and affine parser rejects unsupported transforms',()=>{const p=drawing().packs.drawing;p.joints.push({id:'wrist',parent:'arm',x:30,y:10,rotation:10,min:-90,max:90,length:20});const before=jointMatrices(p);const after=jointMatrices(movePivot(p,'arm',50,120));close(before.wrist,after.wrist);close(parseTransform('translate(10,20) rotate(90) scale(2)'),[0,2,-2,0,10,20]);for(const t of ['skewX(20)','scale(1e999)','rotate(4 2)','translate(4) garbage'])assert.throws(()=>parseTransform(t));});

test('Draw path edits reject incomplete geometry and nonfinite coordinates',()=>{assert.equal(validatePath('M0 0C1 2 3 4 5 6Z'),'M0 0C1 2 3 4 5 6Z');for(const path of ['M0','M0 0L','M0 0A4 4 0 2 0 8 8','M0 0L1e999 2'])assert.throws(()=>validatePath(path));});
