import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
try{const page=await browser.newPage({viewport:{width:1280,height:800}});const base=process.env.POSECRAFT_URL||'http://127.0.0.1:5178';const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'/draw.html');await page.locator('#new').click();await page.locator('[data-shape="ellipse"]').click();assert.equal(await page.locator('#art [data-part]').count(),1);await page.locator('#fill').fill('#ff9944');await page.locator('#fill').press('Tab');await page.locator('#undo').click();assert.equal(await page.locator('#fill').inputValue(),'#b7a0de');await page.locator('#redo').click();assert.equal(await page.locator('#fill').inputValue(),'#ff9944');await page.locator('#add-joint').click();await page.locator('#art-tab').click();await page.locator('#attached').selectOption('joint-1');const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);assert.equal(download.suggestedFilename(),'posecraft-drawing.json');
const importFile=svg=>page.locator('#svg-file').setInputFiles({name:'art.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});
await importFile('<svg xmlns="http://www.w3.org/2000/svg" viewBox="10 20 200 100"><g transform="translate(20 30) rotate(10)" fill="#123456"><rect width="20" height="30"/></g></svg>');await page.waitForFunction(()=>document.querySelector('#fill').value==='#123456');const valid=await page.evaluate(()=>localStorage.getItem('posecraft.draw.v1'));assert.equal(JSON.parse(valid).bounds.width,200);
for(const bad of ['<script/>','<image href="https://example.org/a.png"/>','<foreignObject/>','<path style="fill:red" d="M0 0L1 1"/>','<g transform="skewX(20)"><path d="M0 0L1 1"/></g>','<path fill="url(#a)" d="M0 0L1 1"/>','<path onclick="alert(1)" d="M0 0L1 1"/>']){await importFile('<svg xmlns="http://www.w3.org/2000/svg">'+bad+'</svg>');await page.waitForFunction(()=>document.querySelector('#svg-file').value==='');assert.equal(await page.evaluate(()=>localStorage.getItem('posecraft.draw.v1')),valid);}

await page.locator('#svg-file').setInputFiles({name:'simple.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path fill="#123456" d="M10 10L90 10L50 90Z"/></svg>')});assert.equal(await page.locator('#fill').inputValue(),'#123456');await page.reload();assert.equal(await page.locator('#fill').inputValue(),'#123456');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/draw-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight));await page.locator('#studio').click();await page.waitForURL('**/?from=draw');assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2.draw')).packs.drawing.parts[0].fill),'#123456');assert.deepEqual(errors,[]);console.log('Draw checks passed: safe SVG subset, shape editing, undo/redo, attachment, save/reopen, Studio transfer and mobile fit.');}finally{await browser.close();}
