import test from 'node:test';import assert from'node:assert/strict';import{SceneController,STEP}from'../src/scene.js';import{createDemo}from'../examples/showcase.js';
const document=()=>{const d=createDemo('shake-and-settle');for(const a of d.actors)a.behavior={...a.behavior,mode:'animated',autoRecover:false};return d;};
const advance=(c,t)=>{for(let i=0;i<Math.ceil(t/STEP);i++)c.step(STEP);};const rootX=(c,id)=>{const a=c.document.actors.find(a=>a.id===id),f=c.frame().actors.find(a=>a.id===id),p=c.document.packs[a.pack];return a.transform.x+f.world[p.physics.root].x*a.transform.scale;};
test('one-cycle clip commands use simulation time, pause, concurrency and resume authored animation',()=>{const d=document();d.packs[d.actors.find(a=>a.id==='ona').pack].clips.wave.loop=true;const c=new SceneController(d),events=[];c.subscribe(e=>events.push(e));for(const id of ['ona','dummy']){const a=c.actors.find(a=>a.actor.id===id),clip=Object.keys(a.pack.clips).find(k=>k==='wave')??'idle';c.gameCommand({type:'action',actor:id,request:id,clip});}c.pause();advance(c,5);assert.equal(events.filter(e=>e.type==='actor.command.completed').length,0);c.play();advance(c,8);assert.equal(events.filter(e=>e.type==='actor.command.completed').length,2);const before=c.frame().actors.find(a=>a.id==='ona').pose;advance(c,2);assert.notDeepEqual(c.frame().actors.find(a=>a.id==='ona').pose,before);assert.equal(c.log.length,0);c.dispose();});
test('move completes at actual ground target and following action retains placement',()=>{const c=new SceneController(document()),events=[];c.subscribe(e=>events.push(e));const start=rootX(c,'ona'),target=start+70;c.gameCommand({type:'move',actor:'ona',request:'walk',x:target});advance(c,2);assert.ok(Math.abs(rootX(c,'ona')-target)<.01);assert.ok(events.some(e=>e.request==='walk'&&e.type==='actor.command.completed'));c.gameCommand({type:'action',actor:'ona',request:'wave',clip:'wave'});advance(c,.5);assert.ok(Math.abs(rootX(c,'ona')-target)<.01);c.dispose();});
test('cancel and replace preserve walked location; seek reset and disposal reject pending requests',()=>{const c=new SceneController(document()),events=[];c.subscribe(e=>events.push(e));c.gameCommand({type:'move',actor:'ona',request:'walk',x:rootX(c,'ona')+120});advance(c,.2);const x=rootX(c,'ona');c.gameCommand({type:'cancel',actor:'ona',request:'walk'});advance(c,1);assert.ok(Math.abs(rootX(c,'ona')-x)<.01);for(const [request,operation]of [['replace',()=>c.gameCommand({type:'action',actor:'ona',request:'seek',clip:'wave'})],['seek',()=>c.seek(0)],['reset',()=>c.reset()],['dispose',()=>c.dispose()]]){if(request!=='seek')c.gameCommand({type:'action',actor:'ona',request,clip:'wave'});operation();assert.ok(events.some(e=>e.request===request&&e.type==='actor.command.failed'&&e.cancelled));}});
test('reduced motion completes static actions and gaze, animation pause does not advance',()=>{const c=new SceneController(document(),{reducedMotion:true}),events=[];c.subscribe(e=>events.push(e));c.gameCommand({type:'look',actor:'ona',request:'look',joint:'head',target:{x:700,y:30},maxAngle:15,duration:2});assert.ok(events.some(e=>e.request==='look'&&e.type==='actor.command.completed'));assert.ok(Math.abs(c.frame().actors.find(a=>a.id==='ona').pose['head.rotation']-c.gamePerformance.held.get('ona').base['head.rotation'])<=15.001);c.animationPlaying=false;c.gameCommand({type:'action',actor:'ona',request:'a',clip:'wave'});advance(c,3);assert.ok(!events.some(e=>e.request==='a'));c.animationPlaying=true;advance(c,STEP);assert.ok(events.some(e=>e.request==='a'));c.dispose();});
test('unreachable bounds and blocked routes fail rather than claim arrival',()=>{const d=document(),wall=structuredClone(d.props.find(p=>p.collider.enabled));wall.id='blocking-wall';wall.x=520;wall.y=330;wall.rotation=0;wall.collider={...wall.collider,enabled:true,x:0,y:0,width:30,height:160};d.props.push(wall);const c=new SceneController(d),events=[];c.subscribe(e=>events.push(e));c.gameCommand({type:'move',actor:'dummy',request:'blocked',x:400});c.gameCommand({type:'move',actor:'ona',request:'clamped',x:0});assert.ok(events.some(e=>e.request==='blocked'&&/blocked/.test(e.error)));assert.ok(events.some(e=>e.request==='clamped'&&/clamped/.test(e.error)));assert.throws(()=>c.gameCommand({type:'action',actor:'ona',request:'bad',clip:'constructor'}),/clip/);c.dispose();});
test('completion keeps the exact end then eases to live idle without root drift; entries use visible pose',()=>{
 const d=document(),pack=d.packs[d.actors.find(a=>a.id==='ona').pack];pack.clips.wave={duration:.3,loop:true,tracks:{'head.rotation':[[0,20],[.3,-20]]}};
 const c=new SceneController(d),pose=()=>c.frame().actors.find(a=>a.id==='ona').pose;let completed;
 c.subscribe(e=>{if(e.request==='a'&&e.type==='actor.command.completed')completed={...pose()};});
 const start=pose()['head.rotation'];c.gameCommand({type:'action',actor:'ona',request:'a',clip:'wave'});assert.equal(pose()['head.rotation'],start);advance(c,.3);assert.equal(completed['head.rotation'],-20);assert.equal(pose()['head.rotation'],-20);
 c.pause();advance(c,1);assert.equal(pose()['head.rotation'],-20);c.play();advance(c,.1);assert.ok(pose()['head.rotation']>-20&&pose()['head.rotation']<10);
 const visible={...pose()};c.gameCommand({type:'action',actor:'ona',request:'b',clip:'wave'});assert.equal(pose()['head.rotation'],visible['head.rotation']);advance(c,.6);assert.notEqual(pose()['head.rotation'],-20);
 c.setInput('ona','action','wave');advance(c,.4);const changed=pose()['head.rotation'];advance(c,.15);assert.notEqual(pose()['head.rotation'],changed);
 const target=rootX(c,'ona')+40;c.gameCommand({type:'move',actor:'ona',request:'move',x:target});advance(c,1);for(let i=0;i<40;i++){c.step(STEP);assert.ok(Math.abs(rootX(c,'ona')-target)<.01);}c.dispose();
});
test('physics, previews and external walking take ownership without stale game root overlays',()=>{
 const c=new SceneController(document()),events=[];c.subscribe(e=>events.push(e));const target=rootX(c,'ona')+50;c.gameCommand({type:'move',actor:'ona',request:'move',x:target});advance(c,1);assert.ok(Math.abs(rootX(c,'ona')-target)<.01);
 c.setBehavior('ona',{mode:'ragdoll',autoRecover:false});const entry=c.actors.find(a=>a.actor.id==='ona');advance(c,.15);const actual=c.frame().actors.find(a=>a.id==='ona'),physical=entry.physics.apply(actual.pose);assert.deepEqual(actual.world,physical.world);assert.equal(c.gamePerformance.ground.has('ona'),false);
 c.setBehavior('ona',{mode:'animated'});c.gameCommand({type:'action',actor:'ona',request:'preview-interrupt',clip:'wave'});c.previewClip('ona','idle',0,{'root.x':42});assert.equal(c.frame().actors.find(a=>a.id==='ona').pose['root.x'],42);assert.ok(events.some(e=>e.request==='preview-interrupt'&&e.cancelled));c.clearPreview('ona');
 c.gameCommand({type:'move',actor:'ona',request:'move-again',x:target});advance(c,1);c.walkTo('ona',target+35);c.frame();assert.equal(c.gamePerformance.ground.has('ona'),false);advance(c,1);assert.ok(Math.abs(rootX(c,'ona')-(target+35))<.01);c.dispose();
});
