import test from 'node:test';
import assert from 'node:assert/strict';
import {hairShellPath} from '../src/hair-shell.js';
const shell={width:43,height:33,depth:31,y:-22},styles=['short','swept','curls','bob','ponytail'];
const matrix=(yaw,pitch=0)=>{const y=yaw*Math.PI/180,p=pitch*Math.PI/180,c=Math.cos,s=Math.sin;return [c(y),s(y)*s(p),s(y)*c(p),0,c(p),-s(p),-s(y),c(y)*s(p),c(y)*c(p)];};
function shape(path){const polygons=path.split('M').slice(1).map(part=>{const values=part.match(/-?\d+(?:\.\d+)?/g).map(Number);return Array.from({length:values.length/2},(_,i)=>[values[i*2],values[i*2+1]]);}),points=polygons.flat(),xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);return {polygons,points,bounds:[Math.min(...xs),Math.max(...xs),Math.min(...ys),Math.max(...ys)],area:polygons.reduce((sum,p)=>sum+Math.abs(p.reduce((area,a,i)=>{const b=p[(i+1)%p.length];return area+a[0]*b[1]-b[0]*a[1];},0)/2),0)};}
function edgeAtX(polygon,x){const ys=[];for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length];if((a[0]<=x&&b[0]>x)||(b[0]<=x&&a[0]>x)){const t=(x-a[0])/(b[0]-a[0]);ys.push(a[1]+(b[1]-a[1])*t);}}return ys;}
test('Each opaque hairstyle exposes forehead and has a distinct front silhouette',()=>{const paths=styles.map(style=>hairShellPath(shell,matrix(0),style));assert.equal(new Set(paths).size,styles.length);for(const [i,path] of paths.entries()){const geometry=shape(path),bottom=Math.max(...geometry.polygons.flatMap(p=>edgeAtX(p,0)));assert.ok(bottom<-27,`${styles[i]} central hairline ${bottom} covers forehead`);assert.ok(geometry.area>700);assert.ok(geometry.bounds[2]<-54);assert.equal(geometry.polygons.length,1);}const curls=shape(paths[2]),short=shape(paths[0]);assert.ok(curls.bounds[2]<short.bounds[2]-2,'Curls retain their raised crown.');});
test('Opaque hair contours stay bounded and continuous through full turns and tilted views',()=>{for(const style of styles)for(const pitch of [-30,0,30]){let previous;for(let yaw=-180;yaw<=180;yaw+=2){const path=hairShellPath(shell,matrix(yaw,pitch),style),geometry=shape(path);assert.ok(!/NaN|Infinity/.test(path));assert.ok(geometry.polygons.length<=2,`${style} fragmented at ${yaw}/${pitch}`);assert.ok(geometry.points.length<150);assert.ok(geometry.area>400);if(previous){assert.ok(geometry.bounds.every((n,i)=>Math.abs(n-previous.bounds[i])<6),`${style} bounds pop at ${yaw}/${pitch}`);}previous=geometry;}}});
test('Hair geometry is deterministic and style switching does not mutate cached shells',()=>{const copy=structuredClone(shell),expected=hairShellPath(shell,matrix(45,15),'curls');for(const style of styles)hairShellPath(shell,matrix(100),style);assert.equal(hairShellPath(shell,matrix(45,15),'curls'),expected);assert.deepEqual(shell,copy);assert.equal(hairShellPath(shell,matrix(45),'unknown'),hairShellPath(shell,matrix(45),'short'));});

test('Hair visibility crossings have no discrete contour jumps',()=>{for(const style of styles)for(const pitch of [-30,0,30])for(let yaw=-180;yaw<=180;yaw+=3){const a=shape(hairShellPath(shell,matrix(yaw-.001,pitch),style)),b=shape(hairShellPath(shell,matrix(yaw+.001,pitch),style));assert.ok(Math.abs(a.area-b.area)/a.area<.003,`${style} area discontinuity at ${yaw}/${pitch}`);assert.ok(a.bounds.every((v,i)=>Math.abs(v-b.bounds[i])<.12),`${style} contour discontinuity at ${yaw}/${pitch}`);}});
