import {applyMotionLayers} from '../src/motion-layers.js';
import {ActorBehaviorRuntime} from '../src/actor-behaviors.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {IllustrationController} from '../src/illustration.js';import {ReplayCheckpoints} from '../src/replay-checkpoints.js';
import {createCampfire} from '../examples/campfire.js';import {createBottle} from '../examples/bottle.js';import {CampfireEnsemble} from '../src/ensemble.js';import {BehaviorRuntime} from '../src/behaviors.js';import {BottleFluid} from '../src/bottle-fluid.js';import {ScenePointerInteraction} from '../src/pointer-interactions.js';import {applyContacts} from '../src/contacts.js';import {createDrawing} from '../src/vector-authoring.js';
const providers={motionLayerSolver:applyMotionLayers,actorBehaviorFactory:ActorBehaviorRuntime,ensembleFactory:CampfireEnsemble,behaviorFactory:BehaviorRuntime,fluidFactory:BottleFluid,pointerFactory:ScenePointerInteraction,contactSolver:applyContacts};
function fixture(){const d=createDrawing();d.packs.drawing.clips.idle={duration:2,loop:true,tracks:{'root.rotation':[[0,-20,'linear'],[2,20,'linear']]},events:[{time:1,name:'beat'}]};d.packs.drawing.inputs={speed:{type:'number',default:0,min:0,max:1}};return d;}
function pair(d,limits={}){return [new IllustrationController(d,{...providers,checkpoints:{interval:.5,...limits}}),new IllustrationController(d,{...providers,checkpoints:false})];}
function equalAt(a,b,t){assert.deepEqual(a.seek(t),b.seek(t));}

test('cached illustration seeks reproduce animation, input edits and subsequent event delivery',()=>{const [a,b]=pair(fixture());try{for(const c of[a,b]){c.seek(1);c.setInput('character','speed',.7);c.setAcceleration(400,100);}equalAt(a,b,12);for(const t of[8.2,4.5,11.1])equalAt(a,b,t);assert.ok(a.checkpointStats().hits>=3);assert.ok(a.checkpointStats().replayedTicks<=61);const events=[[],[]];a.subscribe(e=>events[0].push(e));b.subscribe(e=>events[1].push(e));for(let i=0;i<12;i++){a.step(.1);b.step(.1);}assert.deepEqual(a.frame(),b.frame());assert.deepEqual(events[0],events[1]);for(const c of[a,b]){c.seek(2);c.setInput('character','speed',.2);}equalAt(a,b,9);assert.equal(a.frame().actors[0].inputs.speed,.2);a.log[0].value=.4;b.log[0].value=.4;equalAt(a,b,10);assert.equal(a.frame().actors[0].inputs.speed,.2);a.document.revision++;b.document.revision++;equalAt(a,b,8);assert.ok(a.checkpointStats().misses>0);}finally{a.dispose();b.dispose();}});

test('checkpoint data and count remain bounded and an oversized state falls back to replay',()=>{const cache=new ReplayCheckpoints({maxBytes:1024,maxEntries:2,interval:.1});cache.store(1,0,{text:'a'});cache.store(2,0,{text:'b'});cache.store(3,0,{text:'c'});assert.equal(cache.stats().entries,2);assert.ok(cache.stats().bytes<=1024);assert.equal(cache.store(4,0,{text:'x'.repeat(2000)}),false);const[a,b]=pair(fixture(),{maxBytes:1024,maxEntries:2});try{equalAt(a,b,3);equalAt(a,b,2);assert.ok(a.checkpointStats().bytes<=1024);assert.equal(a.checkpointStats().entries,0);assert.match(a.checkpointStats().reason,/budget/);}finally{a.dispose();b.dispose();}});

test('campfire cached replay preserves seeded social state, fire dependencies and pointer springs',()=>{const[a,b]=pair(createCampfire());try{for(const c of[a,b]){c.seek(1);c.triggerEnsemble('share-help');c.seek(2);c.dispatch('extinguish-fire');c.seek(3);const binding=c.document.interactions.find(v=>v.gesture==='drag'&&v.response==='resist');c.pointer({binding:binding.id,phase:'start',x:250,y:220});c.pointer({binding:binding.id,phase:'move',x:280,y:235});}equalAt(a,b,15);equalAt(a,b,8.7);equalAt(a,b,14.1);assert.ok(a.checkpointStats().hits>=2);for(const c of[a,b])c.pointer({binding:c.document.interactions.find(v=>v.gesture==='drag'&&v.response==='resist').id,phase:'end',x:280,y:235});equalAt(a,b,17);}finally{a.dispose();b.dispose();}});

test('bottle checkpoints preserve waves, droplets, held anchors and manual-step replay',()=>{const[a,b]=pair(createBottle());try{for(const c of[a,b]){c.seek(.5);c.fluidInput({type:'nudge',ax:650,ay:180});c.seek(1);c.fluidInput({type:'motion',ax:180,ay:80,turn:14,gravityX:.3,gravityY:.9});c.seek(1.4);c.pause();c.fluidInput({type:'wind',value:1.2});c.play();}equalAt(a,b,4);equalAt(a,b,2.3);equalAt(a,b,3.6);assert.ok(a.checkpointStats().hits>=2);assert.ok(a.checkpointStats().replayedTicks<=61);}finally{a.dispose();b.dispose();}});
import {SceneController} from '../src/scene.js';
import fs from 'node:fs';

test('seeded activity choices and effects replay through illustration and animated full checkpoints',()=>{
 const d=fixture(),p=d.packs.drawing;p.clips.other={duration:1.4,loop:false,tracks:{'root.x':[[0,0],[1.4,30]]}};d.behaviorGraph={seed:731,variables:{wins:0},initial:'idle',states:{idle:{actions:[]}},edges:[],handlers:[{event:'go',actions:[{type:'perform',activity:'work'}]},{event:'done',actions:[{type:'perform',activity:'work'}]}],activities:{work:{actor:'character',variants:[{id:'first',clip:'idle',weight:1,speed:{min:.8,max:1.2},offsets:{'root.x':{min:-5,max:5}}},{id:'second',clip:'other',weight:2,speed:{min:.7,max:1.3}}],success:{base:1,modifiers:[]},onStart:[],onSuccess:[{type:'add',variable:'wins',value:1},{type:'event',event:'done'}],onFailure:[]}}};
 for(const Controller of[IllustrationController,SceneController]){const a=new Controller(d,{...providers,checkpoints:{interval:.5}}),b=new Controller(d,{...providers,checkpoints:false});try{a.dispatch('go');b.dispatch('go');for(const t of[12,8.25,4.2,11.9])equalAt(a,b,t);assert.ok(a.frame().behavior.variables.wins>=3);assert.ok(a.checkpointStats().hits>=3);assert.ok(a.checkpointStats().replayedTicks<=61);}finally{a.dispose();b.dispose();}}
});

test('full controller refuses to cache active physical solver states',()=>{const d=JSON.parse(fs.readFileSync(new URL('../examples/characters/ona.json',import.meta.url))),a=new SceneController(d,{checkpoints:{interval:.5}}),b=new SceneController(d,{checkpoints:false}),id=d.actors[0].id;try{a.setBehavior(id,{mode:'ragdoll',autoRecover:false});b.setBehavior(id,{mode:'ragdoll',autoRecover:false});equalAt(a,b,2);equalAt(a,b,1.2);assert.equal(a.checkpointStats().entries,0);assert.match(a.checkpointStats().reason,/Physical solver/);}finally{a.dispose();b.dispose();}});

test('checkpoint history accounting is bounded and edits at old times invalidate retained snapshots',()=>{const c=new ReplayCheckpoints({maxBytes:4096});const log=[{time:0,type:'input',value:1}];c.syncHistory(log);c.store(1,1,{value:1});c.syncHistory([{...log[0],value:2}]);assert.equal(c.stats().entries,0);c.syncHistory(Array.from({length:200},(_,i)=>({time:i,type:'input',value:'x'.repeat(20)})));assert.ok(c.stats().bytes<=4096);assert.equal(c.store(2,200,{value:1}),false);});
import {createCatch} from '../examples/catch.js';import {SceneObjects} from '../src/scene-objects.js';import {PropGameRuntime} from '../src/prop-games.js';
test('shared object and catch planning snapshots preserve exact full/lite replay and commands',()=>{const d=createCatch();for(const C of[IllustrationController,SceneController]){const a=new C(d,{...providers,objectFactory:SceneObjects,gameFactory:PropGameRuntime,checkpoints:{interval:.5}}),b=new C(d,{...providers,objectFactory:SceneObjects,gameFactory:PropGameRuntime,checkpoints:false});try{for(const t of[6,3.2,5.8])equalAt(a,b,t);assert.ok(a.checkpointStats().hits>=2);for(const c of[a,b])c.objectCommand({type:'impulse',object:'ball',vx:12,vy:-20});equalAt(a,b,7);}finally{a.dispose();b.dispose();}}});
