import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'reduce'}),errors=[];
page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
const slider=async(id,value)=>{await page.locator(`[data-light-control="${id}"]`).fill(String(value));await page.locator(`[data-light-control="${id}"]`).dispatchEvent('input');};
try{
 await page.goto(base+'/demos.html#light-and-shade');await page.locator('#demo-art svg').waitFor();
 assert.equal(await page.locator('#demo-shading').inputValue(),'cel');await page.screenshot({path:'test-results/cel-shading.png'});const sharp=await page.locator('#demo-art').innerHTML();await page.locator('#demo-shading').selectOption('gradient');assert.equal(await page.locator('#demo-art [data-shading="cel"]').count(),0);assert.notEqual(await page.locator('#demo-art').innerHTML(),sharp);await page.locator('#demo-shading').selectOption('cel');
 assert.equal(await page.locator('#demo-art [data-floor-shadow]').count(),2);assert.equal(await page.locator('#demo-art [data-reflection]').count(),2);
 // Rasterize the actual SVG to prove each effect contributes visible pixels.
 const pixels=await page.locator('#demo-art svg').evaluate(async node=>{
  async function raster(remove){const svg=node.cloneNode(true);for(const n of svg.querySelectorAll(remove))n.remove();svg.setAttribute('width','800');svg.setAttribute('height','450');const image=new Image();image.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(new XMLSerializer().serializeToString(svg));await image.decode();const canvas=document.createElement('canvas');canvas.width=800;canvas.height=450;const ctx=canvas.getContext('2d');ctx.drawImage(image,0,0);return ctx.getImageData(0,0,800,450).data;}
  const all=await raster('[data-nothing]'),result={};for(const [key,selector] of [['floor','[data-floor-shadow]'],['reflection','[data-reflection]'],['wall','[data-light-effects] > g:first-child']]){const without=await raster(selector);let changed=0;for(let i=0;i<all.length;i+=4)if(Math.abs(all[i]-without[i])+Math.abs(all[i+1]-without[i+1])+Math.abs(all[i+2]-without[i+2])>8)changed++;result[key]=changed;}return result;
 });assert.ok(pixels.floor>100&&pixels.wall>100&&pixels.reflection>100,JSON.stringify(pixels));
 const focus=await page.locator('#demo-art [data-surface]').first().getAttribute('cx');await slider('angle',-45);assert.notEqual(await page.locator('#demo-art [data-surface]').first().getAttribute('cx'),focus);
 await page.locator('#light-cool').click();assert.equal(await page.locator('[data-light-control="gloss"]').inputValue(),'0.5');await page.locator('#light-flat').click();assert.equal(await page.locator('#demo-art [data-surface]').count(),0);await page.locator('#light-warm').click();
 await slider('reflection',0);assert.equal(await page.locator('#demo-art [data-reflection]').count(),0);await slider('reflection',.3);await slider('softness',0);assert.equal(await page.locator('#demo-art feGaussianBlur').getAttribute('stdDeviation'),'0');await slider('softness',3);
 const before=await page.locator('#demo-art [data-contact="ona"]').getAttribute('opacity');await page.locator('#light-jump').click();await page.waitForFunction(before=>+document.querySelector('#demo-art [data-contact="ona"]').getAttribute('opacity')<+before*.7,before);await page.locator('#demo-play').click();
 const downloadPromise=page.waitForEvent('download');await page.locator('#download-demo').click();const download=await downloadPromise;await download.saveAs('test-results/lighting-export.json');const saved=JSON.parse(fs.readFileSync('test-results/lighting-export.json'));assert.equal(saved.lighting.shading,'cel');assert.equal(saved.lighting.reflection,.3);assert.equal(saved.lighting.enabled,true);
 for(const size of [{width:1366,height:768},{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1));const footer=await page.locator('.demo-footer').boundingBox(),art=await page.locator('#demo-art').boundingBox();assert.ok(footer.y+footer.height<=size.height+1);assert.ok(art.height>100);await page.screenshot({path:`test-results/lighting-${size.width}.png`});}
 await page.setViewportSize({width:1366,height:768});await page.locator('#edit-demo').click();await page.locator('[data-panel="light"]').click();await page.locator('#lighting-shading').selectOption('gradient');await page.locator('#lighting-color').fill('#aaccff');await page.locator('#lighting-color').dispatchEvent('change');await page.locator('#lighting-enabled').uncheck();await page.locator('[data-light-tab="shadows"]').click();await page.locator('[data-light-field="reflection"]').fill('0.4');await page.locator('[data-light-field="reflection"]').dispatchEvent('change');assert.equal(await page.locator('#art [data-reflection]').count(),0);await page.locator('#lighting-enabled').check();await page.reload();await page.locator('[data-panel="light"]').click();assert.equal(await page.locator('#lighting-shading').inputValue(),'gradient');await page.locator('#lighting-shading').selectOption('cel');assert.ok(await page.locator('#art [data-shading="cel"]').count()>0);await page.locator('#undo').click();assert.equal(await page.locator('#lighting-shading').inputValue(),'gradient');assert.equal(await page.locator('#lighting-color').inputValue(),'#aaccff');await page.locator('[data-light-tab="shadows"]').click();assert.equal(await page.locator('[data-light-field="reflection"]').inputValue(),'0.4');assert.equal(await page.locator('#art [data-reflection]').count(),2);
 await page.locator('[data-light-tab="source"]').click();await page.locator('[data-light-field="angle"]').fill('30');await page.locator('[data-light-field="angle"]').dispatchEvent('change');await page.locator('#undo').click();assert.equal(await page.locator('[data-light-field="angle"]').inputValue(),'-135');
 await page.locator('[data-light-tab="shadows"]').click();for(const size of [{width:1024,height:700},{width:390,height:844}]){await page.setViewportSize(size);if(size.width<760)await page.locator('#inspector-panel').click();const field=await page.locator('#lighting-wallY').boundingBox(),timeline=await page.locator('.timeline').boundingBox();await page.screenshot({path:`test-results/lighting-studio-${size.width}.png`});assert.ok(field.y+field.height<timeline.y,'Light panel fits '+size.width+' '+JSON.stringify({field,timeline}));}
 assert.deepEqual(errors,[]);console.log('Lighting checks passed: visible shadow/reflection pixels '+JSON.stringify(pixels)+', animated contact, controls, export, saved Studio settings, undo and compact layouts.');
}finally{await browser.close();}
