import test from 'node:test';
import assert from 'node:assert/strict';
import {createLoveseat,loveseatActions,loveseatBeat} from '../examples/loveseat.js';
import {assertDocument} from '../src/schema.js';
import {SceneController} from '../src/scene.js';
import {spatialKinematics} from '../src/spatial.js';
const sample=(scene,controller,action,time)=>{for(const a of scene.actors)controller.previewClip(a.id,action,time,{});return Object.fromEntries(controller.frame().actors.map(a=>[a.id,{pose:a.pose,world:spatialKinematics(scene.packs[scene.actors.find(v=>v.id===a.id).pack],a.pose)}]));};
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
test('loveseat is an editable bounded scene with synchronized carry and rest actions',()=>{const d=assertDocument(JSON.parse(JSON.stringify(createLoveseat())));assert.deepEqual(d.groups.map(g=>g.id),['scenery','carriers','furniture']);assert.equal(d.actors.filter(a=>a.group==='carriers').length,2);assert.ok(JSON.stringify(d).length<1000000);for(const p of Object.values(d.packs)){assert.deepEqual(p.inputs.action.options,loveseatActions);for(const action of loveseatActions)assert.ok(p.clips[action].loop);}assert.equal(d.lighting.floorShadow,0,'a flat global floor shadow cannot represent a staircase');});
test('every supporting hand stays on its loveseat handle between authored keys',()=>{const d=createLoveseat(),c=new SceneController(d);let maximum=0;for(const action of loveseatActions){const duration=action==='carry'?12:6;for(let t=.013;t<duration;t+=.073){const frame=sample(d,c,action,t),rests=loveseatBeat(t,action).rests;let supported=0;for(const [id,index] of [['lower',0],['upper',1]])for(const side of ['left','right']){const released=(index===0&&side==='left'||index===1&&side==='right')&&rests[index]>.0001;if(released)continue;supported++;const hand=frame[id].world[side+'Hand'],handle=frame.loveseat.world[id+(side==='left'?'Left':'Right')];maximum=Math.max(maximum,distance(hand,handle));assert.ok(distance(hand,handle)<.12,`${action} ${t.toFixed(3)} ${id} ${side} hand stays on its handle`);}assert.ok(supported>=3,'at least three hands support the load');}}assert.ok(maximum<.12);c.dispose();});
test('planted feet remain on actual moving stair treads and resting pauses the staircase',()=>{const d=createLoveseat(),c=new SceneController(d);for(let t=.02;t<12;t+=.077){const frame=sample(d,c,'carry',t),steps=Object.entries(frame.stairs.world).filter(([id])=>id.startsWith('step-')).map(([,w])=>w);for(const id of ['lower','upper'])for(const side of ['left','right'])if(frame[id].pose[side+'Contact.opacity']>.129){const foot=frame[id].world[side+'Foot'],step=steps.find(s=>foot.x>=s.x&&foot.x<=s.x+70);assert.ok(step);assert.ok(Math.abs(foot.y+5-step.y)<.12,`${id} ${side} planted on its tread at ${t}`);}}
 const a=sample(d,c,'carry',4.6),b=sample(d,c,'carry',5.2);assert.equal(a.stairs.world.root.x,b.stairs.world.root.x);assert.equal(a.stairs.world.root.y,b.stairs.world.root.y);c.dispose();});
test('one arm rests while the partner compensates and the full cycle returns continuously',()=>{const d=createLoveseat(),c=new SceneController(d);for(const [action,rester,side,partner] of [['rest-left','lower','left','upper'],['rest-right','upper','right','lower']]){const start=sample(d,c,action,0),rest=sample(d,c,action,3);assert.ok(distance(rest[rester].world[side+'Hand'],rest.loveseat.world[rester+(side==='left'?'Left':'Right')])>25);assert.ok(Math.abs(rest[partner].pose['torso.rotation']-start[partner].pose['torso.rotation'])>=5);}
 const first=sample(d,c,'carry',0),last=sample(d,c,'carry',11.9999);for(const id of ['lower','upper','loveseat'])for(const joint of Object.keys(first[id].world))assert.ok(distance(first[id].world[joint],last[id].world[joint])<.02,`${id}.${joint} has no loop teleport`);
 const visible=frame=>Object.entries(frame.stairs.world).filter(([id])=>id.startsWith('step-')).map(([,w])=>w).filter(w=>w.x>=0&&w.x<800&&w.y>=0&&w.y<450).map(w=>[Math.round(w.x),Math.round(w.y)]).sort((a,b)=>a[0]-b[0]);assert.deepEqual(visible(first),visible(last),'stair identities wrap to visually identical treads outside the frame');c.dispose();});
