import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.sensorPermissions=0;window.sensorPermission='granted';Object.defineProperty(window,'DeviceMotionEvent',{configurable:true,value:{requestPermission:async()=>{window.sensorPermissions++;return window.sensorPermission;}}});window.emitMotion=()=>{const e=new Event('devicemotion');Object.defineProperties(e,{acceleration:{value:{x:12,y:8,z:0}},rotationRate:{value:{alpha:40,beta:20,gamma:30}}});dispatchEvent(e);};});
const home=()=>page.waitForFunction(()=>[...document.querySelectorAll('#demo-art [data-actor]')].length===3&&[...document.querySelectorAll('#demo-art [data-actor]')].every(e=>e.dataset.recovery==='home'),null,{timeout:25000});
try{
 await page.goto(base+'/demos.html#shake-and-settle');await home();assert.equal(await page.evaluate(()=>window.sensorPermissions),0);
 await page.locator('#shake-scene').click();await page.waitForFunction(()=>[...document.querySelectorAll('#demo-art [data-actor]')].some(e=>e.dataset.recovery==='none'));await home();
 const before=await page.locator('#demo-art [data-actor="dummy"] [data-joint="root"]').first().getAttribute('transform');await page.locator('#demo-target').selectOption('dummy');const stage=await page.locator('#demo-stage').boundingBox();await page.mouse.click(stage.x+stage.width*.55,stage.y+stage.height*.7);await page.waitForFunction(()=>document.querySelector('#demo-art [data-actor="dummy"]').dataset.recovery==='walking');await home();const after=await page.locator('#demo-art [data-actor="dummy"] [data-joint="root"]').first().getAttribute('transform');assert.notEqual(after,before,'Walk changes position');
 await page.locator('#phone-motion').click();assert.equal(await page.evaluate(()=>window.sensorPermissions),1);await page.evaluate(()=>{window.emitMotion();window.sensorTimer=setInterval(window.emitMotion,40);});await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.includes('Phone motion on'));await page.waitForFunction(()=>[...document.querySelectorAll('#demo-art [data-actor]')].some(e=>e.dataset.recovery==='none'));await page.waitForTimeout(450);await page.evaluate(()=>clearInterval(window.sensorTimer));await home();assert.equal(await page.locator('#phone-motion').getAttribute('aria-pressed'),'true');
 await page.locator('#demo-play').click();assert.equal(await page.locator('#phone-motion').getAttribute('aria-pressed'),'false');await page.evaluate(()=>window.sensorPermission='denied');await page.locator('#phone-motion').click();await page.waitForFunction(()=>document.querySelector('#demo-status').textContent.includes('denied'));assert.equal(await page.locator('#phone-motion').getAttribute('aria-pressed'),'false');
 await page.locator('#wander-cast').click();await page.waitForFunction(()=>document.querySelector('#demo-art [data-actor="dummy"]').dataset.recovery==='walking');await page.locator('#wander-cast').click();await home();
 for(const size of [{width:1366,height:768},{width:390,height:844}]){await page.setViewportSize(size);const footer=await page.locator('.demo-footer').boundingBox();assert.ok(footer.y+footer.height<=size.height+1);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&document.documentElement.scrollHeight<=innerHeight+1));await page.screenshot({path:`test-results/motion-${size.width}.png`});}
 await page.locator('[data-demo="zero-gravity"]').click();await page.evaluate(()=>window.emitMotion());assert.equal(await page.locator('#phone-motion').count(),0);assert.deepEqual(errors,[]);console.log('Motion demo passed: shake, stand and return, walking, simulated phone permission and sensors, stale-input decay, pause cleanup, denied permission, wander and mobile layout.');
}finally{await browser.close();}
