import test from 'node:test';
import assert from 'node:assert/strict';
import ona from '../examples/characters/ona.json' with {type:'json'};
import {addSpatialRig} from '../src/character-rigs.js';
import {addOnaArmJoints} from '../src/ona-arms.js';
import {assertDocument} from '../src/schema.js';
import {SceneController} from '../src/scene.js';
import {spatialParts,softLimbPath} from '../src/spatial.js';
const make=()=>{const d=structuredClone(ona);addSpatialRig(d.packs.ona,'ona');return d;};
test('Ona elbow/wrist upgrade preserves shoulder transforms, action keys and physical attachments',()=>{const doc=make(),pack=doc.packs.ona,shoulders=structuredClone(pack.joints.filter(j=>['leftArm','rightArm'].includes(j.id))),physics=structuredClone(pack.physics),clips=structuredClone(pack.clips);assert.equal(addOnaArmJoints(pack),pack);assertDocument(doc);assert.deepEqual(pack.joints.filter(j=>['leftArm','rightArm'].includes(j.id)),shoulders);assert.deepEqual(pack.physics,physics);for(const [id,clip] of Object.entries(clips))for(const [channel,keys] of Object.entries(clip.tracks))assert.deepEqual(pack.clips[id].tracks[channel],keys);for(const side of ['left','right']){assert.equal(pack.joints.find(j=>j.id===side+'Forearm').parent,side+'Arm');assert.equal(pack.joints.find(j=>j.id===side+'Wrist').parent,side+'Forearm');assert.equal(pack.parts.find(p=>p.id===side+'-arm-volume').spatial.softLimb.radius,6.5);}assert.deepEqual(JSON.parse(JSON.stringify(doc)),doc);});
test('Legacy bend performances become editable elbow tracks without replacing authored curves',()=>{const doc=make(),p=doc.packs.ona;p.clips['reach-depth'].tracks['rightForearm.rotation']=[[0,-10],[4,-15,'linear']];addOnaArmJoints(p);assert.deepEqual(p.clips['reach-depth'].tracks['rightForearm.rotation'],[[0,-10],[4,-15,'linear']]);assert.deepEqual(p.clips['tuck-jump'].tracks['leftForearm.rotation'],p.clips['tuck-jump'].tracks['leftArm.bend'].map(([t,v,e])=>[t,v*70||0,e]));assert.deepEqual(p.clips['tuck-jump'].tracks['rightForearm.rotation'],p.clips['tuck-jump'].tracks['rightArm.bend'].map(([t,v,e])=>[t,-v*70||0,e]));const snapshot=structuredClone(p);addOnaArmJoints(p);assert.deepEqual(p,snapshot);});
test('Compact arm endpoints remain within the legacy reach while independent elbow and wrist turns deform the skin',()=>{const doc=make(),pack=doc.packs.ona;addOnaArmJoints(pack);const c=new SceneController(doc);for(const side of ['left','right']){const sign=side==='left'?1:-1;for(const shoulder of [-120,-15,18,90,120])for(const bend of [0,35,70])for(const yaw of [0,45,90,135,180]){c.previewClip('ona','idle',0,{[side+'Arm.rotation']:shoulder,[side+'Forearm.rotation']:bend*sign,'root.yaw':yaw});const frame=c.frame().actors[0],view=spatialParts(pack,frame),upper=view.world[side+'Arm'],wrist=view.world[side+'Wrist'],tip={x:wrist.x+wrist.m[0]*7,y:wrist.y+wrist.m[3]*7};assert.ok(Math.hypot(tip.x-upper.x,tip.y-upper.y)<=34);const path=view.parts.get(side+'-arm-volume').d;assert.ok(!/NaN|Infinity/.test(path));assert.ok(path.length<1600);}}
 c.previewClip('ona','idle',0,{});const rest=c.frame().actors[0],part=pack.parts.find(p=>p.id==='right-arm-volume'),before=softLimbPath(pack,part,rest.pose);c.previewClip('ona','idle',0,{'rightWrist.yaw':80,'rightWrist.pitch':45,'rightForearm.rotation':-55});assert.notEqual(softLimbPath(pack,part,c.frame().actors[0].pose),before);c.dispose();});
test('Conflicting custom joint names fail before modifying either arm or source JSON',()=>{const doc=make(),p=doc.packs.ona;p.joints.push({id:'rightWrist',parent:'root',x:1,y:2,rotation:0,min:-180,max:180,length:0});const snapshot=structuredClone(p);assert.throws(()=>addOnaArmJoints(p),/already exists/);assert.deepEqual(p,snapshot);assert.ok(!ona.packs.ona.joints.some(j=>j.id==='leftForearm'));});

test('Existing physical responses keep the added arm chains finite without new collision bodies',()=>{const doc=make();addOnaArmJoints(doc.packs.ona);doc.actors[0].behavior={mode:'protective',autoRecover:true};const c=new SceneController(doc);for(let i=0;i<90;i++){const frame=c.step(1/60).actors[0],view=spatialParts(doc.packs.ona,frame);for(const side of ['left','right']){assert.ok(!/NaN|Infinity/.test(view.parts.get(side+'-arm-volume').d));assert.ok(Object.values(view.world[side+'Wrist']).every(v=>typeof v!=='number'||Number.isFinite(v)));}}c.dispose();});
