import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
const browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
const page=await browser.newPage({viewport:{width:1366,height:768},reducedMotion:'no-preference'}),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,'');
await page.addInitScript(()=>{
 window.audioStarts=0;window.audioContexts=[];
 const Original=window.AudioContext;if(!Original)return;
 window.AudioContext=class extends Original{constructor(...args){super(...args);window.audioContexts.push(this);}createOscillator(){const node=super.createOscillator(),start=node.start.bind(node);node.start=(...args)=>{window.audioStarts++;return start(...args);};return node;}createGain(){const node=super.createGain();if(!this.testMaster){this.testMaster=node;this.testAnalyser=this.createAnalyser();node.connect(this.testAnalyser);const sink=super.createGain();sink.gain.value=0;this.testAnalyser.connect(sink);sink.connect(this.destination);}return node;}};
});
try{
 await page.goto(base);await page.locator('#reset').click();await page.locator('#motion-policy').selectOption('full');await page.locator('[data-panel="feel"]').click();
 assert.equal(await page.locator('#emotion option').count(),14);assert.equal(await page.evaluate(()=>window.audioContexts.length),0,'no audio context before consent');
 await page.getByRole('button',{name:'Enable sound',exact:true}).click();await page.getByRole('button',{name:'Mute sound',exact:true}).waitFor();assert.ok(await page.evaluate(()=>window.audioContexts[0].state==='running'&&window.audioStarts>0));
 await page.waitForTimeout(350);await page.locator('[data-interact="startle"]').click();await page.waitForTimeout(40);
 const audioPeak=await page.evaluate(()=>new Promise(resolve=>{const a=window.audioContexts[0].testAnalyser,buffer=new Float32Array(a.fftSize);let peak=0,n=0;const timer=setInterval(()=>{a.getFloatTimeDomainData(buffer);for(const v of buffer)peak=Math.max(peak,Math.abs(v));if(++n===20){clearInterval(timer);resolve(peak);}},10);}));console.log('Audio peak',audioPeak,await page.evaluate(()=>({starts:window.audioStarts,state:window.audioContexts[0].state,time:window.audioContexts[0].currentTime,gain:window.audioContexts[0].testMaster.gain.value})));assert.ok(audioPeak>.00001,'sound produces a nonzero audio waveform');
 await page.getByRole('button',{name:'Mute sound',exact:true}).click();const starts=await page.evaluate(()=>window.audioStarts);await page.locator('[data-interact="pet"]').click();await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.audioStarts),starts);
 await page.locator('[data-interact="hurt"]').click();assert.equal(await page.locator('#art [data-actor]').first().getAttribute('data-emotion'),'hurt');assert.equal(await page.locator('#art [data-part="hurt-cheek"]').getAttribute('visibility'),'visible');
 await page.locator('#body-mode').selectOption('protective');await page.locator('#strategy').selectOption('protect');await page.waitForTimeout(1500);
 await page.evaluate(()=>{window.responseHistory=[];window.recordResponses=true;function sample(){if(!window.recordResponses)return;const s=document.querySelector('#art [data-actor]')?.dataset.response;if(window.responseHistory.at(-1)!==s)window.responseHistory.push(s);requestAnimationFrame(sample);}sample();});
 await page.locator('[data-interact="drop"]').click();await page.locator('#art [data-response="hurt"]').waitFor({timeout:5000});await page.screenshot({path:'test-results/response-hurt.png'});await page.waitForTimeout(2300);const history=await page.evaluate(()=>{window.recordResponses=false;return window.responseHistory;});assert.ok(history.indexOf('protecting')>=0&&history.indexOf('protecting')<history.indexOf('hurt'),JSON.stringify(history));assert.ok(history.includes('recovering'));
 assert.ok(await page.locator('[data-physics-debug] circle').count()>1,'contact and center diagnostics render');
 await page.locator('#body-mode').selectOption('floating');await page.locator('[data-interact="toss"]').click();await page.waitForTimeout(250);assert.match(await page.locator('#response-status').innerText(),/Floating/);await page.screenshot({path:'test-results/response-floating.png'});
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2')));assert.equal(saved.actors[0].behavior.mode,'floating');assert.equal(saved.actors[0].behavior.strategy,'protect');
 await page.reload();await page.locator('[data-panel="feel"]').click();assert.equal(await page.locator('#body-mode').inputValue(),'floating');
 await page.setViewportSize({width:390,height:844});await page.locator('#inspector-panel').click();await page.screenshot({path:'test-results/response-mobile.png'});const responseBox=await page.locator('#response-status').boundingBox();assert.ok(responseBox.y+responseBox.height<683,'mobile Feel controls fit without page scrolling');await page.screenshot({path:'test-results/response-mobile.png'});
 await page.setViewportSize({width:1366,height:768});await page.goto(base+'/react-demo.html');await page.locator('[data-posecraft] svg').waitFor();await page.getByLabel('Demo motion').selectOption('full');await page.getByRole('button',{name:'Enable sound',exact:true}).click();await page.getByRole('button',{name:'Mute sound',exact:true}).waitFor();await page.getByRole('button',{name:'Hurt',exact:true}).click();assert.equal(await page.locator('[data-posecraft] [data-actor]').getAttribute('data-emotion'),'hurt');await page.getByRole('button',{name:'Drop',exact:true}).click();assert.equal(await page.getByLabel('Demo body mode').inputValue(),'protective');await page.waitForTimeout(700);assert.match(await page.locator('.event-log').innerText(),/hurt|bracing|recovering/);
 await page.getByRole('button',{name:'Unmount',exact:true}).click();assert.equal(await page.locator('[data-posecraft] svg').count(),0);await page.getByRole('button',{name:'Mount',exact:true}).click();await page.locator('[data-posecraft] svg').waitFor();
 const old=JSON.parse(fs.readFileSync('examples/characters/ona.json'));delete old.packs.ona.physics;old.requiredFeatures=old.requiredFeatures.filter(f=>!['rigid-body-physics','response-states'].includes(f));old.revision=12;old.actors[0].appearance={eyes:'#5588aa'};old.packs.ona.clips.wave.tracks['head.rotation']=[[0,7],[old.packs.ona.clips.wave.duration,7]];
 const upgradePage=await browser.newPage();await upgradePage.addInitScript(value=>localStorage.setItem('posecraft.studio.v2',JSON.stringify(value)),old);await upgradePage.goto(base);await upgradePage.locator('#art [data-part]').first().waitFor();const upgraded=await upgradePage.evaluate(()=>({doc:JSON.parse(localStorage.getItem('posecraft.studio.v2')),backup:JSON.parse(localStorage.getItem('posecraft.studio.v2.before-responses'))}));assert.equal(upgraded.doc.revision,13);assert.ok(upgraded.doc.packs.ona.physics);assert.equal(upgraded.doc.actors[0].appearance.eyes,'#5588aa');assert.equal(upgraded.doc.packs.ona.clips.wave.tracks['head.rotation'][0][1],7);assert.equal(upgraded.backup.revision,12);await upgradePage.close();
 assert.deepEqual(errors,[]);console.log('Response browser checks passed: real sound waveform, mute, automatic hurt face, predicted protection before impact, recovery, contact overlays, mode persistence, compact Feel panel, React responses and remount.');console.log('Observed sequence:',history.join(' → '));
}finally{await browser.close();}
