import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {bakeSceneMotion} from '../src/scene-baking.js';import {SceneController,STEP} from '../src/scene.js';import {IllustrationController} from '../src/illustration.js';import {DocumentStore} from '../src/commands.js';import {inspectSceneFeatures} from '../src/scene-export.js';import {wrapAngle} from '../src/index.js';import {spatialParts} from '../src/spatial.js';import {addSpatialRig} from '../src/character-rigs.js';
const fixture=()=>{const d=JSON.parse(fs.readFileSync(new URL('../examples/characters/ona.json',import.meta.url)));d.actors[0].behavior={mode:'ragdoll',autoFace:false,autoRecover:false};return d;};
const events=[{time:0,type:'interaction',actor:'ona',interaction:'toss',strength:.7},{time:.4,type:'acceleration',ax:400,ay:-150},{time:.8,type:'acceleration',ax:0,ay:0}];
function apply(c,e){if(e.type==='interaction')c.interact(e.actor,e.interaction,e.strength);else c.setAcceleration(e.ax,e.ay);}
async function checkMotion(d,spatial=false){const before=JSON.stringify(d),options={actor:'ona',start:.2,duration:1.6,fps:15,clipId:'fall-recorded',events,maxPositionError:.2,maxAngleError:.25},result=await bakeSceneMotion(d,options),source=new SceneController(d),baked=new IllustrationController(result.document);let cursor=0,position=0,angle=0;try{for(let tick=0;tick<=216;tick++){while(cursor<events.length&&events[cursor].time<=source.time+1e-9)apply(source,events[cursor++]);if(tick>=24){const time=Math.min(options.duration,(tick-24)*STEP),a=source.frame().actors[0],b=baked.previewClip('ona','fall-recorded',time).actors[0],aw=spatial?spatialParts(d.packs[d.actors[0].pack],a).world:a.world,bw=spatial?spatialParts(result.document.packs[result.diagnostics.packId],b).world:b.world;for(const id of Object.keys(aw)){position=Math.max(position,Math.hypot(aw[id].x-bw[id].x,aw[id].y-bw[id].y)*d.actors[0].transform.scale);if(!spatial)angle=Math.max(angle,Math.abs(wrapAngle(aw[id].rotation-bw[id].rotation)));}}if(tick<216)source.step(STEP);}assert.ok(position<=.200001,position);assert.ok(angle<=.250001,angle);assert.equal(JSON.stringify(d),before);assert.deepEqual(result.document.packs[d.actors[0].pack],d.packs[d.actors[0].pack]);assert.equal(inspectSceneFeatures(result.document).runtime,'illustration');assert.equal(baked.frame().actors[0].physics,null);assert.ok(result.diagnostics.keys<result.diagnostics.samples*d.packs[d.actors[0].pack].joints.length*3);assert.ok(Object.values(result.document.packs[result.diagnostics.packId].clips['fall-recorded'].tracks).every(keys=>keys.length<=1000));const store=new DocumentStore(d);assert.deepEqual(store.transact(result.commands),result.document);store.undo();assert.deepEqual({...store.document,revision:d.revision},d);store.redo();assert.deepEqual({...store.document,revision:result.document.revision},result.document);return result;}finally{source.dispose();baked.dispose();}}
test('physical bake reconstructs real body/root translation, obeys errors and survives ordinary illustration playback and undo',async()=>{const d=fixture();d.actors[0].transform.rotation=18;d.actors[0].transform.scale=1.25;await checkMotion(d);});
test('spatial physical bake follows renderer root placement and existing projected rig poses',async()=>{const d=fixture();addSpatialRig(d.packs.ona,'ona',{studies:false});await checkMotion(d,true);});
test('baking one actor isolates a shared source pack and honestly retains other actors physics',async()=>{const d=fixture();d.actors.push({...structuredClone(d.actors[0]),id:'other',transform:{...d.actors[0].transform,x:480}});const r=await bakeSceneMotion(d,{actor:'ona',duration:.3});assert.deepEqual(r.document.actors[1],d.actors[1]);assert.equal(r.document.actors[1].pack,'ona');assert.notEqual(r.document.actors[0].pack,'ona');assert.deepEqual(r.diagnostics.remainingPhysicalActors,['other']);assert.equal(inspectSceneFeatures(r.document).runtime,'physics');});
test('bake rejects unsupported live systems and changing appearances, and cancels without source edits',async()=>{const d=fixture(),before=JSON.stringify(d);for(const options of[{duration:9},{fps:59},{clipId:'idle'},{maxPositionError:0},{events:[{time:0,type:'pointer'}]}])await assert.rejects(()=>bakeSceneMotion(d,{actor:'ona',...options}));const enabled=structuredClone(d);enabled.actors[0].behavior.autoFace=true;await assert.rejects(()=>bakeSceneMotion(enabled,{actor:'ona',duration:2,events}),/inputs change/);const controller=new AbortController();await assert.rejects(()=>bakeSceneMotion(d,{actor:'ona',duration:2,signal:controller.signal,onProgress:()=>controller.abort()}),{name:'AbortError'});assert.equal(JSON.stringify(d),before);const live=structuredClone(d);live.behaviorGraph={seed:1,variables:{},initial:'idle',states:{idle:{actions:[]}},edges:[]};await assert.rejects(()=>bakeSceneMotion(live,{actor:'ona'}),/live decision graphs/);});
import {spawnSync} from 'node:child_process';
test('bake captures a recovery interval and removes only selected-actor contacts',async()=>{const d=fixture();d.actors[0].behavior.autoRecover=true;d.contacts=[{id:'face-lock',name:'Face lock',enabled:true,actor:'ona',chain:{upper:'root',lower:'head',end:'eyes'},target:{type:'point',x:320,y:220},bend:1,weight:1,start:0,end:180}];const r=await bakeSceneMotion(d,{actor:'ona',duration:3,events:[events[0]]});assert.deepEqual(r.diagnostics.removedContacts,['face-lock']);assert.deepEqual(r.document.contacts,[]);assert.equal(d.contacts.length,1);assert.ok(r.diagnostics.maxPositionError<=.500001);});
test('CLI baking writes a separate validated result and refuses overwriting any file',()=>{fs.mkdirSync('test-results',{recursive:true});const folder=fs.mkdtempSync('test-results/bake-cli-'),source=folder+'/source.json',request=folder+'/request.json',output=folder+'/baked.json';fs.writeFileSync(source,JSON.stringify(fixture()));fs.writeFileSync(request,JSON.stringify({actor:'ona',duration:.2}));const before=fs.readFileSync(source,'utf8'),run=()=>spawnSync(process.execPath,['tools/cli.mjs','bake',source,request,output],{encoding:'utf8'});const first=run();assert.equal(first.status,0,first.stderr);assert.equal(JSON.parse(first.stdout).actor,'ona');assert.equal(JSON.parse(fs.readFileSync(output,'utf8')).actors[0].behavior.mode,'animated');assert.equal(run().status,1);assert.equal(fs.readFileSync(source,'utf8'),before);});
