import test from 'node:test';
import assert from 'node:assert/strict';
import {createCatch} from '../examples/catch.js';
import {SceneController} from '../src/scene.js';
import {SceneObjects,objectGrip} from '../src/scene-objects.js';
import {PropGameRuntime} from '../src/prop-games.js';

function fixture(observer=false){const doc=createCatch();if(observer)doc.actors.push({...structuredClone(doc.actors[1]),id:'observer',transform:{x:720,y:300,rotation:0,scale:1}});const controller=new SceneController(doc);controller.propGames=null;const frame=controller.frame(),events=[],game=new PropGameRuntime(controller.document,controller.objects,{onEvent:e=>events.push(e)});return {doc:controller.document,controller,objects:controller.objects,frame,events,game};}
function moveOwner(f,actor,joint){const p=objectGrip(f.doc,f.frame,{actor,joint});assert.equal(f.objects.command({type:'place',object:'ball',x:p.x,y:p.y},f.frame),true);assert.equal(f.objects.command({type:'attach',object:'ball',actor,joint,maxDistance:1},f.frame),true);}

test('manual participant handoff reconciles all catch phases without a phantom throw or ownership theft',()=>{for(const phase of ['prepare','flight','settle','retrieve','rise']){const f=fixture();try{f.game.games[0].phase=phase;f.game.time=2;moveOwner(f,'fern','leftWrist');f.game.tick(1/120,f.frame);assert.equal(f.objects.bodies[0].owner.actor,'fern');assert.equal(f.game.games[0].turn,1);assert.equal(f.game.games[0].phase,'celebrate');assert.equal(f.game.games[0].throws,0);assert.ok(!f.events.some(e=>e.type==='throw'));}finally{f.controller.dispose();}}});

test('outside ownership immediately interrupts catch and yields the authored actor poses',()=>{const f=fixture(true);try{f.game.time=2;moveOwner(f,'observer','leftWrist');f.game.tick(1/120,f.frame);assert.equal(f.game.games[0].phase,'interrupted');assert.equal(f.game.games[0].throws,0);assert.equal(f.objects.bodies[0].owner.actor,'observer');assert.deepEqual(f.game.apply(f.frame).actors,f.frame.actors);}finally{f.controller.dispose();}});

test('failed release and missing grip do not count throws or dereference absent actors',()=>{for(const missing of [false,true]){const f=fixture();try{f.game.time=2;if(!missing){const command=f.objects.command.bind(f.objects);f.objects.command=(c,frame)=>c.type==='release'?false:command(c,frame);}assert.doesNotThrow(()=>f.game.tick(1/120,missing?{...f.frame,actors:[]}:f.frame));assert.equal(f.game.games[0].throws,0);assert.ok(!f.events.some(e=>e.type==='throw'));assert.notEqual(f.game.games[0].phase,'flight');}finally{f.controller.dispose();}}});

test('disabled balls and hidden participants stop procedural catch poses while previewed actors remain authored',()=>{for(const disabled of ['ball','actor']){const f=fixture();try{if(disabled==='ball')f.objects.command({type:'enable',object:'ball',enabled:false},f.frame);else f.doc.actors[0].hidden=true;const phase=f.game.games[0].phase;f.game.tick(1/120,f.frame);assert.equal(f.game.games[0].phase,phase);assert.deepEqual(f.game.apply(f.frame).actors,f.frame.actors);}finally{f.controller.dispose();}}const f=fixture();try{assert.deepEqual(f.game.apply(f.frame,{disabledActors:new Set(['pip'])}).actors.find(a=>a.id==='pip'),f.frame.actors.find(a=>a.id==='pip'));}finally{f.controller.dispose();}});

test('hidden owners release their grip once and cannot acquire an object while hidden',()=>{const f=fixture();try{f.doc.actors[0].hidden=true;f.objects.tick(1/120,f.frame);assert.equal(f.objects.bodies[0].owner,null);assert.equal(f.objects.drainEvents().filter(e=>e.type==='object-grip-broken').length,1);f.objects.tick(1/120,f.frame);assert.equal(f.objects.drainEvents().filter(e=>e.type==='object-grip-broken').length,0);assert.equal(f.objects.command({type:'attach',object:'ball',actor:'pip',joint:'rightWrist',maxDistance:2000},f.frame),false);}finally{f.controller.dispose();}});

function collisionFixture(category,mask=65535){const joint={id:'root',parent:null,x:0,y:0,rotation:0,length:20,min:-180,max:180},doc={bounds:{width:300,height:200},packs:{simple:{joints:[joint],physics:{bodies:{root:{x:0,y:0,width:20,height:20}}}}},actors:[{id:'actor',pack:'simple',transform:{x:150,y:100,rotation:0,scale:1}}],objects:[{id:'ball',name:'Ball',shape:'circle',x:130,y:100,radius:5,mass:1,fill:'#ff0000',category,mask}],objectPhysics:{gravity:0,floorY:190,actorCollisions:true}},frame={actors:[{id:'actor',pose:{},world:{root:{x:0,y:0,rotation:0}}}]};return {doc,frame,objects:new SceneObjects(doc)};}
test('actor collision masks suppress excluded bodies and impacts identify the pushed joint',()=>{for(const [category,mask,expected]of [[1,0,false],[1,1,false],[1,2,true]]){const f=collisionFixture(category,mask);f.objects.command({type:'impulse',object:'ball',vx:300},f.frame);f.objects.tick(1/30,f.frame);const impacts=f.objects.drainEvents().filter(e=>e.type==='object-impact'&&e.actor);assert.equal(impacts.length>0,expected);if(expected){assert.equal(impacts[0].joint,'root');assert.ok(impacts[0].impulseX<0);assert.ok(f.objects.bodies[0].vx<0);}}});

test('physical actor receives the opposite scene-space impulse from a shared object hit',()=>{const doc=createCatch();delete doc.objectGames;delete doc.objects[0].owner;doc.objectPhysics={gravity:0,floorY:440,actorCollisions:true};doc.actors[1].hidden=true;const c=new SceneController(doc),events=[];try{c.setBehavior('pip',{mode:'ragdoll',gravity:0,autoRecover:false});const physical=c.actors.find(a=>a.actor.id==='pip').physics,frame=c.frame(),shape=doc.packs.ona.physics.bodies.root,p=objectGrip(c.document,frame,{actor:'pip',joint:'root',offsetX:shape.x,offsetY:shape.y}),radius=Math.min(shape.width,shape.height)*doc.actors[0].transform.scale/2,ball=c.objects.bodies[0];c.objects.command({type:'place',object:'ball',x:p.x-radius-ball.radius-2,y:p.y},frame);c.objects.command({type:'impulse',object:'ball',vx:400},frame);const before=new Map([...physical.bodies].map(([id,b])=>[id,{...b.getLinearVelocity()}]));c.subscribe(e=>{if(e.type==='object-impact'&&e.actor==='pip')events.push(e);});c.objects.tick(1/30,frame);assert.ok(events.length>0);for(const event of events){const body=physical.bodies.get(event.joint),v=body.getLinearVelocity(),old=before.get(event.joint),dot=(v.x-old.x)*event.impulseX+(v.y-old.y)*event.impulseY;assert.ok(dot<0,'opposite impulse must move the physical actor away from the ball');assert.ok(Number.isFinite(v.x)&&Number.isFinite(v.y));}}finally{c.dispose();}});


test('manual release during throw preparation preserves the commanded flight instead of reacquiring the ball',()=>{const f=fixture();try{f.game.time=2;f.objects.command({type:'release',object:'ball',actor:'pip',vx:123,vy:-45},f.frame);f.game.tick(1/120,f.frame);assert.equal(f.objects.bodies[0].owner,null);assert.equal(f.objects.bodies[0].vx,123);assert.equal(f.objects.bodies[0].vy,-45);assert.equal(f.game.games[0].throws,0);assert.ok(!f.events.some(e=>e.type==='throw'));}finally{f.controller.dispose();}});

test('a circle with no collision category cannot hit an actor proxy',()=>{const f=collisionFixture(0);f.objects.command({type:'impulse',object:'ball',vx:300},f.frame);f.objects.tick(1/30,f.frame);assert.equal(f.objects.drainEvents().some(e=>e.type==='object-impact'&&e.actor),false);assert.ok(f.objects.bodies[0].vx>0);});
