import test from 'node:test';import assert from 'node:assert/strict';
import {ScrollSignal,assertScrollConfig,applyScrollSample} from '../src/scroll-bindings.js';
import {createDrawing} from '../src/vector-authoring.js';
const fixture=()=>{const d=createDrawing();d.packs.drawing.inputs={speed:{type:'number',min:-2,max:2,default:0}};d.behaviorGraph={variables:{progress:0},variableBounds:{progress:{min:0,max:1}}};return d;};
const live={mode:'live',bindings:[{source:'velocity',target:{type:'input',actor:'character',name:'speed'},from:[-1000,1000],to:[-2,2]},{source:'progress',target:{type:'variable',name:'progress'},from:[0,1],to:[0,1]}]};
test('scroll signal measures CSS pixels per second, clamps overscroll and decays without frames after rest',()=>{const s=new ScrollSignal({maxVelocity:500,smoothing:.05});assert.equal(s.sample({offset:-20,max:1000,time:0}).progress,0);const moving=s.sample({offset:100,max:1000,time:.1});assert.equal(moving.progress,.1);assert.ok(moving.velocity>400&&moving.velocity<=500);for(let i=2;i<20;i++)s.sample({offset:100,max:1000,time:i*.1});assert.ok(Math.abs(s.velocity)<.001);assert.equal(s.sample({offset:2000,max:1000,time:2}).progress,1);assert.equal(s.sample({offset:0,max:0,time:2.1}).progress,0);s.reset();assert.equal(s.sample({offset:800,max:1000,time:5}).velocity,0);assert.throws(()=>s.sample({offset:NaN,max:1,time:0}));});
test('live bindings clamp and avoid duplicate writes; reduced motion suppresses velocity',()=>{const d=fixture(),calls=[],controller={setInput:(...v)=>calls.push(['input',...v]),setVariable:(...v)=>calls.push(['variable',...v])},lastValues=new Map();assertScrollConfig(d,live);const sample={progress:.6,velocity:2000};applyScrollSample(controller,d,live,sample,{lastValues});assert.deepEqual(calls,[['input','character','speed',2],['variable','progress',.6]]);applyScrollSample(controller,d,live,sample,{lastValues});assert.equal(calls.length,2);applyScrollSample(controller,d,{...live,reducedMotion:'progress'},sample,{reducedMotion:true,lastValues});assert.deepEqual(calls.at(-1),['input','character','speed',0]);applyScrollSample(controller,d,live,sample,{reducedMotion:true,lastValues});assert.deepEqual(calls.at(-1),['variable','progress',0]);});
test('authored scroll previews explicit clip time and never invokes physics seek',()=>{const d=fixture(),calls=[],c={previewClip:(...args)=>calls.push(args),seek:()=>assert.fail('scroll must never seek')},config={mode:'authored',clips:[{actor:'character',clip:'idle',start:.2,end:1.2}]};assertScrollConfig(d,config);applyScrollSample(c,d,config,{progress:.5,velocity:100});assert.deepEqual(calls,[['character','idle',.7]]);applyScrollSample(c,d,config,{progress:1,velocity:100},{reducedMotion:true});assert.deepEqual(calls.at(-1),['character','idle',.2]);});
test('scroll authoring rejects ambiguous, undeclared, physical and out-of-range targets',()=>{const d=fixture();for(const config of[{...live,source:'window'},{...live,bindings:[live.bindings[0],live.bindings[0]]},{...live,bindings:[{...live.bindings[0],to:[-3,3]}]},{...live,bindings:[{...live.bindings[0],from:[1,1]}]},{mode:'authored',clips:[{actor:'missing',clip:'idle'}]},{mode:'authored',clips:[{actor:'character',clip:'idle',start:1,end:0}]},{mode:'authored',clips:[],bindings:live.bindings},{...live,smoothing:3}])assert.throws(()=>assertScrollConfig(d,config));d.actors[0].behavior={mode:'ragdoll'};assert.throws(()=>assertScrollConfig(d,{mode:'authored',clips:[{actor:'character',clip:'idle'}]}));});
