import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const base=(process.env.POSECRAFT_URL||'http://127.0.0.1:5178').replace(/\/$/,''),browser=await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})}),page=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));
const slider=async(id,value)=>{await page.locator(`[data-spatial-control="${id}"]`).fill(String(value));await page.locator(`[data-spatial-control="${id}"]`).dispatchEvent('input');await page.waitForTimeout(120);};
try{
 await page.goto(base+'/demos.html#turn-and-pose');await page.locator('#study-turn').waitFor();await slider('body',0);assert.equal(await page.locator('#demo-art [data-part="face-2"]').getAttribute('visibility'),'visible');
 await slider('body',90);assert.equal(await page.locator('#demo-art [data-part="face-2"]').getAttribute('visibility'),'visible');assert.equal(await page.locator('#demo-art [data-part="face-3"]').getAttribute('visibility'),'hidden');await page.screenshot({path:'test-results/spatial-profile.png'});
 await slider('body',180);assert.equal(await page.locator('#demo-art [data-part="face-2"]').getAttribute('visibility'),'hidden');assert.equal(await page.locator('#demo-art [data-part="back-panel"]').getAttribute('visibility'),'visible');await page.screenshot({path:'test-results/spatial-back.png'});
 await slider('body',30);await slider('head',20);await slider('depth',30);await slider('shape',100);const order=await page.locator('#demo-art [data-actor="ona"] [data-artwork]').evaluate(g=>[...g.children].map(e=>e.dataset.slot));assert.ok(order.indexOf('right-arm-volume')>order.indexOf('shirt-0'));await page.screenshot({path:'test-results/spatial-reach.png'});
 await page.locator('#study-extremities').click();const footBefore=await page.locator('#demo-art [data-actor="dummy"] [data-joint="rightFoot"]').first().getAttribute('transform');await page.waitForFunction(before=>document.querySelector('#demo-art [data-actor="dummy"] [data-joint="rightFoot"]').getAttribute('transform')!==before,footBefore);await page.screenshot({path:'test-results/hands-feet.png'});
 await page.locator('#study-jump').click();await page.waitForTimeout(1100);await page.screenshot({path:'test-results/spatial-jump.png'});
 await page.setViewportSize({width:390,height:844});await slider('body',45);const footer=await page.locator('.demo-footer').boundingBox();assert.ok(footer.y+footer.height<=844);await page.screenshot({path:'test-results/spatial-mobile.png'});
 await page.setViewportSize({width:1366,height:768});await page.locator('#edit-demo').click();await page.locator('#pose-channel').waitFor();await page.locator('[data-select-joint="head"]').click();await page.locator('#pose-channel').selectOption('yaw');await page.locator('#rotation').fill('65');await page.locator('#rotation').dispatchEvent('input');await page.locator('#add-key').click();const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2.demo.turn-and-pose')));assert.ok(Object.values(saved.packs.ona.clips).some(c=>c.tracks['head.yaw']?.some(k=>k[1]===65)));
 await page.locator('[data-select-joint="rightArm"]').click();await page.locator('#pose-channel').selectOption('bend');await page.locator('#rotation').fill('0.8');await page.locator('#rotation').dispatchEvent('input');await page.locator('#add-key').click();const draft=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2.demo.turn-and-pose')));assert.ok(Object.values(draft.packs.ona.clips).some(c=>c.tracks['rightArm.bend']?.some(k=>k[1]===.8)));await page.reload();await page.locator('#pose-channel').waitFor();await page.screenshot({path:'test-results/spatial-studio.png'});
 await page.locator('#actors').selectOption('dummy');await page.locator('[data-select-joint="rightFoot"]').click();await page.locator('#pose-channel').selectOption('yaw');await page.locator('#rotation').fill('-90');await page.locator('#rotation').dispatchEvent('input');await page.locator('#add-key').click();const feet=await page.evaluate(()=>JSON.parse(localStorage.getItem('posecraft.studio.v2.demo.turn-and-pose')));assert.ok(Object.values(feet.packs.dummy.clips).some(c=>c.tracks['rightFoot.yaw']?.some(k=>k[1]===-90)));
 assert.deepEqual(errors,[]);console.log('Spatial browser checks passed: curved face/profile/back, live depth sorting, morph and jump, mobile layout, Studio yaw/bend keyframes and saved reload.');
}finally{await browser.close();}
