import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createGym} from '../examples/gym.js';
import {createGpuSkin} from '../src/three-skin.js';
import {createThreeAtlas,evaluateThreeAtlasPose} from '../src/three-atlas.js';
import {evaluateSkinnedMesh} from '../src/skinned-mesh.js';
import {spatialKinematics,poseDefaults} from '../src/spatial.js';
import {sampleClip} from '../src/index.js';
test('GPU skin coordinates preserve the adapted volume, contact anchors and immutable buffers',()=>{const pack=createGym().packs.atlas,atlas=createThreeAtlas(pack),before=[];atlas.object.traverse(o=>{if(o.userData.gpuSkin)before.push([o.geometry,o.geometry.attributes.position.version,Array.from(o.geometry.attributes.position.array)]);});let maximumError=0;
for(const [clip,time]of [['full-set',0],['full-set',6],['full-set',31],['full-set',42],['full-set',54],['turnaround',3],['turnaround',6]]){const pose={...poseDefaults(pack),...sampleClip(pack.clips[clip],time)},world=evaluateThreeAtlasPose(pack,pose).world;atlas.update(pose);for(const joint of ['head','leftHand','rightHand','leftFoot','rightFoot']){const anchor=atlas.object.getObjectByName(joint+'-anchor');assert.ok(Math.abs(anchor.matrix.elements[12]-world[joint].x)<1e-9);assert.ok(Math.abs(anchor.matrix.elements[13]-world[joint].y)<1e-9);assert.ok(Math.abs(anchor.matrix.elements[14]-world[joint].z)<1e-9);}for(const part of pack.parts.filter(p=>p.spatial?.mesh)){const mesh=atlas.object.getObjectByName(part.id),g=mesh.geometry,expected=evaluateSkinnedMesh(part.spatial.mesh,world,pose);const shader={uniforms:{},vertexShader:'#include <begin_vertex>\n#include <beginnormal_vertex>'};mesh.material.onBeforeCompile(shader);assert.ok(shader.vertexShader.includes('pcBones[int(pcJoints.x)]'));for(let i=0;i<g.attributes.position.count;i++){const actual=new THREE.Vector3();for(let influence=0;influence<4;influence++){const w=g.attributes.pcWeights.array[i*4+influence],j=g.attributes.pcJoints.array[i*4+influence],p=new THREE.Vector3().fromBufferAttribute(g.attributes['pcLocal'+influence],i);actual.addScaledVector(p.applyMatrix4(shader.uniforms.pcBones.value[j]),w);}for(const [k,c]of (part.spatial.mesh.correctives||[]).entries()){const p=new THREE.Vector3().fromBufferAttribute(g.attributes['pcCorrection'+k],i),m=shader.uniforms.pcBones.value[pack.joints.findIndex(j=>j.id===c.joint)],rotation=new THREE.Matrix3().setFromMatrix4(m);actual.addScaledVector(p.applyMatrix3(rotation),shader.uniforms['pcAmount'+k].value);}const e=expected.vertices[i],error=actual.distanceTo(new THREE.Vector3(e.x,e.y,e.z));maximumError=Math.max(maximumError,error);assert.ok(error<.0001,`${part.id} ${i} error${error}`);}}}
let previous=null,maximumStretch=1;for(let i=0;i<=240;i++){const pose={...poseDefaults(pack),...sampleClip({...pack.clips.turnaround,loop:false},i/20)},raw=spatialKinematics(pack,pose),adapted=evaluateThreeAtlasPose(pack,pose);maximumStretch=Math.max(maximumStretch,adapted.diagnostics.maxStretch);assert.ok(adapted.diagnostics.maxStretch<=1.150001);for(const id of ['leftHand','rightHand','leftFoot','rightFoot']){assert.equal(adapted.world[id].x,raw[id].x);assert.equal(adapted.world[id].y,raw[id].y);}for(const id of ['leftUpper','rightUpper','leftLower','rightLower','leftThigh','rightThigh','leftCalf','rightCalf']){const joint=adapted.world[id];assert.ok([joint.x,joint.y,joint.z,...joint.m].every(Number.isFinite));if(previous)assert.ok(new THREE.Vector3(joint.x,joint.y,joint.z).distanceTo(new THREE.Vector3(previous[id].x,previous[id].y,previous[id].z))<5,'Turnaround joint jumped: '+id);}previous=adapted.world;}assert.ok(maximumStretch>1,'Turnaround should exercise bounded depth reach');
for(const [g,version,data]of before){assert.equal(g.attributes.position.version,version);assert.deepEqual(Array.from(g.attributes.position.array),data);}let materialDisposals=0;atlas.object.traverse(o=>{if(o.userData.gpuSkin)o.material.addEventListener('dispose',()=>materialDisposals++);});const stats={...atlas.stats};atlas.dispose();atlas.dispose();assert.equal(materialDisposals,stats.gpuSkinnedMeshes);assert.equal(atlas.object.children.length,0);console.log(JSON.stringify({passed:true,poses:7,maximumError,immutableVertexBuffers:true,exactAnchors:true,singleDispose:true,stats}));

});

test('GPU pilot rejects skeletons above the WebGL2 uniform budget',()=>{assert.throws(()=>createGpuSkin({vertices:[],triangles:[]},{},Array.from({length:33},(_,i)=>'joint'+i),new THREE.MeshToonMaterial()),/at most 32 joints/);});
