const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const select=(id,label,values,value)=>`<label class="field">${label}<select id="${id}">${values.map(v=>{const [key,text]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${key===value?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;
const input=(id,label,value,attrs='')=>`<label class="field">${label}<input id="${id}" type="number" value="${esc(value)}" ${attrs}></label>`;
const text=(id,label,value='')=>`<label class="field">${label}<input id="${id}" value="${esc(value)}"></label>`;
const button=(id,label)=>`<button class="text-button" id="${id}">${label}</button>`;
const validName=name=>/^[a-zA-Z][\w-]{0,63}$/.test(name);
export function createActionTools(){
 let recipeId='',variantId='',variantKind='variants',effect='onStart';
 return function render({page,fields,target,d,g,graph,notify,actions,rerender}){
  const $=id=>target.querySelector('#'+id),on=(id,fn)=>{const e=$(id);if(e)e.onchange=()=>fn(e.value);},click=(id,fn)=>{const e=$(id);if(e)e.onclick=fn;},numeric=Object.keys(g.variables).filter(k=>typeof g.variables[k]==='number');
  if(page==='stats'){
   fields.innerHTML='<h3>Character stats</h3><p class="note">Initial values reset with the scene. Bounds keep changes within a useful range. Actions can spend or recover a stat.</p>'+numeric.map((name,i)=>{const b=g.variableBounds?.[name];return `<fieldset><legend>${esc(name)}</legend>`+input('stat-value-'+i,'Initial value',g.variables[name],'step="any"')+input('stat-min-'+i,'Minimum',b?.min??Math.min(0,g.variables[name]),'step="any"')+input('stat-max-'+i,'Maximum',b?.max??Math.max(100,g.variables[name]),'step="any"')+(!b?button('stat-bound-'+i,'Apply these bounds'):'')+'</fieldset>';}).join('')+text('stat-name','New stat name')+input('stat-initial','Initial value',0,'step="any"')+input('stat-new-min','Minimum',0,'step="any"')+input('stat-new-max','Maximum',100,'step="any"')+button('stat-add','Add stat');
   const setBound=(name,min,max)=>graph(g=>{(g.variableBounds??={})[name]={min,max};g.variables[name]=Math.max(min,Math.min(max,g.variables[name]));});
   numeric.forEach((name,i)=>{on('stat-value-'+i,v=>graph(g=>{const b=g.variableBounds?.[name];g.variables[name]=b?Math.max(b.min,Math.min(b.max,+v)):+v;}));on('stat-min-'+i,v=>setBound(name,+v,Math.max(+v,+$('stat-max-'+i).value)));on('stat-max-'+i,v=>setBound(name,Math.min(+v,+$('stat-min-'+i).value),+v));click('stat-bound-'+i,()=>setBound(name,+$('stat-min-'+i).value,+$('stat-max-'+i).value));});
   click('stat-add',()=>{const name=$('stat-name').value.trim(),min=+$('stat-new-min').value,max=+$('stat-new-max').value,initial=+$('stat-initial').value;if(Object.keys(g.variables).length>=32)return notify('Keep at most 32 scene variables.');if(!validName(name)||name in g.variables)return notify('Use a unique stat name starting with a letter.');if(![min,max,initial].every(Number.isFinite)||min>max)return notify('Use finite values with minimum no higher than maximum.');graph(g=>{g.variables[name]=Math.max(min,Math.min(max,initial));(g.variableBounds??={})[name]={min,max};});});return;
  }
  const recipes=g.activities||{},ids=Object.keys(recipes);if(!ids.includes(recipeId))recipeId=ids[0]||'';const recipe=recipes[recipeId];
  fields.innerHTML='<h3>Action recipes</h3><p class="note">Each attempt chooses a weighted variation and speed. Stats affect success; completion effects happen once. Start a recipe from a state or event with Perform action.</p>'+select('recipe-selected','Recipe',ids,recipeId)+text('recipe-name','New recipe name')+select('recipe-new-actor','Character',d.actors.map(a=>[a.id,a.name]),d.actors[0]?.id)+button('recipe-add','Add recipe');
  on('recipe-selected',v=>{recipeId=v;variantId='';rerender();});
  click('recipe-add',()=>{const id=$('recipe-name').value.trim(),actor=$('recipe-new-actor').value,pack=d.packs[d.actors.find(a=>a.id===actor).pack],clip=Object.keys(pack.clips)[0];if(ids.length>=32)return notify('This scene already has 32 recipes.');if(!validName(id)||recipes[id])return notify('Use a unique recipe name starting with a letter.');recipeId=id;graph(g=>(g.activities??={})[id]={actor,variants:[{id:'variation-1',clip,weight:1,speed:{min:1,max:1}}],success:{base:1,modifiers:[]},onStart:[],onSuccess:[],onFailure:[]});});
  if(!recipe)return;
  const pack=d.packs[d.actors.find(a=>a.id===recipe.actor).pack],clips=Object.keys(pack.clips),patch=fn=>graph(g=>fn(g.activities[recipeId]));
  fields.insertAdjacentHTML('beforeend',select('recipe-actor','Character',d.actors.map(a=>[a.id,a.name]),recipe.actor)+button('recipe-remove','Remove recipe')+select('recipe-variation-kind','Outcome animation',[['variants','Successful attempt'],['failureVariants','Failed attempt']],variantKind));
  on('recipe-actor',v=>{const clip=Object.keys(d.packs[d.actors.find(a=>a.id===v).pack].clips)[0];patch(r=>{r.actor=v;r.variants=[{id:'variation-1',clip,weight:1,speed:{min:1,max:1}}];delete r.failureVariants;});});
  click('recipe-remove',()=>{const references=[];for(const [name,s]of Object.entries(g.states))if(s.actions.some(a=>a.type==='perform'&&a.activity===recipeId))references.push('state '+name);for(const h of g.handlers||[])if(h.actions.some(a=>a.type==='perform'&&a.activity===recipeId))references.push('event '+h.event);for(const [name,r]of Object.entries(recipes))for(const key of ['onStart','onSuccess','onFailure'])if(r[key]?.some(a=>a.type==='perform'&&a.activity===recipeId))references.push('recipe '+name);if(references.length)return notify('Remove Perform references first: '+references.join(', '));graph(g=>delete g.activities[recipeId]);});
  on('recipe-variation-kind',v=>{variantKind=v;variantId='';rerender();});
  const variants=recipe[variantKind]||[];if(!variants.some(v=>v.id===variantId))variantId=variants[0]?.id||'';const variant=variants.find(v=>v.id===variantId),vp=fn=>patch(r=>fn(r[variantKind].find(v=>v.id===variantId)));
  fields.insertAdjacentHTML('beforeend',select('recipe-variant','Variation',variants.map(v=>[v.id,v.id+' · '+v.clip]),variantId)+button('variant-add','Add variation')+(variant?'': '<p class="note">Without a failed variation, the normal movement plays before failure effects.</p>'));
  on('recipe-variant',v=>{variantId=v;rerender();});click('variant-add',()=>{if(variants.length>=16)return notify('Keep at most 16 variations per outcome.');let n=1;while(variants.some(v=>v.id==='variation-'+n))n++;variantId='variation-'+n;patch(r=>(r[variantKind]??=[]).push({id:variantId,clip:clips[0],weight:1,speed:{min:1,max:1}}));});
  if(variant){const duration=pack.clips[variant.clip].duration;fields.insertAdjacentHTML('beforeend',select('variant-clip','Animation clip',clips,variant.clip)+input('variant-start','Start, seconds',variant.start??0,`min="0" max="${duration}" step=".05"`)+input('variant-end','End, seconds',variant.end??duration,`min="0" max="${duration}" step=".05"`)+input('variant-weight','Choice weight',variant.weight,'min=".01" max="1000" step=".1"')+input('variant-speed-min','Slowest speed',variant.speed.min,'min=".1" max="4" step=".05"')+input('variant-speed-max','Fastest speed',variant.speed.max,'min=".1" max="4" step=".05"')+button('variant-remove','Remove variation')+'<h4>Pose variation</h4><p class="note">Each attempt samples an offset per channel. It fades in over the first 10% and out over the last 10%, preserving the original starting and ending pose.</p>'+Object.entries(variant.offsets||{}).map(([name,b],i)=>`<fieldset><legend>${esc(name)}</legend>`+input('offset-min-'+i,'Minimum',b.min,'step=".1"')+input('offset-max-'+i,'Maximum',b.max,'step=".1"')+button('offset-remove-'+i,'Remove offset')+'</fieldset>').join('')+select('offset-channel','Pose channel',[...new Set([...Object.values(pack.clips).flatMap(c=>Object.keys(c.tracks)),...pack.joints.flatMap(j=>['rotation','x','y'].map(k=>j.id+'.'+k))])].filter(k=>!variant.offsets?.[k]),'')+button('offset-add','Add pose offset'));
   fields.insertAdjacentHTML('beforeend','<h4>When to use this variation</h4>'+select('variant-condition','Only when variable',[['','Always'],...numeric],variant.when?.variable||'')+(variant.when?input('variant-condition-value','Equals',variant.when.value,'min="-1000000" max="1000000" step="any"'):'')+'<p class="note">Only matching variations can be chosen. Keep an unconditional variation if this action should work in every situation.</p>');
   on('variant-condition',v=>vp(x=>{if(v)x.when={variable:v,op:'eq',value:g.variables[v]};else delete x.when;}));on('variant-condition-value',v=>{const value=Number(v);if(!v.trim()||!Number.isFinite(value)||Math.abs(value)>1e6)return notify('Enter a number between −1,000,000 and 1,000,000.');vp(x=>x.when.value=value);});
   on('variant-clip',v=>vp(x=>{x.clip=v;delete x.start;delete x.end;delete x.offsets;}));on('variant-start',v=>{if(+v<0||+v>=(variant.end??duration))return notify('Start must be before the end.');vp(x=>x.start=+v);});on('variant-end',v=>{if(+v<= (variant.start??0)||+v>duration)return notify('End must follow the start and stay inside the clip.');vp(x=>x.end=+v);});on('variant-weight',v=>vp(x=>x.weight=+v));on('variant-speed-min',v=>vp(x=>{x.speed.min=+v;x.speed.max=Math.max(+v,x.speed.max);}));on('variant-speed-max',v=>vp(x=>{x.speed.max=+v;x.speed.min=Math.min(+v,x.speed.min);}));click('variant-remove',()=>{if(variantKind==='variants'&&variants.length===1)return notify('Keep at least one successful variation.');patch(r=>{r[variantKind]=r[variantKind].filter(v=>v.id!==variantId);if(!r[variantKind].length)delete r[variantKind];});});
   Object.keys(variant.offsets||{}).forEach((key,i)=>{on('offset-min-'+i,v=>vp(x=>{x.offsets[key].min=+v;x.offsets[key].max=Math.max(+v,x.offsets[key].max);}));on('offset-max-'+i,v=>vp(x=>{x.offsets[key].max=+v;x.offsets[key].min=Math.min(+v,x.offsets[key].min);}));click('offset-remove-'+i,()=>vp(x=>{delete x.offsets[key];if(!Object.keys(x.offsets).length)delete x.offsets;}));});click('offset-add',()=>{if(Object.keys(variant.offsets||{}).length>=32)return notify('Keep at most 32 pose offsets.');const key=$('offset-channel').value;if(key)vp(x=>(x.offsets??={})[key]={min:0,max:0});});
  }
  if(effect==='variantSuccess'&&!variant)effect='onStart';
  const success=recipe.success||{base:1,modifiers:[]};fields.insertAdjacentHTML('beforeend','<h3>Success chance</h3>'+input('recipe-success','Base chance',success.base,'min="0" max="1" step=".05"')+'<p class="note">Final chance = base + each stat × influence, limited to 0–1. A negative influence makes high values reduce success.</p>'+(success.modifiers||[]).map((m,i)=>`<fieldset><legend>Influence ${i+1}</legend>`+select('modifier-variable-'+i,'Stat',numeric,m.variable)+input('modifier-weight-'+i,'Influence per stat point',m.weight,'step=".01"')+button('modifier-remove-'+i,'Remove influence')+'</fieldset>').join('')+(numeric.length?button('modifier-add','Add stat influence'):'<p class="note">Add a numeric stat in Stats to influence success.</p>')+'<h3>Effects</h3>'+select('recipe-effect','When',[['onStart','On starting'],['onSuccess','On success'],['onFailure','On failure'],...(variant?[['variantSuccess','On this variation’s success']]:[])],effect)+'<div id="recipe-effects"></div>');
  on('recipe-success',v=>patch(r=>(r.success??={base:1,modifiers:[]}).base=+v));(success.modifiers||[]).forEach((m,i)=>{on('modifier-variable-'+i,v=>patch(r=>r.success.modifiers[i].variable=v));on('modifier-weight-'+i,v=>patch(r=>r.success.modifiers[i].weight=+v));click('modifier-remove-'+i,()=>patch(r=>r.success.modifiers.splice(i,1)));});click('modifier-add',()=>{if((success.modifiers||[]).length>=32)return notify('Keep at most 32 influences.');patch(r=>{r.success??={base:1,modifiers:[]};(r.success.modifiers??=[]).push({variable:numeric[0],weight:0});});});on('recipe-effect',v=>{effect=v;rerender();});if(effect==='variantSuccess')actions($('recipe-effects'),variant.onSuccess||[],fn=>vp(v=>fn(v.onSuccess??=[])));else actions($('recipe-effects'),recipe[effect]||[],fn=>patch(r=>fn(r[effect]??=[])));
 };
}
