const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const finiteInput=element=>element.value.trim()!==''&&Number.isFinite(Number(element.value))&&element.reportValidity();
export function createBakeTools({getDocument,commit,notify=()=>{}}){
 let actor='',start=0,duration=2,fps=30,clipId='physics-take',position=.5,angle=.5,busy=false,status='',abort=null,result=null,sourceJSON='',preview=null,previewTime=0,target=null;
 const disposePreview=()=>{preview?.controller.dispose();preview=null;};
 function render(container){
  target=container;const doc=getDocument(),actors=doc.actors.filter(a=>a.behavior?.mode&&a.behavior.mode!=='animated');if(!actors.some(a=>a.id===actor))actor=actors[0]?.id||'';
  const field=(id,label,value,min,max,step='any')=>`<label class="field">${label}<input id="${id}" type="number" required min="${min}" max="${max}" step="${step}" value="${value}" ${busy?'disabled':''}></label>`;
  const stale=result&&JSON.stringify(doc)!==sourceJSON;
  container.innerHTML=`<div class="section-label">Bake physics into a clip</div><p class="note">Record one physical character from the saved scene. Review the resulting motion before adding an editable clip. Live graphs, fluid and shared-object scenes are not supported by this bake.</p>${actors.length?`<label class="field">Character<select id="bake-actor" ${busy?'disabled':''}>${actors.map(a=>`<option value="${esc(a.id)}" ${a.id===actor?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><label class="field">New clip name<input id="bake-clip" required pattern="[a-zA-Z][a-zA-Z0-9_-]{0,63}" maxlength="64" value="${esc(clipId)}" ${busy?'disabled':''}></label><div class="two-col">${field('bake-start','Start / seconds',start,0,180)}${field('bake-duration','Length / seconds',duration,.1,8)}<label class="field">Samples per second<select id="bake-fps" ${busy?'disabled':''}>${[15,24,30,60,120].map(value=>`<option ${fps===value?'selected':''}>${value}</option>`).join('')}</select></label>${field('bake-position','Position tolerance / px',position,.01,5)}${field('bake-angle','Angle tolerance / degrees',angle,.01,5)}</div><button id="bake-run" class="text-button" ${busy?'disabled':''}>Record motion</button>${busy?'<button id="bake-cancel" class="text-button">Cancel recording</button>':''}`:'<p class="note">Choose a physical Body mode in the Feel panel before recording.</p>'}<p id="bake-status" class="note" role="status">${esc(status)}</p>${result?`<div id="bake-review"><p class="note" data-bake-summary>${result.diagnostics.samples} evaluated samples · ${result.diagnostics.keys} keys · error ${Number(result.diagnostics.maxPositionError).toFixed(3)}px / ${Number(result.diagnostics.maxAngleError).toFixed(3)}°</p><div id="bake-preview" aria-label="Baked character preview" style="width:100%;aspect-ratio:${doc.bounds.width}/${doc.bounds.height};overflow:hidden"></div><label class="field">Review time<input id="bake-scrub" type="range" min="0" max="${result.diagnostics.duration}" step="${1/120}" value="${previewTime}"></label><p class="note">${esc((result.diagnostics.notes||[]).join(' '))}</p>${result.diagnostics.widenedLimits?.length?`<p class="note">The copied rig widens ${result.diagnostics.widenedLimits.length} limits to retain the recorded motion.</p>`:''}${stale?'<p class="note">The scene changed since this recording. Record again before applying it.</p>':''}<button id="bake-apply" class="text-button" ${stale||busy?'disabled':''}>Apply baked motion</button><button id="bake-discard" class="text-button" ${busy?'disabled':''}>Discard recording</button></div>`:''}`;
  const $=id=>container.querySelector('#'+id);
  if(actors.length){$('bake-actor').onchange=e=>actor=e.target.value;$('bake-clip').onchange=e=>clipId=e.target.value;$('bake-fps').onchange=e=>fps=Number(e.target.value);
   for(const [id,set]of [['bake-start',v=>start=v],['bake-duration',v=>duration=v],['bake-position',v=>position=v],['bake-angle',v=>angle=v]])$(id).onchange=e=>{if(finiteInput(e.target))set(Number(e.target.value));};
   $('bake-run').onclick=async()=>{if(![...container.querySelectorAll('input:not([type="range"])')].every(el=>el.type==='number'?finiteInput(el):el.reportValidity()))return notify('Use a clip name and values within the shown limits.');const source=structuredClone(getDocument()),request={actor,start,duration,fps,clipId,maxPositionError:position,maxAngleError:angle};sourceJSON=JSON.stringify(source);busy=true;status='Recording physics…';abort=new AbortController();result=null;disposePreview();render(container);try{const {bakeSceneMotion}=await import('../src/scene-baking.js');const baked=await bakeSceneMotion(source,{...request,signal:abort.signal,onProgress:progress=>{status=({simulate:'Recording physics',refine:'Checking curves',validate:'Verifying motion'}[progress.phase]||progress.phase)+' · '+Math.round(progress.progress*100)+'%';const label=target?.querySelector('#bake-status');if(label)label.textContent=status;}});if(abort.signal.aborted){status='Recording cancelled.';return;}const [{SceneController},{renderSVG}]=await Promise.all([import('../src/scene.js'),import('../src/svg.js')]);result=baked;previewTime=0;preview={controller:new SceneController(baked.document,{reducedMotion:true}),renderSVG};status='Recording ready to review. The saved scene is unchanged.';}catch(error){status=error.name==='AbortError'?'Recording cancelled.':error.message;notify(status);}finally{busy=false;abort=null;if(target?.isConnected)render(target);}};
  }
  if(busy)$('bake-cancel')?.addEventListener('click',()=>{abort?.abort();status='Cancelling recording…';$('bake-status').textContent=status;});
  if(result){const draw=()=>{preview.controller.previewClip(result.diagnostics.actor,result.diagnostics.clipId,previewTime);$('bake-preview').innerHTML=preview.renderSVG(result.document,preview.controller.frame());};draw();$('bake-scrub').oninput=e=>{previewTime=Number(e.target.value);draw();};$('bake-discard').onclick=()=>{result=null;disposePreview();status='Recording discarded.';render(container);};$('bake-apply').onclick=()=>{if(JSON.stringify(getDocument())!==sourceJSON){status='The scene changed. Record again before applying.';return render(container);}const baked=result,oldPreview=preview;try{result=null;preview=null;const revision=getDocument().revision;commit(baked.commands);if(getDocument().revision===revision){result=baked;preview=oldPreview;throw Error('The recording was not applied. Check the scene validation message.');}oldPreview.controller.dispose();status='Baked motion added. Use Undo to restore the physical character.';notify(status);if(target?.isConnected)render(target);}catch(error){notify(error.message);if(target?.isConnected)render(target);}};}
 }
 return {render};
}
