import {validateObjectCommand} from '../src/scene-objects.js';
import {createActionTools} from './action-tools.js';
import {createPlacementTools} from './placement-tools.js';
import {inspectSceneFeatures,createSceneExport} from '../src/scene-export.js';
import {behaviorEnsembleEvents} from '../src/behaviors.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const select=(id,label,values,value)=>`<label class="field">${label}<select id="${id}">${values.map(v=>{const [key,text]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${key===value?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;
const input=(id,label,value,type='text',attrs='')=>`<label class="field">${label}<input id="${id}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
const button=(id,label)=>`<button id="${id}" class="text-button">${label}</button>`;
const parse=v=>v==='true'?true:v==='false'?false:Number.isFinite(+v)&&v.trim()!==''?+v:v;
const fresh=()=>({seed:17,variables:{enabled:true},initial:'idle',states:{idle:{actions:[]}},edges:[],handlers:[]});
export function createBehaviorTools({getDocument,commit,getController,getBottleControls=()=>null,play,notify}){
 const actionTools=createActionTools(),placementTools=createPlacementTools();
 let page='states',state='',edgeId='',bindingId='',handlerIndex=0;
 const doc=()=>getDocument();
 function change(fn){const next=structuredClone(doc());fn(next);const keys=['presentation','behaviorGraph','poseBindings','interactions','fluid','requiredFeatures'];const commands=keys.filter(k=>JSON.stringify(next[k])!==JSON.stringify(doc()[k])).map(k=>next[k]===undefined?{op:'delete',path:[k]}:{op:'set',path:[k],value:next[k]});if(commands.length)commit(commands);}
 function graph(fn){change(d=>{d.behaviorGraph??=fresh();d.requiredFeatures=[...new Set([...(d.requiredFeatures||[]),'behavior-graphs'])];fn(d.behaviorGraph);if(Object.keys(d.behaviorGraph.activities||{}).length)d.requiredFeatures=[...new Set([...d.requiredFeatures,'action-variations'])];});}
 function exportWebsite(){try{const result=createSceneExport(doc(),{runtimeBase:new URL('./runtime/',location.href).href}),url=URL.createObjectURL(new Blob([result.html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.download=doc().id+'.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Website illustration exported. Its runtime loads from this site.');}catch(e){notify(e.message);}}
 function render(target){
  if(page==='water'&&!doc().fluid)page='states';
  const d=doc(),g=d.behaviorGraph,$=id=>target.querySelector('#'+id),on=(id,fn)=>{const e=$(id);if(e)e.onchange=ev=>fn(ev.target.value);},click=(id,fn)=>{const e=$(id);if(e)e.onclick=fn;};
  target.innerHTML='<div class="inspector-heading">Scene behaviors<small>Events, states and interaction</small></div>'+select('behavior-presentation','Playback',[['live','Live illustration'],['sequence','Sequenced scene']],d.presentation||'live')+'<p class="note">Live scenes keep responding. Clips supply individual movements; branches decide what happens next. Sequence mode disables the live graph for a directed shot.</p><nav class="prop-tabs">'+['states','branches','events','stats','actions','placements','pointer',...(d.fluid?['water']:[]),'export'].map(p=>`<button data-behavior-page="${p}" class="${p===page?'active':''}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')+'</nav><div id="behavior-fields"></div><p id="behavior-live" class="note" aria-live="off"></p>';
  on('behavior-presentation',v=>change(d=>d.presentation=v));target.querySelectorAll('[data-behavior-page]').forEach(b=>b.onclick=()=>{page=b.dataset.behaviorPage;render(target);});const fields=$('behavior-fields');
  if(page==='export'){const info=inspectSceneFeatures(d);fields.innerHTML=`<h3>${info.runtime==='illustration'?'Physics-free illustration':'Full scene player'}</h3><p class="note">${esc(info.features.join(', '))}</p><p class="note">${esc(info.reasons.join(' '))} The HTML contains your scene and loads only its selected runtime from this website. Use the compiler for a self-hosted folder.</p>`+button('behavior-export','Download website HTML');click('behavior-export',exportWebsite);return;}
  if(page==='water'){
   const f=d.fluid;fields.innerHTML='<h3>Contained water</h3>'+input('fluid-fill','Water fill',f.fill,'number','min=".1" max=".65" step=".01"')+input('fluid-damping','Slosh damping',f.damping,'number','min=".1" max="3" step=".05"')+input('fluid-wind','Wind strength / direction',f.wind,'number','min="-2" max="2" step=".05"')+input('fluid-mass','Ship mass',f.ship.mass,'number','min=".1" max="10" step=".1"')+input('fluid-scale','Ship size',f.ship.scale,'number','min=".35" max="1" step=".05"')+button('fluid-nudge','Swirl water')+button('fluid-phone','Enable phone motion')+'<p class="note">Drag the bottle with one finger to let it hang. Two fingers hold its rotation. Shift-drag gives a second grip with a mouse. Water and ship continue moving after release. Arrow keys nudge a focused bottle.</p><p class="note">These settings are saved with the scene and included in website exports. This is a bounded 2D slosh and buoyancy model.</p>';
   for(const key of ['fill','damping','wind'])on('fluid-'+key,v=>change(d=>d.fluid[key]=+v));for(const key of ['mass','scale'])on('fluid-'+key,v=>change(d=>d.fluid.ship[key]=+v));click('fluid-nudge',()=>{getController().fluidInput({type:'nudge',ax:1100,ay:-350});play();});click('fluid-phone',async()=>{const controls=getBottleControls();if(controls?.motionEnabled){controls.disableMotion();$('fluid-phone').textContent='Enable phone motion';}else{play();if(await controls?.enableMotion())$('fluid-phone').textContent='Motion off';}});return;
  }
  if(page!=='pointer'&&!g){fields.innerHTML=button('behavior-enable','Add behavior graph');click('behavior-enable',()=>graph(()=>{}));return;}
  const actors=[['$actor','Actor that triggered the event'],...d.actors.map(a=>[a.id,a.name])],names=g?Object.keys(g.states):[];
  function actions(container,items,mutate,allowPerform=true){
   const inputSpecs=a=>d.packs[d.actors.find(v=>v.id===a.actor)?.pack]?.inputs||Object.assign({},...d.actors.map(v=>d.packs[v.pack].inputs));
   const valueField=(id,label,value,spec)=>spec?.options?select(id,label,spec.options,value):spec?.type==='boolean'?select(id,label,['true','false'],String(value)):input(id,label,value,spec?.type==='number'?'number':'text');
   const actionLabel=type=>({perform:'Perform action',add:'Change stat',set:'Set variable',input:'Set character input',event:'Send event',emitter:'Change emission',ensemble:'Character response',object:'Shared object command'}[type]||type);
   const types=['event',...(allowPerform&&Object.keys(g.activities||{}).length?['perform']:[]),...(Object.values(g.variables).some(v=>typeof v==='number')?['add']:[]),...(Object.keys(g.variables).length?['set']:[]),...(d.actors.some(a=>Object.keys(d.packs[a.pack].inputs).length)?['input']:[]),...(d.emitters?.length?['emitter']:[]),...(d.ensemble?['ensemble']:[]),...(d.objects?.length?['object']:[])];
   const objectActor=c=>d.actors.find(a=>a.id===c.actor),objectJoints=c=>d.packs[objectActor(c)?.pack]?.joints||[];
   const objectDefault=(type,objectId)=>{const prop=d.objects.find(o=>o.id===objectId)||d.objects[0],actor=d.actors.find(a=>a.id===prop.owner?.actor)||d.actors[0],joints=d.packs[actor?.pack]?.joints||[],joint=joints.find(j=>j.id===prop.owner?.joint)||joints.find(j=>/wrist|hand/i.test(j.id))||joints[0];if(!prop.mass||!actor)type='enable';return {type,object:prop.id,...(['attach','transfer'].includes(type)?{actor:actor.id,joint:joint.id,maxDistance:(prop.radius||12)+6,offsetX:0,offsetY:0}:{}),...(type==='transfer'?{from:prop.owner?.actor||actor.id}:{}),...(['release','impulse'].includes(type)?{vx:0,vy:0}:{}),...(type==='place'?{x:prop.x,y:prop.y}:{}),...(type==='enable'?{enabled:true}:{})};};
   const objectFields=(a,i)=>{const c=a.command,prop=d.objects.find(o=>o.id===c.object),num=(key,label,value)=>input('object-action-'+key+'-'+i,label,value,'number','required min="'+(key==='maxDistance'?0:-2000)+'" max="2000" step="any"');return select('object-action-object-'+i,'Shared object',d.objects.map(o=>[o.id,o.name]),c.object)+select('object-action-type-'+i,'Command',prop.mass?['attach','transfer','release','impulse','place','enable']:['enable'],c.type)+(['attach','transfer'].includes(c.type)?(c.type==='transfer'?select('object-action-from-'+i,'Required current owner',d.actors.map(a=>[a.id,a.name]),c.from):'')+select('object-action-actor-'+i,'Receiving actor',d.actors.map(a=>[a.id,a.name]),c.actor)+select('object-action-joint-'+i,'Grip joint',objectJoints(c).map(j=>j.id),c.joint)+num('maxDistance','Maximum contact distance',c.maxDistance??(prop.radius||12)+6)+num('offsetX','Grip offset X',c.offsetX||0)+num('offsetY','Grip offset Y',c.offsetY||0):c.type==='enable'?select('object-action-enabled-'+i,'Enabled',['true','false'],String(c.enabled)):select('object-action-actor-'+i,'Required owner (optional)',[['','No owner check'],...d.actors.map(a=>[a.id,a.name])],c.actor||'')+(c.type==='place'?num('x','Scene X',c.x)+num('y','Scene Y',c.y):num('vx','Horizontal speed / impulse',c.vx||0)+num('vy','Vertical speed / impulse',c.vy||0)))+'<p class="note">Transfers require the named owner and hand contact. Static objects only support enable/disable.</p>';};
   container.innerHTML=items.map((a,i)=>`<fieldset data-action="${i}"><legend>${i+1}. ${esc(actionLabel(a.type))}</legend>${select('action-type-'+i,'Action',types.map(t=>[t,actionLabel(t)]),a.type)}${a.type==='object'?objectFields(a,i):a.type==='perform'?select('action-activity-'+i,'Recipe',Object.keys(g.activities||{}),a.activity):['set','add'].includes(a.type)?select('action-variable-'+i,a.type==='add'?'Stat':'Variable',Object.keys(g.variables).filter(k=>a.type!=='add'||typeof g.variables[k]==='number'),a.variable)+input('action-value-'+i,a.type==='add'?'Change (+ or −)':'Value',a.value,a.type==='add'?'number':'text','step="any"'):a.type==='input'?select('action-actor-'+i,'Actor',actors,a.actor)+select('action-input-'+i,'Input',Object.keys(inputSpecs(a)),a.input)+valueField('action-value-'+i,'Value',a.value,inputSpecs(a)[a.input]):a.type==='emitter'?select('action-emitter-'+i,'Effect',(d.emitters||[]).map(e=>[e.id,e.name]),a.emitter)+select('action-enabled-'+i,'Emission',['true','false'],String(a.enabled)):select('action-actor-'+i,'Actor',[['','None'],...actors],a.actor||'')+(a.type==='ensemble'?select('action-event-'+i,'Response',behaviorEnsembleEvents,a.event):input('action-event-'+i,'Event',a.event))}${button('action-remove-'+i,'Remove action')}</fieldset>`).join('')+select('action-add-type','New action',types.map(t=>[t,actionLabel(t)]),'event')+button('action-add','Add action');
   const defaultAction=type=>{if(type==='object')return {type,command:objectDefault('enable',d.objects[0].id)};if(type==='perform')return {type,activity:Object.keys(g.activities)[0]};if(type==='add')return {type,variable:Object.keys(g.variables).find(k=>typeof g.variables[k]==='number'),value:1};if(type==='set'){const variable=Object.keys(g.variables)[0];return {type,variable,value:g.variables[variable]};}if(type==='input'){const actor=d.actors.find(a=>Object.keys(d.packs[a.pack].inputs||{}).length),input=Object.keys(d.packs[actor.pack].inputs)[0];return {type,actor:actor.id,input,value:d.packs[actor.pack].inputs[input].default};}if(type==='emitter')return {type,emitter:d.emitters?.[0]?.id,enabled:true};return {type,event:type==='ensemble'?'conversation':'scene-event'};};
   items.forEach((a,i)=>{if(a.type!=='object')return;for(const key of ['object','type','actor','joint','from','enabled','x','y','vx','vy','offsetX','offsetY','maxDistance'])on('object-action-'+key+'-'+i,v=>{const el=$('object-action-'+key+'-'+i),numeric=['x','y','vx','vy','offsetX','offsetY','maxDistance'].includes(key);if(numeric&&(v.trim()===''||!Number.isFinite(Number(v))||!el.reportValidity()))return notify('Enter a number in the shown range.');let command=structuredClone(a.command);if(key==='type')command=objectDefault(v,command.object);else if(key==='object')command=objectDefault(command.type,v);else if(key==='actor'){if(v){command.actor=v;if(['attach','transfer'].includes(command.type))command.joint=objectJoints(command).find(j=>/wrist|hand/i.test(j.id))?.id||objectJoints(command)[0]?.id;}else delete command.actor;}else command[key]=numeric?Number(v):key==='enabled'?v==='true':v;try{validateObjectCommand(d,command);mutate(list=>list[i]={type:'object',command});}catch(e){notify(e.message);}});});
   items.forEach((a,i)=>{on('action-type-'+i,v=>mutate(list=>list[i]=defaultAction(v)));for(const key of ['variable','actor','input','value','emitter','enabled','event','activity'])on('action-'+key+'-'+i,v=>mutate(list=>{if(key==='actor'&&!v)delete list[i][key];else list[i][key]=key==='value'||key==='enabled'?parse(v):v;if(key==='variable')list[i].value=list[i].type==='add'?1:g.variables[v];if(list[i].type==='input'){if(key==='actor'){list[i].input=Object.keys(inputSpecs(list[i]))[0];list[i].value=inputSpecs(list[i])[list[i].input].default;}if(key==='input')list[i].value=inputSpecs(list[i])[v].default;if(key==='value'&&inputSpecs(list[i])[list[i].input]?.type==='string')list[i].value=v;}}));click('action-remove-'+i,()=>mutate(list=>list.splice(i,1)));});click('action-add',()=>{if(items.length>=16)return notify('Keep at most 16 effects here.');mutate(list=>list.push(defaultAction($('action-add-type').value)));});
  }
  if(page==='placements'){placementTools({fields,d,change,notify,rerender:()=>render(target)});return;}
  if(page==='stats'||page==='actions'){actionTools({page,fields,target,d,g,graph,notify,actions:(container,items,mutate)=>actions(container,items,mutate,false),rerender:()=>render(target)});return;}
  if(page==='states'){
   if(!names.includes(state))state=g.initial;fields.innerHTML=select('behavior-initial','Start in',names,g.initial)+input('behavior-seed','Random seed',g.seed,'number','min="0" max="4294967295"')+select('behavior-state','Edit state',names,state)+input('behavior-new-state','New state name','')+button('behavior-add-state','Add state')+button('behavior-remove-state','Remove selected state')+'<h3>On entering this state</h3><div id="behavior-actions"></div>';
   on('behavior-initial',v=>graph(g=>g.initial=v));on('behavior-seed',v=>graph(g=>g.seed=+v));on('behavior-state',v=>{state=v;render(target);});click('behavior-add-state',()=>{const name=$('behavior-new-state').value.trim();if(!/^[a-zA-Z][\w-]{0,63}$/.test(name)||g.states[name])return notify('Use a unique state name, starting with a letter.');state=name;graph(g=>g.states[name]={actions:[]});});click('behavior-remove-state',()=>{if(names.length<2)return notify('Keep at least one state.');graph(g=>{delete g.states[state];g.edges=g.edges.filter(e=>e.from!==state&&e.to!==state);if(g.initial===state)g.initial=Object.keys(g.states)[0];});});actions($('behavior-actions'),g.states[state].actions,fn=>graph(g=>fn(g.states[state].actions)));
  }else if(page==='branches'){
   let edge=g.edges.find(e=>e.id===edgeId)||g.edges[0];edgeId=edge?.id||'';fields.innerHTML=select('behavior-edge','Branch',g.edges.map(e=>[e.id,e.from+' → '+e.to]),edgeId)+button('behavior-add-edge','Add branch')+(edge?select('edge-from','From',['*',...names],edge.from)+select('edge-to','To',names,edge.to)+select('edge-trigger','Trigger',['event','delay'],edge.after?'delay':'event')+(edge.after?input('edge-min','Earliest, seconds',edge.after.min,'number','min="0" step=".1"')+input('edge-max','Latest, seconds',edge.after.max,'number','min="0" step=".1"'):input('edge-event','Event name',edge.event))+input('edge-weight','Choice weight',edge.weight,'number','min=".01" max="1000" step=".1"')+select('edge-condition','Only if variable',[['','Always'],...Object.keys(g.variables)],edge.when?.variable||'')+(edge.when?select('edge-op','Comparison',['eq','neq',...(typeof g.variables[edge.when.variable]==='number'?['gt','gte','lt','lte']:[])],edge.when.op)+input('edge-value','Value',edge.when.value):'')+button('behavior-remove-edge','Remove branch'):'')+'<p class="note">Delays are sampled on state entry. Weights choose among eligible branches. * means any state.</p>';
   const patch=fn=>graph(g=>fn(g.edges.find(e=>e.id===edgeId)));on('behavior-edge',v=>{edgeId=v;render(target);});click('behavior-add-edge',()=>{edgeId='branch-'+Date.now().toString(36);graph(g=>g.edges.push({id:edgeId,from:g.initial,to:g.initial,event:'scene-event',weight:1}));});if(edge){for(const key of ['from','to','event','weight'])on('edge-'+key,v=>patch(e=>e[key]=key==='weight'?+v:v));on('edge-trigger',v=>patch(e=>{delete e.event;delete e.after;if(v==='delay')e.after={min:2,max:5};else e.event='scene-event';}));on('edge-min',v=>patch(e=>{e.after.min=+v;e.after.max=Math.max(+v,e.after.max);}));on('edge-max',v=>patch(e=>{e.after.max=+v;e.after.min=Math.min(+v,e.after.min);}));on('edge-condition',v=>patch(e=>{if(v)e.when={variable:v,op:'eq',value:g.variables[v]};else delete e.when;}));on('edge-op',v=>patch(e=>e.when.op=v));on('edge-value',v=>patch(e=>e.when.value=parse(v)));click('behavior-remove-edge',()=>graph(g=>g.edges=g.edges.filter(e=>e.id!==edgeId)));}
  }else if(page==='events'){
   const handlers=g.handlers||[];handlerIndex=Math.min(handlerIndex,Math.max(0,handlers.length-1));fields.innerHTML='<h3>Initial variables</h3>'+Object.entries(g.variables).map(([name,value],i)=>input('variable-'+i,name,value)).join('')+input('variable-name','New variable','')+select('variable-type','Type',['boolean','number'],'boolean')+button('variable-add','Add variable')+'<h3>Events in any state</h3>'+select('behavior-handler','Handler',handlers.map((h,i)=>[String(i),h.event]),String(handlerIndex))+input('handler-name','Event name',handlers[handlerIndex]?.event||'scene-event')+input('handler-new-name','New event name','scene-event')+button('handler-add','Add event handler')+(handlers.length?button('handler-remove','Remove handler')+'<div id="handler-actions"></div>':'')+'<h3>Try an event</h3>'+input('behavior-test-event','Event','extinguish-fire')+select('behavior-test-actor','Actor',[['','None'],...d.actors.map(a=>[a.id,a.name])],'')+button('behavior-test','Send event');
   Object.keys(g.variables).forEach((name,i)=>on('variable-'+i,v=>{const value=parse(v);if(typeof value!==typeof g.variables[name])return notify('Keep the variable’s existing type.');graph(g=>g.variables[name]=value);}));click('variable-add',()=>{const name=$('variable-name').value.trim();if(!/^[a-zA-Z][\w-]{0,63}$/.test(name)||name in g.variables)return notify('Use a unique variable name.');graph(g=>g.variables[name]=$('variable-type').value==='boolean'?false:0);});on('behavior-handler',v=>{handlerIndex=+v;render(target);});on('handler-name',v=>{if(handlers.length)graph(g=>g.handlers[handlerIndex].event=v);});click('handler-add',()=>{const event=$('handler-new-name').value.trim();if(!event)return notify('Enter an event name.');if(handlers.some(h=>h.event===event))return notify('This event already has a handler.');handlerIndex=handlers.length;graph(g=>(g.handlers??=[]).push({event,actions:[]}));});click('handler-remove',()=>graph(g=>g.handlers.splice(handlerIndex,1)));if(handlers.length)actions($('handler-actions'),handlers[handlerIndex].actions,fn=>graph(g=>fn(g.handlers[handlerIndex].actions)));click('behavior-test',()=>{try{getController().dispatch($('behavior-test-event').value,$('behavior-test-actor').value?{actor:$('behavior-test-actor').value}:{});play();}catch(e){notify(e.message);}});
  }else if(page==='pointer'){
   const bindings=d.interactions||[],b=bindings.find(b=>b.id===bindingId)||bindings[0];bindingId=b?.id||'';const a=d.actors.find(a=>a.id===b?.actor),pack=d.packs[a?.pack];fields.innerHTML=select('pointer-binding','Binding',bindings.map(b=>[b.id,b.actor+' · '+b.gesture+' · '+(b.joint||'whole actor')]),bindingId)+button('pointer-add','Add interaction')+(b?select('pointer-actor','Actor',d.actors.map(a=>[a.id,a.name]),b.actor)+select('pointer-joint','Body part',[['','Whole actor'],...pack.joints.map(j=>j.id)],b.joint||'')+select('pointer-gesture','Gesture',['click','drag','hover-fast'],b.gesture)+select('pointer-response','Response',b.gesture==='drag'?['event','carry','resist']:['event'],b.response)+input('pointer-event','Send event on release / gesture',b.event)+input('pointer-resistance','Resistance',b.resistance,'number','min="0" max="1" step=".05"')+(b.gesture==='hover-fast'?input('pointer-threshold','Speed threshold',b.threshold||450,'number','min="50" max="5000"'):'')+button('pointer-remove','Remove interaction'):'')+'<p class="note">Carry follows the pointer. Resist bends a limb or tugs the head and settles on release. Use an event handler to choose the character’s response. Test gestures on the stage while in Scene mode.</p>';
   const patch=fn=>change(d=>fn(d.interactions.find(b=>b.id===bindingId)));on('pointer-binding',v=>{bindingId=v;render(target);});click('pointer-add',()=>{bindingId='pointer-'+Date.now().toString(36);change(d=>{(d.interactions??=[]).push({id:bindingId,actor:d.actors[0].id,gesture:'click',response:'event',event:'scene-event',resistance:.7});d.requiredFeatures=[...new Set([...(d.requiredFeatures||[]),'pointer-interactions'])];});});if(b){on('pointer-actor',v=>patch(b=>{b.actor=v;delete b.joint;delete b.part;b.response='event';}));on('pointer-joint',v=>patch(b=>{if(v)b.joint=v;else{delete b.joint;b.response='event';}delete b.part;}));on('pointer-gesture',v=>patch(b=>{b.gesture=v;if(v!=='drag')b.response='event';}));on('pointer-response',v=>patch(b=>{b.response=v;if(v!=='event'&&!b.joint)b.joint=pack.joints.find(j=>j.id==='head')?.id||pack.joints[0].id;}));for(const key of ['event','resistance','threshold'])on('pointer-'+key,v=>patch(b=>b[key]=key==='event'?v:+v));click('pointer-remove',()=>change(d=>d.interactions=d.interactions.filter(b=>b.id!==bindingId)));}
  }
 }
 function update(frame){const el=document.getElementById('behavior-live');if(el&&frame.behavior)el.textContent='Now: '+frame.behavior.state+' · '+Object.entries(frame.behavior.variables).map(([k,v])=>k+'='+(typeof v==='number'?Math.round(v*100)/100:v)).join(' · ')+Object.entries(frame.behavior.actions||{}).map(([actor,a])=>' · '+actor+': '+a.activity+' / '+a.variant+' '+Math.round((a.progress||0)*100)+'%'+(a.active?'':' · done')).join('');}
 return {render,update,exportWebsite};
}
