import {spatialKinematics} from '../src/spatial.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=v=>v.replace(/([a-z])([A-Z])/g,'$1 $2').replaceAll('-',' ');
const set=(path,value)=>({op:'set',path,value});
export function createContactTools({getDocument,getFrame,commit}){
 let chosen=null,showGuides=true;
 const doc=()=>getDocument();
 const chains=actor=>{const joints=doc().packs[actor.pack].joints;return joints.flatMap(end=>{const lower=joints.find(j=>j.id===end.parent),upper=lower&&joints.find(j=>j.id===lower.parent);return upper&&Math.hypot(lower.x,lower.y)>.001&&Math.hypot(end.x,end.y)>.001?[{upper:upper.id,lower:lower.id,end:end.id}]:[];});};
 function point(actor,end){const f=getFrame().actors.find(a=>a.id===actor.id),p=doc().packs[actor.pack],w=p.spatial?spatialKinematics(p,f.pose)[end]:f.world[end],t=f.placement||actor.transform,r=t.rotation*Math.PI/180;return {x:+(t.x+t.scale*(w.x*Math.cos(r)-w.y*Math.sin(r))).toFixed(2),y:+(t.y+t.scale*(w.x*Math.sin(r)+w.y*Math.cos(r))).toFixed(2)};}
 function write(items){if(JSON.stringify(items)===JSON.stringify(doc().contacts||[]))return;commit([set(['contacts'],items),set(['requiredFeatures'],[...new Set([...(doc().requiredFeatures||[]),'contacts'])])]);}
 function render(target,actor){
  const items=(doc().contacts||[]).filter(c=>c.actor===actor.id),choices=chains(actor);if(!items.some(c=>c.id===chosen))chosen=items[0]?.id;
  const contact=items.find(c=>c.id===chosen),options=(values,value)=>values.map(([id,text])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(text)}</option>`).join(''),select=(id,title,values,value)=>`<label class="field">${title}<select id="contact-${id}">${options(values,value)}</select></label>`,number=(id,title,value,min,max,step=1)=>`<label class="field">${title}<input id="contact-${id}" type="number" value="${value}" min="${min}" max="${max}" step="${step}"></label>`;
  target.innerHTML=`<div class="contact-heading"><strong>Contacts & grips</strong><button id="contact-add" ${choices.length?'':'disabled'} title="Hold a hand or foot at its current position"><span class="material-symbols-outlined" aria-hidden="true">add</span>Add</button></div>${items.length?select('select','Contact',items.map(c=>[c.id,c.name]),chosen):'<p class="note">Add a contact to plant a foot or keep a hand on a handle. The two connected bones follow the target.</p>'}${!choices.length?'<p class="note">This actor needs a chain of three connected joints with nonzero bone lengths.</p>':''}`;
  target.querySelector('#contact-add').onclick=()=>{const chain=choices.find(c=>/leftFoot/i.test(c.end))||choices.find(c=>/Wrist|Hand/.test(c.end))||choices[0];if(!chain)return;let n=1;while(doc().contacts?.some(c=>c.id==='contact-'+n))n++;chosen='contact-'+n;write([...(doc().contacts||[]),{id:chosen,name:label(chain.end)+' contact',enabled:true,actor:actor.id,chain,target:{type:'point',...point(actor,chain.end)},bend:1,weight:1,start:0,end:180}]);};
  if(!contact)return;
  const p=doc().packs[actor.pack],targetActor=doc().actors.find(a=>a.id===contact.target.actor),targetJoints=targetActor?doc().packs[targetActor.pack].joints:[],targetOptions=[['','Scene point'],...doc().actors.map(a=>[a.id,a.name])];
  target.insertAdjacentHTML('beforeend',`<div class="contact-tabs"><button id="contact-enabled" aria-pressed="${contact.enabled}">${contact.enabled?'Enabled':'Disabled'}</button><label class="face-auto"><input id="contact-guides" type="checkbox" ${showGuides?'checked':''}>Show targets</label></div>${select('end','Hand or foot',choices.map(c=>[c.end,label(c.end)]),contact.chain.end)}<p class="note">${esc(label(contact.chain.upper))} → ${esc(label(contact.chain.lower))} → ${esc(label(contact.chain.end))}</p>${select('target-actor','Hold onto',targetOptions,contact.target.actor||'')}${targetActor?select('target-joint','Target joint',targetJoints.map(j=>[j.id,label(j.id)]),contact.target.joint):''}<div class="two-col">${number('x',targetActor?'Offset X':'Target X',contact.target.x??contact.target.offsetX??0,targetActor?-1000:-10000,targetActor?1000:10000,.5)}${number('y',targetActor?'Offset Y':'Target Y',contact.target.y??contact.target.offsetY??0,targetActor?-1000:-10000,targetActor?1000:10000,.5)}</div>${!targetActor?'<button id="contact-capture" class="text-button">Use current hand / foot position</button>':''}<div class="two-col">${select('bend','Knee / elbow side',[['1','Side A'],['-1','Side B']],String(contact.bend))}${number('weight','Strength',contact.weight,0,1,.05)}</div>${select('clip','During animation',[['','Every animation'],...Object.keys(p.clips).map(id=>[id,label(id)])],contact.clip||'')}<div class="two-col">${number('start','Start, seconds',contact.start,0,180,.05)}${number('end-time','End, seconds',contact.end,0,180,.05)}</div>${number('period','Repeat every, seconds · 0 = off',contact.period||0,0,180,.1)}<p id="contact-readout" class="note" role="status"></p><p class="note">Times repeat with the source clip. Joint limits stay in force. Unreachable targets show an orange gap. Contacts do not move the torso.</p><button id="contact-delete" class="text-button">Remove contact</button>`);
  const patch=change=>write(doc().contacts.map(c=>{if(c.id!==chosen)return c;const next={...c,...change};if(!next.clip)delete next.clip;if(!next.period)delete next.period;return next;}));
  target.querySelector('#contact-select').onchange=e=>{chosen=e.target.value;render(target,actor);};
  target.querySelector('#contact-enabled').onclick=()=>patch({enabled:!contact.enabled});
  target.querySelector('#contact-guides').onchange=e=>{showGuides=e.target.checked;};
  target.querySelector('#contact-end').onchange=e=>patch({chain:choices.find(c=>c.end===e.target.value)});
  target.querySelector('#contact-target-actor').onchange=e=>{const a=doc().actors.find(a=>a.id===e.target.value);patch({target:a?{type:'joint',actor:a.id,joint:doc().packs[a.pack].joints[0].id,offsetX:0,offsetY:0}:{type:'point',...point(actor,contact.chain.end)}});};
  if(targetActor)target.querySelector('#contact-target-joint').onchange=e=>patch({target:{...contact.target,joint:e.target.value}});
  else target.querySelector('#contact-capture').onclick=()=>patch({target:{type:'point',...point(actor,contact.chain.end)}});
  for(const axis of ['x','y'])target.querySelector('#contact-'+axis).onchange=e=>patch({target:{...contact.target,[targetActor?'offset'+axis.toUpperCase():axis]:+e.target.value}});
  for(const [id,key]of [['bend','bend'],['weight','weight'],['start','start'],['end-time','end'],['period','period']])target.querySelector('#contact-'+id).onchange=e=>patch({[key]:+e.target.value});
  target.querySelector('#contact-clip').onchange=e=>patch({clip:e.target.value});
  target.querySelector('#contact-delete').onclick=()=>write(doc().contacts.filter(c=>c.id!==chosen));
 }
 function update(frame,svg,active){
  const status=document.getElementById('contact-readout'),c=frame.contacts?.find(c=>c.id===chosen);if(status)status.textContent=!c?'Waiting for preview…':!c.active?'Outside active window or disabled':`Target gap: ${c.error.toFixed(1)} px${c.limited?' · limited by reach or joint range':''}`;
  let g=svg?.querySelector('[data-contact-guides]');if(!active||!showGuides){g?.remove();return;}if(!svg)return;if(!g){g=document.createElementNS('http://www.w3.org/2000/svg','g');g.dataset.contactGuides='';g.setAttribute('pointer-events','none');svg.append(g);}
  const points=(frame.contacts||[]).filter(c=>c.active&&c.target&&c.actual);g.innerHTML=points.map(c=>{const color=c.error>2?'#e78b35':'#6b55b4';return `<g data-contact-guide="${esc(c.id)}" stroke="${color}" stroke-width="1.5" fill="none"><path d="M${c.actual.x} ${c.actual.y}L${c.target.x} ${c.target.y}" stroke-dasharray="3 3"/><circle cx="${c.target.x}" cy="${c.target.y}" r="6"/><path d="M${c.target.x-9} ${c.target.y}h18M${c.target.x} ${c.target.y-9}v18"/><circle cx="${c.actual.x}" cy="${c.actual.y}" r="2" fill="${color}"/></g>`;}).join('');
 }
 return {render,update};
}
