import './director.css';
import {episodeExample} from '../examples/episode.js';
import {assertEpisode,episodeDuration,shotAt} from '../src/episode.js';
import {assertDocument} from '../src/schema.js';
import {interpolate,clamp,constrainPose,forwardKinematics} from '../src/index.js';
import {PerformanceCapture} from './performance-capture.js';
import {mountSVG,renderSVG} from '../src/svg.js';
import {saveReference,loadReference,captureVideo} from './reference.js';
const $=id=>document.getElementById(id),esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<span class="material-symbols-outlined" aria-hidden="true">${name}</span>`;
const button=(id,name,label)=>`<button id="${id}" aria-label="${label}" title="${label}">${icon(name)}</button>`;
const field=(label,id,value,attrs='type="number"')=>`<label class="field">${label}<input id="${id}" value="${esc(value)}" ${attrs}></label>`;
const select=(label,id,values,value)=>`<label class="field">${label}<select id="${id}">${values.map(([v,n])=>`<option value="${esc(v)}" ${v===value?'selected':''}>${esc(n)}</option>`).join('')}</select></label>`;
const key='posecraft.director.v1',unique=prefix=>prefix+'-'+crypto.randomUUID().slice(0,8);
let project;try{project=assertEpisode(JSON.parse(localStorage.getItem(key)));}catch{project=structuredClone(episodeExample);}
let selected=project.shots[0].id,panel='shot',actorId,joint='head',time=0,playing=false,last=null,current,renderer,renderedScene,worker,inFlight=false,pendingTime=0,ready=false,camDraft=null,past=[],future=[],referenceURL,referenceId,mediaURL,mediaName='',toastTimer,referenceOpacity=.5,difference=false,generation=0,bakeTarget=null;
const video=document.createElement('video');video.className='reference-video';video.controls=true;video.preload='auto';video.muted=true;video.playsInline=true;
const shot=()=>project.shots.find(s=>s.id===selected),scene=()=>project.scenes[shot().scene],actor=()=>scene().actors.find(a=>a.id===actorId)||scene().actors[0],pack=()=>scene().packs[actor()?.pack];
const startOf=id=>{let t=0;for(const s of project.shots){if(s.id===id)return t;t+=s.duration;}return 0;};
const localTime=()=>clamp(time-startOf(selected),0,shot().duration);
const cue=()=>shot().actors?.[actor()?.id]||{clip:pack()?.states[pack().initial].clip,offset:0,speed:1};
const cameraAt=()=>({...project.size,...Object.fromEntries(Object.entries(shot().camera).map(([k,keys])=>[k,interpolate(keys,localTime())])),...camDraft});
document.body.className='director-app';
$('app').innerHTML=`<header class="topbar"><a href="./" class="brand"><span class="brand-mark">p</span>posecraft <span class="director-title">Director</span></a><input id="episode-name" class="director-project-name" aria-label="Episode name" maxlength="100"><div class="director-mobile toolbar-group">${button('shots-panel','skeleton','Shots panel')}${button('settings-panel','tune','Shot settings')}</div><div class="toolbar-group">${button('undo','undo','Undo')}${button('redo','redo','Redo')}${button('open','folder_open','Open episode or scene')}${button('save','save','Save episode')}${button('export-frame','download','Export current frame SVG')}</div><div class="toolbar-group end"><a href="./" class="icon-button" aria-label="Character Studio" title="Character Studio">${icon('edit')}</a><a href="https://github.com/jelizarovas/posecraft/blob/main/docs/director.md" class="icon-button" aria-label="Director guide" title="Director guide">${icon('code')}</a></div><input id="project-file" type="file" hidden accept=".json,application/json"></header>
<main class="director-workspace"><aside class="director-left"><div class="section-label">Scenes <span id="scene-count"></span></div><select id="scene-select" aria-label="Shot scene"></select><div class="director-buttons"><button id="from-studio">Use Studio scene</button><button id="copy-scene" title="Duplicate this set">Copy set</button></div><div class="section-label">Shots <span id="shot-count"></span></div><div id="shots" class="shot-list"></div><div class="director-buttons">${button('add-shot','add','Add shot')}${button('copy-shot','content_copy','Duplicate shot')}${button('previous-shot','arrow_back','Move shot earlier')}${button('next-shot','open_in_new','Move shot later')}${button('delete-shot','delete','Delete shot')}</div></aside>
<section class="director-view"><div id="film" class="film-frame"><div id="film-art" class="film-art"></div><img id="reference-overlay" class="reference-overlay hidden" alt="Reference frame"></div><div id="film-caption" class="film-caption"></div></section>
<aside class="director-right"><nav class="director-panel-tabs">${['shot','camera','motion','place','reference','perform'].map(p=>`<button data-panel="${p}">${p[0].toUpperCase()+p.slice(1)}</button>`).join('')}</nav><div id="settings"></div></aside></main>
<section class="director-timeline"><div class="director-playback">${button('start','skip_previous','Start of episode')}${button('back-frame','arrow_back','Previous frame')}${button('play','play_arrow','Play episode')}${button('next-frame','open_in_new','Next frame')}<input id="frame-number" type="number" min="0" aria-label="Frame number"><span id="timecode"></span><span id="duration" class="duration"></span></div><input id="scrubber" class="director-scrub" type="range" min="0" step="1" aria-label="Episode timeline"><div id="ruler" class="director-ruler"></div></section><footer class="footer"><span id="status" class="director-status">Preparing episode...</span><span>Local project · MIT</span></footer><div id="toast" class="director-toast hidden" role="status"></div>`;
let performancePreview=null,performanceTarget=null;
const capture=new PerformanceCapture({preview:sample=>{performancePreview=sample;if(current)showFrame(current);},notify:toast,apply:take=>{if(!ready)return toast('Wait for the episode to load.');playing=false;performanceTarget={id:unique('take'),shot:selected,actor:actor().id,start:localTime()};capture.$('take-apply').disabled=true;worker.postMessage({type:'performance',...performanceTarget,take});}});
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),5500);}
function persist(){try{localStorage.setItem(key,JSON.stringify(project));}catch{toast('Local storage is full. Save the episode to a file.');}}
function commit(fn){try{const next=structuredClone(project);fn(next);next.revision++;assertEpisode(next);past.push(project);if(past.length>10)past.shift();future=[];project=next;camDraft=null;persist();rebuild();return true;}catch(e){toast(e.message);return false;}}
function rebuild(){
 if(!project.shots.some(s=>s.id===selected))selected=project.shots[0].id;time=clamp(time,startOf(selected),startOf(selected)+shot().duration);actorId=actor()?.id;if(!pack()?.joints.some(j=>j.id===joint))joint=pack()?.joints[0]?.id;
 $('episode-name').value=project.name;$('film').style.aspectRatio=`${project.size.width}/${project.size.height}`;$('undo').disabled=!past.length;$('redo').disabled=!future.length;
 drawShots();drawSettings();drawTimeline();startWorker();
}
function startWorker(){
 worker?.terminate();const token=++generation;ready=false;inFlight=false;pendingTime=time;renderer=null;renderedScene=null;
 worker=new Worker(new URL('../src/episode-worker.js',import.meta.url),{type:'module'});
 worker.onmessage=({data:m})=>{if(token!==generation)return;if(m.type==='error'){inFlight=false;playing=false;capture.updateTake();toast(m.message);return;}if(m.type==='performance'){const target=performanceTarget;if(!target||target.id!==m.id)return;if(commit(p=>{const s=p.shots.find(s=>s.id===target.shot);s.actors||={};s.actors[target.actor]=m.cue;}))toast('Take applied as editable pose and expression keys. Undo is available.');capture.updateTake();return;}if(m.type==='ready'){ready=true;send();return;}if(m.type==='bake'){const target=bakeTarget;if(!target||target.id!==m.id)return;commit(p=>{const s=p.shots.find(s=>s.id===target.shot),c=s.actors[target.actor];c.pose={...c.pose,[target.joint+'.rotation']:m.keys};delete c.motion;});toast('Motion baked into editable rotation keys.');return;}if(m.type==='frame'){inFlight=false;current=m.frame;showFrame(m.frame);$('status').textContent=`${project.scenes[m.frame.scene].name} · ${m.frame.actors.length} actors · Worker ${m.computeMs.toFixed(1)} ms`;if(pendingTime!==null)send();}};
 worker.onerror=e=>{if(token===generation){playing=false;ready=false;toast(e.message||'Episode worker could not load.');}};
 worker.postMessage({type:'init',project});
}
function send(){if(!ready||inFlight||pendingTime===null)return;inFlight=true;worker.postMessage({type:'frame',time:pendingTime});pendingTime=null;}
function requestFrame(){pendingTime=time;send();}
function showFrame(frame){
 if(performancePreview){const a=actor(),p=pack(),sample=performancePreview;frame={...frame,actors:frame.actors.map(f=>{if(f.id!==a?.id)return f;const basePose={...f.pose};for(const [key,value] of Object.entries(p.expressions?.[f.inputs.emotion]||{}))basePose[key]-=value;for(const [key,value] of Object.entries(p.expressions?.[sample.emotion]||{}))basePose[key]+=value;const pose=constrainPose(p.joints,{...basePose,...sample.pose});return {...f,pose,world:forwardKinematics(p.joints,pose),inputs:{...f.inputs,emotion:sample.emotion}};})};}
 const displayed=camDraft&&frame.shot===selected?{...frame,camera:{...frame.camera,...camDraft}}:frame;
 if(renderedScene!==frame.scene){renderer=mountSVG($('film-art'),project.scenes[frame.scene],displayed);renderedScene=frame.scene;}else renderer.update(displayed);
 $('film-caption').textContent=`${project.shots[frame.shotIndex].name} · ${frame.localTime.toFixed(2)} s`;
 refreshReference(project.shots[frame.shotIndex]);
}
async function refreshReference(s){const id=s.reference?.id;if(id===referenceId)return;referenceId=id;if(referenceURL)URL.revokeObjectURL(referenceURL);referenceURL=null;$('reference-overlay').classList.add('hidden');if(!id)return;try{const blob=await loadReference(id);if(referenceId!==id)return;if(blob){referenceURL=URL.createObjectURL(blob);$('reference-overlay').src=referenceURL;$('reference-overlay').classList.remove('hidden');}else if(panel==='reference')toast('Reference image is not on this device. Load the matching image again.');}catch(e){toast(e.message);}}
function drawShots(){
 $('scene-select').innerHTML=Object.entries(project.scenes).map(([id,s])=>`<option value="${id}" ${id===shot().scene?'selected':''}>${esc(s.name)}</option>`).join('');$('scene-count').textContent=Object.keys(project.scenes).length;$('shot-count').textContent=project.shots.length;
 let offset=0;$('shots').innerHTML=project.shots.map(s=>{const html=`<button class="shot-card ${s.id===selected?'active':''}" data-shot="${s.id}"><span><strong>${esc(s.name)}</strong><small>${offset.toFixed(2)}–${(offset+s.duration).toFixed(2)} s · ${esc(project.scenes[s.scene].name)}</small></span></button>`;offset+=s.duration;return html;}).join('');
 $('shots').querySelectorAll('[data-shot]').forEach(b=>b.onclick=()=>seek(startOf(b.dataset.shot),b.dataset.shot));$('delete-shot').disabled=project.shots.length===1;
}
function seek(value,shotId){playing=false;camDraft=null;time=clamp((shotId?Math.ceil(value*project.fps-1e-9):Math.round(value*project.fps))/project.fps,0,episodeDuration(project));selected=shotId||shotAt(project,time).shot.id;actorId=actor()?.id;drawShots();drawSettings();drawTimeline();requestFrame();}
function drawTimeline(){const total=episodeDuration(project);$('scrubber').max=Math.ceil(total*project.fps);$('scrubber').value=Math.round(time*project.fps);$('frame-number').max=Math.ceil(total*project.fps);if(document.activeElement!==$('frame-number'))$('frame-number').value=Math.round(time*project.fps);$('timecode').textContent=time.toFixed(2)+' s';$('duration').textContent=total.toFixed(2)+' s · '+project.fps+' fps';$('play').innerHTML=icon(playing?'pause':'play_arrow');$('play').setAttribute('aria-label',playing?'Pause episode':'Play episode');$('ruler').innerHTML=[0,.25,.5,.75,1].map(t=>`<span>${(total*t).toFixed(1)} s</span>`).join('');}
function editShot(fn){const id=selected;commit(p=>fn(p.shots.find(s=>s.id===id),p));}
function ensureCue(s){const a=actor(),p=pack();s.actors||={};return s.actors[a.id]||=( {clip:p.states[p.initial].clip,offset:0,speed:1});}
function addKey(keys,t,value){return [...(keys||[]).filter(k=>Math.abs(k[0]-t)>.00001),[t,value,$('key-easing')?.value||'smooth']].sort((a,b)=>a[0]-b[0]);}
function trimTracks(s,duration){const trim=tracks=>{for(const [key,keys] of Object.entries(tracks||{})){const value=interpolate(keys,duration);tracks[key]=keys.filter(k=>k[0]<duration);tracks[key].push([duration,value,'smooth']);}};trim(s.camera);for(const c of Object.values(s.actors||{})){trim(c.pose);trim(c.placement);if(c.expressions){c.expressions=c.expressions.filter(k=>k[0]<=duration);if(!c.expressions.length)delete c.expressions;}}s.duration=duration;}
function drawSettings(){
 document.querySelectorAll('[data-panel]').forEach(b=>b.classList.toggle('active',b.dataset.panel===panel));const s=shot();
 if(panel!=='perform'&&(capture.stream||capture.loading||capture.reviewing||performancePreview))capture.stop();
 if(panel==='shot'){
  $('settings').innerHTML=`<div class="inspector-heading">Shot details</div>${field('Shot name','shot-name',s.name,'maxlength="100"')}${field('Duration in seconds','shot-duration',s.duration,'type="number" min=".05" max="600" step=".1"')}<div class="section-label">Episode output</div>${select('Frame rate','fps',[12,24,25,30,60].map(n=>[String(n),n+' fps']),String(project.fps))}<div class="two-col">${field('Width','output-width',project.size.width,'type="number" min="64" max="4096"')}${field('Height','output-height',project.size.height,'type="number" min="64" max="4096"')}</div><p class="note">Shots cut at their boundaries. Several shots can reuse the same scene. Import scene JSON or use your current Studio scene to build another set.</p><button id="save-scene" class="text-button">Export this scene for Studio</button>`;
  $('shot-name').onchange=e=>editShot(s=>s.name=e.target.value);$('shot-duration').onchange=e=>editShot(s=>trimTracks(s,+e.target.value));$('fps').onchange=e=>commit(p=>p.fps=+e.target.value);for(const axis of ['width','height'])$('output-'+axis).onchange=e=>commit(p=>p.size[axis]=+e.target.value);$('save-scene').onclick=()=>download(scene().id+'.json',JSON.stringify(scene(),null,2));
 }else if(panel==='camera'){
  const c=cameraAt();$('settings').innerHTML=`<div class="inspector-heading">Camera<small>${localTime().toFixed(2)} s in shot</small></div><div class="two-col">${field('Center X','camera-x',c.x)}${field('Center Y','camera-y',c.y)}${field('Zoom','camera-zoom',c.zoom,'type="number" min=".1" max="10" step=".05"')}${field('Rotation','camera-rotation',c.rotation,'type="number" min="-180" max="180" step="1"')}</div>${select('Interpolation','key-easing',[['smooth','Smooth'],['linear','Linear'],['step','Hold / cut']],'smooth')}<button id="camera-key" class="text-button">${icon('add')}Key camera here</button><button id="camera-remove" class="text-button">Remove camera keys here</button><button id="camera-fit" class="text-button">Fit scene</button><div class="key-summary">Key times: ${[...new Set(Object.values(s.camera).flatMap(t=>t.map(k=>k[0])))].sort((a,b)=>a-b).map(t=>t.toFixed(2)).join(', ')} s</div><p class="note">Drag the preview to pan; scroll to zoom. Scrub to a frame, set the composition, then key it. Camera movement changes the view, not the actors or their joints.</p>`;
  for(const k of ['x','y','zoom','rotation'])$('camera-'+k).oninput=e=>{playing=false;const n=+e.target.value;if(!Number.isFinite(n)||(k==='zoom'&&n<=0))return;camDraft={...cameraAt(),[k]:n};if(current)showFrame(current);drawTimeline();};
  $('camera-key').onclick=()=>{const values=cameraAt(),t=localTime();editShot(s=>{for(const k of ['x','y','zoom','rotation'])s.camera[k]=addKey(s.camera[k],t,values[k]);});};
  $('camera-remove').onclick=()=>{const t=localTime();editShot(s=>{for(const k of Object.keys(s.camera)){const old=s.camera[k];s.camera[k]=old.filter(v=>Math.abs(v[0]-t)>.00001);if(!s.camera[k].length)s.camera[k]=[[0,old[0][1]]];}});};
  $('camera-fit').onclick=()=>{camDraft={x:scene().bounds.width/2,y:scene().bounds.height/2,zoom:Math.min(1,project.size.height/project.size.width*scene().bounds.width/scene().bounds.height),rotation:0};drawSettings();if(current)showFrame(current);};
 }else if(panel==='motion')drawMotion();else if(panel==='place')drawPlace();else if(panel==='perform'){playing=false;const a=actor();if(a)capture.mount($('settings'),{shot:selected,actor:a.id,pack:pack(),actors:scene().actors},id=>{actorId=id;drawSettings();});else{capture.stop();$('settings').textContent='Add a character in Studio first.';}}else drawReference();
}
function drawMotion(){
 const a=actor(),p=pack();if(!a){$('settings').innerHTML='<p>Add a character to this scene in Studio.</p>';return;}actorId=a.id;if(!p.joints.some(j=>j.id===joint))joint=p.joints[0].id;const c=cue(),j=p.joints.find(j=>j.id===joint),m=c.motion;
 $('settings').innerHTML=`${select('Actor','motion-actor',scene().actors.map(a=>[a.id,a.name]),a.id)}<div class="two-col">${select('Action','motion-clip',Object.keys(p.clips).map(id=>[id,id]),c.clip)}${select('Expression key','motion-emotion',(p.inputs.emotion?.options||[]).map(id=>[id,id]),c.expressions?.filter(k=>k[0]<=localTime()).at(-1)?.[1]||c.emotion||a.inputs?.emotion||p.inputs.emotion?.default)}</div><div class="two-col">${field('Speed','motion-speed',c.speed,'type="number" min="0" max="4" step=".1"')}${field('Clip offset','motion-offset',c.offset,'type="number" min="0" max="600" step=".1"')}</div>${select('Body part','motion-joint',p.joints.map(j=>[j.id,j.id]),joint)}<div class="two-col">${field('Rotation key','pose-angle',c.pose?.[joint+'.rotation']?interpolate(c.pose[joint+'.rotation'],localTime()):j.rotation,`type="number" min="${j.min}" max="${j.max}"`)}<button id="pose-key">${icon('add')}Key pose</button></div>${select('Procedural layer','motion-kind',[['off','Off'],['sway','Periodic sway'],['noise','Smooth seeded noise']],m?.kind||'off')}<div class="two-col">${field('Amplitude (degrees)','motion-amplitude',m?.amplitude??3,'type="number" min="0" max="180" step=".5"')}${field('Frequency (Hz)','motion-frequency',m?.frequency??1,'type="number" min=".01" max="10" step=".1"')}</div>${field('Seed','motion-seed',m?.seed??42,'type="number" min="0" max="2147483647" step="1"')}<div class="director-buttons"><button id="bake-motion" ${!m?'disabled':''}>Bake motion</button><button id="clear-expressions" ${!c.expressions?'disabled':''}>Clear face keys</button></div><p class="note">Expression changes key the current frame. Joint limits still apply. The same seed reproduces the same motion. Keys live in this shot.</p>`;
 $('motion-actor').onchange=e=>{actorId=e.target.value;drawSettings();};$('motion-joint').onchange=e=>{joint=e.target.value;drawSettings();};
 for(const k of ['clip','emotion','speed','offset'])$('motion-'+k).onchange=e=>editShot(s=>{const c=ensureCue(s);if(k==='emotion'){c.expressions=[...(c.expressions||[]).filter(key=>Math.abs(key[0]-localTime())>.00001),[localTime(),e.target.value]].sort((a,b)=>a[0]-b[0]);}else c[k]=['speed','offset'].includes(k)?+e.target.value:e.target.value;});
 $('clear-expressions').onclick=()=>{const value=$('motion-emotion').value;editShot(s=>{const c=ensureCue(s);delete c.expressions;c.emotion=value;});};
 $('pose-key').onclick=()=>{const angle=+$('pose-angle').value,t=localTime();editShot(s=>{const c=ensureCue(s);c.pose||={};c.pose[joint+'.rotation']=addKey(c.pose[joint+'.rotation'],t,angle);});};
 for(const id of ['kind','amplitude','frequency','seed'])$('motion-'+id).onchange=()=>{const kind=$('motion-kind').value,m={kind,joint,channel:'rotation',amplitude:+$('motion-amplitude').value,frequency:+$('motion-frequency').value,seed:+$('motion-seed').value};editShot(s=>{const c=ensureCue(s);if(kind==='off')delete c.motion;else c.motion=m;});};
 $('bake-motion').onclick=()=>{if(c.motion?.channel!=='rotation')return toast('Only rotation layers can be baked here.');joint=c.motion.joint;bakeTarget={id:unique('bake'),shot:selected,actor:actorId,joint};worker.postMessage({type:'bake',...bakeTarget});};
}
function drawPlace(){
 const a=actor();if(!a){$('settings').innerHTML='<p>Add a character in Studio first.</p>';return;}actorId=a.id;const c=cue(),values={...a.transform,...Object.fromEntries(Object.entries(c.placement||{}).map(([k,keys])=>[k,interpolate(keys,localTime())]))};
 $('settings').innerHTML=`${select('Actor','place-actor',scene().actors.map(a=>[a.id,a.name]),a.id)}<div class="inspector-heading">Placement<small>${localTime().toFixed(2)} s</small></div><div class="two-col">${field('X','place-x',values.x)}${field('Y','place-y',values.y)}${field('Scale','place-scale',values.scale,'type="number" min=".05" max="10" step=".05"')}${field('Rotation','place-rotation',values.rotation,'type="number" min="-180" max="180"')}</div>${select('Interpolation','key-easing',[['smooth','Smooth'],['linear','Linear'],['step','Hold / cut']],'smooth')}<button id="place-key" class="text-button">${icon('add')}Key placement here</button><button id="place-remove" class="text-button">Remove placement keys here</button><p class="note">Move actors through the scene without changing their source rigs. For walking, pair placement keys with a suitable walk cycle. Placement keys do not create foot planting.</p>`;
 $('place-actor').onchange=e=>{actorId=e.target.value;drawSettings();};$('place-key').onclick=()=>{const values=Object.fromEntries(['x','y','scale','rotation'].map(k=>[k,+$('place-'+k).value])),t=localTime();editShot(s=>{const c=ensureCue(s);c.placement||={};for(const [k,v] of Object.entries(values))c.placement[k]=addKey(c.placement[k],t,v);});};
 $('place-remove').onclick=()=>{const t=localTime();editShot(s=>{const c=ensureCue(s);for(const [k,keys] of Object.entries(c.placement||{})){c.placement[k]=keys.filter(v=>Math.abs(v[0]-t)>.00001);if(!c.placement[k].length)delete c.placement[k];}});};
}
function drawReference(){
 const ref=shot().reference;$('settings').innerHTML=`<div class="inspector-heading">Reference frame</div><button id="load-media" class="text-button">${icon('folder_open')}Open video or image</button><input id="media-file" type="file" hidden accept="video/*,image/png,image/jpeg,image/webp"><div id="video-slot"></div>${field('Source time (seconds)','source-time',video.currentTime||0,'type="number" min="0" step=".01"')}<div class="director-buttons"><button id="capture">Use video frame</button><button id="download-reference">Export PNG</button></div><label class="field">Overlay opacity<input id="reference-opacity" type="range" min="0" max="1" step=".05" value="${referenceOpacity}"></label><label class="face-auto"><input id="reference-difference" type="checkbox" ${difference?'checked':''}> Difference comparison</label><p id="reference-name" class="note">${ref?esc(ref.name)+' · source '+ref.time.toFixed(3)+' s':'No reference attached to this shot.'}</p><button id="clear-reference" class="text-button">Remove reference</button><p class="note">Media stays on this device. Captured frames are stored locally; exported episode JSON contains reference names and timestamps. Export PNGs to move references to another device.</p>`;
 if(mediaURL)$('video-slot').append(video);$('capture').disabled=!mediaURL;$('download-reference').disabled=!ref;
 $('load-media').onclick=()=>$('media-file').click();$('media-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.type.startsWith('video/')){if(file.size>500000000)throw new Error('Use a video smaller than 500 MB.');if(mediaURL)URL.revokeObjectURL(mediaURL);mediaURL=URL.createObjectURL(file);mediaName=file.name;video.src=mediaURL;video.onerror=()=>toast('This browser could not decode the video. Try MP4/H.264 or WebM.');drawReference();}else if(['image/png','image/jpeg','image/webp'].includes(file.type)){if(file.size>20000000)throw new Error('Use an image smaller than 20 MB.');await attachReference(file,file.name,0);}else throw new Error('Use a video, PNG, JPEG, or WebP file.');}catch(e){toast(e.message);}};
 $('source-time').onchange=e=>{if(mediaURL&&Number.isFinite(video.duration))video.currentTime=clamp(+e.target.value,0,Math.max(0,video.duration-.001));};video.ontimeupdate=()=>{if($('source-time')&&document.activeElement!==$('source-time'))$('source-time').value=video.currentTime.toFixed(3);};
 $('capture').onclick=async()=>{const target=selected;try{$('capture').disabled=true;const frame=await captureVideo(video,+$('source-time').value);if(target!==selected)return toast('Shot changed during capture. Capture again on the intended shot.');await attachReference(frame.blob,mediaName,frame.time);}catch(e){toast(e.message);}finally{if($('capture'))$('capture').disabled=!mediaURL;}};
 $('download-reference').onclick=async()=>{const ref=shot().reference;if(!ref)return;const blob=await loadReference(ref.id);if(blob)download(ref.id+(blob.type==='image/png'?'.png':blob.type==='image/jpeg'?'.jpg':'.webp'),blob);else toast('Load this reference on this device first.');};
 $('reference-opacity').oninput=e=>{referenceOpacity=+e.target.value;$('reference-overlay').style.opacity=referenceOpacity;};$('reference-difference').onchange=e=>{difference=e.target.checked;$('reference-overlay').style.mixBlendMode=difference?'difference':'normal';};$('clear-reference').onclick=()=>editShot(s=>delete s.reference);
}
async function attachReference(blob,name,time){const target=selected,id=unique('ref');await saveReference(id,blob);commit(p=>{const s=p.shots.find(s=>s.id===target);if(s)s.reference={id,name:name.slice(0,200),time};});toast('Reference attached. Use opacity or difference to compare.');}
function download(name,content,type='application/json'){const url=URL.createObjectURL(content instanceof Blob?content:new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function importScene(doc){assertDocument(doc);const id=unique('scene'),shotId=unique('shot');const done=commit(p=>{p.scenes[id]=doc;p.shots.push({id:shotId,name:doc.name,scene:id,duration:3,camera:{x:[[0,doc.bounds.width/2]],y:[[0,doc.bounds.height/2]],zoom:[[0,1]],rotation:[[0,0]]},actors:{}});});if(done){selected=shotId;seek(startOf(shotId),shotId);}}
$('episode-name').onchange=e=>commit(p=>p.name=e.target.value);$('scene-select').onchange=e=>editShot(s=>{s.scene=e.target.value;s.actors={};const b=project.scenes[e.target.value].bounds;s.camera={x:[[0,b.width/2]],y:[[0,b.height/2]],zoom:[[0,1]],rotation:[[0,0]]};});
$('from-studio').onclick=()=>{try{const doc=JSON.parse(localStorage.getItem('posecraft.studio.v2'));if(!doc)throw new Error('Save a scene in Character Studio first.');importScene(doc);}catch(e){toast(e.message);}};
$('copy-scene').onclick=()=>{const source=shot().scene,id=unique('scene');editShot((s,p)=>{p.scenes[id]=structuredClone(p.scenes[source]);p.scenes[id].name=(p.scenes[id].name+' copy').slice(0,100);s.scene=id;});};
function copyShot(){const copy=structuredClone(shot());copy.id=unique('shot');copy.name=(copy.name+' copy').slice(0,100);const index=project.shots.indexOf(shot());if(commit(p=>p.shots.splice(index+1,0,copy)))seek(startOf(copy.id),copy.id);}
$('add-shot').onclick=$('copy-shot').onclick=copyShot;$('delete-shot').onclick=()=>{if(project.shots.length>1)commit(p=>p.shots=p.shots.filter(s=>s.id!==selected));};
for(const [id,delta] of [['previous-shot',-1],['next-shot',1]])$(id).onclick=()=>{const index=project.shots.indexOf(shot()),to=index+delta;if(to<0||to>=project.shots.length)return;commit(p=>{[p.shots[index],p.shots[to]]=[p.shots[to],p.shots[index]];});seek(startOf(selected),selected);};
for(const b of document.querySelectorAll('[data-panel]'))b.onclick=()=>{panel=b.dataset.panel;drawSettings();};
$('undo').onclick=()=>{if(!past.length)return;future.push(project);project=past.pop();camDraft=null;persist();rebuild();};$('redo').onclick=()=>{if(!future.length)return;past.push(project);project=future.pop();camDraft=null;persist();rebuild();};
$('save').onclick=()=>download(project.id+'.episode.json',JSON.stringify(project,null,2));$('export-frame').onclick=()=>{if(current)download(`${project.id}-frame-${Math.round(current.time*project.fps)}.svg`,renderSVG(project.scenes[current.scene],camDraft?{...current,camera:cameraAt()}:current).replace('width="100%" height="100%"',`width="${project.size.width}" height="${project.size.height}"`),'image/svg+xml');};
$('open').onclick=()=>$('project-file').click();$('project-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw new Error('Project exceeds 20 MB.');const doc=JSON.parse(await file.text());if(doc.kind==='scene')importScene(doc);else{assertEpisode(doc);past.push(project);future=[];project=doc;selected=doc.shots[0].id;time=0;playing=false;camDraft=null;persist();rebuild();}}catch(e){toast(e.message);}e.target.value='';};
$('scrubber').oninput=e=>seek(+e.target.value/project.fps);$('frame-number').onchange=e=>seek(+e.target.value/project.fps);$('start').onclick=()=>seek(0);$('back-frame').onclick=()=>seek(time-1/project.fps);$('next-frame').onclick=()=>seek(time+1/project.fps);$('play').onclick=()=>{if(time>=episodeDuration(project))time=0;playing=!playing;camDraft=null;last=null;drawTimeline();};
$('shots-panel').onclick=()=>{document.body.classList.toggle('director-show-left');document.body.classList.remove('director-show-right');};$('settings-panel').onclick=()=>{document.body.classList.toggle('director-show-right');document.body.classList.remove('director-show-left');};
document.addEventListener('visibilitychange',()=>{last=null;video.pause();});window.addEventListener('pagehide',()=>{worker?.terminate();if(mediaURL)URL.revokeObjectURL(mediaURL);if(referenceURL)URL.revokeObjectURL(referenceURL);});
let pan=null;
$('film').style.touchAction='none';
$('film').onpointerdown=e=>{if(panel!=='camera'||e.button!==0)return;playing=false;pan={x:e.clientX,y:e.clientY,camera:cameraAt()};$('film').setPointerCapture(e.pointerId);};
$('film').onpointermove=e=>{if(!pan)return;const c=pan.camera,scale=scene().bounds.width/$('film').getBoundingClientRect().width/c.zoom,dx=(e.clientX-pan.x)*scale,dy=(e.clientY-pan.y)*scale,a=c.rotation*Math.PI/180;camDraft={...c,x:c.x-dx*Math.cos(a)+dy*Math.sin(a),y:c.y-dx*Math.sin(a)-dy*Math.cos(a)};if(current)showFrame(current);for(const k of ['x','y'])if($('camera-'+k))$('camera-'+k).value=camDraft[k].toFixed(2);};
$('film').onpointerup=$('film').onpointercancel=()=>{pan=null;};
$('film').addEventListener('wheel',e=>{if(panel!=='camera')return;e.preventDefault();playing=false;camDraft={...cameraAt(),zoom:clamp(cameraAt().zoom*Math.exp(-e.deltaY*.001),.1,10)};if(current)showFrame(current);$('camera-zoom').value=camDraft.zoom.toFixed(3);},{passive:false});
rebuild();
function tick(now){const dt=last===null?0:Math.min((now-last)/1000,.1);last=now;if(playing&&!document.hidden){time=Math.min(time+dt,episodeDuration(project));const next=shotAt(project,time).shot.id;if(next!==selected){selected=next;actorId=actor()?.id;drawShots();drawSettings();}if(time===episodeDuration(project))playing=false;drawTimeline();pendingTime=Math.round(time*project.fps)/project.fps;pendingTime=Math.min(pendingTime,episodeDuration(project));send();}requestAnimationFrame(tick);}requestAnimationFrame(tick);
