import './draw.css';
import {DocumentStore} from '../src/commands.js';
import {createDrawing,shapePath,validatePath,importSVG,assignArtwork,movePivot,reparentJoint,jointMatrices,matrixText,parseTransform,multiply} from '../src/vector-authoring.js';
const $=id=>document.getElementById(id),ns='http://www.w3.org/2000/svg',key='posecraft.draw.v1';
let store;try{store=new DocumentStore(JSON.parse(localStorage.getItem(key))||createDrawing());}catch{store=new DocumentStore(createDrawing());}
let selected=null,joint='root',mode='art',drag=null;const pack=()=>store.document.packs.drawing;
const shapeIcons={rectangle:'<rect x="4" y="6" width="16" height="12" rx="1"/>',circle:'<circle cx="12" cy="12" r="8"/>',change_history:'<path d="M12 4L21 20H3Z"/>'};
const icon=(name)=>shapeIcons[name]?`<svg class="shape-icon" viewBox="0 0 24 24" aria-hidden="true">${shapeIcons[name]}</svg>`:`<span class="material-symbols-outlined" aria-hidden="true">${name}</span>`;
document.getElementById('app').innerHTML=`<header><a class="brand" href="./">p <b>posecraft</b></a><strong>Draw & Rig</strong><nav><a href="./">Studio</a><a href="./director.html">Director</a><a href="./demos.html">Demos</a></nav></header><div class="tools"><button id="new" title="New drawing">${icon('add')}New</button><button id="import">${icon('folder_open')}Import SVG</button><button id="open">${icon('folder_open')}Open</button><button id="save">${icon('download')}Save JSON</button><button id="studio" class="primary">${icon('animation')}Animate</button><span class="spacer"></span><button id="undo" aria-label="Undo">${icon('undo')}</button><button id="redo" aria-label="Redo">${icon('redo')}</button><input id="svg-file" type="file" accept=".svg,image/svg+xml" hidden><input id="json-file" type="file" accept=".json,application/json" hidden></div><main><section class="canvas"><div class="canvas-tools"><button data-shape="rectangle">${icon('rectangle')}Rectangle</button><button data-shape="ellipse">${icon('circle')}Ellipse</button><button data-shape="triangle">${icon('change_history')}Triangle</button><button id="add-joint">${icon('skeleton')}Joint</button></div><div class="paper"><svg id="art" role="img" aria-label="Drawing canvas"></svg></div><p class="hint">Select artwork to move it. In Rig, drag a joint to set its pivot.</p></section><aside><div class="tabs"><button id="art-tab" class="active">Artwork</button><button id="rig-tab">Rig</button></div><div id="panel"></div></aside></main><footer id="status" role="status">Draw shapes or import a simple SVG to begin. Saved locally.</footer>`;
function status(text){$('status').textContent=text;}
function persist(){try{localStorage.setItem(key,JSON.stringify(store.document));}catch{status('Local storage is full. Save JSON to keep your work.');}}
function commit(next,message='Saved locally.'){try{store.transact([{op:'set',path:['packs','drawing'],value:next}]);persist();render();status(message);}catch(e){status(e.message);}}
function load(doc){if(Object.keys(doc.packs||{}).length!==1||!doc.packs.drawing||doc.actors?.length!==1||doc.actors[0].pack!=='drawing'||doc.packs.drawing.spatial||!Object.entries({x:0,y:0,rotation:0,scale:1}).every(([k,v])=>doc.actors[0].transform?.[k]===v))throw Error('Open a Draw & Rig JSON project here. Use Character Studio for other scenes.');for(const part of doc.packs.drawing.parts){validatePath(part.d);parseTransform(part.transform);if(part.spatial||part.variants||part.showWhen||part.opacityChannel)throw Error('Open complex artwork in Character Studio. Draw & Rig currently edits flat paths.');}store=new DocumentStore(doc);selected=null;joint='root';persist();render();}
function element(tag,attrs={}){const el=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,String(v));return el;}
function render(){if(!pack().joints.some(j=>j.id===joint))joint=pack().joints[0].id;if(!pack().parts.some(p=>p.id===selected))selected=pack().parts[0]?.id;draw();panel();$('undo').disabled=!store.past.length;$('redo').disabled=!store.future.length;}
function draw(){const svg=$('art'),world=jointMatrices(pack());svg.replaceChildren();svg.setAttribute('viewBox',`0 0 ${store.document.bounds.width} ${store.document.bounds.height}`);for(const p of pack().parts){const path=element('path',{d:p.d,fill:p.fill,stroke:p.stroke||'none','stroke-width':p.strokeWidth||0,'stroke-linecap':'round','stroke-linejoin':'round',transform:matrixText(multiply(world[p.joint],parseTransform(p.transform))),'data-part':p.id});svg.append(path);if(mode==='art'&&p.id===selected){const outline=path.cloneNode();outline.removeAttribute('data-part');outline.setAttribute('fill','none');outline.setAttribute('stroke','#8060bf');outline.setAttribute('stroke-width','2');outline.setAttribute('vector-effect','non-scaling-stroke');outline.setAttribute('stroke-dasharray','5 4');outline.setAttribute('pointer-events','none');svg.append(outline);}}
 if(mode==='rig')for(const j of pack().joints){const m=world[j.id];if(j.parent){const p=world[j.parent];svg.append(element('line',{x1:p[4],y1:p[5],x2:m[4],y2:m[5],stroke:'#7760a1','stroke-width':2,'pointer-events':'none'}));}svg.append(element('circle',{cx:m[4],cy:m[5],r:7,fill:j.id===joint?'#8060bf':'#ffffff',stroke:'#8060bf','stroke-width':2,'data-joint':j.id}));}}
function input(label,id,value,type='text'){const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement('input');el.type=type;el.id=id;el.value=value;if(type==='number')el.step='any';wrap.append(el);return wrap;}
function select(label,id,items,value){const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement('select');el.id=id;for(const [v,t] of items){const o=new Option(t,v);el.add(o);}el.value=value;wrap.append(el);return wrap;}
function button(id,text,fn){const b=document.createElement('button');b.id=id;b.textContent=text;b.onclick=fn;return b;}
function panel(){const panel=$('panel');panel.replaceChildren();$('art-tab').classList.toggle('active',mode==='art');$('rig-tab').classList.toggle('active',mode==='rig');const p=pack().parts.find(p=>p.id===selected);
 if(mode==='art'){panel.append(select('Artwork','parts',pack().parts.map(p=>[p.id,p.id]),selected));$('parts').onchange=e=>{selected=e.target.value;render();};if(!p){panel.append(document.createTextNode('Add a shape above the canvas.'));return;}
 panel.append(input('Fill · hex or none','fill',p.fill),input('Stroke · hex or none','stroke',p.stroke||'none'),input('Stroke width','stroke-width',p.strokeWidth||0,'number'),select('Attached joint','attached',pack().joints.map(j=>[j.id,j.id]),p.joint));
 for(const [id,property] of [['fill','fill'],['stroke','stroke'],['stroke-width','strokeWidth']])$(id).onchange=e=>{const n=structuredClone(pack());n.parts.find(q=>q.id===selected)[property]=property==='strokeWidth'?Number(e.target.value):e.target.value;commit(n);};$('attached').onchange=e=>{try{commit(assignArtwork(pack(),p.id,e.target.value),'Artwork attached. Its position is preserved.');}catch(err){status(err.message);}};
 const label=document.createElement('label');label.textContent='Path points';const area=document.createElement('textarea');area.id='path';area.value=p.d;area.rows=4;label.append(area);panel.append(label,button('apply-path','Apply path',()=>{let value;try{value=validatePath($('path').value);}catch(e){status(e.message);return;}const n=structuredClone(pack());n.parts.find(q=>q.id===selected).d=value;commit(n);}));
 panel.append(input('Local transform','transform',p.transform||''),button('apply-transform','Apply transform',()=>{try{const transform=matrixText(parseTransform($('transform').value)),n=structuredClone(pack());n.parts.find(q=>q.id===selected).transform=transform;commit(n);}catch(e){status(e.message);}}));
 panel.append(button('raise','Bring forward',()=>order(1)),button('lower','Send backward',()=>order(-1)),button('remove','Delete artwork',()=>{const n=structuredClone(pack());n.parts=n.parts.filter(q=>q.id!==selected);commit(n);}));
 }else{panel.append(select('Joint','joints',pack().joints.map(j=>[j.id,j.id]),joint));$('joints').onchange=e=>{joint=e.target.value;render();};const j=pack().joints.find(j=>j.id===joint);panel.append(select('Parent','parent',[['','No parent'],...pack().joints.filter(j=>j.id!==joint).map(j=>[j.id,j.id])],j.parent||''),input('Pivot X','pivot-x',j.x,'number'),input('Pivot Y','pivot-y',j.y,'number'),button('pivot','Set pivot',()=>{try{commit(movePivot(pack(),joint,Number($('pivot-x').value),Number($('pivot-y').value)),'Pivot moved. Artwork and child joints stay in place.');}catch(e){status(e.message);}}));$('parent').onchange=e=>{try{commit(reparentJoint(pack(),joint,e.target.value||null),'Parent changed without moving the artwork.');}catch(err){status(err.message);panel();}};
 panel.append(input('Rest rotation','rotation',j.rotation,'number'),input('Minimum rotation','min',j.min,'number'),input('Maximum rotation','max',j.max,'number'),input('Bone length','length',j.length,'number'),button('apply-joint','Apply joint settings',()=>{const n=structuredClone(pack()),next=n.joints.find(j=>j.id===joint);for(const field of ['rotation','min','max','length'])next[field]=Number($(field).value);commit(n);}));const note=document.createElement('p');note.className='note';note.textContent='Pivots and parents preserve the rest drawing. Rotation poses the attached artwork. Set keys in Animate.';panel.append(note);}}
function order(delta){const n=structuredClone(pack()),i=n.parts.findIndex(p=>p.id===selected),to=Math.max(0,Math.min(n.parts.length-1,i+delta));n.parts.splice(to,0,n.parts.splice(i,1)[0]);commit(n);}
function id(prefix,items){let n=1;while(items.some(p=>p.id===prefix+n))n++;return prefix+n;}
for(const b of document.querySelectorAll('[data-shape]'))b.onclick=()=>{const n=structuredClone(pack());selected=id('shape-',n.parts);n.parts.push({id:selected,joint:pack().joints[0].id,d:shapePath(b.dataset.shape,store.document.bounds.width/2-60,store.document.bounds.height/2-60),fill:'#b7a0de',stroke:'#453e50',strokeWidth:3});mode='art';commit(n);};
$('add-joint').onclick=()=>{const n=structuredClone(pack());const parent=joint;joint=id('joint-',n.joints);n.joints.push({id:joint,parent,x:60,y:60,rotation:0,min:-90,max:90,length:40});mode='rig';commit(n);};
$('art-tab').onclick=()=>{mode='art';render();};$('rig-tab').onclick=()=>{mode='rig';render();};
$('undo').onclick=()=>{store.undo();persist();render();};$('redo').onclick=()=>{store.redo();persist();render();};
$('new').onclick=()=>{store=new DocumentStore(createDrawing());selected=null;joint='root';persist();render();status('New drawing.');};
$('import').onclick=()=>$('svg-file').click();$('open').onclick=()=>$('json-file').click();
for(const [id,parse] of [['svg-file',s=>importSVG(s)],['json-file',JSON.parse]])$(id).onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>(id==='svg-file'?1000000:5000000))throw Error(id==='svg-file'?'Choose an SVG smaller than 1 MB.':'Choose a project smaller than 5 MB.');load(parse(await file.text()));status('Imported. SVG supports paths, basic shapes, groups, hex colors and numeric transforms.');}catch(err){status(err.message);}e.target.value='';};
$('save').onclick=()=>{const blob=new Blob([JSON.stringify(store.document,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='posecraft-drawing.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('studio').onclick=()=>{try{localStorage.setItem('posecraft.studio-transfer.v1',JSON.stringify(store.document));location.href='./?from=draw';}catch{status('Could not transfer. Save JSON and open it in Character Studio.');}};
function point(e){const p=new DOMPoint(e.clientX,e.clientY).matrixTransform($('art').getScreenCTM().inverse());return {x:p.x,y:p.y};}
$('art').onpointerdown=e=>{const pid=e.target.dataset.part,jid=e.target.dataset.joint;if(mode==='art'&&pid)selected=pid;else if(mode==='rig'&&jid)joint=jid;else return;drag={start:point(e),pack:structuredClone(pack()),pid:mode==='art'?selected:null,jid:mode==='rig'?joint:null};$('art').setPointerCapture(e.pointerId);render();};
$('art').onpointermove=e=>{if(!drag)return;const p=point(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y,n=structuredClone(drag.pack),world=jointMatrices(n);try{if(drag.pid){const part=n.parts.find(p=>p.id===drag.pid),m=world[part.joint],det=m[0]*m[3]-m[1]*m[2];part.transform=matrixText(multiply([1,0,0,1,(m[3]*dx-m[2]*dy)/det,(-m[1]*dx+m[0]*dy)/det],parseTransform(part.transform)));drag.preview=n;}else {const j=n.joints.find(j=>j.id===drag.jid),m=j.parent?world[j.parent]:[1,0,0,1,0,0],det=m[0]*m[3]-m[1]*m[2];drag.preview=movePivot(n,j.id,j.x+(m[3]*dx-m[2]*dy)/det,j.y+(-m[1]*dx+m[0]*dy)/det);}const original=store.document.packs.drawing;store.document.packs.drawing=drag.preview;draw();store.document.packs.drawing=original;}catch(err){status(err.message);}};
$('art').onpointerup=()=>{if(drag?.preview)commit(drag.preview);drag=null;render();};$('art').onpointercancel=()=>{drag=null;render();};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&!['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName)){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}});render();
