import './map-editor.css';
import {assertMap, projectMap} from '../src/map.js';
import {mountMap} from '../src/map-browser.js';
import {fenceCollisionParts} from '../src/map-fence.js';
import {createWoodlandMap, woodlandArt, upgradeWoodlandArt} from '../examples/woodland-map.js';
import {createTownMap} from '../examples/town-map.js';

export const mapEditorDraftKey='posecraft-map-editor-draft-v1';
const clone=value=>structuredClone(value);
const escape=value=>String(value).replace(/[&<>"']/g,character=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[character]));
const terrainNames=['Grass','Road','Water','Sand'];
const terrainSymbols=['grass','road','water','sand'];
const fallbackCatalog={editorImages:{},terrainBrushes:terrainNames.map((label,terrain)=>({id:terrainSymbols[terrain],label,terrain})),propBrushes:[
  {id:'branch',label:'Fallen branch',prop:{kind:'decoration',art:'editor-branches',width:1,height:1,collision:{shape:'rect',x:.08,y:.4,width:.84,height:.18},traversal:{activation:'auto',kind:'vault',height:.28,style:'branch'}}},
  {id:'fence',label:'Low fence',prop:{kind:'decoration',art:'editor-fence',width:3,height:1,collision:{shape:'rect',x:0,y:.42,width:3,height:.16},traversal:{activation:'click',kind:'vault',height:.55,endpoints:[{x:1.5,y:-.45},{x:1.5,y:1.45}]}}},
  {id:'ridge',label:'Rocky ridge',prop:{kind:'decoration',art:'editor-ridge',width:3,height:3,collision:{shape:'rect',x:0,y:.96,width:3,height:.22},traversal:{activation:'click',kind:'climb',height:.4,endpoints:[{x:1.5,y:2.85},{x:1.5,y:.15}]}}},
  {id:'bush',label:'Bush',prop:{kind:'decoration',art:'editor-bush',width:1,height:1,collision:{shape:'circle',x:.5,y:.5,radius:.34}}},
  {id:'tombstone',label:'Tombstone',prop:{kind:'decoration',art:'editor-tombstone',width:1,height:1,collision:{shape:'rect',x:.25,y:.26,width:.5,height:.48}}},
  {id:'shipwreck',label:'Wreckage',prop:{kind:'decoration',art:'editor-shipwreck',width:2,height:2,collision:{shape:'compound',parts:[{shape:'rect',x:.05,y:.15,width:.62,height:.42},{shape:'rect',x:1.3,y:1.05,width:.55,height:.48}]}}}
]};
const $=(root,selector)=>root.querySelector(selector);
const clamp=(value,low,high)=>Math.max(low,Math.min(high,value));
const iconAliases={map:'palette',format_paint:'gesture',add_location:'edit',near_me:'edit',directions_walk:'gesture',block:'code',my_location:'restart_alt'};
const icon=name=>name==='grain'?'<svg width="19" height="19" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><circle cx="5" cy="6" r="2"/><circle cx="17" cy="4" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="5" cy="19" r="2"/><circle cx="20" cy="18" r="2"/></svg>':name==='remove'?'<span class="map-editor-symbol" aria-hidden="true">−</span>':name==='close'?'<span class="map-editor-symbol" aria-hidden="true">×</span>':name==='upload'?'<span class="material-symbols-outlined map-editor-icon-flip" aria-hidden="true">download</span>':`<span class="material-symbols-outlined" aria-hidden="true">${iconAliases[name]||name}</span>`;
const inside=(map,p)=>p.x>=0&&p.y>=0&&p.x<map.width&&p.y<map.height;
const gridPoint=p=>({x:Math.floor(p.x),y:Math.floor(p.y)});
const shapeParts=collision=>collision?.shape==='compound'?collision.parts:collision&&collision.shape!=='none'?[collision]:[];
const labelCollision=collision=>!collision?'full footprint':collision.shape==='none'?'walkable':collision.shape==='compound'?`${collision.parts.length} shapes`:collision.shape;
const defaultMap=()=>{const map=createWoodlandMap({seed:20260919,width:40,height:40});map.name='Untitled clearing';map.art=clone(woodlandArt);return map;};
function normalizeMap(input,catalog){
  const map=upgradeWoodlandArt(clone(input));map.groundPaint??={};map.art??={images:{}};map.art.images={...clone(woodlandArt.images),...catalog.editorImages,...map.art.images};map.art.terrain??=clone(woodlandArt.terrain);map.navigation??={mode:'continuous',radius:.12};
  if(!map.actors?.length)throw Error('Map editor needs one player actor. Add an actor before loading this map.');
  return map;
}
function validMap(map){try{assertMap(map);return null;}catch(error){return error.message;}}
function tileKey(map,x,y){return String(y*map.width+x);}
function propAt(map,p){const x=Math.floor(p.x),y=Math.floor(p.y);return map.props.findLast(prop=>x>=prop.x&&y>=prop.y&&x<prop.x+prop.width&&y<prop.y+prop.height);}
function safeId(map,prefix){let id=`${prefix}-${crypto.randomUUID?.().slice(0,8)||Math.random().toString(36).slice(2,10)}`;while(map.props.some(prop=>prop.id===id))id+='x';return id;}
function saveDraft(map){const error=validMap(map);if(error)throw Error(error);localStorage.setItem(mapEditorDraftKey,JSON.stringify(map));}
function loadDraft(){const raw=localStorage.getItem(mapEditorDraftKey);if(!raw)return null;try{const map=JSON.parse(raw);assertMap(map);return map;}catch{return null;}}
function collisionForParts(parts){if(!parts.length)return {shape:'none'};return parts.length===1?parts[0]:{shape:'compound',parts};}
function propCollision(prop){if(prop.fence&&prop.collision===undefined)return{shape:'compound',parts:fenceCollisionParts(prop).map(part=>({...part,x:part.x-prop.x,y:part.y-prop.y}))};return prop.collision??(prop.kind==='decoration'?{shape:'none'}:{shape:'rect',x:0,y:0,width:prop.width,height:prop.height});}
function defaultTraversal(prop){return {activation:'click',kind:'vault',height:.5,endpoints:[{x:prop.width/2,y:-.4},{x:prop.width/2,y:prop.height+.4}]};}
function traversalEditor(prop){const traversal=prop.traversal;if(!traversal)return `<div class="section-title traversal-title">Traversal <button data-action="add-traversal" title="Add traversal">${icon('add')}</button></div><p class="small-note">Add a click traversal with relative entry and exit endpoints.</p>`;
 const activation=traversal.activation??'auto',click=activation==='click',endpoints=traversal.endpoints||defaultTraversal(prop).endpoints;
 return `<div class="section-title traversal-title">Traversal <button data-action="remove-traversal" title="Remove traversal">${icon('close')}</button></div><div class="two"><label class="field">Activation <select data-traversal-field="activation"><option value="auto" ${activation==='auto'?'selected':''}>Automatic</option><option value="click" ${click?'selected':''}>On click</option></select></label><label class="field">Kind <select data-traversal-field="kind"><option value="vault" ${traversal.kind==='vault'?'selected':''}>Vault</option><option value="climb" ${traversal.kind==='climb'?'selected':''}>Climb</option></select></label></div><label class="field">Height <input data-traversal-field="height" type="number" min=".05" max="4" step=".05" value="${traversal.height}" /></label>${click?`<div class="endpoint-grid"><span>Relative endpoint</span><span>X</span><span>Y</span><span>Entry</span><input data-traversal-endpoint="0" data-axis="x" type="number" min="-2" max="${prop.width+2}" step=".05" value="${endpoints[0].x}" /><input data-traversal-endpoint="0" data-axis="y" type="number" min="-2" max="${prop.height+2}" step=".05" value="${endpoints[0].y}" /><span>Exit</span><input data-traversal-endpoint="1" data-axis="x" type="number" min="-2" max="${prop.width+2}" step=".05" value="${endpoints[1].x}" /><input data-traversal-endpoint="1" data-axis="y" type="number" min="-2" max="${prop.height+2}" step=".05" value="${endpoints[1].y}" /></div><p class="small-note">Endpoints are relative to the prop's upper-left corner.</p>`:'<p class="small-note">Automatic traversal has no endpoints. It starts when a route reaches this obstacle.</p>'}`;
}

const root=document.querySelector('#map-editor');
root.className='map-editor';
root.innerHTML=`
  <header class="editor-topbar">
    <div class="brand">${icon('map')} <span>Map editor</span></div>
    <div class="top-actions">
      <button class="icon mobile" data-panel="palette" title="Tools">${icon('palette')}</button>
      <button class="icon" data-action="undo" title="Undo">${icon('undo')}</button>
      <button class="icon" data-action="redo" title="Redo">${icon('redo')}</button>
      <button class="label-button desktop-only" data-action="save">${icon('download')} <span>Save JSON</span></button>
      <button class="label-button desktop-only" data-action="load">${icon('upload')} <span>Load JSON</span></button>
    </div>
    <div class="top-actions end">
      <button class="label-button" data-action="play">${icon('play_arrow')} <span>Play draft</span></button>
      <button class="icon mobile" data-panel="inspector" title="Inspector">${icon('tune')}</button>
    </div>
    <input type="file" class="hidden" data-input="load" accept="application/json,.json" />
  </header>
  <div class="editor-body">
    <aside class="panel palette">
      <section class="section"><h2 class="section-title">Tools</h2><div class="tool-grid" data-tools></div></section>
      <section class="section"><h2 class="section-title">Terrain</h2><div class="asset-grid" data-terrain></div><label class="field">Brush radius <input data-input="radius" type="range" min="1" max="6" value="2" /><span data-radius>2 tiles</span></label></section>
      <section class="section"><h2 class="section-title">Plateau</h2><label class="field">Height <select data-input="terrace-height"><option value="3">Low · 3</option><option value="8">High · 8</option><option value="15">Peak · 15</option><option value="erase">Erase</option></select></label><p class="small-note">Choose Plateau, then drag a rectangle up to 16 × 16 tiles.</p></section>
      <section class="section"><h2 class="section-title">Scatter and place</h2><div class="asset-grid" data-props></div><label class="field">Density <input data-input="density" type="range" min="1" max="5" value="2" /><span data-density>one per tile</span></label><p class="small-note">Scatter paints a loose run of props. Place adds one per click.</p></section>
    </aside>
    <section class="stage">
      <div class="map-host"></div><div class="map-overlay" data-mode="terrain"></div><div class="preview"></div><svg class="collision-overlay" width="100%" height="100%" aria-hidden="true"></svg>
      <div class="map-status" aria-live="polite">Loading map</div>
      <div class="stage-controls"><button class="icon" data-action="zoom-out" title="Zoom out">${icon('remove')}</button><button class="icon" data-action="home" title="Center hero">${icon('my_location')}</button><button class="icon" data-action="zoom-in" title="Zoom in">${icon('add')}</button></div>
    </section>
    <aside class="panel inspector">
      <section class="section"><h2 class="section-title">Map</h2><label class="field">Name <input data-input="name" /></label><div class="two"><label class="field">Width <input data-input="width" type="number" min="8" max="512" /></label><label class="field">Height <input data-input="height" type="number" min="8" max="512" /></label></div><button data-action="resize">Resize map</button><p class="small-note">Resizing keeps the upper-left part of the map.</p></section>
      <section class="section"><h2 class="section-title">Selection</h2><div data-selection class="empty">Select a prop to edit its footprint or collision shapes.</div></section>
      <section class="section"><label class="toggle">Show collision shapes <input data-input="show-collisions" type="checkbox" /></label><p class="small-note">A selected decoration can be made walkable in its collision controls.</p></section>
    </aside>
  </div>`;

let catalog=clone(fallbackCatalog);
let map;try{map=normalizeMap(new URLSearchParams(location.search).get('template')==='town'?createTownMap():loadDraft()||defaultMap(),catalog);}catch{map=normalizeMap(defaultMap(),catalog);}
let view=null,selectedId=null,mode='terrain',activeBrush='grass',brushRadius=2,density=2,terraceHeight=3,showCollisions=false,undoStack=[],redoStack=[],stroke=null,lastPaint='',camera={zoom:2.1},rebuildQueued=false,renderGeneration=0;
const host=$(root,'.map-host'),overlay=$(root,'.map-overlay'),preview=$(root,'.preview'),collisionLayer=$(root,'.collision-overlay'),status=$(root,'.map-status');
const terrainButtons=$(root,'[data-terrain]'),propButtons=$(root,'[data-props]'),toolButtons=$(root,'[data-tools]');

function report(message,bad=false){status.textContent=message;status.classList.toggle('danger',bad);}
function commit(next,reason){const error=validMap(next);if(error){report(error,true);return false;}undoStack.push(map);if(undoStack.length>40)undoStack.shift();redoStack=[];map=next;saveDraft(map);renderInspector();renderMap(reason);return true;}
function updateMap(mutator,reason){const next=clone(map);mutator(next);return commit(next,reason);}
function renderTools(){const tools=[['terrain','format_paint','Paint terrain'],['terrace','layers','Plateau'],['scatter','grain','Scatter'],['place','add_location','Place prop'],['select','near_me','Select / delete'],['pan','pan_tool','Pan']];toolButtons.innerHTML=tools.map(([id,glyph,label])=>`<button class="tool ${mode===id?'active':''}" data-tool="${id}" title="${label}">${icon(glyph)} ${label}</button>`).join('');}
function thumb(image,label){return image?.src?`<img src="${escape(image.src)}" alt="" />`:`<i>${escape(label.slice(0,2))}</i>`;}
function fenceThumb(fence){const points=fence.nodes.map(node=>[8+node.x*32,8+node.y*32]);return `<svg viewBox="0 0 48 48" aria-hidden="true">${fence.links.map(([a,b])=>`<line x1="${points[a][0]}" y1="${points[a][1]}" x2="${points[b][0]}" y2="${points[b][1]}" stroke="#745a3f" stroke-width="5" stroke-linecap="round"/>`).join('')}${points.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3.5" fill="#a58b64" stroke="#49372b"/>`).join('')}</svg>`;}
function renderBrushes(){terrainButtons.innerHTML=catalog.terrainBrushes.map(brush=>`<button class="asset ${activeBrush===brush.id?'active':''}" data-terrain-brush="${escape(brush.id)}">${thumb(map.art?.images?.[brush.image],brush.label)}<span>${escape(brush.label)}</span></button>`).join('');propButtons.innerHTML=catalog.propBrushes.map(brush=>`<button class="asset ${activeBrush===brush.id?'active':''}" data-prop-brush="${escape(brush.id)}">${brush.prop?.fence?fenceThumb(brush.prop.fence):thumb(map.art?.images?.[brush.prop?.art],brush.label)}<span>${escape(brush.label)}</span></button>`).join('');}
function setMode(next,brush){mode=next;if(brush)activeBrush=brush;overlay.dataset.mode=mode;renderTools();renderBrushes();renderPreview();root.classList.remove('show-palette','show-inspector');}
function selected(){return map.props.find(prop=>prop.id===selectedId)||null;}
function renderSelection(){const target=$(root,'[data-selection]'),prop=selected();if(!prop){target.className='empty';target.textContent='Select a prop to edit its footprint or collision shapes.';return;}
 if(prop.fence){const straight=prop.fence.nodes.length===2&&prop.fence.links.length===1;target.className='';target.innerHTML=`<div class="selected-readout"><strong>${escape(prop.id)}</strong><br>connected fence · ${prop.fence.nodes.length} posts · ${prop.fence.links.length} rails<br>collision follows rail geometry</div><div class="two"><label class="field">X <input data-prop-field="x" type="number" min="0" value="${prop.x}" /></label><label class="field">Y <input data-prop-field="y" type="number" min="0" value="${prop.y}" /></label></div><p class="small-note">Fence shape, artwork, and collision stay linked. Choose another fence piece to change its connections.</p>${straight?traversalEditor(prop):'<div class="section-title">Traversal</div><p class="small-note">Corners and junctions cannot be vaulted. Use a straight fence piece for a precise crossing.</p>'}<button data-action="delete-prop" class="danger">${icon('delete')} Delete prop</button>`;return;}
 const collision=propCollision(prop),parts=shapeParts(collision);target.className='';target.innerHTML=`<div class="selected-readout"><strong>${escape(prop.id)}</strong><br>${escape(prop.kind)} · ${prop.width} × ${prop.height} cells<br>${escape(labelCollision(collision))}</div><div class="two"><label class="field">X <input data-prop-field="x" type="number" min="0" value="${prop.x}" /></label><label class="field">Y <input data-prop-field="y" type="number" min="0" value="${prop.y}" /></label></div><div class="two"><label class="field">Width <input data-prop-field="width" type="number" min="1" max="16" value="${prop.width}" /></label><label class="field">Height <input data-prop-field="height" type="number" min="1" max="16" value="${prop.height}" /></label></div><label class="field">Image <select data-prop-field="art"><option value="">Seeded/default art</option>${Object.keys(map.art?.images||{}).map(id=>`<option ${prop.art===id?'selected':''} value="${escape(id)}">${escape(id)}</option>`).join('')}</select></label><div class="section-title">Collision <button data-action="add-shape" title="Add shape">${icon('add')}</button></div><div class="shape-list">${parts.map((shape,index)=>shapeRow(shape,index)).join('')}</div><button data-action="walkable">${icon(collision.shape==='none'?'block':'directions_walk')} ${collision.shape==='none'?'Make solid footprint':'Make decoration walkable'}</button>${occlusionEditor(prop)}${traversalEditor(prop)}<button data-action="delete-prop" class="danger">${icon('delete')} Delete prop</button>`;
}
function shapeRow(shape,index){if(shape.shape==='circle')return `<div class="shape-row" data-shape-index="${index}"><select data-shape="shape"><option value="circle" selected>Circle</option><option value="rect">Rect</option></select><input data-shape="x" type="number" step=".05" value="${shape.x??.5}" title="Local X"/><input data-shape="y" type="number" step=".05" value="${shape.y??.5}" title="Local Y"/><input data-shape="radius" type="number" step=".05" min=".05" value="${shape.radius}" title="Radius"/><button data-remove-shape="${index}" title="Remove">${icon('close')}</button></div>`;
 return `<div class="shape-row" data-shape-index="${index}"><select data-shape="shape"><option value="circle">Circle</option><option value="rect" selected>Rect</option></select><input data-shape="x" type="number" step=".05" value="${shape.x}" title="Local X"/><input data-shape="y" type="number" step=".05" value="${shape.y}" title="Local Y"/><input data-shape="width" type="number" step=".05" min=".05" value="${shape.width}" title="Width"/><input data-shape="height" type="number" step=".05" min=".05" value="${shape.height}" title="Height"/><button data-remove-shape="${index}" title="Remove">${icon('close')}</button></div>`;
}
function renderInspector(){$(root,'[data-input="name"]').value=map.name;$(root,'[data-input="width"]').value=map.width;$(root,'[data-input="height"]').value=map.height;$(root,'[data-input="show-collisions"]').checked=showCollisions;$(root,'[data-radius]').textContent=`${brushRadius} tile${brushRadius===1?'':'s'}`;$(root,'[data-density]').textContent=density===1?'one per tile':`one per ${density} tiles`;renderSelection();renderCollisionOverlay();}
async function renderMap(reason='Updated map'){
 if(rebuildQueued)return;rebuildQueued=true;requestAnimationFrame(async()=>{rebuildQueued=false;const generation=++renderGeneration,rect=host.getBoundingClientRect(),previousCenter=view?.screenToMap(rect.width/2,rect.height/2),previousZoom=view?.snapshot().camera.zoom;view?.dispose();host.replaceChildren();const mounted=mountMap(host,map,{autoplay:false,execution:'main',renderer:new URLSearchParams(location.search).get('renderer')==='webgl2'?'webgl2':'canvas2d',onError(error){if(generation===renderGeneration)report(error.message,true);}});view=mounted;try{await mounted.ready;if(generation!==renderGeneration||view!==mounted)return;if(previousCenter&&inside(map,previousCenter)){mounted.zoomTo(previousZoom);mounted.panTo(previousCenter.x,previousCenter.y);}else{mounted.zoomTo(camera.zoom);mounted.panTo(map.actors[0].x,map.actors[0].y);}report(reason);renderCollisionOverlay();}catch(error){if(generation===renderGeneration&&view===mounted)report(error.message,true);}});
}
function renderCollisionOverlay(){collisionLayer.replaceChildren();if(!showCollisions||!view)return;const prop=selected();if(!prop)return;for(const shape of shapeParts(propCollision(prop))){const el=document.createElementNS('http://www.w3.org/2000/svg','polygon');el.setAttribute('fill','#f9df5350');el.setAttribute('stroke','#e2bb35');el.setAttribute('stroke-width','2');const points=shape.shape==='circle'?Array.from({length:20},(_,index)=>{const angle=index/20*Math.PI*2,point=view.mapToScreen({x:prop.x+(shape.x??prop.width/2)+Math.cos(angle)*shape.radius,y:prop.y+(shape.y??prop.height/2)+Math.sin(angle)*shape.radius});return `${point.x},${point.y}`;}).join(' '):[[shape.x,shape.y],[shape.x+shape.width,shape.y],[shape.x+shape.width,shape.y+shape.height],[shape.x,shape.y+shape.height]].map(([x,y])=>{const point=view.mapToScreen({x:prop.x+x,y:prop.y+y});return `${point.x},${point.y}`;}).join(' ');el.setAttribute('points',points);collisionLayer.append(el);}}
function renderPreview(point){if(!point||!view||mode==='select'||mode==='pan'||mode==='terrace'){preview.hidden=true;return;}const screen=view.mapToScreen({x:Math.floor(point.x)+.5,y:Math.floor(point.y)+.5}),edge=view.mapToScreen({x:Math.floor(point.x)+brushRadius+.5,y:Math.floor(point.y)+.5});preview.hidden=false;preview.style.left=`${screen.x}px`;preview.style.top=`${screen.y}px`;preview.style.width=preview.style.height=`${Math.max(12,Math.abs(edge.x-screen.x)*2)}px`;}
function terraceRect(anchor,point){const end=gridPoint(point),endX=clamp(end.x,Math.max(0,anchor.x-15),Math.min(map.width-1,anchor.x+15)),endY=clamp(end.y,Math.max(0,anchor.y-15),Math.min(map.height-1,anchor.y+15)),x=Math.min(anchor.x,endX),y=Math.min(anchor.y,endY);return{x,y,width:Math.abs(endX-anchor.x)+1,height:Math.abs(endY-anchor.y)+1};}
function renderTerracePreview(rect){renderCollisionOverlay();if(!rect||!view)return;const el=document.createElementNS('http://www.w3.org/2000/svg','polygon'),points=[[rect.x,rect.y],[rect.x+rect.width,rect.y],[rect.x+rect.width,rect.y+rect.height],[rect.x,rect.y+rect.height]].map(([x,y])=>{const point=view.mapToScreen({x,y});return `${point.x},${point.y}`;}).join(' ');el.dataset.terracePreview='';el.setAttribute('points',points);el.setAttribute('fill',terraceHeight==='erase'?'#cc585540':'#8ec58f55');el.setAttribute('stroke',terraceHeight==='erase'?'#b13c3c':'#4f8d5b');el.setAttribute('stroke-width','2');collisionLayer.append(el);}
function terraceId(){const used=new Set([...(map.props??[]),...(map.actors??[]),...(map.birds??[]),...(map.terraces??[])].map(item=>item.id));let id=`terrace-${crypto.randomUUID?.().slice(0,8)||Math.random().toString(36).slice(2,10)}`;while(used.has(id))id+='x';return id;}
const overlaps=(a,b)=>a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y;
function paintTerrain(point){const brush=catalog.terrainBrushes.find(entry=>entry.id===activeBrush);if(!brush)return;const center=gridPoint(point),baseImage=map.art?.terrain?.[terrainSymbols[brush.terrain]],paintImage=brush.image&&brush.image!==baseImage?brush.image:null;for(let y=center.y-brushRadius+1;y<center.y+brushRadius;y++)for(let x=center.x-brushRadius+1;x<center.x+brushRadius;x++){if(!inside(map,{x,y})||Math.hypot(x-center.x,y-center.y)>=brushRadius)continue;const hero=map.actors[0];if(brush.terrain===2&&Math.floor(hero.x)===x&&Math.floor(hero.y)===y)continue;const key=tileKey(map,x,y);if(map.terrain[y*map.width+x]===brush.terrain&&(paintImage?map.groundPaint?.[key]===paintImage:!map.groundPaint?.[key]))continue;map.terrain[y*map.width+x]=brush.terrain;if(paintImage)map.groundPaint[key]=paintImage;else delete map.groundPaint[key];}}
function placeProp(point,scatter=false){const brush=catalog.propBrushes.find(entry=>entry.id===activeBrush);if(!brush)return;const grid=gridPoint(point),key=`${grid.x},${grid.y}`;if(lastPaint===key||!inside(map,grid)||propAt(map,grid))return;lastPaint=key;if(scatter&&density>1&&((grid.x*17+grid.y*31+map.seed)%density))return;const raw=clone(brush.prop||{}),width=raw.width??1,height=raw.height??1;if(grid.x+width>map.width||grid.y+height>map.height)return;const prop={...raw,id:safeId(map,brush.id),x:grid.x,y:grid.y,width,height};if(raw.traversal?.kind==='climb'){const previous=map.elevations;if(!map.elevations)map.elevations=Array((map.width+1)*(map.height+1)).fill(0);if(!catalog.shapeRidgeTerrain?.(map,prop)){map.elevations=previous;report('Ridge needs clear, level terrain with room for its 0.4 rise.',true);return;}}map.props.push(prop);}
function scatterProps(point){const center=gridPoint(point);for(let y=center.y-brushRadius+1;y<center.y+brushRadius;y++)for(let x=center.x-brushRadius+1;x<center.x+brushRadius;x++)if(Math.hypot(x-center.x,y-center.y)<brushRadius)placeProp({x:x+.5,y:y+.5},true);}
function startStroke(event){if(event.button!==0)return;event.preventDefault();overlay.setPointerCapture(event.pointerId);const point=view?.screenToMap(event.offsetX,event.offsetY);if(!point)return;if(mode==='pan'){const rect=host.getBoundingClientRect();stroke={pointer:event.pointerId,pan:{x:event.clientX,y:event.clientY},camera:view.screenToMap(rect.width/2,rect.height/2)};overlay.classList.add('panning');return;}if(mode==='select'){const hit=propAt(map,point);selectedId=hit?.id||null;renderInspector();return;}if(mode==='terrace'){const anchor=gridPoint(point);if(!inside(map,anchor))return;stroke={pointer:event.pointerId,before:clone(map),changed:false,terraceAnchor:anchor,terraceRect:terraceRect(anchor,point)};renderTerracePreview(stroke.terraceRect);return;}stroke={pointer:event.pointerId,before:clone(map),changed:false};lastPaint='';applyStroke(point);}
function applyStroke(point){if(!stroke||!view)return;if(mode==='terrace'&&stroke.terraceAnchor){stroke.terraceRect=terraceRect(stroke.terraceAnchor,point);renderTerracePreview(stroke.terraceRect);return;}renderPreview(point);const before=JSON.stringify(map),previous=stroke.lastPoint||point,steps=Math.max(1,Math.ceil(Math.hypot(point.x-previous.x,point.y-previous.y)*2));for(let index=1;index<=steps;index++){const progress=index/steps,current={x:previous.x+(point.x-previous.x)*progress,y:previous.y+(point.y-previous.y)*progress};if(mode==='terrain')paintTerrain(current);if(mode==='place')placeProp(current);if(mode==='scatter')scatterProps(current);}stroke.lastPoint=point;if(before!==JSON.stringify(map)){stroke.changed=true;renderCollisionOverlay();}}
function moveStroke(event){const point=view?.screenToMap(event.offsetX,event.offsetY);if(!point)return;if(mode==='pan'&&stroke?.pan){const dx=event.clientX-stroke.pan.x,dy=event.clientY-stroke.pan.y;const origin=view.screenToMap(0,0),target=view.screenToMap(-dx,-dy);view.panTo(stroke.camera.x+target.x-origin.x,stroke.camera.y+target.y-origin.y);renderCollisionOverlay();return;}applyStroke(point);}
function endStroke(event){if(!stroke||stroke.pointer!==event.pointerId)return;try{overlay.releasePointerCapture(event.pointerId);}catch{}overlay.classList.remove('panning');if(stroke.terraceRect){const rect=stroke.terraceRect,before=stroke.before,next=clone(before),terraces=next.terraces??[];if(terraceHeight==='erase')next.terraces=terraces.filter(terrace=>!overlaps(terrace,rect));else if(terraces.length>=64){report('A map can contain up to 64 plateaus.',true);renderCollisionOverlay();}else next.terraces=[...terraces,{id:terraceId(),...rect,heightOffset:Number(terraceHeight)}];if(JSON.stringify(next)!==JSON.stringify(before)){map=before;commit(next,terraceHeight==='erase'?'Plateau erased':'Plateau placed');}}else if(stroke.changed){const next=map;map=stroke.before;if(!commit(next,'Stroke saved')){map=stroke.before;renderInspector();renderMap('Stroke rejected');}}stroke=null;lastPaint='';renderCollisionOverlay();}
function updateSelected(mutator,reason='Prop updated'){const id=selectedId;if(!id)return;updateMap(next=>{const prop=next.props.find(entry=>entry.id===id);if(prop)mutator(prop,next);},reason);}
function changeShape(element){const index=Number(element.closest('[data-shape-index]').dataset.shapeIndex),field=element.dataset.shape,value=field==='shape'?element.value:Number(element.value);updateSelected(prop=>{const parts=shapeParts(propCollision(prop));const previous=parts[index];if(field==='shape')parts[index]=value==='circle'?{shape:'circle',x:previous.x??.5,y:previous.y??.5,radius:.25}:{shape:'rect',x:previous.x??.15,y:previous.y??.15,width:.5,height:.5};else parts[index]={...previous,[field]:value};prop.collision=collisionForParts(parts);},'Collision updated');}
function changeTraversal(element){const field=element.dataset.traversalField,value=field==='height'?Number(element.value):element.value;updateSelected(prop=>{const traversal={...prop.traversal};traversal[field]=value;if(field==='activation'){if(value==='click')traversal.endpoints=traversal.endpoints||defaultTraversal(prop).endpoints;else delete traversal.endpoints;}prop.traversal=traversal;},'Traversal updated');}
function changeTraversalEndpoint(element){const index=Number(element.dataset.traversalEndpoint),axis=element.dataset.axis,value=Number(element.value);updateSelected(prop=>{const traversal={...prop.traversal,endpoints:(prop.traversal.endpoints||defaultTraversal(prop).endpoints).map(point=>({...point}))};traversal.endpoints[index][axis]=value;prop.traversal=traversal;},'Traversal endpoint updated');}
function resizeMap(){const width=Number($(root,'[data-input="width"]').value),height=Number($(root,'[data-input="height"]').value);if(!Number.isInteger(width)||!Number.isInteger(height)||width<8||height<8||width>512||height>512){report('Use whole dimensions between 8 and 512.',true);return;}updateMap(next=>{const oldWidth=next.width,oldHeight=next.height,terrain=Array(width*height).fill(0),paint={};for(let y=0;y<Math.min(height,oldHeight);y++)for(let x=0;x<Math.min(width,oldWidth);x++){const old=y*oldWidth+x,index=y*width+x;terrain[index]=next.terrain[old];if(next.groundPaint?.[String(old)])paint[String(index)]=next.groundPaint[String(old)];}if(next.elevations){const old=next.elevations,oldStride=oldWidth+1,elevations=Array((width+1)*(height+1));for(let y=0;y<=height;y++)for(let x=0;x<=width;x++)elevations[y*(width+1)+x]=old[Math.min(oldHeight,y)*oldStride+Math.min(oldWidth,x)];next.elevations=elevations;}next.width=width;next.height=height;next.terrain=terrain;next.groundPaint=paint;next.props=next.props.filter(prop=>prop.x+prop.width<=width&&prop.y+prop.height<=height);if(next.terraces)next.terraces=next.terraces.filter(terrace=>terrace.x+terrace.width<=width&&terrace.y+terrace.height<=height);if(next.birds)next.birds=next.birds.filter(bird=>bird.home.x>=0&&bird.home.y>=0&&bird.home.x<width&&bird.home.y<height);next.actors=next.actors.map(actor=>({...actor,x:Math.min(width-.5,actor.x),y:Math.min(height-.5,actor.y)}));},'Map resized');}

root.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(button.dataset.tool){setMode(button.dataset.tool);return;}if(button.dataset.terrainBrush){setMode('terrain',button.dataset.terrainBrush);return;}if(button.dataset.propBrush){setMode('place',button.dataset.propBrush);return;}if(button.dataset.panel){root.classList.toggle(`show-${button.dataset.panel}`);return;}if(action==='undo'&&undoStack.length){redoStack.push(map);map=undoStack.pop();saveDraft(map);renderInspector();renderMap('Undid edit');}if(action==='redo'&&redoStack.length){undoStack.push(map);map=redoStack.pop();saveDraft(map);renderInspector();renderMap('Redid edit');}if(action==='zoom-in')view?.zoomTo((view.snapshot().camera.zoom||2)+.2);if(action==='zoom-out')view?.zoomTo((view.snapshot().camera.zoom||2)-.2);if(action==='home')view?.panTo(map.actors[0].x,map.actors[0].y);if(action==='resize')resizeMap();if(action==='delete-prop'){const id=selectedId;selectedId=null;updateMap(next=>next.props=next.props.filter(prop=>prop.id!==id),'Prop deleted');}if(action==='walkable')updateSelected(prop=>{prop.collision=propCollision(prop).shape==='none'?{shape:'rect',x:0,y:0,width:prop.width,height:prop.height}:{shape:'none'};},'Collision changed');if(action==='add-shape')updateSelected(prop=>{const parts=shapeParts(propCollision(prop));parts.push({shape:'rect',x:.2,y:.2,width:.4,height:.4});prop.collision=collisionForParts(parts);},'Collision shape added');if(button.dataset.removeShape!==undefined)updateSelected(prop=>{const parts=shapeParts(propCollision(prop));parts.splice(Number(button.dataset.removeShape),1);prop.collision=collisionForParts(parts);},'Collision shape removed');if(action==='add-traversal')updateSelected(prop=>{prop.traversal=defaultTraversal(prop);},'Traversal added');if(action==='remove-traversal')updateSelected(prop=>{delete prop.traversal;},'Traversal removed');if(action==='save'){try{saveDraft(map);const blob=new Blob([JSON.stringify(map,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`${map.id||'posecraft-map'}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);report('Saved map JSON');}catch(error){report(error.message,true);}}if(action==='load')$(root,'[data-input="load"]').click();if(action==='play'){try{saveDraft(map);window.open('./play.html?draft=1'+(new URLSearchParams(location.search).get('renderer')==='webgl2'?'&renderer=webgl2':''),'_blank','noopener');report('Opened draft in play mode');}catch(error){report(error.message,true);}}});
root.addEventListener('input',event=>{const input=event.target;if(input.matches('[data-input="radius"]')){brushRadius=Number(input.value);renderInspector();}if(input.matches('[data-input="density"]')){density=Number(input.value);renderInspector();}if(input.matches('[data-input="terrace-height"]'))terraceHeight=input.value==='erase'?'erase':Number(input.value);if(input.matches('[data-input="show-collisions"]')){showCollisions=input.checked;renderCollisionOverlay();}});
root.addEventListener('change',event=>{const input=event.target;if(input.matches('[data-input="name"]'))updateMap(next=>{next.name=input.value;},'Map name updated');if(input.dataset.propField){const field=input.dataset.propField,value=field==='art'?input.value:Number(input.value);updateSelected(prop=>{if(field==='art'){if(value)prop.art=value;else delete prop.art;}else prop[field]=value;},'Prop updated');}if(input.dataset.occlusionField){const field=input.dataset.occlusionField;updateSelected(prop=>{if(field==='mode'){if(input.value==='auto')delete prop.occlusion;else prop.occlusion=input.value==='ground'?{mode:'ground'}:{mode:'low-foliage',lowerBodyFraction:.5};}else prop.occlusion={mode:'low-foliage',lowerBodyFraction:Number(input.value)/100};},'Cover updated');}if(input.dataset.shape)changeShape(input);if(input.dataset.traversalField)changeTraversal(input);if(input.dataset.traversalEndpoint!==undefined)changeTraversalEndpoint(input);});
$(root,'[data-input="load"]').addEventListener('change',async event=>{const file=event.target.files?.[0];if(!file)return;try{const loaded=normalizeMap(JSON.parse(await file.text()),catalog);assertMap(loaded);undoStack.push(map);redoStack=[];map=loaded;selectedId=null;saveDraft(map);renderInspector();renderMap('Loaded map JSON');}catch(error){report(`Could not load map: ${error.message}`,true);}event.target.value='';});
overlay.addEventListener('pointerdown',startStroke);overlay.addEventListener('pointermove',moveStroke);overlay.addEventListener('pointerup',endStroke);overlay.addEventListener('pointercancel',endStroke);overlay.addEventListener('pointerleave',event=>{if(!stroke)renderPreview(null);});
overlay.addEventListener('wheel',event=>{event.preventDefault();view?.zoomTo((view.snapshot().camera.zoom||2)+(event.deltaY<0?.16:-.16));},{passive:false});

renderTools();renderBrushes();renderInspector();renderMap('Ready');
import('../examples/map-editor-catalog.js').then(module=>{catalog={...fallbackCatalog,...module,editorImages:{...fallbackCatalog.editorImages,...module.editorImages},terrainBrushes:module.terrainBrushes||fallbackCatalog.terrainBrushes,propBrushes:module.propBrushes||fallbackCatalog.propBrushes};map=normalizeMap(map,catalog);renderBrushes();renderInspector();renderMap('Editor art loaded');}).catch(()=>{});

function occlusionEditor(prop){
 const mode=prop.occlusion?.mode||'auto';
 return `<div class="section-title">Character cover</div><label class="field">Drawing <select data-occlusion-field="mode"><option value="auto" ${mode==='auto'?'selected':''}>Depth and silhouette</option><option value="low-foliage" ${mode==='low-foliage'?'selected':''}>Crop / low foliage</option><option value="ground" ${mode==='ground'?'selected':''}>Always underfoot</option></select></label>${mode==='low-foliage'?`<label class="field">Lower body covered (%) <input type="number" data-occlusion-field="fraction" min="1" max="100" step="1" value="${Math.round((prop.occlusion.lowerBodyFraction??.5)*100)}" /></label>`:''}`;
}
