import {evaluateSkinnedMesh} from '../src/skinned-mesh.js';
import {spatialKinematics} from '../src/spatial.js';
import {editMeshInfluence,bindMeshJoint,removeMeshInfluence,setMeshVertexCorrection} from '../src/mesh-editing.js';
import './mesh-tools.css';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const options=(values,selected)=>values.map(([id,label])=>`<option value="${esc(id)}" ${String(id)===String(selected)?'selected':''}>${esc(label)}</option>`).join('');
const select=(id,label,values,value)=>`<label class="field">${label}<select id="mesh-${id}">${options(values,value)}</select></label>`;
const number=(id,label,value,min=-4096,max=4096,step='any')=>`<label class="field">${label}<input id="mesh-${id}" type="number" min="${min}" max="${max}" step="${step}" value="${+Number(value??0).toFixed(6)}"></label>`;
const channels={rotation:[-180,180],yaw:[-180,180],pitch:[-90,90],bend:[0,1]};
export function createMeshTools({getDocument,getActor,getFrame,commit,notice,pause}){
 let partId,vertex=0,influence=0,correction=0,panel='weights',guides=true,host;
 const context=()=>{const doc=getDocument(),actor=getActor(),pack=doc.packs[actor?.pack],parts=pack?.parts.filter(p=>p.spatial?.mesh)||[];if(!parts.some(p=>p.id===partId)){partId=parts[0]?.id;vertex=0;influence=0;}const part=parts.find(p=>p.id===partId),mesh=part?.spatial.mesh;if(mesh){vertex=Math.min(vertex,mesh.vertices.length-1);influence=Math.min(influence,mesh.vertices[vertex].weights.length-1);correction=Math.min(correction,Math.max(0,(mesh.correctives?.length||0)-1));}return {doc,actor,pack,parts,part,mesh};};
 function save(mesh){const nextInfluence=influence,nextCorrection=correction,c=context();influence=nextInfluence;correction=nextCorrection;if(JSON.stringify(mesh)===JSON.stringify(c.mesh))return;pause();commit([{op:'set',path:['packs',c.actor.pack,'parts',c.pack.parts.indexOf(c.part),'spatial','mesh'],value:mesh},{op:'set',path:['requiredFeatures'],value:[...new Set([...(c.doc.requiredFeatures||[]),'skinned-mesh'])]}]);}
 function act(fn){try{fn();}catch(error){notice(error.message);}}
 const redraw=()=>{if(host)render(host);};
 function render(target){
  host=target;const {actor,pack,parts,part,mesh}=context();target.classList.add('mesh-panel');
  target.innerHTML='<div class="inspector-heading">Connected surface</div>';
  if(!mesh){target.insertAdjacentHTML('beforeend','<p class="note">This character has no connected surface. Open a character with a weighted mesh to edit its points and joint influence.</p><p class="note">Surface editing keeps the existing triangles. Drawing and remeshing tools are not part of this editor yet.</p>');return;}
  const weights=mesh.vertices[vertex].weights,w=weights[influence],drivers=mesh.correctives||[],driver=drivers[correction],joints=pack.joints.map(j=>[j.id,j.id]);
  target.insertAdjacentHTML('beforeend',`${select('part','Surface',parts.map(p=>[p.id,p.id]),part.id)}<div class="mesh-summary">${mesh.vertices.length} vertices · ${mesh.triangles.length} triangles</div><div class="mesh-vertex-row">${select('vertex','Vertex',mesh.vertices.map((_,i)=>[i,i+1]),vertex)}<label class="face-auto"><input id="mesh-guides" type="checkbox" ${guides?'checked':''}>Wireframe</label></div><nav class="prop-tabs"><button id="mesh-weights-tab" class="${panel==='weights'?'active':''}">Bind weights</button><button id="mesh-corrections-tab" class="${panel==='corrections'?'active':''}">Corrections</button></nav>`);
  const $=id=>target.querySelector('#mesh-'+id),bind=(id,event,fn)=>{const node=$(id);if(node)node[event]=fn;};
  bind('part','onchange',e=>{partId=e.target.value;vertex=0;influence=0;redraw();});bind('vertex','onchange',e=>{vertex=+e.target.value;influence=0;redraw();});bind('guides','onchange',e=>{guides=e.target.checked;});bind('weights-tab','onclick',()=>{panel='weights';redraw();});bind('corrections-tab','onclick',()=>{panel='corrections';redraw();});
  if(panel==='weights'){
   const available=joints.filter(([id])=>!weights.some(w=>w.joint===id));
   target.insertAdjacentHTML('beforeend',`${select('influence','Joint influence',weights.map((v,i)=>[i,`${v.joint} · ${(v.weight*100).toFixed(1)}%`]),influence)}${select('joint','Attached joint',joints.filter(([id])=>id===w.joint||!weights.some(v=>v.joint===id)),w.joint)}${number('weight','Weight',w.weight,.000001,1,'any')}<div class="two-col">${number('x','Bind X',w.x,-10000,10000)}${number('y','Bind Y',w.y,-10000,10000)}${number('z','Bind Z',w.z||0,-10000,10000)}</div><button id="mesh-apply-bind" class="text-button">Apply bind edit</button><div class="mesh-add-row">${select('add-joint','Add joint',available,available[0]?.[0])}<button id="mesh-add-influence" ${weights.length>=4||!available.length?'disabled':''} aria-label="Add joint influence">+</button><button id="mesh-remove-influence" ${weights.length===1?'disabled':''} aria-label="Remove joint influence">−</button></div><p class="note">Coordinates are local to the attached joint in its rest pose. Weight changes keep the other weights proportional. Adding or changing a joint preserves the rest shape.</p>`);
   if(weights.length===1)$('weight').disabled=true;
   bind('influence','onchange',e=>{influence=+e.target.value;redraw();});bind('joint','onchange',e=>act(()=>save(bindMeshJoint(pack,mesh,vertex,e.target.value,influence))));
   bind('apply-bind','onclick',()=>act(()=>{for(const id of ['weight','x','y','z'])if(!$(id).reportValidity())return;save(editMeshInfluence(mesh,vertex,influence,Object.fromEntries(['weight','x','y','z'].map(k=>[k,+$(k).value]))));}));
   bind('add-influence','onclick',()=>act(()=>{const next=bindMeshJoint(pack,mesh,vertex,$('add-joint').value);influence=next.vertices[vertex].weights.length-1;save(next);}));bind('remove-influence','onclick',()=>act(()=>{const next=removeMeshInfluence(mesh,vertex,influence);influence=Math.max(0,influence-1);save(next);}));
  }else{
   target.insertAdjacentHTML('beforeend',`<div class="mesh-add-row">${drivers.length?select('correction','Pose correction',drivers.map((d,i)=>[i,`${i+1}: ${d.joint} ${d.channel}`]),correction):'<p class="note">Add a pose correction to reshape this surface when a joint bends or turns.</p>'}<button id="mesh-add-correction" ${drivers.length>=32?'disabled':''} aria-label="Add pose correction">+</button></div>`);
   bind('add-correction','onclick',()=>act(()=>{const next=structuredClone(mesh);const j=pack.joints.find(j=>j.id===w.joint),rotation=j.min<j.max;(next.correctives??=[]).push({joint:w.joint,channel:rotation?'rotation':'bend',min:rotation?Math.max(j.min,Math.min(0,j.max-1)):0,max:rotation?Math.min(j.max,Math.max(90,j.min+1)):1,offsets:[]});correction=next.correctives.length-1;save(next);}));bind('correction','onchange',e=>{correction=+e.target.value;redraw();});
   if(driver){const offset=driver.offsets.find(o=>o.vertex===vertex)||{},drivingJoint=pack.joints.find(j=>j.id===driver.joint),range=driver.channel==='rotation'?[drivingJoint.min,drivingJoint.max]:channels[driver.channel];
    target.insertAdjacentHTML('beforeend',`${select('driver-joint','Driving joint',joints,driver.joint)}${select('driver-channel','Driving motion',Object.keys(channels).map(k=>[k,k]),driver.channel)}<div class="two-col">${number('driver-min','Starts at',driver.min,range[0],range[1],'any')}${number('driver-max','Full at',driver.max,range[0],range[1],'any')}</div><button id="mesh-apply-driver" class="text-button">Apply driver</button><div class="section-label">Vertex ${vertex+1} offset</div><div class="two-col">${number('offset-x','Offset X',offset.x)}${number('offset-y','Offset Y',offset.y)}${number('offset-z','Offset Z',offset.z)}</div><button id="mesh-apply-offset" class="text-button">Apply vertex correction</button><p id="mesh-driver-live" class="note" role="status"></p><p class="note">Offsets use the driving joint’s axes. They ease from zero at Starts at to full strength at Full at. Use the timeline to review the shape in motion.</p><button id="mesh-clear-offset" class="text-button">Clear this vertex offset</button><button id="mesh-remove-correction" class="text-button">Remove pose correction</button>`);
    const driverBounds=()=>{const j=pack.joints.find(j=>j.id===$('driver-joint').value),bounds=$('driver-channel').value==='rotation'?[j.min,j.max]:channels[$('driver-channel').value];for(const id of ['driver-min','driver-max']){$(id).min=bounds[0];$(id).max=bounds[1];}if(+$('driver-max').value>bounds[1])$('driver-max').value=bounds[1];if(+$('driver-min').value<bounds[0])$('driver-min').value=bounds[0];};bind('driver-channel','onchange',driverBounds);bind('driver-joint','onchange',driverBounds);
    bind('apply-driver','onclick',()=>act(()=>{for(const id of ['driver-min','driver-max'])if(!$(id).reportValidity())return;const min=+$('driver-min').value,max=+$('driver-max').value;if(min>=max)throw Error('Full at must be greater than Starts at.');const next=structuredClone(mesh);Object.assign(next.correctives[correction],{joint:$('driver-joint').value,channel:$('driver-channel').value,min,max});save(next);}));
    bind('apply-offset','onclick',()=>act(()=>{for(const axis of ['x','y','z'])if(!$('offset-'+axis).reportValidity())return;save(setMeshVertexCorrection(mesh,correction,vertex,Object.fromEntries(['x','y','z'].map(axis=>[axis,+$('offset-'+axis).value]))));}));bind('clear-offset','onclick',()=>act(()=>save(setMeshVertexCorrection(mesh,correction,vertex,{}))));bind('remove-correction','onclick',()=>act(()=>{const next=structuredClone(mesh);next.correctives.splice(correction,1);correction=Math.max(0,correction-1);save(next);}));
   }
  }
  target.insertAdjacentHTML('beforeend',`<p class="note mesh-shared-note">Edits update the shared ${esc(actor.pack)} pack and every character using it.</p>`);
 }
 function update(frame,svg,active){
  let overlay=svg?.querySelector('[data-mesh-guides]');if(!active){overlay?.remove();return;}const {actor,pack,mesh}=context(),evaluated=frame.actors.find(a=>a.id===actor?.id);if(!svg||!mesh||!evaluated){overlay?.remove();return;}
  const driver=mesh.correctives?.[correction],readout=host?.querySelector('#mesh-driver-live');if(driver&&readout){const value=evaluated.pose[driver.joint+'.'+driver.channel]??0,t=Math.max(0,Math.min(1,(value-driver.min)/(driver.max-driver.min)));readout.textContent=`Current ${driver.channel}: ${value.toFixed(1)} · correction ${Math.round(t*t*(3-2*t)*100)}%`;}
  if(!guides){overlay?.remove();return;}
  const geometry=evaluateSkinnedMesh(mesh,spatialKinematics(pack,evaluated.pose),evaluated.pose),placement=evaluated.placement||actor.transform,parent=svg.querySelector('[data-camera]')||svg;
  if(!overlay){overlay=document.createElementNS('http://www.w3.org/2000/svg','g');overlay.dataset.meshGuides='';overlay.setAttribute('aria-label','Surface wireframe');parent.append(overlay);overlay.onpointerdown=e=>{const dot=e.target.closest('[data-mesh-vertex]');if(!dot)return;e.stopPropagation();e.preventDefault();pause();vertex=+dot.dataset.meshVertex;influence=0;redraw();};overlay.onkeydown=e=>{if(!['Enter',' '].includes(e.key))return;const dot=e.target.closest('[data-mesh-vertex]');if(dot){e.stopPropagation();e.preventDefault();pause();vertex=+dot.dataset.meshVertex;influence=0;redraw();}};}
  overlay.setAttribute('transform',`translate(${placement.x} ${placement.y}) rotate(${placement.rotation}) scale(${placement.scale})`);
  // Keep the vertex hit targets stable while playback changes their positions.
  if(overlay.dataset.part!==partId||overlay.querySelectorAll('circle').length!==geometry.vertices.length){overlay.dataset.part=partId;overlay.innerHTML='<path data-mesh-wire="" fill="none" stroke="#7959b9" stroke-width=".7" vector-effect="non-scaling-stroke" pointer-events="none"/>'+geometry.vertices.map((_,i)=>`<circle data-mesh-vertex="${i}" tabindex="0" role="button" aria-label="Select surface vertex ${i+1}" stroke="#fff" stroke-width="1.2" vector-effect="non-scaling-stroke"/>`).join('');}
  overlay.querySelector('[data-mesh-wire]').setAttribute('d',geometry.edges.map(e=>e.d).join(''));
  const scale=Math.max(.05,Math.hypot(overlay.getScreenCTM()?.a||1,overlay.getScreenCTM()?.b||0));overlay.querySelectorAll('circle').forEach((dot,i)=>{const p=geometry.vertices[i];dot.setAttribute('cx',p.x);dot.setAttribute('cy',p.y);dot.setAttribute('r',(i===vertex?5:3.5)/scale);dot.setAttribute('fill',i===vertex?'#e77d32':'#7959b9');dot.setAttribute('aria-pressed',String(i===vertex));});

 }
 return {render,update};
}
