import './native-three.css';
import {BenchProject3DStore,createBenchProject3D,assertBenchProject3D} from '../src/bench-project-3d.js';
import {WorkoutProject3DStore,createWorkoutProject3D,assertWorkoutProject3D} from '../src/workout-project-3d.js';
import {createNativeThreeView} from '../src/native-three-view.js';

const WORKOUT=new URLSearchParams(location.search).get('demo')==='gym-routine';
const storageFor=p=>p.kind==='workout3d'?'posecraft.workout3d.v1':'posecraft.native3d.v1';
const assertProject=p=>p?.kind==='workout3d'?assertWorkoutProject3D(p):assertBenchProject3D(p);
const makeStore=p=>p.kind==='workout3d'?new WorkoutProject3DStore(p):new BenchProject3DStore(p);
const paths={undo:'M7 7H3V3 M3 7a8 8 0 1 1 0 10',redo:'M17 7h4V3 M21 7a8 8 0 1 0 0 10',open:'M3 7h7l2 2h9l-3 11H3Z M3 7V4h7l2 3',save:'M5 3h12l4 4v14H3V3Z M7 3v6h10V3 M7 21v-8h10v8',export:'M12 15V3 M7 8l5-5 5 5 M4 13v8h16v-8',character:'M12 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6 M5 21v-5a7 7 0 0 1 14 0v5',bench:'M3 12h18v4H3Z M6 16v5 M18 16v5',pullup:'M4 21V4h16v17 M2 21h4 M18 21h4',bottle:'M9 3h6v4l2 3v11H7V10l2-3Z M9 7h6',camera:'M3 7h5l2-3h4l2 3h5v14H3Z M16 14a4 4 0 1 0-8 0 4 4 0 0 0 8 0',action:'m14 2-9 12h7l-2 8 9-12h-7Z',play:'m8 4 12 8-12 8Z',pause:'M8 4v16 M16 4v16',restart:'M5 4v16 M19 4 7 12l12 8Z'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.action}"/></svg>`;
const button=(id,label,name)=>`<button id="${id}" title="${label}" aria-label="${label}">${icon(name)}<span class="button-label">${label}</span></button>`;
document.querySelector('#app').innerHTML=`<div class="native-app"><header class="native-header"><a class="brand" href="./index.html" aria-label="Posecraft Studio"><span class="brand-mark">p</span><span>posecraft</span></a><input class="project-name" id="project-name" aria-label="Project name" maxlength="80"><span class="spacer"></span>${button('undo','Undo','undo')}${button('redo','Redo','redo')}${button('open','Open','open')}${button('save','Save','save')}${button('export','Website','export')}<a class="legacy-link" href="./index.html">2D Studio ↗</a></header><main class="native-layout"><nav class="native-nav" aria-label="Scene controls"><h2>Scene</h2>${['character','bench','pullup','bottle','camera','action'].map(name=>`<button data-section="${name}" aria-pressed="${name==='character'}">${icon(name)}${name==='pullup'?'Pull-up':name==='action'&&WORKOUT?'Workout':name[0].toUpperCase()+name.slice(1)}</button>`).join('')}<small>Native 3D<br>Meters · Y up<br><br>Drag to orbit.<br>Scroll to zoom.</small></nav><section class="native-stage" aria-label="Scene preview"><div class="native-stage-top"><strong id="stage-title">Bench movement study</strong><div class="view-presets" aria-label="View presets"><button data-view="three">Three-quarter</button><button data-view="front">Front</button><button data-view="side">Side</button></div></div><div class="native-canvas-wrap"><canvas id="native-canvas" aria-label="3D character and bench" tabindex="0"></canvas><div class="stage-loading" id="loading">Loading character…</div><div class="stage-badge" id="phase">Preparing scene</div></div><div class="playback"><div class="play-buttons">${button('restart','Restart','restart')}${button('play','Play','play')}</div><div class="timeline"><div class="timeline-label"><span>Movement <button id="finish-safely" type="button" hidden>Finish safely</button></span><span id="timeline-end">—</span></div><input id="time" type="range" min="0" max="1" step="0.01" value="0" aria-label="Animation time"></div><output id="clock">0.00 / 0.00</output></div></section><aside class="native-inspector" id="inspector" aria-label="Properties"></aside></main><footer class="native-footer"><span id="save-state">Local project</span><span id="render-state">Native skeleton · Contact solver</span></footer><div class="native-message" id="message" role="status" hidden></div><input id="project-file" type="file" accept=".json,application/json" hidden><input id="character-file" type="file" accept=".glb,model/gltf-binary" hidden></div>`;
const $=id=>document.getElementById(id),inspector=$('inspector');
let initial=WORKOUT?createWorkoutProject3D():createBenchProject3D(),initialError;
try{const saved=localStorage.getItem(storageFor(initial));if(saved)initial=assertProject(JSON.parse(saved));}catch{initialError='The saved draft could not be opened. A new study is ready; the old draft is unchanged until your next edit.';}
let store=makeStore(initial);
let view,section='character',time=0,playing=WORKOUT&&!matchMedia('(prefers-reduced-motion: reduce)').matches,busy=false,customURL=null,customName='',last=0,dirty=true,messageTimer;
function notice(message){$('message').textContent=message;$('message').hidden=false;clearTimeout(messageTimer);messageTimer=setTimeout(()=>$('message').hidden=true,9000);}
function persist(){try{localStorage.setItem(storageFor(store.document),JSON.stringify(store.document));$('save-state').textContent=customURL?'Saved · Custom character is session-only':'Saved on this device';}catch{$('save-state').textContent='Autosave unavailable — use Save';}}
function refresh(){const p=store.document;$('project-name').value=p.name;$('stage-title').textContent=p.name;$('undo').disabled=busy||!store.canUndo;$('redo').disabled=busy||!store.canRedo;$('export').disabled=busy||!view||!!customURL;$('export').title=customURL?'Custom GLB is session-only; choose a catalog character to export.':'Export a self-contained website';for(const id of ['open','save','project-name'])$(id).disabled=busy;for(const id of ['play','restart','time'])$(id).disabled=busy||!view;document.querySelectorAll('[data-view]').forEach(b=>b.disabled=busy||!view);inspector.querySelectorAll('input,select,button').forEach(e=>e.disabled=busy||!view);$('play').innerHTML=icon(playing?'pause':'play');$('play').setAttribute('aria-label',playing?'Pause':'Play');$('play').title=playing?'Pause':'Play';$('finish-safely').hidden=!view?.action?.interrupt||time>=(view?.duration||0);$('finish-safely').disabled=busy||!view;const live=p.kind==='workout3d';$('time').hidden=live;$('time').max=String(Number.isFinite(view?.duration)?view.duration:1);$('timeline-end').textContent=live?'Live decisions':(view?.duration||0).toFixed(1)+' s';document.querySelectorAll('[data-section="pullup"],[data-section="bottle"]').forEach(node=>node.hidden=!live);}
function field(label,id,value,min,max,step=.01){const wrap=document.createElement('label');wrap.textContent=label;const input=document.createElement('input');Object.assign(input,{id,type:'number',value:String(value),min:String(min),max:String(max),step:String(step)});wrap.append(input);return wrap;}
function text(tag,content,cls){const node=document.createElement(tag);node.textContent=content;if(cls)node.className=cls;return node;}
function changeNumber(input,apply){input.addEventListener('change',()=>{const value=input.valueAsNumber;if(!Number.isFinite(value)||!input.checkValidity()){notice('Enter a number within the displayed limits.');renderInspector();return;}const p=store.document;apply(p,value);commit(p);});}
function number(label,id,value,min,max,step,apply,parent=inspector){const wrap=field(label,id,value,min,max,step);parent.append(wrap);changeNumber(wrap.querySelector('input'),apply);}
function vector(label,id,values,min,max,apply){inspector.append(text('h3',label));const row=document.createElement('div');row.className='field-grid';values.forEach((v,i)=>number(['X','Y','Z'][i],`${id}-${i}`,v,min,max,.01,(p,n)=>apply(p,i,n),row));inspector.append(row);}
function wide(label,id,handler){const b=document.createElement('button');b.textContent=label;b.id=id;b.className='wide';b.addEventListener('click',handler);inspector.append(b);return b;}
function renderInspector(){inspector.replaceChildren();const p=store.document;inspector.append(text('h1',{character:'Character',bench:'Bench',pullup:'Pull-up station',bottle:'Water bottle',camera:'Camera',action:p.kind==='workout3d'?'Workout':'Movement'}[section]));
 if(section==='character'){
  inspector.append(text('p','Choose a rigged character. Height changes rebuild the movement for its proportions.','intro'));
  const label=text('label','Character'),select=document.createElement('select');select.id='character-asset';for(const [value,name]of [['athlete','Athlete A · Male'],['regular','Athlete B · Female']]){const option=document.createElement('option');option.value=value;option.textContent=name;select.append(option);}select.value=p.character.asset;label.append(select);inspector.append(label);select.onchange=()=>{const next=store.document;next.character.asset=select.value;commit(next,{clearCustom:true});};
  number('Height · meters','character-height',p.character.height,.9,2.4,.01,(p,n)=>p.character.height=n);
  wide('Import rigged GLB…','import-character',()=>$('character-file').click());
  inspector.append(text('p',customURL?`${customName} is loaded for this session. JSON saves keep the catalog choice; website export is unavailable for this import.`:'Custom GLB files need a compatible humanoid skeleton. They stay in this session and are not embedded in project JSON.',customURL?'warning':'note'));
  if(customURL)wide('Use catalog character','clear-character',()=>commit(store.document,{clearCustom:true}));
 }else if(section==='bench'){
  inspector.append(text('p','Place the furniture in meters. The action follows its position, facing and size.','intro'));
  vector('Floor position','bench-position',p.bench.position,-20,20,(p,i,n)=>p.bench.position[i]=n);
  const q=p.bench.rotation,yaw=Math.atan2(2*(q[3]*q[1]+q[0]*q[2]),1-2*(q[1]**2+q[2]**2))*180/Math.PI;
  number('Facing · degrees around Y','bench-yaw',Math.round(yaw*100)/100,-180,180,1,(p,n)=>p.bench.rotation=[0,Math.sin(n*Math.PI/360),0,Math.cos(n*Math.PI/360)]);
  number('Rack height · meters','bench-rack-height',p.bench.rackHeight??1,.65,1.5,.01,(p,n)=>p.bench.rackHeight=n);
  number('Furniture scale','bench-scale',p.bench.scale,.5,2,.01,(p,n)=>p.bench.scale=n);
  inspector.append(text('p','Unreachable furniture sizes and tilted benches are rejected without changing the current study.','note'));
 }else if(section==='pullup'||section==='bottle'){
  if(p.kind!=='workout3d'){section='character';renderInspector();return;}
  inspector.append(text('p',section==='pullup'?'The bar position and facing define the pull-up grips.':'The bottle rests on a shelf at this position and travels with the hand during drinking.','intro'));
  vector('Position · meters',section+'-position',p[section].position,-20,20,(p,i,n)=>p[section].position[i]=n);
  const q=p[section].rotation,yaw=Math.atan2(2*(q[3]*q[1]+q[0]*q[2]),1-2*(q[1]**2+q[2]**2))*180/Math.PI;
  number('Facing · degrees around Y',section+'-yaw',Math.round(yaw*100)/100,-180,180,1,(p,n)=>p[section].rotation=[0,Math.sin(n*Math.PI/360),0,Math.cos(n*Math.PI/360)]);
  if(section==='pullup')number('Bar width · meters','pullup-width',p.pullup.width,.5,2,.01,(p,n)=>p.pullup.width=n);
 }else if(section==='camera'){
  inspector.append(text('p','Orbit the preview, then save that view. The saved camera is used by the exported website.','intro'));
  wide('Save current view','save-camera',()=>{const next=store.document;next.camera=view.cameraState();commit(next);});
  vector('Camera position','camera-position',p.camera.position,-1000,1000,(p,i,n)=>p.camera.position[i]=n);
  vector('Look at','camera-target',p.camera.target,-1000,1000,(p,i,n)=>p.camera.target[i]=n);
  number('Visible height · meters','camera-height',p.camera.height,.5,30,.1,(p,n)=>p.camera.height=n);
 }else{
  const live=p.kind==='workout3d';
  inspector.append(text('p',live?'The character chooses sets, recovery and water from the saved workout rules. Pause to inspect; Restart repeats the seed.':'A full sequence: approach, sit, recline, press, rerack and stand.','intro'));
  if(live){
    inspector.append(text('h3','Live state'));const state=text('div','Starting workout…','contact-readout');state.id='workout-stats';state.setAttribute('role','status');inspector.append(state);
    const controls=document.createElement('div');controls.className='workout-requests';for(const [action,label] of [['pullup','Pull-ups next'],['bench','Bench next'],['rest','Rest next'],['drink','Get water next']]){const b=document.createElement('button');b.textContent=label;b.dataset.request=action;b.onclick=()=>view.request(action).then(()=>{playing=true;refresh();notice(label+' queued.');}).catch(error=>notice(error.message));controls.append(b);}inspector.append(controls);
    const label=text('label','Exercise order'),select=document.createElement('select');select.id='workout-sequence';for(const [value,name] of [['pullup,bench','Pull-ups then bench'],['bench,pullup','Bench then pull-ups'],['pullup','Pull-ups only'],['bench','Bench only']]){const o=document.createElement('option');o.value=value;o.textContent=name;select.append(o);}select.value=(p.workout.sequence||['pullup','bench']).join(',');label.append(select);inspector.append(label);select.onchange=()=>{const next=store.document;next.workout.sequence=select.value.split(',');commit(next);};
    number('Minimum repetitions','workout-reps-min',p.workout.reps.min,1,12,1,(p,n)=>p.workout.reps.min=n);
    number('Maximum repetitions','workout-reps-max',p.workout.reps.max,1,12,1,(p,n)=>p.workout.reps.max=n);
    number('Random seed','workout-seed',p.workout.seed,0,4294967295,1,(p,n)=>p.workout.seed=n);
    number('Rest · seconds','workout-rest',p.workout.restDuration,3,30,.5,(p,n)=>p.workout.restDuration=n);
    number('Drink · seconds','workout-drink',p.workout.drinkDuration,3,30,.5,(p,n)=>p.workout.drinkDuration=n);
    number('Rest when fatigue reaches','workout-rest-threshold',p.workout.restThreshold??60,0,100,1,(p,n)=>p.workout.restThreshold=n);
    number('Drink when dehydration reaches','workout-drink-threshold',p.workout.drinkThreshold??45,0,100,1,(p,n)=>p.workout.drinkThreshold=n);
    number('Initial fatigue','workout-fatigue',p.workout.fatigue,0,100,1,(p,n)=>p.workout.fatigue=n);
    number('Initial dehydration','workout-dehydration',p.workout.dehydration,0,100,1,(p,n)=>p.workout.dehydration=n);
    number('Base failure chance','workout-failure',p.workout.failureBase,0,1,.01,(p,n)=>p.workout.failureBase=n);

  }else number('Repetitions','action-reps',p.settings.reps,1,12,1,(p,n)=>p.settings.reps=n);
  number('Effort · 0 to 1','action-effort',p.settings.effort,0,1,.05,(p,n)=>p.settings.effort=n);
  number('Tempo multiplier','action-tempo',p.settings.tempo,.25,3,.05,(p,n)=>p.settings.tempo=n);
  inspector.append(text('h3','Bend limits'));
  number('Maximum elbow bend · degrees','action-elbow-max',p.settings.elbowMax??170,20,175,1,(p,n)=>p.settings.elbowMax=n);
  number('Maximum knee bend · degrees','action-knee-max',p.settings.kneeMax??170,20,175,1,(p,n)=>p.settings.kneeMax=n);
  inspector.append(text('p','These limits can narrow the rig’s own range; they cannot extend it. Restrictive limits may make targets unreachable.','note'));
  inspector.append(text('h3','Contact check'));const readout=text('div','Move the playhead to inspect contacts.','contact-readout');readout.id='contacts';readout.setAttribute('role','status');inspector.append(readout);
  inspector.append(text('p',live?'Fatigue and dehydration influence decisions and outcomes. They are authored gameplay values, not a muscle-force simulation.':'This study evaluates authored movement with contact constraints. It does not simulate lifting forces or muscle strength.','note'));
 }
 refresh();dirty=true;
}
async function commit(next,{clearCustom=false}={}){if(busy)return;try{assertProject(next);}catch(error){notice(error.message);renderInspector();return;}busy=true;playing=false;refresh();const previous=store.document,oldURL=customURL,oldName=customName;try{
 if(clearCustom&&customURL){view.dispose();view=undefined;try{view=await createNativeThreeView($('native-canvas'),next);}catch(error){view=await createNativeThreeView($('native-canvas'),{...previous,assetUrl:oldURL});throw error;}customURL=null;customName='';URL.revokeObjectURL(oldURL);}else if(view)await view.setProject(next);else{view=await createNativeThreeView($('native-canvas'),next);$('loading').hidden=true;}
 if(store.document.kind===next.kind)store.replace(next);else store=makeStore(next);time=next.kind==='workout3d'?0:Math.min(time,view.duration);persist();dirty=true;
 }catch(error){customName=oldName;notice(error.message||'This edit could not be applied.');}finally{busy=false;renderInspector();refresh();}}
async function history(direction){if(busy||!(direction==='undo'?store.canUndo:store.canRedo))return;busy=true;playing=false;refresh();const before=store.document;store[direction]();try{await view.setProject(store.document);persist();time=store.document.kind==='workout3d'?0:Math.min(time,view.duration);dirty=true;}catch(error){store[direction==='undo'?'redo':'undo']();notice(error.message);if(JSON.stringify(before)!==JSON.stringify(store.document))notice('The previous project could not be restored.');}finally{busy=false;renderInspector();}}
function download(contents,extension,type){const url=URL.createObjectURL(new Blob([contents],{type})),a=document.createElement('a');a.href=url;a.download=(store.document.name.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'bench-study')+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('project-name').onchange=()=>{const p=store.document;p.name=$('project-name').value.trim();commit(p);};$('undo').onclick=()=>history('undo');$('redo').onclick=()=>history('redo');$('save').onclick=()=>download(JSON.stringify(store.document,null,2),'.json','application/json');$('open').onclick=()=>$('project-file').click();
$('project-file').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>65536)throw Error('Project JSON must be smaller than 64 KB.');const next=assertProject(JSON.parse(await file.text()));await commit(next,{clearCustom:true});}catch(error){notice('Project was not opened. '+error.message);}};
$('character-file').onchange=async event=>{const file=event.target.files[0];event.target.value='';if(!file||busy)return;let url;try{if(!/\.glb$/i.test(file.name)||file.size>25*1024*1024||file.size<20)throw Error('Choose a binary GLB file smaller than 25 MB.');const header=new DataView(await file.slice(0,12).arrayBuffer());if(header.getUint32(0,true)!==0x46546c67||header.getUint32(4,true)!==2||header.getUint32(8,true)!==file.size)throw Error('This file is not a valid GLB 2 container.');busy=true;playing=false;refresh();url=URL.createObjectURL(file);view.dispose();view=undefined;try{view=await createNativeThreeView($('native-canvas'),{...store.document,assetUrl:url});}catch(error){view=await createNativeThreeView($('native-canvas'),{...store.document,...(customURL?{assetUrl:customURL}:{})});throw error;}if(customURL)URL.revokeObjectURL(customURL);customURL=url;customName=file.name;url=null;time=0;dirty=true;notice('Custom character loaded for this session.');}catch(error){notice(error.message);}finally{if(url)URL.revokeObjectURL(url);busy=false;renderInspector();}};
$('export').onclick=async()=>{if(!view||busy||customURL)return;busy=true;playing=false;refresh();try{download(await view.exportHTML(store.document),'.html','text/html');notice('Website exported with the character and player included.');}catch(error){notice('Website export failed. '+error.message);}finally{busy=false;refresh();}};
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;document.querySelectorAll('[data-section]').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));renderInspector();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{const p=store.document,center=p.bench.position;const positions={three:[3,2.2,3.4],front:[0,1.3,5],side:[5,1.3,0]};p.camera={position:positions[b.dataset.view].map((n,i)=>n+center[i]),target:[center[0],center[1]+.85,center[2]],height:3.6};commit(p);});
$('play').onclick=()=>{if(time>=view.duration)time=0;playing=!playing;dirty=true;refresh();};$('restart').onclick=()=>{view.resetMovement?.();time=0;dirty=true;refresh();};$('finish-safely').onclick=()=>{if(view.finishSafely?.(time)){if(store.document.kind!=='workout3d')time=0;playing=true;dirty=true;refresh();notice('Finishing the movement and returning to standing.');}else notice('Finish safely is available once the bar is held. Pause or restart during the approach.');};$('time').oninput=()=>{playing=false;time=Number($('time').value);dirty=true;refresh();};
function frameInfo(frame){const state=view?.stats();$('render-state').textContent=state?.motionWorker?'Motion worker · Skinned mesh':'Local motion · Skinned mesh';$('render-state').title=state?.workerError||'';$('phase').textContent=(frame?.workout?.activity||frame?.phase||'Ready').replaceAll('-',' ');const live=$('workout-stats');if(live&&frame?.workout){const stats=frame.workout.stats;live.textContent=`${frame.workout.activity} · Fatigue ${Number(stats.fatigue).toFixed(0)} · Dehydration ${Number(stats.dehydration).toFixed(0)} · ${stats.sets} sets · ${stats.reps} reps`;}const node=$('contacts');if(node){const diagnostics=Array.isArray(frame?.diagnostics)?frame.diagnostics:Object.values(frame?.diagnostics||{}),errors=diagnostics.flatMap(d=>typeof d?.error==='number'?[d.error]:[]),active=Array.isArray(frame?.contacts)?frame.contacts.filter(c=>c.active!==false).length:0;node.textContent=`${active} contacts · ${frame?.valid===false?'Some targets are unreachable':'Pose evaluated'}${errors.length?' · Largest error '+(Math.max(...errors)*1000).toFixed(1)+' mm':''}`;}}
document.addEventListener('visibilitychange',()=>{last=0;dirty=true;});
Object.defineProperty(window,'posecraftNativeStudio',{value:Object.freeze({snapshot:()=>structuredClone({ready:!!view&&!busy,project:store.document,time,playing,duration:view?.duration||0,frame:view?.frame,stats:view?.stats(),beats:view?.action?.beats,character:view?.character?.metadata})}),writable:false});
function loop(now){if(document.hidden){last=0;requestAnimationFrame(loop);return;}const delta=last?Math.min(.05,(now-last)/1000):0;last=now;if(view&&!busy&&(playing||dirty)){if(playing){time=Math.min(view.duration,time+delta);if(time===view.duration||view.frame?.workout?.stopped){playing=false;refresh();}}try{frameInfo(playing?view.renderAsync(time):view.render(time));$('time').value=String(time);$('clock').textContent=Number.isFinite(view.duration)?`${time.toFixed(2)} / ${view.duration.toFixed(2)}`:`${time.toFixed(1)} s`;}catch(error){playing=false;notice(error.message);refresh();}dirty=false;}requestAnimationFrame(loop);}
renderInspector();requestAnimationFrame(loop);
try{view=await createNativeThreeView($('native-canvas'),store.document);$('loading').hidden=true;dirty=true;refresh();if(initialError)notice(initialError);}catch(error){$('loading').textContent='Preview unavailable. '+error.message;notice(error.message);}
window.addEventListener('pagehide',()=>{view?.dispose();if(customURL)URL.revokeObjectURL(customURL);});
