import {removeSceneEntity} from '../src/scene-graph.js';
import {evaluatedProps} from '../src/scene-attachments.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const set=(path,value)=>({op:'set',path,value});
const option=(id,label,selected)=>`<option value="${esc(id)}" ${id===selected?'selected':''}>${esc(label)}</option>`;
const numberValid=el=>el.value.trim()!==''&&Number.isFinite(Number(el.value))&&el.reportValidity();
const chains=pack=>pack.joints.flatMap(upper=>pack.joints.filter(lower=>lower.parent===upper.id).flatMap(lower=>pack.joints.filter(end=>end.parent===lower.id).map(end=>({upper:upper.id,lower:lower.id,end:end.id}))));
export function defaultCatchParticipant(doc,actor){
 const pack=doc.packs[doc.actors.find(a=>a.id===actor)?.pack];if(!pack)return null;
 const possible=chains(pack),chain=possible.find(c=>/right.*(arm|shoulder)|upper.*right/i.test(c.upper)&&/wrist|hand/i.test(c.end))||possible.find(c=>/wrist|hand/i.test(c.end))||possible[0],root=pack.joints.find(j=>j.parent===null)?.id;
 if(!chain||!root)return null;const head=pack.joints.find(j=>/^head$/i.test(j.id))?.id,left=pack.joints.find(j=>/left.*(foot|ankle)|(foot|ankle).*left/i.test(j.id))?.id,right=pack.joints.find(j=>/right.*(foot|ankle)|(foot|ankle).*right/i.test(j.id))?.id;
 return {actor,root,...(head?{head}:{}),...(left&&right?{feet:[left,right]}:{}),chain,bend:/left/i.test(chain.upper)?-1:1,speed:145,skill:.8,reaction:.14,crouch:48};
}
export function createObjectTools({getDocument,commit,getController,notify=()=>{}}){
 let selected='',renderVersion=0;
 function render(target){
  const version=++renderVersion;
  const doc=getDocument(),objects=doc.objects||[];if(!objects.some(o=>o.id===selected))selected=objects[0]?.id||'';
  const object=objects.find(o=>o.id===selected),index=objects.indexOf(object),game=doc.objectGames?.find(g=>g.object===selected),gameIndex=doc.objectGames?.indexOf(game),dynamic=object?.shape==='circle'&&object.mass>0;
  const $=id=>target.querySelector('#'+id),save=commands=>{try{const changed=commands.filter(c=>JSON.stringify(getDocument()[c.path[0]])!==JSON.stringify(c.value));if(changed.length)commit(changed);render(target);return true;}catch(e){notify(e.message);return false;}};
  const field=(scope,key,label,value,min,max,step='any')=>`<label class="field">${label}<input data-${scope}-field="${key}" type="number" required value="${value}" min="${min}" max="${max}" step="${step}"></label>`;
  const patch=values=>{const next=structuredClone(getDocument().objects);Object.assign(next[index],values);save([set(['objects'],next)]);};
  const live=()=>getController()?.frame()?.objects?.find(o=>o.id===selected),liveOwner=live()?.owner;
  target.innerHTML=`<div class="inspector-heading">Shared objects<small>Catch & throw</small></div><label class="field">Object<select id="object-select">${objects.map(o=>option(o.id,o.name,selected)).join('')}</select></label><button id="object-add" class="text-button">Add ball</button>${object?`<label class="field">Name<input id="object-name" required value="${esc(object.name)}" maxlength="100"></label><div class="two-col">${field('object','x','Start X',object.x,-10000,10000)}${field('object','y','Start Y',object.y,-10000,10000)}${object.shape==='circle'?field('object','radius','Radius',object.radius,4,200)+field('object','mass','Mass / 0 is static',object.mass,0,100):'<p class="note">Static collision surface</p>'}${field('object','restitution','Bounce',object.restitution??.6,0,1,.05)}${field('object','friction','Friction',object.friction??.5,0,1,.05)}${field('object','damping','Air drag',object.damping??.05,0,10,.01)}</div><label class="field">Color<input id="object-color" type="color" value="${object.fill}"></label><label class="field">Grip actor<select id="object-owner" ${dynamic?'':'disabled'}><option value="">Unattached</option>${doc.actors.map(a=>option(a.id,a.name,object.owner?.actor)).join('')}</select></label><label class="field">Grip joint<select id="object-joint" ${dynamic?'':'disabled'}></select></label><button id="object-owner-save" class="text-button" ${dynamic?'':'disabled'}>Save starting grip</button><div class="two-col"><button id="object-try-grip" class="text-button" ${dynamic?'':'disabled'}>Try grip now</button><button id="object-drop" class="text-button" ${dynamic?'':'disabled'}>Drop now</button></div><label class="field">Transfer from<select id="object-transfer-from" ${dynamic?'':'disabled'}><option value="">Choose current owner</option>${doc.actors.map(a=>option(a.id,a.name,liveOwner?.actor)).join('')}</select></label><button id="object-transfer" class="text-button" ${dynamic?'':'disabled'}>Transfer to selected grip now</button><p id="object-live-owner" class="note" role="status">Live owner: ${esc(liveOwner?liveOwner.actor+' / '+liveOwner.joint:'none')}</p><p class="note">A live grip requires contact. A transfer checks the current owner and the receiving hand. Saved grips apply when the scene starts. Static objects cannot be carried.</p><button id="object-remove" class="text-button">Remove object</button><div id="object-game"></div>`:'<p class="note">Shared props have one physical position and one owner across all characters.</p>'}`;
  $('object-select').onchange=e=>{selected=e.target.value;render(target);};
  $('object-add').onclick=()=>{if(objects.length>=64)return notify('Keep at most 64 shared objects.');selected='object-'+Date.now().toString(36);save([set(['objects'],[...objects,{id:selected,name:'Ball',shape:'circle',x:doc.bounds.width/2,y:doc.bounds.height/2,radius:12,fill:'#df8257',mass:.2,restitution:.6,friction:.5,damping:.05}]),set(['requiredFeatures'],[...new Set([...(doc.requiredFeatures||[]),'scene-objects'])])]);};
  if(!object)return;
  target.querySelectorAll('[data-object-field]').forEach(el=>el.onchange=()=>{if(!numberValid(el))return notify('Enter a number in the shown range.');const value=Number(el.value),key=el.dataset.objectField;if(key==='mass'&&value===0){if(game)return notify('Remove this ball’s Catch behavior before making it static.');const next=structuredClone(objects);next[index].mass=0;delete next[index].owner;return save([set(['objects'],next)]);}patch({[key]:value});});
  $('object-name').onchange=e=>{if(e.target.value.trim())patch({name:e.target.value.trim()});else notify('Enter an object name.');};$('object-color').onchange=e=>patch({fill:e.target.value});
  const owner=$('object-owner'),joint=$('object-joint'),joints=()=>{const a=doc.actors.find(a=>a.id===owner.value);joint.innerHTML=(doc.packs[a?.pack]?.joints||[]).map(j=>option(j.id,j.id,game?.participants.find(p=>p.actor===owner.value)?.chain.end||object.owner?.joint)).join('');};owner.onchange=joints;joints();
  $('object-owner-save').onclick=()=>{if(!dynamic)return;if(game&&owner.value&&!game.participants.some(p=>p.actor===owner.value&&p.chain.end===joint.value))return notify('A Catch starting grip must use one of its configured participant hands.');const next=structuredClone(objects);if(owner.value&&joint.value)next[index].owner={actor:owner.value,joint:joint.value};else delete next[index].owner;save([set(['objects'],next)]);};
  const command=async c=>{
   const controller=getController(),buttons=['object-try-grip','object-drop','object-transfer'].map($),current=()=>version===renderVersion&&controller===getController()&&target.isConnected;
   try{
    // Worker commands are ordered, but frame() remains the last acknowledged frame.
    // Wait for the batch containing this command instead of inspecting that stale frame.
    const sequence=Number.isInteger(controller.sequence)?controller.sequence+1:null;
    buttons.forEach(b=>b.disabled=true);$('object-live-owner').textContent='Waiting for grip result…';
    const result=controller.objectCommand(c),deadline=performance.now()+2500;
    if(sequence!==null){
     while(controller.sequence<sequence||(controller.sequence===sequence&&controller.inFlight)){
      if(!current())return;if(controller.disposed)throw Error('The scene worker is unavailable. Grip result was not confirmed.');
      if(performance.now()>=deadline){$('object-live-owner').textContent='Grip result not confirmed yet.';notify('Still waiting for the scene. Check the live owner before trying again.');return;}
      await new Promise(resolve=>setTimeout(resolve,16));
     }
    }
    if(!current())return;
    const actual=controller.frame()?.objects?.find(o=>o.id===c.object)?.owner,expected=['attach','transfer'].includes(c.type)?actual?.actor===c.actor&&actual?.joint===c.joint:c.type==='release'?!actual:true;
    notify(result===false||!expected?'Grip unchanged: check the current owner and receiving hand contact.':'Object command applied.');$('object-live-owner').textContent='Live owner: '+(actual?actual.actor+' / '+actual.joint:'none');
   }catch(e){if(current())notify(e.message);}finally{if(current())buttons.forEach(b=>b.disabled=!dynamic);}
  };
  $('object-try-grip').onclick=()=>{if(!owner.value||!joint.value)return notify('Select an actor and grip joint.');command({type:'attach',object:object.id,actor:owner.value,joint:joint.value});};
  $('object-drop').onclick=()=>command({type:'release',object:object.id,...(live()?.owner?{actor:live().owner.actor}:{}),vx:0,vy:0});
  $('object-transfer').onclick=()=>{const from=$('object-transfer-from').value;if(!from||live()?.owner?.actor!==from)return notify('Transfer refused: the selected actor is not the live owner.');if(!owner.value||!joint.value)return notify('Select the receiving actor and joint.');command({type:'transfer',object:object.id,from,actor:owner.value,joint:joint.value});};
  $('object-remove').onclick=()=>{
   const next=removeSceneEntity(doc,'object',object.id),frame=getController()?.frame(),placed=frame?evaluatedProps(doc,frame):[];
   for(const prop of next.props||[])if(doc.props.find(p=>p.id===prop.id)?.attachment?.object===object.id){const live=placed.find(p=>p.id===prop.id);if(live&&!live.hidden)Object.assign(prop,{x:live.x,y:live.y,rotation:((live.rotation+180)%360+360)%360-180});}
   save(['objects','objectGames','props','contacts','behaviorGraph','actorBehaviors','game'].filter(key=>next[key]!==undefined).map(key=>set([key],next[key])));
  };
  const panel=$('object-game'),used=new Set((doc.objectGames||[]).filter(g=>g!==game).flatMap(g=>g.participants.map(p=>p.actor))),available=doc.actors.filter(a=>!used.has(a.id)&&defaultCatchParticipant(doc,a.id));
  if(!dynamic){panel.innerHTML='<p class="note">Catch needs a ball with mass greater than zero.</p>';return;}
  panel.innerHTML=`<div class="section-label">Catch behavior</div><fieldset><legend>Participants / choose 2–8</legend>${available.map((a,i)=>`<label class="face-auto"><input type="checkbox" data-catch-participant="${esc(a.id)}" ${(game?game.participants.some(p=>p.actor===a.id):i<2)?'checked':''}>${esc(a.name)}</label>`).join('')}</fieldset><button id="object-game-save-participants" class="text-button">${game?'Save participants':'Create Catch behavior'}</button>${game?`<button id="object-game-remove" class="text-button">Remove Catch behavior</button><label class="face-auto"><input id="object-game-enabled" type="checkbox" ${game.enabled!==false?'checked':''}>Autonomous passing</label><div class="two-col">${field('game','variation','Throw variation, px',game.variation,0,300)}${field('game','flightTime','Flight, seconds',game.flightTime,.5,3,.05)}${field('game','pause','Preparation, seconds',game.pause,.2,8,.1)}${field('game','seed','Seed',game.seed,0,4294967295,1)}</div><div class="section-label">Walking routes</div><label class="face-auto"><input id="object-navigation-enabled" type="checkbox" ${game.navigation?'checked':''}>Walk around obstacles</label>${game.navigation?`<div class="two-col">${['x','y','width','height'].map(key=>field('nav-area',key,({x:'Area X',y:'Area Y',width:'Area width',height:'Area height'})[key],game.navigation.bounds[key],['width','height'].includes(key)?8:0,['x','width'].includes(key)?doc.bounds.width:doc.bounds.height)).join('')}</div><button id="object-navigation-area" class="text-button">Save walking area</button><div class="two-col">${field('nav','cellSize','Grid size',game.navigation.cellSize,8,80)}${field('nav','clearance','Clearance',game.navigation.clearance,0,80)}${field('nav','maxNodes','Work per step',game.navigation.maxNodes,8,256,1)}</div><p class="note">The area contains character position markers; allow room for their feet and heads. Visible collision props and static shared objects block routes. A finer grid finds narrower routes but takes more work.</p>`:''}<div id="object-participants"></div>`:''}<p class="note">Each participant needs a connected upper arm, forearm and grip joint. The saved starting owner goes first, and its grip follows the configured hand. Actors already in another Catch behavior are excluded.</p>`;
  const saveGame=next=>{const commands=[],holder=object.owner&&next.participants.find(p=>p.actor===object.owner.actor);if(object.owner&&!holder)return notify('Include the saved starting owner, or clear the starting grip first.');if(holder){next.participants=[holder,...next.participants.filter(p=>p!==holder)];if(object.owner.joint!==holder.chain.end){const props=structuredClone(objects);props[index].owner={...props[index].owner,joint:holder.chain.end};commands.push(set(['objects'],props));}}const list=structuredClone(doc.objectGames||[]);if(game)list[gameIndex]=next;else list.push(next);return save([...commands,set(['objectGames'],list),set(['requiredFeatures'],[...new Set([...(doc.requiredFeatures||[]),'scene-objects','prop-games',...(next.navigation?['navigation']:[])])])]);};
  $('object-game-save-participants').onclick=()=>{const ids=[...panel.querySelectorAll('[data-catch-participant]:checked')].map(el=>el.dataset.catchParticipant);if(ids.length<2||ids.length>8)return notify('Choose two to eight participants.');if(!game&&(doc.objectGames||[]).length>=8)return notify('Keep at most eight Catch behaviors.');saveGame({...game,id:game?.id||'catch-'+Date.now().toString(36),type:'catch',object:object.id,seed:game?.seed??17,variation:game?.variation??35,flightTime:game?.flightTime??1.35,pause:game?.pause??1.3,participants:ids.map(id=>game?.participants.find(p=>p.actor===id)||defaultCatchParticipant(doc,id))});};
  if(!game)return;
  $('object-game-remove').onclick=()=>save([set(['objectGames'],doc.objectGames.filter(g=>g!==game))]);$('object-game-enabled').onchange=e=>saveGame({...game,enabled:e.target.checked});panel.querySelectorAll('[data-game-field]').forEach(el=>el.onchange=()=>{if(numberValid(el))saveGame({...game,[el.dataset.gameField]:Number(el.value)});else notify('Enter a number in the shown range.');});
  const saveNavigation=navigation=>{const b=navigation?.bounds;if(b&&(!Object.values(b).every(Number.isFinite)||b.x<0||b.y<0||b.width<8||b.height<8||b.x+b.width>doc.bounds.width||b.y+b.height>doc.bounds.height))return notify('Keep the whole walking area inside the scene.');if(b&&Math.min(b.width,b.height)<=2*navigation.clearance+navigation.cellSize*Math.SQRT2)return notify('Make the walking area larger, or reduce clearance / grid size.');if(b&&Math.ceil(b.width/navigation.cellSize)*Math.ceil(b.height/navigation.cellSize)>16384)return notify('The grid exceeds 16,384 cells. Increase grid size.');const next=structuredClone(game);if(navigation)next.navigation=navigation;else delete next.navigation;saveGame(next);};
  $('object-navigation-enabled').onchange=e=>{
   if(!e.target.checked)return saveNavigation(undefined);
   const x=Math.min(40,doc.bounds.width/10),height=Math.min(160,doc.bounds.height),width=doc.bounds.width-2*x,span=Math.min(width,height),cellSize=span>16*Math.SQRT2?16:8,clearance=Math.min(18,Math.max(0,(span-cellSize*Math.SQRT2)/4)),origins=game.participants.map(p=>doc.actors.find(a=>a.id===p.actor)?.transform?.y).filter(Number.isFinite),low=Math.max(0,Math.min(doc.bounds.height-height,(origins.length?Math.min(...origins):doc.bounds.height)-98));
   if(span<=cellSize*Math.SQRT2){e.target.checked=false;return notify('This scene is too small for a walking grid. Enlarge the scene first.');}
   saveNavigation({bounds:{x,y:low,width,height},cellSize,clearance,maxNodes:64});
  };
  if(game.navigation){$('object-navigation-area').onclick=()=>{const inputs=[...panel.querySelectorAll('[data-nav-area-field]')];if(!inputs.every(numberValid))return notify('Enter a valid walking area.');saveNavigation({...game.navigation,bounds:Object.fromEntries(inputs.map(el=>[el.dataset.navAreaField,Number(el.value)]))});};panel.querySelectorAll('[data-nav-field]').forEach(el=>el.onchange=()=>{if(!numberValid(el))return notify('Enter a number in the shown range.');saveNavigation({...game.navigation,[el.dataset.navField]:Number(el.value)});});}
  const participants=$('object-participants');
  participants.innerHTML=game.participants.map((p,i)=>{const pack=doc.packs[doc.actors.find(a=>a.id===p.actor).pack],rigSelect=(key,label,values,value)=>`<label class="field">${label}<select data-rig="${key}">${values.map(v=>option(v,v||'None',value)).join('')}</select></label>`,ids=pack.joints.map(j=>j.id);return `<fieldset data-rig-participant="${i}"><legend>${esc(doc.actors.find(a=>a.id===p.actor)?.name||p.actor)}</legend><div class="two-col">${[['skill','Catch skill',0,1,.05],['reaction','Reaction delay',0,1,.01],['speed','Run speed',10,400,5],['crouch','Pickup crouch',0,120,1]].map(([key,label,min,max,step])=>field('participant',key,label,p[key],min,max,step)).join('')}</div>${rigSelect('root','Root',pack.joints.filter(j=>j.parent===null).map(j=>j.id),p.root)}${rigSelect('head','Head',['',...ids],p.head||'')}<div class="two-col">${rigSelect('foot-left','Left foot',['',...ids],p.feet?.[0]||'')}${rigSelect('foot-right','Right foot',['',...ids],p.feet?.[1]||'')}</div>${rigSelect('upper','Upper arm',[...new Set(chains(pack).map(c=>c.upper))],p.chain.upper)}${rigSelect('lower','Forearm',[],p.chain.lower)}${rigSelect('end','Hand / wrist',[],p.chain.end)}${rigSelect('bend','Elbow bend',['1','-1'],String(p.bend))}<button data-rig-save class="text-button">Save rig joints</button></fieldset>`;}).join('');
  participants.querySelectorAll('[data-rig-participant]').forEach(row=>{const i=Number(row.dataset.rigParticipant),p=game.participants[i],pack=doc.packs[doc.actors.find(a=>a.id===p.actor).pack],possible=chains(pack),rig=k=>row.querySelector('[data-rig="'+k+'"]'),ends=(chosen=p.chain.end)=>{const values=possible.filter(c=>c.upper===rig('upper').value&&c.lower===rig('lower').value).map(c=>c.end);rig('end').innerHTML=values.map(v=>option(v,v,chosen)).join('');},lowers=(chosen=p.chain.lower)=>{const values=[...new Set(possible.filter(c=>c.upper===rig('upper').value).map(c=>c.lower))];rig('lower').innerHTML=values.map(v=>option(v,v,chosen)).join('');ends();};lowers();rig('upper').onchange=()=>lowers();rig('lower').onchange=()=>ends();
   row.querySelectorAll('[data-participant-field]').forEach(el=>el.onchange=()=>{if(!numberValid(el))return notify('Enter a number in the shown range.');const next=structuredClone(game);next.participants[i][el.dataset.participantField]=Number(el.value);saveGame(next);});
   row.querySelector('[data-rig-save]').onclick=()=>{const left=rig('foot-left').value,right=rig('foot-right').value;if(!!left!==!!right||left&&left===right)return notify('Choose two different feet, or leave both empty.');const next=structuredClone(game),part=next.participants[i];part.root=rig('root').value;part.chain={upper:rig('upper').value,lower:rig('lower').value,end:rig('end').value};part.bend=Number(rig('bend').value);if(rig('head').value)part.head=rig('head').value;else delete part.head;if(left&&right)part.feet=[left,right];else delete part.feet;saveGame(next);};
  });
 }
 return {render};
}
