const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const select=(id,label,values,value)=>`<label class="field">${label}<select id="${id}">${values.map(v=>{const [key,name]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${key===value?'selected':''}>${esc(name)}</option>`;}).join('')}</select></label>`;
export function createPlacementTools(){
 let index=0;
 return function render({fields,d,change,notify,rerender}){
  const bindings=d.poseBindings||[],variables=d.behaviorGraph?.variables||{},numeric=Object.keys(variables).filter(k=>typeof variables[k]==='number'),$=id=>fields.querySelector('#'+id),on=(id,fn)=>{const e=$(id);if(e)e.onchange=()=>fn(e.value);};
  index=Math.min(index,Math.max(0,bindings.length-1));const binding=bindings[index],actor=d.actors.find(a=>a.id===binding?.actor),pack=d.packs[actor?.pack];
  fields.innerHTML='<h3>Saved placements</h3><p class="note">Keep a body part or prop at a remembered position in the scene. Numeric variables store its horizontal and vertical position. A successful action can change those variables to leave an object in a new place.</p>'+select('placement-selected','Placement',bindings.map((b,i)=>[String(i),b.actor+' · '+b.joint]),String(index))+'<button id="placement-add" class="text-button">Add saved placement</button>'+(binding?select('placement-actor','Character',d.actors.map(a=>[a.id,a.name]),binding.actor)+select('placement-joint','Body part or prop',pack.joints.filter(j=>j.parent!==null).map(j=>j.id),binding.joint)+select('placement-x','Horizontal position variable',numeric,binding.x.variable)+select('placement-y','Vertical position variable',numeric,binding.y.variable)+`<p class="note">Initial position: ${esc(variables[binding.x.variable])}, ${esc(variables[binding.y.variable])}. Edit initial values in Stats.</p><fieldset><legend>Let these clips move the object</legend><p class="note">The saved position is suspended during selected clips, such as picking up or carrying the object.</p><div style="max-height:14rem;overflow:auto">${Object.keys(pack.clips).map((clip,i)=>`<label class="field"><span><input type="checkbox" id="placement-exclude-${i}" ${binding.excludeClips?.includes(clip)?'checked':''}> ${esc(clip)}</span></label>`).join('')}</div></fieldset><button id="placement-remove" class="text-button">Remove placement</button>`:'<p class="note">Add two numeric variables in Stats first, then choose the part to keep in place.</p>');
  const patch=fn=>change(next=>fn(next.poseBindings[index]));
  on('placement-selected',v=>{index=+v;rerender();});
  $('placement-add').onclick=()=>{if(numeric.length<2)return notify('Add two numeric position variables in Stats first.');if(bindings.length>=32)return notify('Keep at most 32 saved placements.');const candidate=d.actors.flatMap(a=>d.packs[a.pack].joints.filter(j=>j.parent!==null).map(j=>({actor:a.id,joint:j.id}))).find(c=>!bindings.some(b=>b.actor===c.actor&&b.joint===c.joint));if(!candidate)return notify('Every available part already has a saved placement.');index=bindings.length;change(next=>{(next.poseBindings??=[]).push({...candidate,space:'world',x:{variable:numeric[0]},y:{variable:numeric[1]},excludeClips:[]});next.requiredFeatures=[...new Set([...(next.requiredFeatures||[]),'pose-bindings'])];});};
  if(!binding)return;
  on('placement-actor',v=>{const joints=d.packs[d.actors.find(a=>a.id===v).pack].joints,joint=joints.find(j=>j.parent!==null&&!bindings.some((b,i)=>i!==index&&b.actor===v&&b.joint===j.id));if(!joint)return notify('Every part on that character already has a saved placement.');patch(b=>{b.actor=v;b.joint=joint.id;b.excludeClips=[];});});
  on('placement-joint',v=>{if(bindings.some((b,i)=>i!==index&&b.actor===binding.actor&&b.joint===v))return notify('That part already has a saved placement.');patch(b=>b.joint=v);});
  for(const axis of ['x','y'])on('placement-'+axis,v=>patch(b=>b[axis]={variable:v}));
  Object.keys(pack.clips).forEach((clip,i)=>$('placement-exclude-'+i).onchange=()=>{const checked=$('placement-exclude-'+i).checked;if(checked&&(binding.excludeClips||[]).length>=64){$('placement-exclude-'+i).checked=false;return notify('Choose at most 64 clips for each placement.');}patch(b=>{const clips=new Set(b.excludeClips||[]);if(checked)clips.add(clip);else clips.delete(clip);b.excludeClips=[...clips];});});
  $('placement-remove').onclick=()=>change(next=>{next.poseBindings.splice(index,1);if(!next.poseBindings.length)delete next.poseBindings;});
 };
}
