import './scene-tools.css';
import {createEmitter,removeGroup as removeSceneGroup,removeSceneEntity} from '../src/scene-graph.js';
import {createAttachmentTools} from './attachment-tools.js';
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<span class="material-symbols-outlined" aria-hidden="true">${name}</span>`;
const set=(path,value)=>({op:'set',path,value});
const lists={group:'groups',actor:'actors',prop:'props',emitter:'emitters'};
const layers=['background','characters','foreground'];
export function createSceneTools({getDocument,getFrame,getSelection,select,commit,editEntity,play,pause,isPlaying,getTime,setTime,getSceneTime=()=>0,setSceneTime=()=>{},contacts,behaviors,objects,flows,actorBehaviors}){
 const attachments=createAttachmentTools({getDocument,getFrame,commit});
 let contactActor=null;let effectPage='settings';const collapsed=new Set();
 const doc=()=>getDocument(),sel=()=>getSelection();
 const duration=()=>Math.min(180,Math.max(doc().ensemble?60:10,...doc().actors.map(a=>{const p=doc().packs[a.pack],state=p.states[a.inputs?.action]||p.states[p.initial];return p.clips[state.clip].duration;})));
 const entity=()=>sel()?.kind==='behavior'?doc():doc()[lists[sel()?.kind]]?.find(e=>e.id===sel()?.id);
 const groupOptions=(current,exclude=[])=>'<option value="">Scene root</option>'+(doc().groups||[]).filter(g=>!exclude.includes(g.id)).map(g=>`<option value="${esc(g.id)}" ${current===g.id?'selected':''}>${esc(g.name)}</option>`).join('');
 const field=(name,label,value,type='number',attrs='')=>`<label class="field">${label}<input id="scene-${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
 function patch(values){if(Object.entries(values).every(([key,value])=>(Object.is(entity()?.[key],value)||key==='depth'&&JSON.stringify(entity()?.[key])===JSON.stringify(value))))return;const s=sel(),collection=lists[s.kind],items=structuredClone(doc()[collection]),index=items.findIndex(e=>e.id===s.id);Object.assign(items[index],values);for(const key of Object.keys(items[index]))if(items[index][key]===undefined)delete items[index][key];const commands=[set([collection],items)];if(values.depth)commands.push(set(['requiredFeatures'],[...new Set([...(doc().requiredFeatures||[]),'scene-depth'])]));commit(commands);}
 function applyDocument(next){const commands=['groups','actors','props','emitters','lighting','ensemble','contacts','behaviorGraph','interactions','presentation','fluid','objects','objectGames','motionLayers','actorBehaviors','scroll','requiredFeatures'].filter(key=>next[key]!==undefined||doc()[key]!==undefined).map(key=>next[key]===undefined?{op:'delete',path:[key]}:set([key],next[key]));commit(commands);}
 function removeEmitter(id){applyDocument(removeSceneEntity(doc(),'emitter',id));}
 function removeGroup(id){applyDocument(removeSceneGroup(doc(),id));}
 function descendantIds(id){const result=[id];for(let i=0;i<result.length;i++)for(const g of doc().groups||[])if(g.parent===result[i]&&!result.includes(g.id))result.push(g.id);return result;}
 function choose(kind,id){if(kind!=='actor'||id!==contactActor)contactActor=null;select({kind,id});}
 function tree(target){
  const d=doc(),selected=sel(),groups=d.groups||[];const row=(kind,e,depth)=>`<div class="scene-tree-row ${e.hidden||e.enabled===false?'muted':''}" style="--depth:${depth}"><button data-scene-kind="${kind}" data-scene-id="${esc(e.id)}" class="${selected?.kind===kind&&selected.id===e.id?'active':''}">${icon(kind==='group'?'folder_open':kind==='actor'?'skeleton':kind==='prop'?'tune':'animation')}<span>${esc(e.name)}</span></button>${kind==='group'?`<button class="scene-fold" data-fold="${esc(e.id)}" aria-label="${collapsed.has(e.id)?'Expand':'Collapse'} ${esc(e.name)}" aria-expanded="${!collapsed.has(e.id)}">${collapsed.has(e.id)?'▸':'▾'}</button>`:''}<button class="scene-visibility" data-visible-kind="${kind}" data-visible-id="${esc(e.id)}" aria-label="${e.hidden?'Show':'Hide'} ${esc(e.name)}" title="${e.hidden?'Show':'Hide'} ${esc(e.name)}">${e.hidden?'○':'●'}</button></div>`;
  const content=(parent,depth)=>collapsed.has(parent)?'':groups.filter(g=>(g.parent||null)===parent).map(g=>row('group',g,depth)+content(g.id,depth+1)).join('')+['actors','props','emitters'].flatMap(collection=>(d[collection]||[]).filter(e=>(e.group||null)===parent).map(e=>row(collection==='actors'?'actor':collection==='props'?'prop':'emitter',e,depth))).join('');
  const roots=groups.filter(g=>!g.parent);let html=roots.map(g=>row('group',g,0)+content(g.id,1)).join('');
  for(const [label,test] of [['Scene / scenery',a=>a.layer&&a.layer!=='characters'||a.unlit],['Characters',a=>(!a.layer||a.layer==='characters')&&!a.unlit]]){const actors=d.actors.filter(a=>!a.group&&test(a));if(actors.length)html+=`<div class="scene-tree-label">${label}</div>`+actors.map(a=>row('actor',a,0)).join('');}
  html+=(d.props||[]).filter(p=>!p.group).map(p=>row('prop',p,0)).join('')+(d.emitters||[]).filter(e=>!e.group).map(e=>row('emitter',e,0)).join('');
  target.innerHTML=`<button id="scene-behaviors" class="text-button">${icon('animation')}Behaviors & interactions</button><div class="scene-tree-tools"><button id="scene-add-group" title="Add folder">${icon('folder_open')}Folder +</button><select id="scene-new-effect" aria-label="New effect type"><option value="flame">Flame</option><option value="smoke">Smoke</option><option value="embers">Embers</option></select><button id="scene-add-emitter" aria-label="Add effect">${icon('add')}</button></div>${d.ensemble?.type==='campfire'&&!d.emitters?.length?'<button id="scene-convert-legacy" class="text-button">Convert fire to effects</button>':''}<div class="scene-tree-list">${html||'<p class="note">The scene is empty.</p>'}</div><p class="scene-tree-note">Folders organize visibility. Select a character, then Animate to edit its body parts.</p>`;
  target.querySelector('#scene-behaviors').onclick=()=>choose('behavior','behavior');
  if(actorBehaviors){const b=document.createElement('button');b.id='scene-actor-behaviors';b.className='text-button';b.textContent='Character decisions';b.onclick=()=>choose('actor-behavior','actor-behavior');target.querySelector('#scene-behaviors').after(b);}
  if(flows){const button=document.createElement('button');button.id='scene-flows';button.className='text-button';button.textContent='Motion & website';button.onclick=()=>choose('motion-layers','motion-layers');target.querySelector('#scene-behaviors').after(button);}
  if(objects){const button=document.createElement('button');button.id='scene-objects';button.className='text-button';button.textContent='Objects & catching';button.onclick=()=>choose('objects','objects');target.querySelector('#scene-behaviors').after(button);}
  if(target.querySelector('#scene-convert-legacy'))target.querySelector('#scene-convert-legacy').onclick=()=>document.getElementById('convert-campfire').click();
  target.querySelectorAll('[data-scene-kind]').forEach(b=>b.onclick=()=>choose(b.dataset.sceneKind,b.dataset.sceneId));
  target.querySelectorAll('[data-fold]').forEach(b=>b.onclick=()=>{collapsed.has(b.dataset.fold)?collapsed.delete(b.dataset.fold):collapsed.add(b.dataset.fold);tree(target);});
  target.querySelectorAll('[data-visible-kind]').forEach(b=>b.onclick=()=>{const collection=lists[b.dataset.visibleKind],items=doc()[collection],index=items.findIndex(e=>e.id===b.dataset.visibleId);commit([set([collection,index,'hidden'],!items[index].hidden)]);});
  target.querySelector('#scene-add-group').onclick=()=>{const id='folder-'+Date.now().toString(36),parent=sel()?.kind==='group'?sel().id:null;commit([set(['groups'],[...(doc().groups||[]),{id,name:'New folder',parent}]),set(['requiredFeatures'],[...new Set([...(doc().requiredFeatures||[]),'scene-groups'])])]);if(doc().groups?.some(g=>g.id===id))choose('group',id);};
  target.querySelector('#scene-add-emitter').onclick=()=>{const type=target.querySelector('#scene-new-effect').value,id=type+'-'+Date.now().toString(36),effect=createEmitter(type,id);effect.x=doc().bounds.width/2;effect.y=doc().bounds.height*.7;if(sel()?.kind==='group')effect.group=sel().id;commit([set(['emitters'],[...(doc().emitters||[]),effect]),set(['requiredFeatures'],[...new Set([...(doc().requiredFeatures||[]),'procedural-emitters'])])]);if(doc().emitters?.some(e=>e.id===id))choose('emitter',id);};
 }
 function inspector(target){
  const e=entity(),s=sel();if(s?.kind==='actor-behavior'){actorBehaviors.render(target);return;}if(s?.kind==='motion-layers'){flows.render(target);return;}if(s?.kind==='objects'){objects.render(target);return;}if(s?.kind==='behavior'){behaviors.render(target);return;}if(!e){target.innerHTML='<p class="note">Select a scene item.</p>';return;}
  if(s.kind==='actor'&&contactActor===e.id&&contacts){target.innerHTML='<button id="contact-back" class="text-button">← Actor settings</button><div id="contact-panel"></div>';target.querySelector('#contact-back').onclick=()=>{contactActor=null;inspector(target);};contacts.render(target.querySelector('#contact-panel'),e);return;}
  const group=s.kind==='group',effect=s.kind==='emitter';
  const placement=`<label class="field">${group?'Parent folder':'Folder'}<select id="scene-group">${groupOptions(group?e.parent:e.group,group?descendantIds(e.id):[])}</select></label>${group?'':`<label class="field">Layer<select id="scene-layer" ${effect&&e.actor?'disabled':''}>${layers.map(layer=>`<option ${layer===(effect&&e.actor?(doc().actors.find(a=>a.id===e.actor)?.layer||'characters'):(e.layer||(s.kind==='prop'?'background':'characters')))?'selected':''}>${layer}</option>`).join('')}</select></label>${effect&&e.actor?'<p class="note">Layer follows the attached actor.</p>':''}`}<label class="face-auto"><input id="scene-visible" type="checkbox" ${e.hidden?'':'checked'}>Visible</label>`;
  target.innerHTML=`<div class="inspector-heading">${esc(e.name)}<small>${group?'Folder':effect?'Effect':s.kind==='actor'?'Scene actor':'Prop'}</small></div>${field('name','Name',e.name,'text','maxlength="100"')}${effect?`<nav class="prop-tabs"><button id="effect-settings" class="active">Effect</button><button id="effect-placement">Placement</button></nav><div id="effect-fields"></div>`:placement}${!group&&!effect?`<button id="scene-edit-entity" class="text-button">${icon('edit')}${s.kind==='actor'?'Animate character':'Edit prop'}</button><p class="note">${s.kind==='actor'?'Body parts and character clips stay in the Character workspace.':'Props keep their shape and collision controls.'}</p>`:''}${group?'<p class="note">Folder visibility affects all contents. Removing a folder keeps its contents in the parent folder.</p><button id="scene-delete-group" class="text-button">Remove folder</button>':''}${effect?'<button id="scene-delete-emitter" class="text-button">Remove effect</button>':''}`;
  target.querySelector('#scene-name').onchange=ev=>patch({name:ev.target.value});
  function wirePlacement(){target.querySelector('#scene-group').onchange=ev=>patch(group?{parent:ev.target.value||null}:{group:ev.target.value||undefined});if(!group)target.querySelector('#scene-layer').onchange=ev=>patch({layer:ev.target.value});target.querySelector('#scene-visible').onchange=ev=>patch({hidden:!ev.target.checked});}
  if(!effect)wirePlacement();
  if(!group&&!effect){
   const joints=s.kind==='actor'?doc().packs[e.pack].joints:[],mode=e.depth?(Object.hasOwn(e.depth,'value')?'fixed':'joint'):'legacy';
   target.insertAdjacentHTML('beforeend',`<h3>Scene depth</h3><label class="field">Overlap order<select id="scene-depth-mode"><option value="legacy" ${mode==='legacy'?'selected':''}>Keep scene order</option><option value="fixed" ${mode==='fixed'?'selected':''}>Fixed floor depth</option>${s.kind==='actor'?`<option value="joint" ${mode==='joint'?'selected':''}>Follow a joint</option>`:''}</select></label>${mode==='fixed'?field('depth-value','Floor depth / scene Y',e.depth.value,'number','min="-10000" max="10000" step="1"'):mode==='joint'?`<label class="field">Depth anchor<select id="scene-depth-joint">${joints.map(j=>`<option value="${esc(j.id)}" ${j.id===e.depth.joint?'selected':''}>${esc(j.id)}</option>`).join('')}</select></label>`+field('depth-offset','Floor offset / local Y',e.depth.offset??0,'number','min="-4096" max="4096" step="1"'):''}<p class="note">Higher floor depth draws in front of other depth-enabled items in this layer. Use a ground anchor that stays level while jumping or bending. Folders do not change depth.</p>`);
   target.querySelector('#scene-depth-mode').onchange=ev=>patch({depth:ev.target.value==='legacy'?undefined:ev.target.value==='fixed'?{value:e.depth?.value??e.groundY??(s.kind==='prop'?e.y+e.height/2:e.transform.y)}:{joint:joints[0].id,offset:0}});
   if(mode==='fixed')target.querySelector('#scene-depth-value').onchange=ev=>patch({depth:{value:+ev.target.value}});
   if(mode==='joint'){target.querySelector('#scene-depth-joint').onchange=ev=>patch({depth:{...e.depth,joint:ev.target.value}});target.querySelector('#scene-depth-offset').onchange=ev=>patch({depth:{...e.depth,offset:+ev.target.value}});}
  }

  if(s.kind==='prop'){const panel=document.createElement('div');panel.id='scene-attachments';target.append(panel);attachments.render(panel,e.id);}
  if(s.kind==='actor'&&contacts){const b=document.createElement('button');b.id='scene-contacts';b.className='text-button';b.innerHTML=icon('link')+'Contacts & grips';b.onclick=()=>{contactActor=e.id;inspector(target);};target.append(b);}
  if(group)target.querySelector('#scene-delete-group').onclick=()=>removeGroup(e.id);
  if(!group&&!effect)target.querySelector('#scene-edit-entity').onclick=()=>editEntity(s);
  if(effect){
   const fields=target.querySelector('#effect-fields');
   const show=(page=effectPage)=>{effectPage=page;
    target.querySelector('#effect-settings').classList.toggle('active',page==='settings');target.querySelector('#effect-placement').classList.toggle('active',page==='placement');
    if(page==='placement'){
     fields.innerHTML=placement+`<label class="field">Attach to actor<select id="scene-anchor"><option value="">Scene coordinates</option>${doc().actors.map(a=>`<option value="${esc(a.id)}" ${e.actor===a.id?'selected':''}>${esc(a.name)}</option>`).join('')}</select></label><div class="two-col">${field('x',e.actor?'Local X':'Position X',e.x,'number','min="-4096" max="8192"')}${field('y',e.actor?'Local Y':'Position Y',e.y,'number','min="-4096" max="8192"')}</div>`;wirePlacement();fields.querySelector('#scene-anchor').onchange=ev=>patch({actor:ev.target.value||undefined});for(const name of ['x','y'])fields.querySelector('#scene-'+name).onchange=ev=>patch({[name]:+ev.target.value});
    }else{
     fields.innerHTML=`<label class="face-auto"><input id="scene-enabled" type="checkbox" ${e.enabled?'checked':''}>Emission on</label><div class="two-col">${field('rate',e.type==='flame'?'Flutter / second':'Births / second',e.rate,'number','min="0" max="60" step=".1"')}${field('randomness','Randomness',e.randomness,'number','min="0" max="1" step=".05"')}${field('lifetime','Lifetime, seconds',e.lifetime,'number','min=".1" max="30" step=".1"')}${field('size','Size',e.size,'number','min=".5" max="300" step="1"')}${field('speed','Speed',e.speed,'number','min="0" max="300" step="1"')}${field('spread','Spread',e.spread,'number','min="0" max="500" step="1"')}${field('opacity','Opacity',e.opacity,'number','min="0" max="1" step=".05"')}${field('color','Color',e.color,'color')}${field('seed','Seed',e.seed,'number','min="0" max="4294967295" step="1"')}${field('maxParticles','Particle limit',e.maxParticles,'number','min="1" max="128" step="1"')}</div><label class="face-auto"><input id="scene-light-source" type="checkbox" ${doc().lighting?.emitter===e.id?'checked':''}>Drive the scene point light</label><p class="note">${e.type==='flame'?'Frequency sets the flame flutter.':'Frequency sets births per second.'} Zero turns it off. The same seed repeats the same variation.</p>`;
     if(e.type==='flame')for(const name of ['lifetime','speed','maxParticles']){fields.querySelector('#scene-'+name).closest('label').classList.add('hidden');fields.querySelector('#scene-'+name).disabled=true;}
     for(const name of ['rate','randomness','lifetime','size','speed','spread','opacity','color','seed','maxParticles'])fields.querySelector('#scene-'+name).onchange=ev=>patch({[name]:name==='color'?ev.target.value:+ev.target.value});fields.querySelector('#scene-enabled').onchange=ev=>patch({enabled:ev.target.checked});
     fields.querySelector('#scene-light-source').onchange=ev=>{const light={...doc().lighting};if(ev.target.checked){light.emitter=e.id;light.type='point';light.enabled=true;}else delete light.emitter;commit([set(['lighting'],light)]);};
    }
   };target.querySelector('#effect-settings').onclick=()=>show('settings');target.querySelector('#effect-placement').onclick=()=>show('placement');target.querySelector('#scene-delete-emitter').onclick=()=>removeEmitter(e.id);show();
  }
 }
 function bottom(target){const e=entity(),effect=sel()?.kind==='emitter';target.innerHTML=`<div class="scene-bottom"><div><strong>${effect?'Procedural effect':sel()?.kind==='group'?'Scene folder':'Scene organization'}</strong><span>${esc(e?.name||'Select an item')}</span></div>${effect?`<button id="effect-preview">${icon(isPlaying()?'pause':'play_arrow')}${isPlaying()?'Pause':'Preview effect'}</button><label>Frequency<input id="effect-rate" type="number" min="0" max="60" step=".1" value="${e?.rate??0}"></label><label>Randomness<input id="effect-randomness" type="number" min="0" max="1" step=".05" value="${e?.randomness??0}"></label><label class="effect-clock">Preview time<input id="effect-time" type="range" min="0" max="60" step=".01" value="${Math.min(60,getTime())}" aria-label="Effect preview time"></label><p>Seeded motion. No generated keyframes.</p>`:`<button id="scene-preview">${icon(isPlaying()?'pause':'play_arrow')}${isPlaying()?'Pause scene':'Play scene'}</button>${doc().presentation==='live'?'<span>Live illustration · runs until paused</span>':''}<label class="effect-clock" ${doc().presentation==='live'?'hidden':''}>Scene time<input id="scene-time" type="range" min="0" max="${duration()}" step=".04" value="${Math.min(duration(),getSceneTime())}" aria-label="Whole scene preview time"></label><p>Preview all characters and props together. Animate a character to edit its keys.</p>`}</div>`;if(!effect){target.querySelector('#scene-time').oninput=ev=>{pause();setSceneTime(+ev.target.value);target.querySelector('#scene-preview').innerHTML=icon('play_arrow')+'Play scene';};target.querySelector('#scene-preview').onclick=()=>{isPlaying()?pause():play();bottom(target);};}if(effect&&e){target.querySelector('#effect-time').oninput=ev=>{pause();setTime(+ev.target.value);target.querySelector('#effect-preview').innerHTML=icon('play_arrow')+'Preview effect';};target.querySelector('#effect-preview').onclick=()=>{isPlaying()?pause():play();bottom(target);};for(const name of ['rate','randomness'])target.querySelector('#effect-'+name).onchange=ev=>patch({[name]:+ev.target.value});}}
 return {tree,inspector,bottom,entity,contactsActive:()=>sel()?.kind==='actor'&&sel().id===contactActor};
}
