import {mountScene} from '../src/browser.js';

/** Host-owned quest and dialogue. Performances use the public game API. */
export function mountGameDemo(scene,{playing=true,onPlayingChange=()=>{},onEvent=()=>{},onError=()=>{}}={}){
 const $=id=>document.getElementById(id),art=$('demo-art'),saveKey='posecraft.corner-shop.game-state.v1';let player,sequence,session=0,disposed=false,light=false,repaired=false,opened=false;
 art.classList.add('corner-game');art.innerHTML='<div id="corner-scene"></div><button id="sign" class="corner-sign" aria-label="Repair the shop sign">CORNER SH—P</button><button id="shop-lamp" class="corner-lamp" aria-label="Switch the shop light" aria-pressed="false" title="Switch the light"></button><button id="pet-rusty" class="corner-rusty" aria-label="Play with Rusty" title="Play with Rusty"></button><div id="quest" class="corner-quest" role="status">The shop sign needs a little help.</div>';
 $('demo-controls').innerHTML='<div class="demo-actions corner-actions"><button id="repair">Fix the sign</button><button id="encourage">Say hello</button><button id="explore">Explore the yard</button><button id="play-rusty">Play with Rusty</button><button id="lights">Switch light</button><button id="cancel" disabled>Stop</button></div><div class="corner-dialogue" aria-live="polite"><span id="speech">Choose an interaction, or tap something in the scene.</span><button id="continue" hidden>Continue</button></div>';
 $('demo-controls').querySelector('.corner-actions').insertAdjacentHTML('beforeend','<button id="save-game">Save game</button><button id="restore-game">Restore game</button>');
 $('demo-scrub').hidden=true;$('demo-caption').textContent='Fix the sign · tap Rusty · switch the light';$('demo-status').textContent='Ready · choose an interaction';
 function speech({actor,text,signal}){
  $('speech').textContent=`${actor==='friend'?'Rusty':'Ona'}: ${text}`;$('continue').hidden=false;
  return new Promise((resolve,reject)=>{const cleanup=()=>{$('continue').hidden=true;$('continue').removeEventListener('click',done);signal.removeEventListener('abort',cancel);};const done=()=>{cleanup();resolve();},cancel=()=>{cleanup();reject(Object.assign(new Error('Dialogue cancelled.'),{name:'AbortError'}));};$('continue').addEventListener('click',done);signal.addEventListener('abort',cancel,{once:true});if(signal.aborted)cancel();});
 }
 function stop(){session++;sequence?.cancel();sequence=null;player?.actor('shopkeeper').cancel();player?.actor('friend').cancel();$('cancel').disabled=true;}
 function cue(message,run){
  stop();const current=session;playing=true;player.play();onPlayingChange(true);$('cancel').disabled=false;$('speech').textContent=message;$('demo-status').textContent=message;
  Promise.resolve().then(()=>{if(disposed||current!==session)return;return run(current);}).catch(error=>{if(!disposed&&current===session&&error.name!=='AbortError'){$('demo-status').textContent=error.message;onError(error);}}).finally(()=>{if(!disposed&&current===session)$('cancel').disabled=true;});
 }
 function event(e){onEvent(e);if(e.type==='actor.arrived')$('demo-caption').textContent='Ona reached her destination';if(e.type==='actor.command.cancelled')$('demo-caption').textContent='Changing plans…';}
 async function setLight(value){await player.object('shop-light').set('enabled',value);if(disposed)return;light=value;$('shop-lamp').classList.toggle('lit',value);$('shop-lamp').setAttribute('aria-pressed',String(value));}
 function repair(){cue('Ona is coming to inspect your repair.',async current=>{
  repaired=true;$('sign').textContent='CORNER SHOP';$('quest').textContent='Sign repaired. Let’s show Ona.';
  await Promise.all([player.actor('shopkeeper').moveTo('shop.front'),player.actor('shopkeeper').lookAt('shop.sign')]);if(disposed||current!==session)return;
  sequence=player.sequence([{actor:'shopkeeper',do:'inspect'},{actor:'shopkeeper',react:'success'},{actor:'shopkeeper',say:'You fixed it! Shall we open the shop?'}]);await sequence.finished;if(disposed||current!==session)return;await setLight(true);if(disposed||current!==session)return;opened=true;await player.actor('friend').react('success');if(disposed||current!==session)return;$('quest').textContent='The shop is open.';$('speech').textContent='Shop open! Try the light, explore, or play with Rusty.';$('demo-status').textContent='Quest complete · both characters responded.';
 });}
 function greet(){cue('Ona and Rusty say hello.',async()=>{await Promise.all([player.actor('shopkeeper').react('encourage'),player.actor('friend').react('success')]);});}
 function explore(){cue('Ona explores the yard, then returns to the shop.',async()=>{sequence=player.sequence([{actor:'shopkeeper',moveTo:'home'},{actor:'shopkeeper',lookAt:'friend'},{actor:'shopkeeper',do:'wave'},{actor:'shopkeeper',moveTo:'shop.front'},{actor:'shopkeeper',do:'bow'}]);await sequence.finished;});}
 function pet(){cue('Rusty has something to show you.',async current=>{await Promise.all([player.actor('shopkeeper').lookAt('friend'),player.actor('friend').do('paw')]);if(disposed||current!==session)return;await player.actor('friend').do('bounce');if(disposed||current!==session)return;await player.actor('friend').react('success');});}
 function lights(){cue(light?'Who turned out the light?':'The shop light is back on.',async current=>{await setLight(!light);if(disposed||current!==session)return;$('quest').textContent=light?(opened?'The shop is open.':'The light works. The sign still needs fixing.'):'The light is off. Tap the lamp to bring it back.';await Promise.all([player.actor('shopkeeper').react(light?'success':'surprise'),player.actor('friend').react(light?'success':'surprise')]);});}
 function save(){cue('Saving the game.',async current=>{const state=await player.snapshot();if(disposed||current!==session)return;localStorage.setItem(saveKey,JSON.stringify({format:'posecraft-corner-save',version:1,quest:{repaired,opened},scene:state}));$('demo-status').textContent='Game saved · reload and choose Restore game.';$('speech').textContent='Saved character positions, shop light and quest progress.';});}
 function restore(){cue('Restoring the game.',async current=>{const saved=JSON.parse(localStorage.getItem(saveKey)||'null');if(saved?.format!=='posecraft-corner-save'||saved.version!==1||typeof saved.quest?.repaired!=='boolean'||typeof saved.quest?.opened!=='boolean')throw Error('No compatible corner-shop save is available.');await player.restore(saved.scene);if(disposed||current!==session)return;repaired=saved.quest.repaired;opened=saved.quest.opened;light=player.controller.frame().objects.find(o=>o.id==='shop-light').enabled;$('sign').textContent=repaired?'CORNER SHOP':'CORNER SH—P';$('shop-lamp').classList.toggle('lit',light);$('shop-lamp').setAttribute('aria-pressed',String(light));$('quest').textContent=opened?'The shop is open.':repaired?'Sign repaired. Let’s show Ona.':'The shop sign needs a little help.';$('speech').textContent='Game restored. Interrupted dialogue stays cancelled.';$('demo-status').textContent='Game restored · quest progress belongs to the host game.';});}
 $('save-game').onclick=save;$('restore-game').onclick=restore;
 $('repair').onclick=$('sign').onclick=repair;$('encourage').onclick=greet;$('explore').onclick=explore;$('play-rusty').onclick=$('pet-rusty').onclick=pet;$('lights').onclick=$('shop-lamp').onclick=lights;$('cancel').onclick=()=>{stop();$('speech').textContent='Stopped. Choose another interaction.';$('demo-status').textContent='Sequence cancelled.';};
 player=mountScene($('corner-scene'),scene,{execution:'worker',autoplay:playing,onSpeechRequest:speech,onEvent:event,onError});window.gameDemo={player,scene};
 if(playing)greet();
 return {play(){playing=true;player.play();},pause(){playing=false;player.pause();},reset(){stop();player.reset();light=false;repaired=false;opened=false;$('shop-lamp').classList.remove('lit');$('shop-lamp').setAttribute('aria-pressed','false');$('sign').textContent='CORNER SH—P';$('quest').textContent='The shop sign needs a little help.';$('speech').textContent='Choose an interaction, or tap something in the scene.';$('demo-status').textContent='Ready · choose an interaction';$('demo-caption').textContent='Fix the sign · tap Rusty · switch the light';},dispose(){if(disposed)return;stop();disposed=true;player.dispose();art.classList.remove('corner-game');delete window.gameDemo;}};
}
