import ona from './characters/ona.json' with {type:'json'};
import {addSpatialRig,addOnaArmJoints} from '../src/character-rigs.js';
import {poseDefaults} from '../src/spatial.js';
import {solveContact} from '../src/contacts.js';

export const handoffDuration=10;
export const handoffReviews=[{id:'offer',label:'An invitation',time:2.4},{id:'receive',label:'Both hands meet',time:3.8},{id:'admire',label:'A closer look',time:5.6},{id:'return',label:'Passing it back',time:7.8}];
const smooth=x=>{x=Math.max(0,Math.min(1,x));return x*x*(3-2*x);};
const mix=(a,b,q)=>({x:a.x+(b.x-a.x)*q,y:a.y+(b.y-a.y)*q});
function follow(t,stops){let i=0;while(i<stops.length-2&&t>stops[i+1][0])i++;const [a,p]=stops[i],[b,q]=stops[i+1];return mix(p,q,smooth((t-a)/(b-a)));}
const chains={giver:{upper:'rightArm',lower:'rightForearm',end:'rightWrist'},recipient:{upper:'leftArm',lower:'leftForearm',end:'leftWrist'}};
/** The owner's arm is authored. Only the receiving hand uses a scene contact. */
export function handoffPose(pack,role,time){const t=Math.max(0,Math.min(10,time)),giver=role==='giver',rest={x:giver?38:-38,y:22},meeting={x:giver?50:-50,y:0},admire={x:-41,y:15},stops=giver?[[0,rest],[1,rest],[2.7,meeting],[4.3,meeting],[5.2,rest],[6.1,rest],[7.5,meeting],[8.3,meeting],[9.6,rest],[10,rest]]:[[0,rest],[1.6,rest],[3.5,meeting],[4.25,meeting],[5.2,admire],[6,admire],[7.5,meeting],[8.3,meeting],[9.6,rest],[10,rest]],base=poseDefaults(pack),target=follow(t,stops);
 base['head.yaw']=(giver?18:-18)+(giver?0:7*Math.sin(Math.PI*smooth((t-4.2)/1.1)));
 base['head.rotation']=(giver?-3:3)+(giver?0:5*smooth((t-4.3)/.7)*(1-smooth((t-6)/.8)));
 base['eyes.x']=giver?2:-2;base['eyes.y']=giver?0:2*smooth((t-4.3)/.7)*(1-smooth((t-6)/.8));
 for(const blink of giver?[.6,5.7,9.1]:[1.1,6.2,9.4])if(Math.abs(t-blink)<.12)base['eyes.opacity']=.08+.92*smooth(Math.abs(t-blink)/.12);
 base[chains[role].upper+'.z']=8;
 const solved=solveContact(pack,base,chains[role],target,{bend:giver?-1:1,keepOrientation:false}).pose;
 // Keep the little parcel upright while either hand carries it.
 const arm=solved[chains[role].upper+'.rotation'],forearm=solved[chains[role].lower+'.rotation'];solved[chains[role].end+'.rotation']=-(arm+forearm);
 return solved;
}
function clip(pack,role){const defaults=poseDefaults(pack),samples=Array.from({length:241},(_,i)=>[i/24,handoffPose(pack,role,i/24)]),tracks={};for(const key of Object.keys(defaults)){const values=samples.map(([t,p])=>[t,Math.round(p[key]*1e5)/1e5]);if(values.some(([,v])=>Math.abs(v-defaults[key])>1e-5)){const compact=[];for(let i=0;i<values.length;i++)if(i===0||i===values.length-1||values[i][1]!==values[i-1][1]||values[i][1]!==values[i+1][1])compact.push(values[i]);tracks[key]=compact;}}return {duration:10,loop:false,tracks};}
const collider=(width,height)=>({enabled:false,x:0,y:0,width,height,bounce:.2,friction:.5});
function prop(id,name,x,y,width,height,fill,extra={}){return {id,name,x,y,width,height,rotation:0,fill,layer:'background',depth:{value:1},collider:collider(width,height),...extra};}
function backdrop(){const parts=[['window-frame','M76 100Q76 61 119 61H190Q229 61 229 100V244H76Z','#c5d4cc'],['window','M86 103Q86 72 120 72H188Q219 72 219 103V234H86Z','#b6d8df'],['window-glow','M95 108L193 79H211L108 228H95Z','#dceae4'],['window-cross','M147 73H154V234H147ZM87 151H220V157H87Z','#f0eee1'],['plant-pot','M635 305H687L679 351H643Z','#cc9678'],['plant-stem','M659 309Q666 250 658 211L661 211Q675 258 664 309Z','#648575'],['plant-left','M661 268Q611 261 621 228Q654 230 661 268Z','#819d87'],['plant-right','M665 253Q706 248 709 210Q674 211 665 253Z','#70917c'],['plant-top','M658 229Q628 209 642 179Q669 192 658 229Z','#91a78e'],['floor-shadow-left','M228 386Q310 369 392 386Q310 402 228 386Z','#c1bbaa'],['floor-shadow-right','M408 386Q490 369 572 386Q490 402 408 386Z','#c1bbaa']].map(([id,d,fill])=>({id,joint:'root',d,fill,stroke:'none',strokeWidth:0}));return {name:'A quiet room',joints:[{id:'root',parent:null,x:0,y:0,rotation:0,min:0,max:0,length:0}],parts,clips:{still:{duration:10,loop:true,tracks:{}}},inputs:{},states:{still:{clip:'still',speed:1}},initial:'still',transitions:[]};}
export function createHandoff(){const pack=structuredClone(ona.packs.ona);addSpatialRig(pack,'ona',{studies:false});addOnaArmJoints(pack);pack.clips.give=clip(pack,'giver');pack.clips.receive=clip(pack,'recipient');
 const source=ona.actors[0],actors=['giver','recipient'].map((id,i)=>({...structuredClone(source),id,name:i?'Moss':'Clover',pack:'ona',group:'friends',transform:{x:i?490:310,y:290,rotation:0,scale:1.8},inputs:{...source.inputs,action:'idle',emotion:'happy',hair:i?'curls':'bob'},appearance:{...source.appearance,clothing:i?'#e4b370':'#7cab9f',hair:i?'#805130':'#5a403b',eyes:i?'#547875':'#776140'},behavior:{mode:'animated',autoFace:false}}));
 const recipe=(actor,clip)=>({actor,variants:[{id:clip,clip,weight:1,speed:{min:1,max:1}}],success:{base:1,modifiers:[]},onStart:[],onSuccess:[],onFailure:[]});
 const transfer=(actor,from,joint)=>({type:'object',command:{type:'transfer',object:'gift',actor,from,joint,maxDistance:.5}});
 return {schemaVersion:1,kind:'scene',id:'a-little-handoff',name:'A little handoff',revision:0,presentation:'live',bounds:{width:800,height:450},requiredFeatures:['appearance-variants','expressions','scene-groups','spatial-rig','scene-objects','scene-depth','contacts','contact-targets','prop-attachments','behavior-graphs','action-variations'],packs:{ona:pack,room:backdrop()},groups:[{id:'friends',name:'Friends',parent:null},{id:'setting',name:'Room',parent:null},{id:'parcel',name:'The shared gift',parent:null}],actors:[{id:'room',name:'Room details',pack:'room',group:'setting',layer:'background',depth:{value:10},transform:{x:0,y:0,rotation:0,scale:1},inputs:{},behavior:{mode:'animated',autoFace:false}},...actors],
 props:[prop('wall','Warm wall',400,225,800,450,'#eee8dc',{group:'setting'}),prop('floor','Floor',400,401,800,98,'#d4cebd',{group:'setting'}),prop('skirting','Skirting',400,350,800,5,'#d8cdbb',{group:'setting'}),...[["gift-box","Gift box",0,0,26,22,'#487d75'],['gift-lid','Gift lid',0,-9,29,6,'#61978b'],['gift-ribbon','Ribbon',0,0,5,22,'#f4d990'],['gift-bow-left','Bow left',-4,-14,9,5,'#f4d990'],['gift-bow-right','Bow right',4,-14,9,5,'#f4d990']].map(([id,name,offsetX,offsetY,w,h,fill],i)=>prop(id,name,0,0,w,h,fill,{group:'parcel',layer:'characters',depth:{value:391+i*.01},attachment:{type:'object',object:'gift',offsetX,offsetY,rotation:0,inheritRotation:false}}))],
 objects:[{id:'gift',name:'Shared parcel',shape:'circle',x:378.4,y:329.6,radius:9,fill:'#487d75',mass:.2,depth:390,owner:{actor:'giver',joint:'rightWrist'}}],objectPhysics:{gravity:600,floorY:390,actorCollisions:false},
 contacts:[{id:'receive-gift',name:'Receive the parcel',actor:'recipient',chain:chains.recipient,target:{type:'object',object:'gift'},bend:1,weight:1,enabled:true,start:3,end:4,fadeIn:.4,fadeOut:0,clip:'receive',keepOrientation:true},{id:'return-gift',name:'Return the parcel',actor:'giver',chain:chains.giver,target:{type:'object',object:'gift'},bend:-1,weight:1,enabled:true,start:7,end:8,fadeIn:.4,fadeOut:0,clip:'give',keepOrientation:true}],
 behaviorGraph:{seed:20260918,initial:'offer',variables:{exchanges:0},handlers:[{event:'object-attached',actions:[{type:'add',variable:'exchanges',value:.5}]}],activities:{giving:recipe('giver','give'),receiving:recipe('recipient','receive')},states:{offer:{actions:[{type:'perform',activity:'giving'},{type:'perform',activity:'receiving'}]},receive:{actions:[transfer('recipient','giver','leftWrist')]},return:{actions:[transfer('giver','recipient','rightWrist')]}},edges:[{id:'give-at-contact',from:'offer',to:'receive',after:{min:4,max:4},weight:1},{id:'return-at-contact',from:'receive',to:'return',after:{min:4,max:4},weight:1},{id:'repeat',from:'return',to:'offer',after:{min:2,max:2},weight:1}]}};
}
