import React, { StrictMode, useMemo, useRef, useState, useEffect } from 'react';
import { createRoot } from 'react-dom/client';
import { Posecraft } from '../src/react.js';
import { SoundEffects } from '../src/audio.js';
import { library } from './library.js';
import '../studio/style.css';

const title = s => s[0].toUpperCase()+s.slice(1);
const Icon = ({name}) => <span className="material-symbols-outlined" aria-hidden="true">{name}</span>;
function Demo() {
  const [character,setCharacter]=useState('ona'),[action,setAction]=useState('idle'),[emotion,setEmotion]=useState('neutral'),[hair,setHair]=useState('none'),[colors,setColors]=useState({});
  const [mounted,setMounted]=useState(true),[event,setEvent]=useState('Drag the card. Watch the character lean and settle.'),[width,setWidth]=useState(500),[policy,setPolicy]=useState('system');
  const [propsOn,setPropsOn]=useState(false);
  const [mode,setMode]=useState('animated'),[resistance,setResistance]=useState(.65),[strategy,setStrategy]=useState('auto'),[autoFace,setAutoFace]=useState(true),[soundOn,setSoundOn]=useState(false);
  const sound=useRef(null);useEffect(()=>{sound.current=new SoundEffects();return()=>sound.current.dispose();},[]);
  const host=useRef(null),player=useRef(null),drag=useRef(null),position=useRef({x:0,y:0});
  const scene=useMemo(()=>{const d=structuredClone(library[character]);d.actors[0].appearance=colors;if(propsOn)d.props=[{id:'platform',name:'Platform',x:d.bounds.width/2,y:d.bounds.height-15,width:240,height:20,rotation:0,fill:'#b9c8c2',collider:{enabled:true,width:240,height:20,x:0,y:0,friction:.75,bounce:.1}},{id:'ramp',name:'Ramp',x:d.bounds.width*.8,y:d.bounds.height*.65,width:100,height:16,rotation:-20,fill:'#d6c4aa',collider:{enabled:true,width:100,height:16,x:0,y:0,friction:.6,bounce:.1}}];return d;},[character,colors,propsOn]);
  const pack=scene.packs[character];
  const behavior=useMemo(()=>({[character]:{mode,resistance,strategy,autoFace}}),[character,mode,resistance,strategy,autoFace]);
  function interact(type){const controller=player.current?.controller;if(!controller)return;if(['drop','toss'].includes(type)&&mode==='animated'){const next=type==='drop'?'protective':'floating';setMode(next);controller.setBehavior(character,{...behavior[character],mode:next});}player.current.interact(character,type);}
  async function toggleSound(){if(sound.current.enabled){sound.current.mute();setSoundOn(false);}else{const enabled=await sound.current.unlock();setSoundOn(enabled);if(enabled)sound.current.handle({type:'interaction',interaction:'pet'});}}
  const move=(x,y)=>{position.current={x,y};host.current.style.transform=`translate(${x}px,${y}px)`;};
  function chooseCharacter(id){setCharacter(id);setMode('animated');setAutoFace(true);setAction('idle');setEmotion('neutral');setHair('none');setColors({});move(0,0);}
  return <main className="react-page"><header className="demo-heading"><a href="./"><Icon name="arrow_back"/> Studio</a><strong>Posecraft playground</strong><select aria-label="Demo motion" value={policy} onChange={e=>setPolicy(e.target.value)}><option value="system">System motion</option><option value="full">Motion on</option><option value="reduced">Still preview</option></select></header>
    <div className="demo-toolbar"><label>Character <select aria-label="Demo character" value={character} onChange={e=>chooseCharacter(e.target.value)}>{Object.entries(library).map(([id,d])=><option key={id} value={id}>{d.name}</option>)}</select></label><label>Action <select aria-label="Demo action" value={action} onChange={e=>setAction(e.target.value)}>{Object.keys(pack.clips).map(id=><option key={id} value={id}>{title(id)}</option>)}</select></label><label>Emotion <select aria-label="Demo emotion" value={emotion} onChange={e=>{setAutoFace(false);setEmotion(e.target.value);}}>{pack.inputs.emotion.options.map(id=><option key={id} value={id}>{title(id)}</option>)}</select></label>
    {pack.inputs.hair&&<label>Hair <select aria-label="Demo hair" value={hair} onChange={e=>setHair(e.target.value)}>{pack.inputs.hair.options.map(id=><option key={id} value={id}>{title(id)}</option>)}</select></label>}</div>
    <div className="demo-toolbar demo-colors">{Object.entries(pack.appearanceDefaults).map(([name,value])=><label key={name}>{title(name)}<input aria-label={`${name} color`} type="color" value={colors[name]||value} onChange={e=>setColors({...colors,[name]:e.target.value})}/></label>)}</div>
    <div className="react-feel"><label>Body <select aria-label="Demo body mode" value={mode} onChange={e=>setMode(e.target.value)}><option value="animated">Animated</option><option value="floating">Floating ragdoll</option><option value="ragdoll">Falling ragdoll</option><option value="protective">Protective</option></select></label><label>Muscles <input aria-label="Demo muscle strength" type="range" min="0" max="1" step=".05" value={resistance} onChange={e=>setResistance(+e.target.value)}/></label><label>Response <select aria-label="Demo protective response" value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="auto">Automatic</option><option value="protect">Cover head</option><option value="curl">Curl / hold self</option><option value="brace">Break fall</option></select></label><label><input type="checkbox" checked={autoFace} onChange={e=>setAutoFace(e.target.checked)}/>Auto face</label><button onClick={toggleSound} aria-label={soundOn?'Mute sound':'Enable sound'}>{soundOn?'Sound on':'Sound off'}</button></div>
    <div className="react-reactions"><label><input aria-label="Demo props" type="checkbox" checked={propsOn} onChange={e=>setPropsOn(e.target.checked)}/>Platforms</label>{[['pet','Pet'],['tap','Poke'],['startle','Startle'],['drop','Drop'],['toss','Toss'],['hurt','Hurt'],['catch','Catch']].map(([id,name])=><button key={id} onClick={()=>interact(id)}>{name}</button>)}</div>
    <div className="demo-board"><div ref={host} className="react-modal" style={{width}} tabIndex={0} aria-label="Draggable character card" onKeyDown={e=>{if(e.key.startsWith('Arrow')){e.preventDefault();move(position.current.x+(e.key==='ArrowLeft'?-16:e.key==='ArrowRight'?16:0),position.current.y+(e.key==='ArrowUp'?-16:e.key==='ArrowDown'?16:0));}}} onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,start:{...position.current}};}} onPointerMove={e=>{const d=drag.current;if(d)move(Math.max(-170,Math.min(170,d.start.x+e.clientX-d.x)),Math.max(-70,Math.min(70,d.start.y+e.clientY-d.y)));}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
    {mounted&&<Posecraft ref={player} scene={scene} behavior={behavior} inputs={{[character]:{action,emotion,...(pack.inputs.hair?{hair}:{})}}} hostRef={host} reducedMotion={policy==='system'?'system':policy==='reduced'} label={`${scene.name} in a moving card`} onEvent={e=>{sound.current?.handle(e);if(e.type==='transition'||e.type==='response')setEvent(`${e.actor}: ${e.from} → ${e.to}`);}} onError={e=>setEvent(e.message)}/>}</div></div>
    <div className="demo-toolbar"><button aria-label="Pause" onClick={()=>player.current?.pause()}><Icon name="pause"/></button><button aria-label="Play" onClick={()=>player.current?.play()}><Icon name="play_arrow"/></button><button aria-label="Reset" onClick={()=>{move(0,0);player.current?.reset();setMode('animated');setAction('idle');setEmotion('neutral');setHair('none');}}><Icon name="restart_alt"/></button><button onClick={()=>setMounted(v=>!v)}>{mounted?'Unmount':'Mount'}</button><label>Width <input aria-label="Container width" type="range" min="280" max="650" value={width} onChange={e=>setWidth(+e.target.value)}/></label></div>
    <div className="event-log" role="status">{event}</div><p className="demo-caption">Drag the card or use its arrow keys. System motion follows your device preference; Motion on enables the full preview. Protective mode uses bounded muscles and contact prediction. Curling is a pose, not a hand attachment. Rusty is a seated rig. <a href="./wwwzard.html">Original wwwzard cloth and typing demo →</a></p>
  </main>;
}
createRoot(document.getElementById('app')).render(<StrictMode><Demo/></StrictMode>);
