import React, { StrictMode, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Posecraft } from '../src/react.js';
import scene from './ona.posecraft.json';
import '../studio/style.css';

function Demo() {
  const [greeting, setGreeting] = useState(false), [mounted, setMounted] = useState(true), [event, setEvent] = useState('Drag the card or press Wave.'), [width, setWidth] = useState(500);
  const host = useRef(null), player = useRef(null), drag = useRef(null), position = useRef({ x:0,y:0 });
  const move = (x,y) => { position.current={x,y}; host.current.style.transform=`translate(${x}px,${y}px)`; };
  return <main className="react-page"><a href="./">← Posecraft Studio</a><h1>A character that moves with your app.</h1><p>This is a separate React consumer of the same scene and runtime used by the studio. Drag the card, change its size, or switch Ona's greeting input.</p><div className="demo-toolbar"><button className="primary" onClick={()=>setGreeting(v=>!v)}>{greeting?'Rest':'Wave'}</button><button onClick={()=>player.current?.pause()}>Pause</button><button onClick={()=>player.current?.play()}>Play</button><button onClick={()=>{ move(0,0); player.current?.reset(); }}>Reset</button><button onClick={()=>setMounted(v=>!v)}>{mounted?'Unmount':'Mount'}</button><label className="playback">Width <input aria-label="Container width" type="range" min="280" max="650" value={width} onChange={e=>setWidth(+e.target.value)}/></label></div><div className="demo-board"><div ref={host} className="react-modal" style={{width}} tabIndex={0} aria-label="Move the card with arrow keys" onKeyDown={e=>{if(e.key.startsWith('Arrow')){ e.preventDefault(); move(position.current.x+(e.key==='ArrowLeft'?-16:e.key==='ArrowRight'?16:0), position.current.y+(e.key==='ArrowUp'?-16:e.key==='ArrowDown'?16:0)); }}} onPointerDown={e=>{if(e.button!==0)return; e.currentTarget.setPointerCapture(e.pointerId); drag.current={x:e.clientX,y:e.clientY,start:{...position.current}};}} onPointerMove={e=>{const d=drag.current;if(d)move(Math.max(-170,Math.min(170,d.start.x+e.clientX-d.x)),Math.max(-70,Math.min(70,d.start.y+e.clientY-d.y)));}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>{mounted && <Posecraft ref={player} scene={scene} inputs={{ona:{greeting}}} hostRef={host} label="Ona greeting inside a moving card" onEvent={e=>{if(e.type==='transition')setEvent(`${e.actor}: ${e.from} → ${e.to}`);}} onError={e=>setEvent(e.message)}/>}</div></div><div className="event-log" role="status">{event}</div><p className="demo-caption">Translation produces a bounded spring response. Constant velocity produces no sustained force. Foot contact, falling, and fluids are later milestones. Reduced motion uses a still pose.</p><a href="./wwwzard.html">Open the original wwwzard runtime example →</a></main>;
}
createRoot(document.getElementById('app')).render(<StrictMode><Demo/></StrictMode>);
