import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash,randomUUID} from 'node:crypto';
import {Worker} from 'node:worker_threads';
import {inspectScene,diagnoseScene,proposeSceneEdit,applySceneProposal} from '../src/agent-authoring.js';
import {assertDocument} from '../src/schema.js';
const hash=data=>createHash('sha256').update(data).digest('hex');
const jsonBytes=value=>{let text=JSON.stringify(value,null,2)+'\n';if(Buffer.byteLength(text)>5_000_000)text=JSON.stringify(value)+'\n';if(Buffer.byteLength(text)>5_000_000)throw Error('JSON output exceeds 5 MB.');return text;};
export const AGENT_LIMITS=Object.freeze({jsonBytes:5_000_000,simulationSeconds:60,workerTimeoutMs:15_000,rasterSide:2048,rasterPixels:4_194_304});
export async function createAgentService(directory){
 const root=await fs.realpath(path.resolve(directory));
 const inside=p=>p===root||p.startsWith(root+path.sep);
 async function input(filename){if(typeof filename!=='string'||!filename||filename.includes('\0'))throw Error('Expected a file path.');const resolved=path.resolve(root,filename);if(!inside(resolved))throw Error('Path is outside the configured root.');const real=await fs.realpath(resolved);if(!inside(real))throw Error('Symlink leaves the configured root.');const stat=await fs.stat(real);if(!stat.isFile()||stat.size>AGENT_LIMITS.jsonBytes)throw Error('Expected a JSON file under 5 MB.');const bytes=await fs.readFile(real);if(bytes.length>AGENT_LIMITS.jsonBytes)throw Error('JSON exceeds 5 MB.');return {path:real,bytes,value:JSON.parse(bytes.toString('utf8')),sha256:hash(bytes)};}
 async function output(filename,bytes,protectedPaths=[]){if(typeof filename!=='string'||!filename||filename.includes('\0'))throw Error('Expected a separate output path.');const resolved=path.resolve(root,filename);if(!inside(resolved)||resolved===root)throw Error('Output is outside the configured root.');const parent=await fs.realpath(path.dirname(resolved)),destination=path.join(parent,path.basename(resolved));if(!inside(parent)||protectedPaths.includes(destination))throw Error('Output must be a new file inside the root, separate from the source.');const temporary=path.join(parent,'.posecraft-'+randomUUID()+'.tmp');try{await fs.writeFile(temporary,bytes,{flag:'wx'});await fs.link(temporary,destination);}finally{await fs.unlink(temporary).catch(()=>{});}return path.relative(root,destination);}
 async function simulation(document,kind,options){assertDocument(document);return new Promise((resolve,reject)=>{const worker=new Worker(new URL('./agent-runtime-worker.mjs',import.meta.url),{workerData:{kind,document,options},resourceLimits:{maxOldGenerationSizeMb:256,maxYoungGenerationSizeMb:64}}),timer=setTimeout(()=>{worker.terminate();reject(Error('Simulation exceeded 15-second execution limit.'));},AGENT_LIMITS.workerTimeoutMs);worker.once('message',m=>{clearTimeout(timer);worker.terminate();if(m.error){const e=Error(m.error);e.diagnostics=m.diagnostics;reject(e);}else resolve(m.result)});worker.once('error',e=>{clearTimeout(timer);reject(e)});worker.once('exit',code=>{if(code!==0){clearTimeout(timer);reject(Error('Simulation worker stopped.'));}});});}
 async function candidate(file,proposalFile){const source=await input(file);if(!proposalFile)return {source,document:assertDocument(source.value)};const proposal=await input(proposalFile);if(proposal.value?.format!=='posecraft-file-proposal'||proposal.value.version!==1)throw Error('Expected a version1 file proposal.');if(proposal.value.sourceSha256!==source.sha256)throw Error('Source content changed since proposal.');return {source,proposal,document:applySceneProposal(source.value,proposal.value.proposal)};}
 return {
  root,limits:AGENT_LIMITS,
  async inspect({file}){const source=await input(file);return {...inspectScene(source.value),sourceSha256:source.sha256};},
  async validate({file,proposal}){if(!proposal)return diagnoseScene((await input(file)).value);const data=await candidate(file,proposal);return diagnoseScene(data.document);},
  async propose({file,expectedRevision,operations,output:out}){const source=await input(file),proposal=proposeSceneEdit(source.value,{expectedRevision,operations}),envelope={format:'posecraft-file-proposal',version:1,sourceSha256:source.sha256,proposal};if(out)await output(out,jsonBytes(envelope),[source.path]);return {proposal:envelope,output:out||null};},
  async apply({file,proposal,output:out}){if(!proposal)throw Error('Apply requires a saved proposal file.');const data=await candidate(file,proposal),fresh=await input(file);if(fresh.sha256!==data.source.sha256)throw Error('Source changed during apply.');const result=await output(out,jsonBytes(data.document),[data.source.path,data.proposal.path]);return {output:result,revision:data.document.revision,sourcePreserved:true};},
  async simulate({file,proposal,...options}){const data=await candidate(file,proposal);return simulation(data.document,'simulate',options);},
  async preview({file,proposal,output:out,format='svg',width=800,height=450,...options}){if(!['svg','png'].includes(format))throw Error('Preview format must be svg or png.');if(format==='png'&&(!out||!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>2048||height>2048||width*height>AGENT_LIMITS.rasterPixels))throw Error('PNG requires a new output path and dimensions 1..2048.');const data=await candidate(file,proposal),result=await simulation(data.document,'preview',options);if(Buffer.byteLength(result.svg)>8_000_000)throw Error('SVG preview exceeds 8 MB.');let bytes=result.svg;if(format==='png'){if(!Number.isInteger(width)||!Number.isInteger(height)||width<1||height<1||width>2048||height>2048||width*height>AGENT_LIMITS.rasterPixels)throw Error('PNG dimensions must be 1..2048 and at most 4194304 pixels.');const {chromium}=await import('@playwright/test'),browser=await chromium.launch({headless:true,timeout:10000,...(process.platform==='win32'?{channel:'msedge'}:{})});try{const context=await browser.newContext({viewport:{width,height},javaScriptEnabled:false});await context.route('**/*',route=>route.abort());const page=await context.newPage();await page.setContent('<style>html,body{margin:0;width:100%;height:100%;overflow:hidden}svg{display:block;width:100%;height:100%}</style>'+result.svg,{waitUntil:'domcontentloaded',timeout:5000});bytes=await page.screenshot({type:'png',timeout:10000});}finally{await browser.close();}}if(!out)return {...result,format};const saved=await output(out,bytes,[data.source.path,...(data.proposal?[data.proposal.path]:[])]);return {output:saved,format,time:result.time,revision:result.revision,diagnostics:result.diagnostics};}
 };
}
