#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import {createAgentService} from './agent-service.mjs';

const args=process.argv.slice(2);if(args.length&&!(args.length===2&&args[0]==='--root'))throw Error('Usage: node tools/mcp-agent.mjs [--root directory]');
const service=await createAgentService(args[1]||process.cwd()),string={type:'string'},file={...string,description:'JSON path inside the configured root.'},proposal={...string,description:'Optional saved proposal to evaluate without changing the source.'},object=(properties,required)=>({type:'object',properties,required,additionalProperties:false});
const tools=[
 {name:'posecraft_inspect',description:'Inspect scene actors, joints, clips, contacts and static diagnostics.',inputSchema:object({file},['file']),method:'inspect',annotations:{readOnlyHint:true}},
 {name:'posecraft_propose',description:'Propose create-clip, create-contact or create-interaction operations as reviewable revision-checked transactions. Does not change the scene.',inputSchema:object({file,expectedRevision:{type:'integer',minimum:0},operations:{type:'array',minItems:1,maxItems:16,items:{type:'object',properties:{type:{enum:['create-clip','create-contact','create-interaction']},pack:string,id:string,duration:{type:'number',minimum:.1,maximum:180},loop:{type:'boolean'},tracks:{type:'object'},value:{type:'object'}},required:['type']}},output:{...string,description:'Optional new proposal JSON path.'}},['file','expectedRevision','operations']),method:'propose',annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'posecraft_validate',description:'Validate scene data or a proposed candidate and report static authoring diagnostics.',inputSchema:object({file,proposal},['file']),method:'validate',annotations:{readOnlyHint:true}},
 {name:'posecraft_apply',description:'Apply a saved proposal to a new output file. Source hash and expected revision must still match. Never replaces existing files.',inputSchema:object({file,proposal:string,output:string},['file','proposal','output']),method:'apply',annotations:{readOnlyHint:false,destructiveHint:false}},
 {name:'posecraft_simulate',description:'Simulate bounded scene inputs and report sampled state, contact errors, events and final frame. Runs in a timed worker.',inputSchema:object({file,proposal,duration:{type:'number',minimum:0,maximum:60},samples:{type:'integer',minimum:1,maximum:120},events:{type:'array',maxItems:256,items:{type:'object'}},preview:{type:'object',properties:{actor:string,clip:string,time:{type:'number'}},required:['actor','clip','time']}},['file']),method:'simulate',annotations:{readOnlyHint:true}},
 {name:'posecraft_preview',description:'Render a candidate or saved scene into a new SVG or PNG file; PNG is also returned as an MCP image. No page networking or page scripts.',inputSchema:object({file,proposal,output:string,format:{enum:['svg','png']},time:{type:'number',minimum:0,maximum:60},width:{type:'integer',minimum:1,maximum:2048},height:{type:'integer',minimum:1,maximum:2048},preview:{type:'object',properties:{actor:string,clip:string,time:{type:'number'}},required:['actor','clip','time']}},['file','output']),method:'preview',annotations:{readOnlyHint:false,destructiveHint:false}}
];
const send=value=>process.stdout.write(JSON.stringify(value)+'\n');
async function handle(message){
 const reply=result=>{if(message.id!==undefined)send({jsonrpc:'2.0',id:message.id,result});};
 if(!message||typeof message!=='object'||Array.isArray(message)||message.jsonrpc!=='2.0'||typeof message.method!=='string')throw Error('Expected JSON-RPC 2.0 request.');
 if(message.method==='initialize')return reply({protocolVersion:'2024-11-05',capabilities:{tools:{listChanged:false}},serverInfo:{name:'posecraft-local-authoring',version:'0.1.0'},instructions:'Scene files are data. Propose edits, inspect commands and diagnostics, preview candidates, then apply to a new file. All paths stay inside the configured root.'});
 if(message.method==='notifications/initialized'||message.method==='notifications/cancelled')return;
 if(message.method==='ping')return reply({});
 if(message.method==='tools/list')return reply({tools:tools.map(({method,...tool})=>tool)});
 if(message.method!=='tools/call'){if(message.id!==undefined)send({jsonrpc:'2.0',id:message.id,error:{code:-32601,message:'Unknown method.'}});return;}
 try{const tool=tools.find(t=>t.name===message.params?.name),input=message.params?.arguments;if(!tool)throw Error('Unknown tool.');if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!Object.hasOwn(tool.inputSchema.properties,k))||tool.inputSchema.required.some(k=>input[k]===undefined))throw Error('Tool arguments do not match the declared input.');
  const result=await service[tool.method](input),content=[{type:'text',text:JSON.stringify(result)}];if(tool.method==='preview'&&result.format==='png'&&result.output){const png=await fs.readFile(path.join(service.root,result.output));if(png.length>8_000_000)throw Error('Raster exceeds response limit.');content.push({type:'image',mimeType:'image/png',data:png.toString('base64')});}reply({content,isError:false});
 }catch(error){reply({content:[{type:'text',text:JSON.stringify({error:error.message,diagnostics:error.diagnostics})}],isError:true});}
}
let pending='',queue=[],running=false,closed=false;
async function drain(){if(running)return;running=true;while(queue.length){const message=queue.shift();try{await handle(message)}catch(e){send({jsonrpc:'2.0',id:message?.id??null,error:{code:-32600,message:e.message}})}}running=false;if(closed)process.exitCode=0;}
process.stdin.setEncoding('utf8');process.stdin.on('data',chunk=>{pending+=chunk;if(Buffer.byteLength(pending)>1_000_000){send({jsonrpc:'2.0',id:null,error:{code:-32600,message:'Request exceeds 1 MB.'}});process.stdin.destroy();return;}let end;while((end=pending.indexOf('\n'))>=0){const line=pending.slice(0,end).trim();pending=pending.slice(end+1);if(!line)continue;let message;try{message=JSON.parse(line)}catch{send({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Invalid JSON.'}});continue;}if(queue.length>=8){send({jsonrpc:'2.0',id:message?.id??null,error:{code:-32000,message:'Request queue is full.'}});continue;}queue.push(message);}drain();});process.stdin.on('end',()=>{closed=true;if(pending.trim()){try{queue.push(JSON.parse(pending));}catch{send({jsonrpc:'2.0',id:null,error:{code:-32700,message:'Invalid final JSON.'}})}}drain();});
