import type {Rig3D,Pose3D,Placement3D,World3D,Vector3D,Quaternion3D,JointWorld3D} from './rig-3d.js';
import type {GripFrame3D} from './grip-3d.js';
export interface BenchActionRoles {pelvis:string;leftArm?:string;rightArm?:string;leftLeg?:string;rightLeg?:string;gripRotations?:{left:Quaternion3D;right:Quaternion3D};[role:string]:unknown}
export interface BenchActionSettings {reps?:number;effort?:number;tempo?:number;repetitionDuration?:number;startOffset?:number;soleHeight?:number;elbowMax?:number;kneeMax?:number}
export interface BenchActionContact {id:string;chain:string;active:boolean;target:{position:Vector3D;rotation?:Quaternion3D};actual:JointWorld3D;status:'solved'|'limited'|'unreachable'|'conflict';error:number;boneLengths:[number,number];maxStretch:1}
export interface BenchScootFrame {active:true;direction:'back'|'forward';cycle:number;stage:'prepare'|'plant'|'lift'|'shift'|'settle'|'recover'|'finish';progress:number;seatLift:number;handTargets:Vector3D[];footTargets:Vector3D[]}
export interface BenchActionFrame {time:number;duration:number;phase:string;rep:number|null;effort:number;pose:Pose3D;placement:Placement3D;world:World3D;bar:{position:Vector3D;rotation:Quaternion3D;scale:number;length:number};contacts:BenchActionContact[];diagnostics:BenchActionContact[];valid:boolean;scoot:BenchScootFrame|null;clearance:{progress:number;shift:number;rise:number;seatLift:number;handBlend:number}|null;transfer:{stage:'prepare'|'lean'|'push'|'settle';rise:number;pitch:number}|null;support:{seat:boolean;feet:Vector3D[]}}
/** Bench origin is floor center. size is [width, seat-top height, length]; +Z is the foot end. */
export function createBenchAction3D(options:{rig:Rig3D;roles:BenchActionRoles;grips?:Partial<Record<'left'|'right',GripFrame3D>>;bench:{position:Vector3D;rotation:Quaternion3D;scale:number;size?:Vector3D;rackHeight?:number};settings?:BenchActionSettings}):{duration:number;beats:Array<{id:string;label:string;start:number;end:number;rep?:number}>;sample(time:number):BenchActionFrame;interrupt(at:number):{supported:false;reason:string}|{supported:true;duration:number;sample(elapsed:number):BenchActionFrame};measurements:{armReach:number;legReach:number;seatY:number;standY:number;halfGrip:number;soleHeight:number;rackPosition:Vector3D};settings:{reps:number;effort:number;tempo:number;repDuration:number;elbowMax:number;kneeMax:number};bench:{position:Vector3D;rotation:Quaternion3D;scale:number;size:Vector3D;rackHeight:number}};
