import {LiquidWaves,wavedSurface} from './liquid-waves.js';
import {forwardKinematics} from './index.js';
import {validateFluidCommand,validateBottleFluid} from './bottle-validation.js';
const STEP=1/120,TAU=Math.PI*2,rad=Math.PI/180;
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),wrap=a=>((a+Math.PI)%TAU+TAU)%TAU-Math.PI;
const rotate=(p,a)=>({x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)});
const dot=(a,b)=>a.x*b.x+a.y*b.y;
export function polygonArea(points){return Math.abs(points.reduce((s,p,i)=>{const q=points[(i+1)%points.length];return s+p.x*q.y-q.x*p.y;},0))/2;}
export function clipWaterPolygon(boundary,normal,level){const out=[];for(let i=0;i<boundary.length;i++){const a=boundary[i],b=boundary[(i+1)%boundary.length],da=dot(a,normal)-level,db=dot(b,normal)-level;if(da>=0)out.push({...a});if((da>=0)!==(db>=0)){const t=da/(da-db);out.push({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});}}return out;}
const path=points=>points.length?'M'+points.map(p=>`${+p.x.toFixed(4)} ${+p.y.toFixed(4)}`).join('L')+'Z':'';
function inside(point,polygon){let yes=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.y>point.y)!==(b.y>point.y)&&point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y)+a.x)yes=!yes;}return yes;}
function nearest(point,polygon,winding){let best=null;for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length],dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy),t=clamp(((point.x-a.x)*dx+(point.y-a.y)*dy)/(length*length),0,1),x=a.x+dx*t,y=a.y+dy*t,d=Math.hypot(x-point.x,y-point.y);if(!best||d<best.distance)best={x,y,distance:d,normal:{x:-dy/length*winding,y:dx/length*winding}};}return best;}
/** Exact polygon/half-plane volume: gravity selects the normal; bisection finds
 * the offset. Concave bottle necks remain part of the same conserved chamber. */
export function waterSurface(boundary,normal,fill){let low=Infinity,high=-Infinity;for(const p of boundary){const n=dot(p,normal);low=Math.min(low,n);high=Math.max(high,n);}const targetArea=polygonArea(boundary)*fill;for(let i=0;i<32;i++){const middle=(low+high)/2;if(polygonArea(clipWaterPolygon(boundary,normal,middle))>targetArea)low=middle;else high=middle;}const level=(low+high)/2,polygon=clipWaterPolygon(boundary,normal,level),tangent={x:normal.y,y:-normal.x},cuts=[];for(let i=0;i<boundary.length;i++){const a=boundary[i],b=boundary[(i+1)%boundary.length],da=dot(a,normal)-level,db=dot(b,normal)-level;if((da>=0)!==(db>=0)){const t=da/(da-db),p={x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t};cuts.push({...p,u:dot(p,tangent)});}}cuts.sort((a,b)=>a.u-b.u);let surfacePath='';for(let i=1;i<cuts.length;i++){const a=cuts[i-1],b=cuts[i],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(inside(mid,boundary))surfacePath+=`M${a.x.toFixed(4)} ${a.y.toFixed(4)}L${b.x.toFixed(4)} ${b.y.toFixed(4)}`;}return {normal,level,polygon,area:polygonArea(polygon),targetArea,waterPath:path(polygon),surfacePath};}
const hull=[{x:-117,y:-16},{x:121,y:-16},{x:78,y:33},{x:-74,y:33},{x:-7,y:-147},{x:72,y:-120},{x:150,y:-47}];
// Five immersed hull stations, separate from mast/wall contact probes. Their
// rest drafts place the ship's waterline five local units below its origin.
const buoyancyStations=[{x:-84,y:20},{x:-42,y:32},{x:0,y:33},{x:42,y:32},{x:84,y:20}];
/** Fixed-cost contained liquid approximation: an area-conserving free surface,
 * inertial slosh, a buoyant rigid ship, and sampled hull/mast wall contacts. */
export class BottleFluid {
 constructor(document){const errors=[];validateBottleFluid(document,(valid,path,message)=>{if(!valid)errors.push(path+': '+message);});if(errors.length)throw Error(errors.join('; '));this.document=document;this.config=document.fluid;if(!this.config||this.config.type!=='bottle')throw Error('Missing bottle fluid configuration.');this.boundary=this.config.boundary;this.vessel=document.actors.find(a=>a.id===this.config.vessel);this.contents=document.actors.find(a=>a.id===this.config.contents);this.pack=document.packs[this.contents.pack];this.root=this.pack.joints.find(j=>j.id===this.config.ship.joint);this.winding=Math.sign(this.boundary.reduce((s,p,i)=>{const q=this.boundary[(i+1)%this.boundary.length];return s+p.x*q.y-q.x*p.y;},0));const p=rotate({x:this.config.pivot.x*this.vessel.transform.scale,y:this.config.pivot.y*this.vessel.transform.scale},this.vessel.transform.rotation*rad);this.home={x:p.x+this.vessel.transform.x,y:p.y+this.vessel.transform.y};this.reset();}
 reset(){this.time=0;this.accumulator=0;this.wind=this.config.wind;this.motion={ax:0,ay:0,turn:0,gravityX:0,gravityY:1};this.gesture=null;this.bottle={x:this.home.x,y:this.home.y,angle:0,vx:0,vy:0,omega:0};this.waterAngle=0;this.waterVelocity=0;this.slosh=0;this.contacts=0;this.waves=new LiquidWaves();this.previousGravity={x:0,y:1};this.surface=this.makeSurface();this.ship={x:this.root.x,y:this.root.y,vx:0,vy:0,angle:0,omega:0};const delta=this.surface.level-5*this.config.ship.scale-dot(this.ship,this.surface.normal);this.ship.x+=this.surface.normal.x*delta;this.ship.y+=this.surface.normal.y*delta;this.lastSafe=null;this.constrainShip();return this;}
 command(input){const command=validateFluidCommand(input);if(command.type==='wind'){this.wind=command.value;return;}if(command.type==='motion'){this.motion={...this.motion,...command};return;}if(command.type==='nudge'){this.waves.impulse(clamp(command.ax*.025+command.ay*.008,-45,45));this.bottle.vx=clamp(this.bottle.vx+command.ax*.04,-700,700);this.bottle.vy=clamp(this.bottle.vy+command.ay*.04,-700,700);this.waterVelocity=clamp(this.waterVelocity-command.ax*.0008,-3,3);this.ship.vx=clamp(this.ship.vx-command.ax*.03,-250,250);this.ship.vy=clamp(this.ship.vy-command.ay*.03,-250,250);return;}
  const points=command.points.slice().sort((a,b)=>a.id-b.id);if(!points.length){this.gesture=null;return;}const signature=points.map(p=>p.id).join(',');if(!this.gesture||command.type==='grab'||this.gesture.signature!==signature){const mid=points.length===2?{x:(points[0].x+points[1].x)/2,y:(points[0].y+points[1].y)/2}:points[0],anchor=rotate({x:mid.x-this.bottle.x,y:mid.y-this.bottle.y},-this.bottle.angle);this.gesture={signature,points,anchor,offset:points.length===2?this.bottle.angle-Math.atan2(points[1].y-points[0].y,points[1].x-points[0].x):0};}else this.gesture.points=points;
 }
 makeSurface(){const world={x:Math.sin(this.waterAngle),y:Math.cos(this.waterAngle)},normal=rotate(world,-this.bottle.angle-this.contents.transform.rotation*rad);return wavedSurface(this.boundary,normal,this.config.fill,this.waves.heights,this.waves.splashArea);}
 tick(dt){if(!Number.isFinite(dt)||dt<0)throw Error('Fluid time must be finite and nonnegative.');this.accumulator+=Math.min(dt,.1);while(this.accumulator+1e-10>=STEP){this.step();this.accumulator-=STEP;}}
 step(){const dt=STEP,c=this.config,b=this.bottle,previous={x:b.x,y:b.y,angle:b.angle,vx:b.vx,vy:b.vy,omega:b.omega},gravity={x:this.motion.gravityX*900,y:this.motion.gravityY*900},damping=c.damping;
  if(this.gesture){const g=this.gesture,p=g.points,mid=p.length===2?{x:(p[0].x+p[1].x)/2,y:(p[0].y+p[1].y)/2}:p[0];if(p.length===2)b.angle=previous.angle+wrap(Math.atan2(p[1].y-p[0].y,p[1].x-p[0].x)+g.offset-previous.angle);else{const arm=rotate({x:-g.anchor.x,y:-g.anchor.y},b.angle),torque=(arm.x*gravity.y-arm.y*gravity.x)/(dot(arm,arm)+18000);b.omega=clamp(b.omega+(torque-b.omega*(1.5+damping*2))*dt,-5,5);b.angle+=b.omega*dt;}const anchor=rotate(g.anchor,b.angle);b.x=mid.x-anchor.x;b.y=mid.y-anchor.y;b.vx=clamp((b.x-previous.x)/dt,-700,700);b.vy=clamp((b.y-previous.y)/dt,-700,700);if(p.length===2)b.omega=clamp(wrap(b.angle-previous.angle)/dt,-6,6);
  }else{b.vx=clamp(b.vx+(-(b.x-this.home.x)*14-b.vx*(5+damping*3)+this.motion.ax*.1)*dt,-700,700);b.vy=clamp(b.vy+(-(b.y-this.home.y)*18-b.vy*(6+damping*3)+this.motion.ay*.1)*dt,-700,700);b.omega=clamp(b.omega+(-wrap(b.angle)*14-b.omega*(4+damping*2)+this.motion.turn*rad*4)*dt,-6,6);b.x+=b.vx*dt;b.y+=b.vy*dt;b.angle+=b.omega*dt;}
  b.x=clamp(b.x,-10000,10000);b.y=clamp(b.y,-10000,10000);b.angle=wrap(b.angle);const ax=clamp((b.vx-previous.vx)/dt+this.motion.ax,-3500,3500),ay=clamp((b.vy-previous.vy)/dt+this.motion.ay,-3500,3500),angularAcceleration=clamp((b.omega-previous.omega)/dt,-20,20),effective={x:gravity.x-ax*.55,y:gravity.y-ay*.55};const target=Math.atan2(effective.x,effective.y),error=wrap(target-this.waterAngle);this.waterVelocity=clamp(this.waterVelocity+(error*15-this.waterVelocity*(2+damping*3)+angularAcceleration*.07)*dt,-4,4);this.waterAngle=wrap(this.waterAngle+this.waterVelocity*dt);this.slosh+=(Math.min(1,Math.abs(this.waterVelocity)*.5+Math.hypot(ax,ay)/3500)-this.slosh)*Math.min(1,dt*4);const gravityChange={x:(this.motion.gravityX-this.previousGravity.x)/dt,y:(this.motion.gravityY-this.previousGravity.y)/dt},localForce=rotate({x:ax+gravityChange.x*45,y:ay+gravityChange.y*45},-b.angle-this.contents.transform.rotation*rad);this.previousGravity={x:this.motion.gravityX,y:this.motion.gravityY};this.waves.tick(dt,{force:localForce.x,turn:angularAcceleration+this.waterVelocity*3,damping});this.time+=dt;this.waves.splash(dt,this.surface,this.boundary,Math.min(2,Math.hypot(ax,ay)/1200+Math.abs(angularAcceleration)*.035+Math.hypot(gravityChange.x,gravityChange.y)*.018+Math.abs(this.waterVelocity)*.45+this.waves.energy*.035));this.surface=this.makeSurface();
  const s=this.ship,n=this.surface.normal,t={x:n.y,y:-n.x},localAcceleration=rotate({x:-ax*.12,y:-ay*.12},-b.angle-this.contents.transform.rotation*rad),tangentSpeed=s.vx*t.x+s.vy*t.y,forceT=this.wind*22/c.ship.mass-tangentSpeed*(.9+damping)+dot(localAcceleration,t)-(dot(s,t)-dot(this.root,t))*.12;
  let forceN=0,torque=0,inertia=0;const reactions=[],stationWeight=1/buoyancyStations.length;
  for(const station of buoyancyStations){
   const arm=rotate({x:station.x*c.ship.scale,y:station.y*c.ship.scale},s.angle),point={x:s.x+arm.x,y:s.y+arm.y},u=dot(point,t),position=(u-this.surface.low)/(this.surface.high-this.surface.low),draft=(station.y-5)*c.ship.scale,submerged=dot(point,n)-this.surface.level-this.surface.heightAt(u),wet=clamp(submerged/draft,0,2),lever=arm.x*n.y-arm.y*n.x,relativeSpeed=s.vx*n.x+s.vy*n.y+s.omega*lever-this.waves.velocityAt(position);
   // Gravity and displacement balance at the station's rest draft. Dry probes
   // fall rather than experiencing an attractive force from the surface.
   const restoring=(1-wet)*draft*28/c.ship.mass,drag=-relativeSpeed*(5+damping*3)*Math.min(1,wet),force=clamp(restoring+drag,-1800,1800);
   forceN+=force*stationWeight;torque+=lever*force*stationWeight;inertia+=(arm.x*arm.x+arm.y*arm.y)*stationWeight;
   // Transfer only the dynamic correction, not balanced static displacement.
   reactions.push([position,-force*stationWeight*c.ship.mass*dt*.16*Math.min(1,wet)]);
  }
  for(const [position,impulse] of reactions)this.waves.react(position,impulse);
  s.vx=clamp(s.vx+(n.x*forceN+t.x*forceT)*dt,-250,250);s.vy=clamp(s.vy+(n.y*forceN+t.y*forceT)*dt,-250,250);s.x+=s.vx*dt;s.y+=s.vy*dt;
  s.omega=clamp(s.omega+(torque/Math.max(1,inertia)+(this.wind*.035+this.waterVelocity*.035)*24/c.ship.mass-s.omega*.8-angularAcceleration*.12)*dt,-5,5);s.angle=wrap(s.angle+s.omega*dt);this.constrainShip();
 }
 constrainShip(){const s=this.ship,scale=this.config.ship.scale;this.contacts=0;for(let pass=0;pass<8;pass++){let collision=null;for(const sample of hull){const q=rotate({x:sample.x*scale,y:sample.y*scale},s.angle),point={x:s.x+q.x,y:s.y+q.y};if(!inside(point,this.boundary)){const hit=nearest(point,this.boundary,this.winding);if(hit.distance>1e-5&&(!collision||hit.distance>collision.distance))collision={...hit,point};}}if(!collision)break;this.contacts++;s.x+=collision.x-collision.point.x+collision.normal.x*.15;s.y+=collision.y-collision.point.y+collision.normal.y*.15;const speed=s.vx*collision.normal.x+s.vy*collision.normal.y;if(speed<0){s.vx-=collision.normal.x*speed*1.25;s.vy-=collision.normal.y*speed*1.25;}s.omega*=.8;}
  const fits=hull.every(sample=>{const p=rotate({x:sample.x*scale,y:sample.y*scale},s.angle);return inside({x:s.x+p.x,y:s.y+p.y},this.boundary);});
  if(fits)this.lastSafe={x:s.x,y:s.y,angle:s.angle};else if(this.lastSafe){Object.assign(s,this.lastSafe);s.vx*=.2;s.vy*=.2;s.omega*=-.15;this.contacts++;}
  if(!inside(s,this.boundary)){const p=nearest(s,this.boundary,this.winding);s.x=p.x+p.normal.x;s.y=p.y+p.normal.y;s.vx*=.2;s.vy*=.2;}
 }
 ripplePath(){if(this.slosh<.003)return '';const n=this.surface.normal,t={x:n.y,y:-n.x},values=this.surface.polygon.map(p=>dot(p,t)),low=Math.min(...values),high=Math.max(...values),span=high-low;let result='';for(let row=0;row<2;row++){let drawing=false;for(let i=0;i<=32;i++){const u=low+span*(.12+.76*i/32),q=this.surface.level+this.surface.heightAt(u)+7+row*12+Math.sin(i/32*Math.PI*4-this.time*4+row)*Math.min(3,this.slosh*4),p={x:t.x*u+n.x*q,y:t.y*u+n.y*q};if(inside(p,this.boundary)){result+=(drawing?'L':'M')+p.x.toFixed(3)+' '+p.y.toFixed(3);drawing=true;}else drawing=false;}}return result;}
 apply(frame,{disabledActors=new Set()}={}){if(disabledActors.has(this.config.vessel)||disabledActors.has(this.config.contents))return frame;const b=this.bottle,s=this.ship,placement=actor=>{const base=frame.actors.find(a=>a.id===actor.id)?.placement||actor.transform,delta=rotate({x:base.x-this.home.x,y:base.y-this.home.y},b.angle);return {...base,x:b.x+delta.x,y:b.y+delta.y,rotation:base.rotation+b.angle/rad};},actors=frame.actors.map(a=>{if(a.id===this.vessel.id)return {...a,placement:placement(this.vessel)};if(a.id!==this.contents.id)return a;const pose={...a.pose,[this.root.id+'.x']:s.x-this.root.x,[this.root.id+'.y']:s.y-this.root.y,[this.root.id+'.rotation']:s.angle/rad};for(const id of ['main-sail','fore-sail','pennant'])if(this.pack.joints.some(j=>j.id===id)){pose[id+'.bend']=clamp(Math.abs(this.wind)*.36+Math.sin(this.time*(3+Math.abs(this.wind)))*(Math.abs(this.wind)*.04+this.slosh*.035),0,1);pose[id+'.rotation']=this.wind*(id==='pennant'?8:3)+Math.sin(this.time*5)*Math.abs(this.wind)*1.2;}return {...a,pose,placement:placement(this.contents),world:forwardKinematics(this.pack.joints,pose)};});
  return {...frame,actors,fluid:{actor:this.contents.id,vessel:this.vessel.id,contents:this.contents.id,waterPath:this.surface.waterPath,surfacePath:this.surface.surfacePath,waterPolygon:this.surface.polygon.map(p=>({...p})),area:this.surface.area,bulkArea:this.surface.bulkArea,splashArea:this.surface.splashArea,targetArea:this.surface.targetArea,waveAmplitude:this.waves.energy,waveHeights:Array.from(this.waves.heights),waveParticles:this.waves.drops.length,splashPath:this.waves.splashPath,foamPath:this.surface.foamPath,surfaceSamples:this.surface.surfaceSamples.map(p=>({...p})),normal:{...this.surface.normal},level:this.surface.level,paths:{'deep-water':this.surface.waterPath,'rear-wave':this.surface.waterPath,'front-wave':this.surface.waterPath,'front-wave-edge':this.surface.surfacePath,'water-glints':this.ripplePath()},hidden:['interior-sky','horizon-glow','sun','sun-halo','cloud-left','cloud-right','distant-island','gulls','ship-shadow','rear-foam'],bottle:{x:b.x,y:b.y,rotation:b.angle/rad,vx:b.vx,vy:b.vy,angularVelocity:b.omega/rad},ship:{joint:this.root.id,x:s.x,y:s.y,rotation:s.angle/rad,scale:this.config.ship.scale},slosh:this.slosh,wind:this.wind,contacts:this.contacts,grabbed:this.gesture?.points.length||0}};
 }
}
