import {multiplyMatrix,transformPoint} from './render-geometry.js';
import {drawingViewport,CanvasCapabilityError} from './canvas.js';
const color=value=>{let h=value.slice(1);if(h.length===3)h=[...h].map(c=>c+c).join('');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255];};

/** Deliberately narrow depth-testing experiment. It never silently drops an
 * unsupported vector path, translucent material, mask, light or scene unit. */
export function inspectDepthCanvasCapabilities(drawing){const reasons=[...drawing.capabilities.unsupported],actors=new Set(drawing.meshes.filter(m=>m.visible).map(m=>m.actor));if(actors.size!==1)reasons.push({code:'single-mesh-actor',message:'Depth-buffer mode currently accepts exactly one opaque mesh actor.'});for(const unit of drawing.units)for(const c of unit.commands)if(c.visible&&c.opacity>0&&!c.mesh)reasons.push({code:'vector-path',message:'Depth-buffer mode does not yet composite ordinary vector paths or scene effects.'});for(const mesh of drawing.meshes)if(mesh.visible&&(mesh.masked||mesh.outlined||mesh.opacity!==1||mesh.fill?.type!=='solid'||!/^#[a-f\d]{3}(?:[a-f\d]{3})?$/i.test(mesh.fill.color)))reasons.push({code:'mesh-material',message:'Depth-buffer mode requires opaque solid meshes without masks or outlines.'});return {supported:!reasons.length,unsupported:[...new Map(reasons.map(r=>[r.code,r])).values()]};}

export function renderDepthCanvas(context,drawing,{maxPixels=1048576,maxTrianglePixels=8000000}={}){
 const capabilities=inspectDepthCanvasCapabilities(drawing);if(!capabilities.supported)throw new CanvasCapabilityError(capabilities.unsupported);const width=context.canvas.width,height=context.canvas.height;if(width*height>maxPixels)throw RangeError('Depth-buffer surface exceeds its pixel budget.');const image=context.createImageData(width,height),depth=new Float32Array(width*height).fill(-Infinity),picks=new Int32Array(width*height).fill(-1),viewport=drawingViewport(drawing,width,height);let candidatePixels=0,triangles=0;
 for(const [index,mesh]of drawing.meshes.entries()){if(!mesh.visible)continue;const matrix=multiplyMatrix(viewport,mesh.matrix),vertices=mesh.vertices.map(v=>({...transformPoint(matrix,v.x,v.y),depth:v.depth})),rgba=color(mesh.fill.color);for(const triangle of mesh.triangles){const [a,b,c]=triangle.map(i=>vertices[i]),area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(Math.abs(area)<1e-9)continue;const x0=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),x1=Math.min(width-1,Math.ceil(Math.max(a.x,b.x,c.x))),y0=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),y1=Math.min(height-1,Math.ceil(Math.max(a.y,b.y,c.y)));candidatePixels+=Math.max(0,x1-x0+1)*Math.max(0,y1-y0+1);if(candidatePixels>maxTrianglePixels)throw RangeError('Depth-buffer triangle coverage exceeds its fixed work budget.');triangles++;for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const px=x+.5,py=y+.5,u=((b.x-px)*(c.y-py)-(b.y-py)*(c.x-px))/area,v=((c.x-px)*(a.y-py)-(c.y-py)*(a.x-px))/area,w=1-u-v;if(u< -1e-8||v< -1e-8||w< -1e-8)continue;const z=u*a.depth+v*b.depth+w*c.depth,slot=y*width+x;if(z<depth[slot]-1e-6)continue;depth[slot]=z;picks[slot]=index;image.data.set(rgba,slot*4);}}}
 context.putImageData(image,0,0);return {depth,picks,triangles,candidatePixels,pick(x,y){if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>=width||y>=height)return null;const index=picks[Math.floor(y)*width+Math.floor(x)];if(index===undefined||index<0)return null;const mesh=drawing.meshes[index];return {actor:mesh.actor,part:mesh.part,joint:mesh.joint};}};
}
