import {multiplyMatrix,transformPoint,pathBounds} from './render-geometry.js';
import {drawingViewport,CanvasCapabilityError} from './canvas.js';
const color=value=>{let h=value.slice(1);if(h.length===3)h=[...h].map(c=>c+c).join('');return [parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16),255];};

/** Deliberately narrow depth-testing experiment. It never silently drops an
 * unsupported vector path, translucent material, mask, light or scene unit. */
export function inspectDepthCanvasCapabilities(drawing){const reasons=[...drawing.capabilities.unsupported],actors=new Set(drawing.meshes.filter(m=>m.visible).map(m=>m.actor));if(actors.size!==1)reasons.push({code:'single-mesh-actor',message:'Depth-buffer mode currently accepts exactly one opaque mesh actor.'});for(const unit of drawing.units)for(const c of unit.commands)if(c.visible&&c.opacity>0&&!c.mesh)reasons.push({code:'vector-path',message:'Depth-buffer mode does not yet composite ordinary vector paths or scene effects.'});for(const mesh of drawing.meshes)if(mesh.visible&&(mesh.masked||mesh.outlined||mesh.opacity!==1||mesh.fill?.type!=='solid'||!/^#[a-f\d]{3}(?:[a-f\d]{3})?$/i.test(mesh.fill.color)))reasons.push({code:'mesh-material',message:'Depth-buffer mode requires opaque solid meshes without masks or outlines.'});return {supported:!reasons.length,unsupported:[...new Map(reasons.map(r=>[r.code,r])).values()]};}

export function renderDepthCanvas(context,drawing,{maxPixels=1048576,maxTrianglePixels=8000000}={}){
 const capabilities=inspectDepthCanvasCapabilities(drawing);if(!capabilities.supported)throw new CanvasCapabilityError(capabilities.unsupported);const width=context.canvas.width,height=context.canvas.height;if(width*height>maxPixels)throw RangeError('Depth-buffer surface exceeds its pixel budget.');const image=context.createImageData(width,height),depth=new Float32Array(width*height).fill(-Infinity),picks=new Int32Array(width*height).fill(-1),viewport=drawingViewport(drawing,width,height);let candidatePixels=0,triangles=0;
 for(const [index,mesh]of drawing.meshes.entries()){if(!mesh.visible)continue;const matrix=multiplyMatrix(viewport,mesh.matrix),vertices=mesh.vertices.map(v=>({...transformPoint(matrix,v.x,v.y),depth:v.depth})),rgba=color(mesh.fill.color);for(const triangle of mesh.triangles){const [a,b,c]=triangle.map(i=>vertices[i]),area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(Math.abs(area)<1e-9)continue;const x0=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),x1=Math.min(width-1,Math.ceil(Math.max(a.x,b.x,c.x))),y0=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),y1=Math.min(height-1,Math.ceil(Math.max(a.y,b.y,c.y)));candidatePixels+=Math.max(0,x1-x0+1)*Math.max(0,y1-y0+1);if(candidatePixels>maxTrianglePixels)throw RangeError('Depth-buffer triangle coverage exceeds its fixed work budget.');triangles++;for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const px=x+.5,py=y+.5,u=((b.x-px)*(c.y-py)-(b.y-py)*(c.x-px))/area,v=((c.x-px)*(a.y-py)-(c.y-py)*(a.x-px))/area,w=1-u-v;if(u< -1e-8||v< -1e-8||w< -1e-8)continue;const z=u*a.depth+v*b.depth+w*c.depth,slot=y*width+x;if(z<depth[slot]-1e-6)continue;depth[slot]=z;picks[slot]=index;image.data.set(rgba,slot*4);}}}
 context.putImageData(image,0,0);return {depth,picks,triangles,candidatePixels,pick(x,y){if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>=width||y>=height)return null;const index=picks[Math.floor(y)*width+Math.floor(x)];if(index===undefined||index<0)return null;const mesh=drawing.meshes[index];return {actor:mesh.actor,part:mesh.part,joint:mesh.joint};}};
}


const active=c=>c.visible&&c.opacity>0&&c.d;
const painted=c=>c.fill.type!=='solid'||c.fill.color!=='none'||c.strokeWidth>0&&c.stroke.color!=='none';
const opaqueMaterial=m=>m?.type==='solid'?/^#[a-f\d]{3}(?:[a-f\d]{3})?$/i.test(m.color):m?.type==='radial'&&m.rx>0&&m.ry>0&&m.stops.every(([,c,a])=>(a===undefined||a===1)&&/^#[a-f\d]{3}(?:[a-f\d]{3})?$/i.test(c));
export function inspectActorDepthCapabilities(drawing){const reasons=[...drawing.capabilities.unsupported];for(const mesh of drawing.meshes)if(mesh.visible&&mesh.opacity>0){if(mesh.masked)reasons.push({code:'depth-mesh-mask',message:'Actor depth does not yet support mesh masks.'});if(mesh.strokeWidth>0&&mesh.stroke!=='none'&&!/^#[a-f\d]{3}(?:[a-f\d]{3})?$/i.test(mesh.stroke))reasons.push({code:'depth-mesh-outline',message:'Actor depth requires opaque solid mesh contour colors.'});if(mesh.opacity!==1||!opaqueMaterial(mesh.fill))reasons.push({code:'depth-mesh-material',message:'Actor depth requires opaque solid or opaque radial mesh materials.'});}return {supported:!reasons.length,unsupported:[...new Map(reasons.map(r=>[r.code,r])).values()]};}

const actorPools=new WeakMap();
const boundsOf=(d,m,margin=0)=>{const b=pathBounds(d),points=[[b.minX,b.minY],[b.minX,b.maxY],[b.maxX,b.minY],[b.maxX,b.maxY]].map(([x,y])=>transformPoint(m,x,y));return {x0:Math.min(...points.map(p=>p.x))-margin,y0:Math.min(...points.map(p=>p.y))-margin,x1:Math.max(...points.map(p=>p.x))+margin,y1:Math.max(...points.map(p=>p.y))+margin};};
function radialSampler(material){if(material.type==='solid'){const rgba=color(material.color);return ()=>rgba;}const stops=material.stops.map(([t,c])=>[t,color(c)]);return (x,y)=>{const t=Math.hypot((x-material.cx)/material.rx,(y-material.cy)/material.ry);let index=0;while(index<stops.length-1&&t>=stops[index+1][0])index++;if(index===stops.length-1||t<=stops[0][0])return stops[index][1];const [lo,a]=stops[index],[hi,b]=stops[index+1],q=Math.max(0,Math.min(1,(t-lo)/(hi-lo||1)));return [a[0]+(b[0]-a[0])*q,a[1]+(b[1]-a[1])*q,a[2]+(b[2]-a[2])*q,255];};}
function poolFor(context,id,width,height){let pools=actorPools.get(context);if(!pools){pools=new Map();actorPools.set(context,pools);}let pool=pools.get(id);if(!pool||pool.width!==width||pool.height!==height){const canvas=typeof OffscreenCanvas==='function'?new OffscreenCanvas(width,height):context.canvas.ownerDocument.createElement('canvas');canvas.width=width;canvas.height=height;const scratch=canvas.getContext('2d',{willReadFrequently:true});pool={canvas,scratch,width,height,depth:new Float64Array(width*height),priority:new Float64Array(width*height),picks:new Int32Array(width*height),image:scratch.createImageData(width,height)};pools.set(id,pool);}pool.depth.fill(-Infinity);pool.priority.fill(-Infinity);pool.picks.fill(-1);pool.image.data.fill(0);return pool;}
export function releaseActorDepth(context,keep=new Set()){const pools=actorPools.get(context);if(pools)for(const id of pools.keys())if(!keep.has(id))pools.delete(id);if(!keep.size)actorPools.delete(context);}

/** Per-scene-unit depth composition. Mesh geometry is interpolated per pixel;
 * ordinary vector artwork remains a plane at its authored evaluated depth. */
export function renderActorDepth(context,drawing,unit,{viewport,paintCommand,budget={pixels:0,trianglePixels:0,vectorPixels:0},supersample=2,maxActorPixels=2097152,maxFramePixels=4194304,maxTrianglePixels=16000000,maxVectorPixels=16000000}={}){
 const members=new Set(unit.commands.filter(c=>c.mesh).map(c=>c.pick?.part)),actor=unit.commands.find(c=>c.mesh)?.pick?.actor,meshes=drawing.meshes.filter(m=>m.actor===actor&&members.has(m.part)&&m.visible&&m.opacity>0);if(!meshes.length)return null;
 const core=unit.commands.filter(c=>c.pick?.actor===actor&&c.pick.part),tail=unit.commands.filter(c=>!core.includes(c)),vectors=core.filter(c=>!c.mesh&&active(c)&&painted(c));let x0=Infinity,y0=Infinity,x1=-Infinity,y1=-Infinity;
 for(const mesh of meshes){const matrix=multiplyMatrix(viewport,mesh.matrix),margin=mesh.strokeWidth*Math.max(Math.hypot(matrix[0],matrix[1]),Math.hypot(matrix[2],matrix[3]))/2+2;for(const v of mesh.vertices){const p=transformPoint(matrix,v.x,v.y);x0=Math.min(x0,p.x-margin);y0=Math.min(y0,p.y-margin);x1=Math.max(x1,p.x+margin);y1=Math.max(y1,p.y+margin);}}
 for(const c of vectors){const matrix=multiplyMatrix(viewport,c.matrix),margin=c.strokeWidth*Math.max(Math.hypot(matrix[0],matrix[1]),Math.hypot(matrix[2],matrix[3]))/2+2,b=boundsOf(c.d,matrix,margin);x0=Math.min(x0,b.x0);y0=Math.min(y0,b.y0);x1=Math.max(x1,b.x1);y1=Math.max(y1,b.y1);}
 x0=Math.max(0,Math.floor(x0));y0=Math.max(0,Math.floor(y0));x1=Math.min(context.canvas.width,Math.ceil(x1));y1=Math.min(context.canvas.height,Math.ceil(y1));const width=Math.max(0,Math.ceil((x1-x0)*supersample)),height=Math.max(0,Math.ceil((y1-y0)*supersample));if(!width||!height)return {tail,drawn:core.length,pick:()=>null};const pixels=width*height;budget.pixels+=pixels;if(pixels>maxActorPixels||budget.pixels>maxFramePixels)throw RangeError('Actor depth exceeds its bounded pixel budget. Reduce the viewport size or visible mesh actors.');
 const pool=poolFor(context,unit.id,width,height),{depth,priority,picks,image,scratch}=pool,data=image.data,localViewport=multiplyMatrix([supersample,0,0,supersample,-x0*supersample,-y0*supersample],viewport),references=[];
 const write=(slot,z,rank,rgba,pick,source=0)=>{if(z<depth[slot]-1e-5||Math.abs(z-depth[slot])<=1e-5&&rank<priority[slot])return;depth[slot]=z;priority[slot]=rank;picks[slot]=pick;const offset=slot*4,alpha=rgba[source+3]/255,old=data[offset+3]/255,out=alpha+old*(1-alpha);for(let c=0;c<3;c++)data[offset+c]=(rgba[source+c]*alpha+data[offset+c]*old*(1-alpha))/(out||1);data[offset+3]=out*255;};
 for(const mesh of meshes){const matrix=multiplyMatrix(localViewport,mesh.matrix),vertices=mesh.vertices.map(v=>({...transformPoint(matrix,v.x,v.y),depth:v.depth,localX:v.x,localY:v.y})),sample=radialSampler(mesh.fill),pick=references.push({actor:mesh.actor,part:mesh.part,joint:mesh.joint})-1,rank=mesh.order??0;
  for(const triangle of mesh.triangles){const [a,b,c]=triangle.map(i=>vertices[i]),area=(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);if(Math.abs(area)<1e-9)continue;const left=Math.max(0,Math.floor(Math.min(a.x,b.x,c.x))),right=Math.min(width-1,Math.ceil(Math.max(a.x,b.x,c.x))),top=Math.max(0,Math.floor(Math.min(a.y,b.y,c.y))),bottom=Math.min(height-1,Math.ceil(Math.max(a.y,b.y,c.y)));budget.trianglePixels+=Math.max(0,right-left+1)*Math.max(0,bottom-top+1);if(budget.trianglePixels>maxTrianglePixels)throw RangeError('Actor depth exceeds its triangle coverage budget.');for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){const px=x+.5,py=y+.5,u=((b.x-px)*(c.y-py)-(b.y-py)*(c.x-px))/area,v=((c.x-px)*(a.y-py)-(c.y-py)*(a.x-px))/area,w=1-u-v;if(u< -1e-8||v< -1e-8||w< -1e-8)continue;write(y*width+x,u*a.depth+v*b.depth+w*c.depth,rank,sample(u*a.localX+v*b.localX+w*c.localX,u*a.localY+v*b.localY+w*c.localY),pick);}}
 }
 // Contours are tested against the front surface, not painted over hidden limbs.
 for(const mesh of meshes){if(!mesh.strokeWidth||mesh.stroke==='none')continue;const matrix=multiplyMatrix(localViewport,mesh.matrix),vertices=mesh.vertices.map(v=>({...transformPoint(matrix,v.x,v.y),depth:v.depth})),radius=mesh.strokeWidth*Math.sqrt(Math.abs(matrix[0]*matrix[3]-matrix[1]*matrix[2]))/2,rgba=color(mesh.stroke),pick=references.push({actor:mesh.actor,part:mesh.part,joint:mesh.joint})-1;
  for(const edge of mesh.edges||[]){if(!edge.visible)continue;const [a,b]=edge.indices.map(i=>vertices[i]),dx=b.x-a.x,dy=b.y-a.y,length=dx*dx+dy*dy;if(length<1e-10)continue;const left=Math.max(0,Math.floor(Math.min(a.x,b.x)-radius)),right=Math.min(width-1,Math.ceil(Math.max(a.x,b.x)+radius)),top=Math.max(0,Math.floor(Math.min(a.y,b.y)-radius)),bottom=Math.min(height-1,Math.ceil(Math.max(a.y,b.y)+radius));budget.trianglePixels+=(right-left+1)*(bottom-top+1);if(budget.trianglePixels>maxTrianglePixels)throw RangeError('Actor depth exceeds its contour coverage budget.');for(let y=top;y<=bottom;y++)for(let x=left;x<=right;x++){const t=Math.max(0,Math.min(1,((x+.5-a.x)*dx+(y+.5-a.y)*dy)/length));if(Math.hypot(x+.5-a.x-dx*t,y+.5-a.y-dy*t)>radius)continue;write(y*width+x,a.depth+(b.depth-a.depth)*t+.02,(mesh.order??0)+.01,rgba,pick);}}
 }
 for(const c of vectors){const matrix=multiplyMatrix(localViewport,c.matrix),margin=c.strokeWidth*Math.max(Math.hypot(matrix[0],matrix[1]),Math.hypot(matrix[2],matrix[3]))/2+2,b=boundsOf(c.d,matrix,margin),left=Math.max(0,Math.floor(b.x0)),top=Math.max(0,Math.floor(b.y0)),right=Math.min(width,Math.ceil(b.x1)),bottom=Math.min(height,Math.ceil(b.y1)),w=right-left,h=bottom-top;if(w<=0||h<=0)continue;budget.vectorPixels+=w*h;if(budget.vectorPixels>maxVectorPixels)throw RangeError('Actor depth exceeds its vector composition budget.');scratch.setTransform(1,0,0,1,0,0);scratch.clearRect(left,top,w,h);paintCommand(scratch,c,localViewport);const rgba=scratch.getImageData(left,top,w,h).data,pick=references.push({...c.pick,command:c.id})-1;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const source=(y*w+x)*4;if(!rgba[source+3])continue;write((y+top)*width+x+left,c.depth,10000+pick,rgba,pick,source);}}
 scratch.putImageData(image,0,0);context.save();context.setTransform(1,0,0,1,0,0);context.globalAlpha=1;context.imageSmoothingEnabled=true;context.drawImage(pool.canvas,x0,y0,width/supersample,height/supersample);context.restore();
 return {tail,drawn:core.length,pixels,triangles:meshes.reduce((n,m)=>n+m.triangles.length,0),pick(x,y){const px=Math.floor((x-x0)*supersample),py=Math.floor((y-y0)*supersample);if(px<0||py<0||px>=width||py>=height)return null;const id=picks[py*width+px];return id<0?null:references[id];}};
}
