import {renderActorDepth,inspectActorDepthCapabilities,releaseActorDepth} from './canvas-depth.js';
import {assertDocument} from './schema.js';
import {evaluateDrawing} from './render-evaluation.js';
import {registerRenderInput} from './render-input.js';
import {identityMatrix,multiplyMatrix,invertMatrix,transformPoint,cameraMatrix} from './render-geometry.js';

export class CanvasCapabilityError extends Error{constructor(reasons){super('Canvas renderer cannot render this scene: '+reasons.map(r=>r.message).join(' '));this.name='CanvasCapabilityError';this.reasons=reasons;}}
const paths=new Map();
function path(d){if(paths.has(d))return paths.get(d);const value=new Path2D(d);if(paths.size>=1024)paths.delete(paths.keys().next().value);paths.set(d,value);return value;}
function colorWithAlpha(color,opacity=1){if(opacity===1)return color;let h=color.slice(1);if(h.length===3)h=[...h].map(x=>x+x).join('');return `rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},${opacity})`;}
function paint(context,material){if(material.type==='solid')return material.color;const gradient=context.createRadialGradient(material.cx,material.cy,0,material.cx,material.cy,material.rx);for(const [offset,color,opacity]of material.stops)gradient.addColorStop(Math.max(0,Math.min(1,offset)),colorWithAlpha(color,opacity));return gradient;}
function fillPath(context,d,material){if(material.type==='solid'){context.fillStyle=material.color;context.fill(path(d));return;}if(material.rx<=0||material.ry<=0)return;context.save();context.translate(material.cx,material.cy);context.scale(material.rx,material.ry);const normalized=new Path2D();normalized.addPath(path(d),new DOMMatrix([1/material.rx,0,0,1/material.ry,-material.cx/material.rx,-material.cy/material.ry]));context.fillStyle=paint(context,{...material,cx:0,cy:0,rx:1,ry:1});context.fill(normalized);context.restore();}
export function drawingViewport(drawing,width,height){const scale=Math.min(width/drawing.width,height/drawing.height);return [scale,0,0,scale,(width-drawing.width*scale)/2,(height-drawing.height*scale)/2];}

const depthDrawings=new WeakMap();
function paintCommand(context,command,viewport){if(!command.visible||command.opacity<=0||!command.d)return false;context.save();try{for(const clip of command.clips){context.setTransform(...multiplyMatrix(viewport,clip.matrix));context.clip(path(clip.d));}context.setTransform(...multiplyMatrix(viewport,command.matrix));context.globalAlpha=Math.max(0,Math.min(1,command.opacity));context.lineJoin='round';context.lineCap='round';context.setLineDash(command.strokeDash||[]);if(command.fill.type!=='solid'||command.fill.color!=='none')fillPath(context,command.d,command.fill);if(command.strokeWidth>0&&(command.stroke.type!=='solid'||command.stroke.color!=='none')){context.strokeStyle=paint(context,command.stroke);context.lineWidth=command.strokeWidth;context.stroke(path(command.d));}}finally{context.restore();}return true;}
export function renderCanvas(context,drawing,{clear=true,background,viewport=drawingViewport(drawing,context.canvas.width,context.canvas.height)}={}){
 const actorDepth=drawing.depthMode==='actor',capabilities=actorDepth?inspectActorDepthCapabilities(drawing):drawing.capabilities;if(!capabilities.supported)throw new CanvasCapabilityError(capabilities.unsupported);const passes=new Map(),budget={pixels:0,trianglePixels:0,vectorPixels:0};context.save();context.setTransform(...identityMatrix);if(clear)context.clearRect(0,0,context.canvas.width,context.canvas.height);if(background){context.fillStyle=background;context.fillRect(0,0,context.canvas.width,context.canvas.height);}let drawn=0;
 try{for(const unit of drawing.units){const pass=actorDepth&&unit.commands.some(c=>c.mesh)?renderActorDepth(context,drawing,unit,{viewport,paintCommand,budget}):null;if(pass){passes.set(unit.id,pass);drawn+=pass.drawn;}for(const command of pass?pass.tail:unit.commands)if(paintCommand(context,command,viewport))drawn++;}}finally{context.restore();}releaseActorDepth(context,new Set(passes.keys()));depthDrawings.set(context,{drawing,passes,viewport});return {drawn,pathCacheSize:paths.size,...(actorDepth?{depth:budget}: {})};
}

/** Input coordinates are evaluated drawing/viewBox coordinates, not pixels. */
export function pickDrawing(context,drawing,x,y){if(!Number.isFinite(x)||!Number.isFinite(y)||x<0||y<0||x>drawing.width||y>drawing.height)return null;const rendered=depthDrawings.get(context);if(drawing.depthMode==='actor'&&rendered?.drawing!==drawing)throw Error('Render this actor-depth drawing before picking it.');context.save();context.setTransform(...identityMatrix);try{for(let u=drawing.units.length-1;u>=0;u--){const unit=drawing.units[u],pass=rendered?.drawing===drawing?rendered.passes.get(unit.id):null,commands=pass?pass.tail:unit.commands;for(let i=commands.length-1;i>=0;i--){const command=commands[i];if(!command.pick||!command.visible||command.opacity<=.001)continue;let clipped=false;for(const clip of command.clips){const inverse=invertMatrix(clip.matrix);if(!inverse){clipped=true;break;}const p=transformPoint(inverse,x,y);if(!context.isPointInPath(path(clip.d),p.x,p.y)){clipped=true;break;}}if(clipped)continue;const inverse=invertMatrix(command.matrix);if(!inverse)continue;const p=transformPoint(inverse,x,y),filled=(command.fill.type!=='solid'||command.fill.color!=='none')&&context.isPointInPath(path(command.d),p.x,p.y);context.lineWidth=command.strokeWidth;context.lineCap='round';context.lineJoin='round';const stroked=command.strokeWidth>0&&(command.stroke.type!=='solid'||command.stroke.color!=='none')&&context.isPointInStroke(path(command.d),p.x,p.y);if(filled||stroked)return {...command.pick,command:command.id};}if(pass){const p=transformPoint(rendered.viewport,x,y),hit=pass.pick(p.x,p.y);if(hit)return hit;}}return null;}finally{context.restore();}}

export function mountCanvas(element,document,frame,options={}){
 assertDocument(document);const existing=typeof element.getContext==='function',canvas=existing?element:element.ownerDocument.createElement('canvas'),context=canvas.getContext('2d');if(!context)throw Error('A Canvas 2D context is required.');let currentFrame=frame,drawing=evaluateDrawing(document,frame,options),disposed=false,width=options.width||element.clientWidth||drawing.width,height=options.height||element.clientHeight||drawing.height,ratio=Math.min(2,Math.max(.25,options.pixelRatio??globalThis.devicePixelRatio??1));if(!drawing.capabilities.supported)throw new CanvasCapabilityError(drawing.capabilities.unsupported);canvas.setAttribute('role','img');canvas.setAttribute('aria-label',options.label||document.name);canvas.dataset.posecraftRenderer='canvas';if(!existing){canvas.style.width='100%';canvas.style.height='100%';element.append(canvas);}
 const resize=(w=width,h=height)=>{if(disposed)return;width=w;height=h;if(![w,h].every(n=>Number.isFinite(n)&&n>0)||w*ratio>4096||h*ratio>4096)throw RangeError('Canvas dimensions must fit a 4096 pixel backing surface.');canvas.width=Math.max(1,Math.round(w*ratio));canvas.height=Math.max(1,Math.round(h*ratio));renderCanvas(context,drawing,{background:options.background});};resize();
 const coordinate=(clientX,clientY)=>{const box=canvas.getBoundingClientRect(),local={x:(clientX-box.left)*width/box.width,y:(clientY-box.top)*height/box.height};return transformPoint(invertMatrix(drawingViewport(drawing,width,height)),local.x,local.y);};
 const unregister=registerRenderInput(canvas,{point(x,y){const p=coordinate(x,y),inverse=invertMatrix(cameraMatrix(options.camera??currentFrame.camera,document.bounds));return inverse?transformPoint(inverse,p.x,p.y):null;},hit(x,y){const p=coordinate(x,y);return pickDrawing(context,drawing,p.x,p.y);}});
 return {canvas,get drawing(){return drawing;},update(next){if(disposed)return;const evaluated=evaluateDrawing(document,next,options);renderCanvas(context,evaluated,{background:options.background});drawing=evaluated;currentFrame=next;},resize,pick(x,y){if(disposed)return null;const viewport=drawingViewport(drawing,width,height),inverse=invertMatrix(viewport),point=transformPoint(inverse,x,y);return pickDrawing(context,drawing,point.x,point.y);},dispose(){if(disposed)return;disposed=true;unregister();releaseActorDepth(context);depthDrawings.delete(context);context.clearRect(0,0,canvas.width,canvas.height);if(!existing)canvas.remove();}};
}
