import {constrainPose,forwardKinematics} from './index.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const hash=n=>{n=Math.imul(n^(n>>>16),0x45d9f3b);n=Math.imul(n^(n>>>16),0x45d9f3b);return ((n^(n>>>16))>>>0)/4294967295*2-1;};
function noise(t,seed){const i=Math.floor(t),u=t-i,s=u*u*(3-2*u);return hash(i+seed)*(1-s)+hash(i+1+seed)*s;}
export function validateMotionLayers(doc,check){
 if(doc.motionLayers===undefined)return;check(Array.isArray(doc.motionLayers)&&doc.motionLayers.length<=64,'motionLayers','Expected up to 64 additive motion layers.');const ids=new Set();
 for(const [i,l]of (Array.isArray(doc.motionLayers)?doc.motionLayers:[]).entries()){const p='motionLayers.'+i;check(l&&typeof l==='object'&&!Array.isArray(l)&&Object.keys(l).every(k=>['id','actor','joint','channel','type','amplitude','frequency','phase','seed','variable','range','enabled','clips'].includes(k)),p,'Unknown motion layer setting.');if(!l||typeof l!=='object')continue;const a=doc.actors.find(a=>a.id===l.actor),pack=doc.packs[a?.pack];check(typeof l.id==='string'&&/^[a-zA-Z][\w-]{0,63}$/.test(l.id)&&!ids.has(l.id),p+'.id','Expected unique layer ID.');ids.add(l.id);check(pack?.joints.some(j=>j.id===l.joint),p+'.joint','Missing actor joint.');check(['rotation','x','y','yaw','pitch','bend'].includes(l.channel)&&(['rotation','x','y'].includes(l.channel)||pack?.spatial),p+'.channel','Unsupported pose channel.');check(['sine','noise'].includes(l.type),p+'.type','Expected sine or smooth noise.');for(const [k,min,max]of [['amplitude',0,l.channel==='bend'?1:30],['frequency',.05,12],['phase',0,6.2832]])check(Number.isFinite(l[k])&&l[k]>=min&&l[k]<=max,p+'.'+k,'Layer setting outside range.');check(Number.isInteger(l.seed)&&l.seed>=0&&l.seed<=4294967295,p+'.seed','Expected uint32 seed.');if(l.enabled!==undefined)check(typeof l.enabled==='boolean',p+'.enabled','Expected boolean.');if(l.variable!==undefined){check(typeof doc.behaviorGraph?.variables?.[l.variable]==='number',p+'.variable','Expected numeric scene variable.');check(Array.isArray(l.range)&&l.range.length===2&&l.range.every(Number.isFinite)&&l.range[1]>l.range[0],p+'.range','Expected increasing variable range.');}if(l.clips!==undefined)check(Array.isArray(l.clips)&&l.clips.length<=64&&l.clips.every(c=>pack?.clips[c]),p+'.clips','Expected existing clips.');}
 if(doc.motionLayers?.length)check(doc.requiredFeatures?.includes('motion-layers'),'requiredFeatures','Declare motion-layers.');
}
/** Sampled from absolute scene time; no mutable oscillator state or frame-rate
 * noise. Constraints run after these layers so planted grips stay planted. */
export function applyMotionLayers(doc,frame,{disabledActors=new Set()}={}){
 if(!doc.motionLayers?.length)return frame;const time=frame.time;
 return {...frame,actors:frame.actors.map(f=>{if(disabledActors.has(f.id)||f.physics||f.recovery)return f;const actor=doc.actors.find(a=>a.id===f.id),pack=doc.packs[actor.pack],layers=doc.motionLayers.filter(l=>l.actor===f.id&&l.enabled!==false&&(!l.clips||l.clips.includes(f.clip)));if(!layers.length)return f;let pose={...f.pose};
  for(const l of layers){const strength=l.variable?clamp(((frame.behavior?.variables?.[l.variable]??doc.behaviorGraph.variables[l.variable])-l.range[0])/(l.range[1]-l.range[0]),0,1):1,t=time*l.frequency+l.phase/(Math.PI*2),wave=l.type==='sine'?Math.sin(t*Math.PI*2):noise(t,l.seed),key=l.joint+'.'+l.channel;pose[key]=(pose[key]??(l.channel==='rotation'?pack.joints.find(j=>j.id===l.joint).rotation:0))+wave*l.amplitude*strength;if(l.channel==='bend')pose[key]=clamp(pose[key],0,1);if(l.channel==='pitch')pose[key]=clamp(pose[key],-90,90);if(l.channel==='yaw')pose[key]=clamp(pose[key],-180,180);}
  pose=constrainPose(pack.joints,pose);return {...f,pose,world:forwardKinematics(pack.joints,pose)};
 })};
}
