import {solveContact} from './contacts.js';
import {forwardKinematics,constrainPose} from './index.js';
import {objectGrip} from './scene-objects.js';
import {nodeVisible} from './scene-graph.js';
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),mix=(a,b,t)=>a+(b-a)*t,rad=Math.PI/180;
const finite=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b;
const smooth=t=>{t=clamp(t,0,1);return t*t*(3-2*t);};
export function validatePropGames(doc,check){
 if(doc.objectGames===undefined)return;check(Array.isArray(doc.objectGames)&&doc.objectGames.length<=8,'objectGames','Expected up to eight catch games.');if(!Array.isArray(doc.objectGames))return;
 const used=new Set(),actors=new Set();for(const [i,g]of doc.objectGames.entries()){
  const p='objectGames.'+i;check(g&&typeof g==='object'&&!Array.isArray(g)&&Object.keys(g).every(k=>['id','type','object','participants','seed','variation','flightTime','pause','enabled'].includes(k)),p,'Unknown game setting.');if(!g||typeof g!=='object')continue;
  check(typeof g.id==='string'&&/^[a-zA-Z][\w-]{0,63}$/.test(g.id)&&!used.has(g.id),p+'.id','Expected unique game ID.');used.add(g.id);check(g.type==='catch',p+'.type','Expected catch game.');const o=doc.objects?.find(o=>o.id===g.object);check(o?.shape==='circle'&&o.mass>0&&!used.has('object:'+g.object),p+'.object','Each game needs its own dynamic ball.');used.add('object:'+g.object);
  check(Number.isInteger(g.seed)&&finite(g.seed,0,4294967295),p+'.seed','Expected uint32 seed.');for(const [k,a,b]of [['variation',0,300],['flightTime',.5,3],['pause',.2,8]])check(finite(g[k],a,b),p+'.'+k,'Game setting outside range.');if(g.enabled!==undefined)check(typeof g.enabled==='boolean',p+'.enabled','Expected boolean.');
  check(Array.isArray(g.participants)&&g.participants.length>=2&&g.participants.length<=8,p+'.participants','Expected two to eight participants.');for(const [n,m]of (Array.isArray(g.participants)?g.participants:[]).entries()){const q=p+'.participants.'+n,a=doc.actors.find(a=>a.id===m?.actor),pack=doc.packs[a?.pack];check(!!pack&&!actors.has(m?.actor),q+'.actor','Each participant must be an existing actor in one game.');if(!m||!pack)continue;actors.add(m.actor);check(Object.keys(m).every(k=>['actor','chain','bend','speed','skill','reaction','root','head','feet','crouch'].includes(k)),q,'Unknown participant setting.');const c=m.chain,upper=pack.joints.find(j=>j.id===c?.upper),lower=pack.joints.find(j=>j.id===c?.lower),end=pack.joints.find(j=>j.id===c?.end);check(upper&&lower?.parent===upper.id&&end?.parent===lower.id,q+'.chain','Expected connected upper/lower/end grip chain.');check([-1,1].includes(m.bend),q+'.bend','Expected bend side.');check(pack.joints.some(j=>j.id===m.root&&j.parent===null),q+'.root','Expected root joint.');if(m.head!==undefined)check(pack.joints.some(j=>j.id===m.head),q+'.head','Missing head joint.');if(m.feet!==undefined)check(Array.isArray(m.feet)&&m.feet.length===2&&m.feet.every(id=>pack.joints.some(j=>j.id===id)),q+'.feet','Expected two foot joints.');for(const [k,a,b]of [['speed',10,400],['skill',0,1],['reaction',0,1],['crouch',0,120]])check(finite(m[k],a,b),q+'.'+k,'Participant setting outside range.');}
 }
 check(doc.requiredFeatures?.includes('prop-games'),'requiredFeatures','Declare prop-games.');
}
export function predictIntercept(ball,gravity,targetY,{damping=.05,horizon=3,step=1/60}={}){
 let {x,y,vx,vy}=ball;for(let t=step;t<=horizon;t+=step){const before=y;vy+=gravity*step;const decay=Math.exp(-damping*step);vx*=decay;vy*=decay;x+=vx*step;y+=vy*step;if(vy>0&&before<=targetY&&y>=targetY)return {x:x-vx*step*(y-targetY)/(y-before),y:targetY,time:t-step*(y-targetY)/(y-before)};}return null;
}
const gameAvailable=(document,game,ball)=>game.enabled!==false&&ball?.enabled&&game.participants.every(p=>nodeVisible(document,document.actors.find(a=>a.id===p.actor)));
const sweptDistance=(a,b,p)=>{const dx=b.x-a.x,dy=b.y-a.y,t=clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1),0,1);return Math.hypot(a.x+dx*t-p.x,a.y+dy*t-p.y);};
/** Data-authored autonomous passing. Its grips use the same object commands as
 * manual handoffs; sensing/planning has a bounded update rate and no callbacks
 * or executable expressions are stored in the scene. */
export class PropGameRuntime {
 constructor(document,objects,{onEvent=()=>{}}={}){this.document=document;this.objects=objects;this.onEvent=onEvent;this.reset();}
 reset(){this.time=0;this.games=(this.document.objectGames||[]).map(g=>({id:g.id,seed:g.seed,phase:'prepare',at:0,turn:0,receiver:1,catches:0,misses:0,throws:0,notice:false,catchRoll:0,planAt:0,actors:g.participants.map(p=>{const a=this.document.actors.find(a=>a.id===p.actor);return {id:p.actor,x:a.transform.x,y:a.transform.y,vx:0,walk:0,crouch:0};})}));}
 snapshot(){return {version:1,time:this.time,games:structuredClone(this.games)};}
 restore(s){if(s?.version!==1||s.games.length!==this.games.length)throw Error('Incompatible prop game checkpoint.');this.time=s.time;this.games=structuredClone(s.games);}
 random(s){s.seed=(Math.imul(1664525,s.seed)+1013904223)>>>0;return s.seed/4294967296;}
 event(s,type,extra={}){this.onEvent({type,game:s.id,time:this.time,...extra});}
 phase(s,name){s.phase=name;s.at=this.time;}
 tick(dt,frame){if(!dt)return;this.time+=dt;for(const s of this.games){const g=this.document.objectGames.find(g=>g.id===s.id),ball=this.objects.bodies.find(o=>o.id===g.object);if(!gameAvailable(this.document,g,ball))continue;
  if(ball.owner){const owner=g.participants.findIndex(p=>p.actor===ball.owner.actor);if(owner<0){if(s.phase!=='interrupted')this.phase(s,'interrupted');continue;}if(owner!==s.turn||['flight','settle','retrieve','interrupted'].includes(s.phase)){s.turn=owner;s.receiver=(owner+1)%g.participants.length;this.phase(s,'celebrate');continue;}}
  if(s.phase==='interrupted'){if(!ball.owner)this.phase(s,'settle');else {const owner=g.participants.findIndex(p=>p.actor===ball.owner.actor);if(owner>=0){s.turn=owner;s.receiver=(owner+1)%g.participants.length;this.phase(s,'celebrate');}}continue;}
  const age=this.time-s.at,sender=g.participants[s.turn],receiver=g.participants[s.receiver],target=s.actors[s.receiver],source=s.actors[s.turn];for(const a of s.actors){a.vx=0;a.crouch*=Math.exp(-dt*9);}
  for(let i=0;i<s.actors.length;i++)if((s.phase==='prepare'||s.phase==='celebrate'||s.phase==='rise')||s.phase==='retrieve'&&i!==s.receiver){const home=this.document.actors.find(a=>a.id===s.actors[i].id).transform.x;this.move(s.actors[i],home,g.participants[i].speed*.55,dt,8);}
  if(s.phase==='prepare'){
   if(!ball.owner&&ball.ignoreActor===sender.actor&&this.objects.time<ball.ignoreUntil){this.phase(s,'settle');continue;}
   if(!ball.owner){const view=frame,grip=objectGrip(this.document,view,{actor:sender.actor,joint:sender.chain.end});if(grip&&Math.hypot(ball.x-grip.x,ball.y-grip.y)<ball.radius+8)this.objects.command({type:'attach',object:ball.id,actor:sender.actor,joint:sender.chain.end,maxDistance:ball.radius+8},view);else{this.phase(s,'settle');continue;}}
   if(age>=g.pause){const view=frame,grip=objectGrip(this.document,view,ball.owner);if(!grip){this.phase(s,'settle');continue;}const T=g.flightTime,dx=target.x-source.x,direction=Math.sign(dx)||1,landing={x:target.x-direction*18+(this.random(s)-.5)*2*g.variation,y:target.y-15},decay=ball.damping??.05,vx=(landing.x-grip.x)/T*(1+decay*T*.5),vy=(landing.y-grip.y)/T-this.objects.config.gravity*T*.5;
    if(!this.objects.command({type:'release',object:ball.id,actor:sender.actor,vx,vy},view)){this.phase(s,'interrupted');continue;}s.throws++;s.notice=false;s.catchRoll=this.random(s);s.estimate=(this.random(s)-.5)*(1-receiver.skill)*50;this.phase(s,'flight');this.event(s,'throw',{actor:sender.actor,object:ball.id});}
  }else if(s.phase==='flight'){
   if(age>=receiver.reaction){s.notice=true;if(this.time>=s.planAt){s.intercept=predictIntercept(ball,this.objects.config.gravity,target.y-10,{damping:ball.damping??.05});s.planAt=this.time+.1;}const goal=(s.intercept?.x??ball.x)+s.estimate;this.move(target,goal,receiver.speed,dt,ball.radius+25);const view=frame,grip=objectGrip(this.document,view,{actor:receiver.actor,joint:receiver.chain.end});if(grip&&s.catchRoll<=receiver.skill&&sweptDistance({x:ball.previousX,y:ball.previousY},ball,grip)<=ball.radius+5&&Math.hypot(ball.x-grip.x,ball.y-grip.y)<=ball.radius+12){if(this.objects.command({type:'attach',object:ball.id,actor:receiver.actor,joint:receiver.chain.end,maxDistance:ball.radius+12},view)){s.catches++;this.event(s,'catch',{actor:receiver.actor,object:ball.id});s.turn=s.receiver;s.receiver=(s.turn+1)%g.participants.length;this.phase(s,'celebrate');continue;}}}
   if(ball.y>target.y+45&&ball.vy>0||age>4){s.misses++;this.event(s,'miss',{actor:receiver.actor,object:ball.id});this.phase(s,'settle');}
  }else if(s.phase==='settle'){
   if(ball.owner){const ownerIndex=g.participants.findIndex(p=>p.actor===ball.owner.actor);if(ownerIndex<0){this.phase(s,'interrupted');continue;}s.turn=ownerIndex;s.receiver=(s.turn+1)%g.participants.length;this.phase(s,'celebrate');continue;}
   if(Math.hypot(ball.vx,ball.vy)<24&&ball.y>this.objects.config.floorY-ball.radius-5){s.receiver=s.actors.reduce((best,a,i)=>Math.abs(a.x-ball.x)<Math.abs(s.actors[best].x-ball.x)?i:best,0);this.phase(s,'retrieve');}
  }else if(s.phase==='retrieve'){
   const p=g.participants[s.receiver],a=s.actors[s.receiver],direction=Math.sign(ball.x-a.x)||1;this.move(a,ball.x-direction*12,p.speed*.7,dt,5);const distance=Math.abs(ball.x-a.x);a.crouch=p.crouch*smooth(1-distance/70);const view=frame,grip=objectGrip(this.document,view,{actor:p.actor,joint:p.chain.end});if(grip&&distance<35&&this.objects.command({type:'attach',object:ball.id,actor:p.actor,joint:p.chain.end,maxDistance:ball.radius+7},view)){s.turn=s.receiver;s.receiver=(s.turn+1)%g.participants.length;this.event(s,'retrieve',{actor:p.actor,object:ball.id});this.phase(s,'rise');}else if(age>12){this.event(s,'retrieval-blocked',{actor:p.actor,object:ball.id});this.phase(s,'settle');}
  }else if(['celebrate','rise'].includes(s.phase)&&age>.8)this.phase(s,'prepare');
 }}
 move(a,goal,speed,dt,stop){const dx=goal-a.x;if(Math.abs(dx)<=stop)return;const step=clamp(dx,-speed*dt,speed*dt),next=clamp(a.x+step,35,this.document.bounds.width-35);let blocked=this.games.some(g=>g.actors.some(other=>other!==a&&Math.abs(next-other.x)<125&&Math.abs(next-other.x)<Math.abs(a.x-other.x)));for(const p of this.document.props||[])if(p.collider.enabled&&nodeVisible(this.document,p)&&a.y>p.y-p.collider.height/2-60&&a.y<p.y+p.collider.height/2&&Math.abs(next-p.x)<p.collider.width/2+18)blocked=true;if(!blocked){a.vx=(next-a.x)/dt;a.x=next;a.walk+=Math.abs(step)/22;}}
 apply(frame,{disabledActors=new Set()}={}){if(!this.games.length)return frame;const actors=frame.actors.map(f=>({...f,pose:{...f.pose},inputs:{...f.inputs}}));for(const s of this.games){const g=this.document.objectGames.find(g=>g.id===s.id),ball=this.objects.bodies.find(o=>o.id===g.object);if(!gameAvailable(this.document,g,ball)||s.phase==='interrupted')continue;for(let i=0;i<g.participants.length;i++){
   const p=g.participants[i],a=s.actors[i],actor=this.document.actors.find(a=>a.id===p.actor),pack=this.document.packs[actor.pack],f=actors.find(a=>a.id===p.actor);if(!f||f.physics||f.recovery||disabledActors.has(f.id))continue;f.placement={...actor.transform,x:a.x,y:a.y};const pose=f.pose,age=this.time-s.at,side=Math.sign(s.actors[(i+1)%s.actors.length].x-a.x)||1;
   pose[p.root+'.y']=(pose[p.root+'.y']||0)+a.crouch/actor.transform.scale;const walking=Math.abs(a.vx)>1?1:0;if(p.feet)for(const [n,j]of p.feet.entries()){pose[j+'.rotation']=(pose[j+'.rotation']||0)+Math.sin(a.walk+(n?Math.PI:0))*18*walking;pose[j+'.y']=(pose[j+'.y']||0)-Math.max(0,Math.sin(a.walk+(n?Math.PI:0)))*5*walking;}
   if(p.head){pose[p.head+'.yaw']=clamp((ball.x-a.x)/8,-40,40);pose[p.head+'.pitch']=clamp((a.y-25-ball.y)/6,-20,20);}
   let target={x:a.x+side*55,y:a.y+24};if(i===s.turn&&s.phase==='prepare'){const t=smooth(age/g.pause),wind=Math.sin(t*Math.PI);target={x:a.x+side*(55-75*wind),y:a.y+24-50*wind};}
   if(i===s.receiver&&(['retrieve','flight'].includes(s.phase))&&(s.phase==='retrieve'||s.notice))target={x:ball.x,y:ball.y};
   const placement=f.placement,theta=-placement.rotation*rad,dx=(target.x-placement.x)/placement.scale,dy=(target.y-placement.y)/placement.scale,result=solveContact(pack,pose,p.chain,{x:dx*Math.cos(theta)-dy*Math.sin(theta),y:dx*Math.sin(theta)+dy*Math.cos(theta)},{bend:p.bend,keepOrientation:false});f.pose=constrainPose(pack.joints,result.pose);f.world=forwardKinematics(pack.joints,f.pose);const emotion=s.phase==='celebrate'?'happy':s.phase==='settle'?'sad':s.phase==='flight'?'focused':'neutral';if(pack.inputs.emotion?.options.includes(emotion))f.inputs.emotion=emotion;f.activity=s.phase;f.objectContactError=result.error*placement.scale;
  }}return {...frame,actors,objectGames:this.games.map(s=>({id:s.id,phase:s.phase,catches:s.catches,misses:s.misses,throws:s.throws}))};}
}
