import {assertDocument} from './schema.js';
import {SceneController,STEP} from './scene.js';
import {DocumentStore} from './commands.js';
import {forwardKinematics,sampleClip,wrapAngle} from './index.js';
import {poseDefaults,spatialKinematics,spatialChannels} from './spatial.js';
const rad=Math.PI/180,finite=(v,a,b)=>Number.isFinite(v)&&v>=a&&v<=b,id=/^[a-zA-Z][\w-]{0,63}$/;
export const BAKE_LIMITS=Object.freeze({duration:8,samples:961,scalarSamples:250000,events:10000,keys:50000,fps:[15,24,30,60,120]});
const abort=signal=>{if(signal?.aborted){const error=new Error('Motion bake cancelled.');error.name='AbortError';throw error;}},yieldTask=()=>new Promise(resolve=>setTimeout(resolve,0));
function validate(document,options){
 const actor=document.actors.find(a=>a.id===options.actor);if(!actor)throw Error('Choose an existing actor to bake.');const pack=document.packs[actor.pack];if(!pack.physics)throw Error('The selected actor has no physical rig.');
 const start=options.start??0,duration=options.duration??2,fps=options.fps??30,clipId=options.clipId??'baked-motion',position=options.maxPositionError??.5,angle=options.maxAngleError??.5;
 if(!finite(start,0,180)||!finite(duration,.1,8)||start+duration>180||!BAKE_LIMITS.fps.includes(fps)||typeof clipId!=='string'||!id.test(clipId)||pack.clips[clipId]||!finite(position,.01,5)||!finite(angle,.01,5))throw Error('Bake needs a new clip ID, start/end within 180s, duration 0.1..8s, FPS 15/24/30/60/120 and tolerances 0.01..5.');
 const startTick=Math.round(start/STEP),ticks=Math.round(duration/STEP);if(startTick+ticks>21600)throw Error('Rounded bake interval exceeds 180 seconds.');if((ticks+1)*pack.joints.length*(pack.spatial?8:3)>BAKE_LIMITS.scalarSamples)throw Error('Bake sample budget exceeded. Shorten the interval or choose a smaller rig.');
 for(const[field,label]of [['ensemble','ensemble choreography'],['fluid','bottle fluid'],['objects','shared objects'],['objectGames','prop games'],['behaviorGraph','live decision graphs'],['actorBehaviors','actor decision graphs'],['poseBindings','live placement bindings'],['motionLayers','motion layers'],['interactions','pointer interactions'],['scroll','scroll bindings']])if(document[field]&&(Array.isArray(document[field])?document[field].length:true))throw Error(`Motion baking does not yet support scenes with ${label}. Use a separate physical study scene.`);
 if(document.contacts?.some(c=>c.actor!==actor.id&&c.target.type==='joint'&&c.target.actor===actor.id))throw Error('Another actor depends on the selected actor through a contact. Bake that dependency separately first.');
 const events=options.events??[];if(!Array.isArray(events)||events.length>BAKE_LIMITS.events)throw Error('Bake replay needs at most 10000 events.');for(const[e,event]of events.entries()){
  if(!event||!finite(event.time,0,180)||e&&event.time<events[e-1].time||!['input','behavior','interaction','acceleration','walk'].includes(event.type))throw Error('Bake replay accepts ordered input, behavior, interaction, acceleration and walk events only.');
  const fields={input:['actor','name','value'],behavior:['actor','value'],interaction:['actor','interaction','strength'],acceleration:['ax','ay'],walk:['actor','x']}[event.type];if(Object.keys(event).some(k=>!['time','type',...fields].includes(k)))throw Error('Unsupported field in bake replay event.');
 }
 return {actor,pack,startTick,ticks,start:startTick*STEP,duration:ticks*STEP,fps,clipId,position,angle,events:structuredClone(events)};
}
function applyEvent(c,e){if(e.type==='input')c.setInput(e.actor,e.name,e.value);else if(e.type==='behavior')c.setBehavior(e.actor,e.value);else if(e.type==='interaction')c.interact(e.actor,e.interaction,e.strength);else if(e.type==='walk')c.walkTo(e.actor,e.x);else c.setAcceleration(e.ax,e.ay);}
function poseFromFrame(pack,frame){
 const pose={...poseDefaults(pack),...frame.pose};
 if(pack.spatial){if(frame.physics){const root=pack.joints.find(j=>j.parent===null),w=frame.world[root.id];pose[root.id+'.x']=w.x-root.x;pose[root.id+'.y']=w.y-root.y;}return pose;}
 // Planar physical world positions include solver separation and root movement.
 // Convert each position to its parent's local coordinates, not just the root.
 for(const j of pack.joints){const w=frame.world[j.id],parent=frame.world[j.parent]||{x:0,y:0,rotation:0},r=-parent.rotation*rad,dx=w.x-parent.x,dy=w.y-parent.y;pose[j.id+'.x']=dx*Math.cos(r)-dy*Math.sin(r)-j.x;pose[j.id+'.y']=dx*Math.sin(r)+dy*Math.cos(r)-j.y;pose[j.id+'.rotation']=wrapAngle(w.rotation-parent.rotation);}
 return pose;
}
const evaluatedWorld=(pack,pose)=>pack.spatial?spatialKinematics(pack,pose):forwardKinematics(pack.joints,pose);
function discrepancy(pack,actor,actual,pose,limits){const world=evaluatedWorld(pack,pose);let position=0,angle=0,normalized=0;
 for(const j of pack.joints){const a=actual.world[j.id],b=world[j.id];position=Math.max(position,Math.hypot(a.x-b.x,a.y-b.y,(a.z||0)-(b.z||0))*actor.transform.scale);if(a.m){const trace=a.m.reduce((sum,v,i)=>sum+v*b.m[i],0);angle=Math.max(angle,Math.acos(Math.max(-1,Math.min(1,(trace-1)/2)))/rad);const ax=a.x+a.m[0]*j.length,ay=a.y+a.m[3]*j.length,az=a.z+a.m[6]*j.length,bx=b.x+b.m[0]*j.length,by=b.y+b.m[3]*j.length,bz=b.z+b.m[6]*j.length;position=Math.max(position,Math.hypot(ax-bx,ay-by,az-bz)*actor.transform.scale);}else{angle=Math.max(angle,Math.abs(wrapAngle(a.rotation-b.rotation)));position=Math.max(position,Math.hypot(a.endX-b.endX,a.endY-b.endY)*actor.transform.scale);}}
 for(const[key,value]of Object.entries(actual.pose)){const property=key.split('.')[1],tolerance=['opacity','bend'].includes(property)?.002:property==='z'?limits.position/actor.transform.scale:limits.angle;if(['opacity','bend','z','yaw','pitch'].includes(property))normalized=Math.max(normalized,Math.abs(property==='yaw'?wrapAngle(value-pose[key]):value-pose[key])/tolerance);}
 return {position,angle,normalized:Math.max(normalized,position/limits.position,angle/limits.angle)};
}
function makeClip(samples,indices,duration){const tracks={};for(const key of Object.keys(samples[0].pose)){const values=indices.map(i=>[i*STEP,samples[i].pose[key],'linear']);tracks[key]=values.every(v=>Math.abs(v[1]-values[0][1])<1e-12)?[values[0]]:values;}return {duration,loop:false,tracks};}
/** Capture fixed-step physical motion into an isolated editable pack. No source mutation. */
export async function bakeSceneMotion(document,options={}){
 if(!options||typeof options!=='object'||Array.isArray(options)||options.onProgress!==undefined&&typeof options.onProgress!=='function')throw Error('Expected bake options and an optional progress callback.');
 abort(options.signal);assertDocument(document);const spec=validate(document,options),source=structuredClone(document),samples=[],controller=new SceneController(source,{checkpoints:false}),progress=(phase,value)=>options.onProgress?.({phase,progress:Math.max(0,Math.min(1,value))});let inputJSON=null,inputs=null,physical=false,cursor=0;
 controller.replaying=true;
 try{progress('simulate',0);for(let tick=0;tick<=spec.startTick+spec.ticks;tick++){
  abort(options.signal);while(cursor<spec.events.length&&spec.events[cursor].time<=controller.time+1e-9){applyEvent(controller,spec.events[cursor++]);if(cursor%128===0){await yieldTask();abort(options.signal);}}
  if(tick>=spec.startTick){const frame=controller.frame().actors.find(a=>a.id===spec.actor.id);if(frame.placement&&JSON.stringify(frame.placement)!==JSON.stringify(spec.actor.transform))throw Error('Dynamic actor placement is not supported by this bake.');const text=JSON.stringify(frame.inputs);if(inputJSON!==null&&inputJSON!==text)throw Error('Actor inputs change inside this interval. Disable automatic facial responses or choose a constant-appearance interval before baking.');inputJSON=text;inputs={...frame.inputs};const pose=poseFromFrame(spec.pack,frame);for(const[key,value]of Object.entries(pose)){const property=key.split('.')[1],range=spatialChannels[property];if(!Number.isFinite(value)||['x','y'].includes(property)&&Math.abs(value)>1000||range&&(value<range.min||value>range.max))throw Error(`Captured ${key} exceeds editable clip limits.`);}samples.push({pose,world:evaluatedWorld(spec.pack,pose)});physical||=!!frame.physics||!!frame.recovery;}
  if(tick<spec.startTick+spec.ticks)controller.step(STEP);if(tick%64===0){progress('simulate',tick/(spec.startTick+spec.ticks));await yieldTask();}
 }}finally{controller.dispose();}
 if(!physical)throw Error('No physical or recovery motion occurred in the selected interval.');abort(options.signal);progress('refine',0);
 const stride=120/spec.fps,selected=new Set([0,spec.ticks]);for(let i=0;i<spec.ticks;i+=stride)selected.add(i);const initial=[...selected].sort((a,b)=>a-b),pending=initial.slice(1).map((b,i)=>[initial[i],b]);let checked=0;
 while(pending.length){abort(options.signal);const[a,b]=pending.pop();if(b-a<2)continue;const clip=makeClip(samples,[a,b],spec.duration);let worst=-1,error=1+1e-9;for(let i=a+1;i<b;i++){const d=discrepancy(spec.pack,spec.actor,samples[i],sampleClip(clip,i*STEP),spec);if(d.normalized>error){error=d.normalized;worst=i;}}if(worst>=0){selected.add(worst);pending.push([a,worst],[worst,b]);}if(++checked%32===0){progress('refine',selected.size/samples.length);await yieldTask();}}
 const indices=[...selected].sort((a,b)=>a-b),clip=makeClip(samples,indices,spec.duration),keys=Object.values(clip.tracks).reduce((sum,track)=>sum+track.length,0);if(keys>BAKE_LIMITS.keys)throw Error('Baked keys exceed the output budget. Shorten the interval.');
 const pack=structuredClone(spec.pack),widenedLimits=[];for(const joint of pack.joints){const values=samples.map(s=>s.pose[joint.id+'.rotation']),seam=values.some((v,i)=>i&&Math.abs(v-values[i-1])>180),min=seam?-180:Math.min(joint.min,...values),max=seam?180:Math.max(joint.max,...values);if(min<joint.min||max>joint.max)widenedLimits.push(joint.id);joint.min=min;joint.max=max;}
 delete pack.physics;delete pack.reaction;delete pack.expressions;pack.clips[spec.clipId]=clip;pack.states[spec.clipId]={clip:spec.clipId,transitions:[]};pack.initial=spec.clipId;
 const base=(spec.actor.id+'-baked').slice(0,57);let packId=base,n=1;while(Object.hasOwn(source.packs,packId))packId=base+'-'+n++;
 const actor={...structuredClone(spec.actor),pack:packId,inputs,behavior:{...spec.actor.behavior,mode:'animated',autoFace:false,autoRecover:false}},removedContacts=(source.contacts||[]).filter(c=>c.actor===actor.id).map(c=>c.id),commands=[{op:'set',path:['packs',packId],value:pack},{op:'set',path:['actors',source.actors.findIndex(a=>a.id===actor.id)],value:actor}];if(removedContacts.length)commands.push({op:'set',path:['contacts'],value:source.contacts.filter(c=>c.actor!==actor.id)});
 progress('validate',0);const result=new DocumentStore(source).transact(commands,source.revision);let maxPositionError=0,maxAngleError=0,maxNormalizedError=0;
 for(let i=0;i<samples.length;i++){abort(options.signal);const d=discrepancy(pack,actor,samples[i],sampleClip(clip,i*STEP),spec);maxPositionError=Math.max(maxPositionError,d.position);maxAngleError=Math.max(maxAngleError,d.angle);maxNormalizedError=Math.max(maxNormalizedError,d.normalized);if(i%64===0){progress('validate',i/(samples.length-1));await yieldTask();}}
 if(maxNormalizedError>1.000001)throw Error('Baked motion failed its fixed-step error bound.');progress('validate',1);
 return {document:result,commands,diagnostics:{actor:actor.id,clipId:spec.clipId,packId,start:spec.start,duration:spec.duration,fps:spec.fps,samples:samples.length,keys,maxPositionError,maxAngleError,tolerance:{position:spec.position,angle:spec.angle},widenedLimits,removedContacts,remainingPhysicalActors:result.actors.filter(a=>(a.behavior?.mode||'animated')!=='animated').map(a=>a.id),notes:['Error bounds were measured at every recorded 120 Hz sample, including joint endpoints; they do not bound unsampled motion between ticks.','Only the selected actor is rebased to the new clip clock. Other actors and lighting retain their original scene timing.','The source pack remains in the document. A private pack contains the baked clip and any widened joint limits.','This captures one local solver run; it does not guarantee identical physics across engine versions.']}};
}
