export interface SceneLighting {shadowLength?:number;celThickness?:number;celIntensity?:number;type?:'directional'|'point';receiver?:'corner'|'floor';pointX?:number;pointY?:number;pointHeight?:number;range?:number;motion?:'none'|'orbit'|'flicker';motionRadius?:number;motionSpeed?:number;flicker?:number;showSource?:boolean;shading?:'gradient'|'cel';enabled?:boolean;angle?:number;elevation?:number;intensity?:number;ambient?:number;color?:string;shadowColor?:string;softness?:number;floorY?:number;wallY?:number;floorShadow?:number;wallShadow?:number;reflection?:number;gloss?:number}
export interface Joint { id:string; parent:string|null; x:number; y:number; length:number; rotation:number; min:number; max:number }
export interface Camera {x:number;y:number;zoom:number;rotation:number;width:number;height:number}
export type Keyframe = [number, number, ('linear'|'smooth'|'step')?];
export interface Clip { duration:number; loop:boolean; tracks:Record<string,Keyframe[]> }
export type Input = {type:'boolean'; default:boolean}|{type:'number';default:number;min:number;max:number}|{type:'string';default:string;options:string[]};
export interface SpatialPart {depth?:number;order?:number;center?:[number,number];thickness?:number;axis?:'x'|'y';facing?:'front'|'back';mask?:string;surface?:{x:number;width:number;depth:number};morph?:{channel:string;target:string}}
export interface Part {opacityChannel?:string; spatial?:SpatialPart; id:string; joint:string; d:string; fill:string; channel?:string; transform?:string; stroke?:string; strokeWidth?:number; variantInput?:string; variants?:Record<string,{d?:string;transform?:string;visible?:boolean}>;showWhen?:{input:string;equals:string|number|boolean} }
export interface CharacterPack { spatial?:boolean; name:string; joints:Joint[]; parts:Part[]; clips:Record<string,Clip>; inputs:Record<string,Input>; initial:string; states:Record<string,{clip:string;transitions?:{to:string;duration:number;when:{input:string;equals:string|number|boolean}}[]}>; reaction?:{joint:string;strength:number;stiffness:number;damping:number}; physics?:PhysicsProfile; expressions?:Record<string,Record<string,number>>; appearanceDefaults?:Record<string,string>; description?:string; provenance?:Record<string,string> }
export interface BehaviorSettings {mode?:'animated'|'floating'|'ragdoll'|'protective';resistance?:number;gravity?:number;bounce?:number;strategy?:'auto'|'brace'|'protect'|'curl';autoFace?:boolean;autoRecover?:boolean}
export interface PhysicsProfile {root:string;head:string;bodies:Record<string,{width:number;height:number;x:number;y:number;density:number}>;responses:Record<string,Record<string,number>>}
export interface Actor {groundY?:number;layer?:'background'|'characters'|'foreground';unlit?:boolean;id:string;name:string;pack:string;transform:{x:number;y:number;scale:number;rotation:number};appearance?:Record<string,string>;inputs?:Record<string,string|number|boolean>;behavior?:BehaviorSettings}
export interface SceneProp {id:string;name:string;x:number;y:number;width:number;height:number;rotation:number;fill:string;collider:{enabled:boolean;width:number;height:number;x:number;y:number;friction:number;bounce:number}}
export interface SceneDocument {ensemble?:{type:'campfire';seed:number;members:string[];sky:string}; lighting?:SceneLighting; schemaVersion:1;kind:'scene';id:string;name:string;revision:number;bounds:{width:number;height:number};requiredFeatures?:string[];packs:Record<string,CharacterPack>;actors:Actor[];props?:SceneProp[] }
export const capabilities: {schemaVersion:1;renderer:string;features:readonly string[];unavailable:readonly string[]};
export function validateDocument(doc:unknown):{valid:boolean;errors:{path:string;message:string}[]};
export function assertDocument(doc:unknown):SceneDocument;
