import {sampleEmitters} from './emitters.js';
import {nodeVisible} from './scene-graph.js';
import {surfaceStopValues,sampleLighting,partLighting,actorAnchor,wallProjection,lightingConfig,surfaceStops,surfaceRamp,surfaceFocus,shadowProjection,contactShadow,lightingDefinitions} from './lighting.js';
import {spatialParts} from './spatial.js';
import {appearance,evaluateActorDrawing,evaluatedObjects} from './render-shared.js';
import {sceneDepth,sortSceneDepth,scenePartGroups} from './scene-depth.js';
let spatialInstance=0;
import { assertDocument } from './schema.js';
const escape = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;' })[c]);
const transform = w => `translate(${w.x} ${w.y}) rotate(${w.rotation})`;
const spatialBone=j=>`matrix(${j.m[0]} ${j.m[3]} ${j.m[1]} ${j.m[4]} ${j.x} ${j.y})`;
const placement = t => `${transform(t)} scale(${t.scale})`;
const meshGradient=(b,f)=>`gradientUnits="userSpaceOnUse" cx="${b.minX+(b.maxX-b.minX)*f.cx}" cy="${b.minY+(b.maxY-b.minY)*f.cy}" r="${Math.max(b.maxX-b.minX,b.maxY-b.minY)*.85}"`;
const orderChildren=(parent,nodes)=>{let next=parent.firstElementChild;for(const node of nodes){if(node===next)next=next.nextElementSibling;else parent.insertBefore(node,next);}};
const sameDepth=(a,b)=>a!==null&&b!==null&&Math.abs(a-b)<.001;
const objectSVG=object=>`<g data-scene-unit="object:${object.id}" data-object="${object.id}" transform="${transform(object)}" display="${object.visible?'inline':'none'}"><title>${escape(object.name||object.id)}</title>${object.shape==='circle'?`<circle r="${object.radius}"`: `<rect x="${-object.width/2}" y="${-object.height/2}" width="${object.width}" height="${object.height}" rx="2"`} fill="${escape(object.fill)}" stroke="#454451" stroke-width="1.5"/></g>`;
const fluidDescendants=new WeakMap();
function fluidEffects(document,frame,actor,prefix){
 const config=document.fluid;if(config?.contents!==actor.id)return '';
 const fluid=frame.fluid?.actor===actor.id?frame.fluid:null,id=prefix+'-'+actor.id+'-liquid-effects',boundary='M'+config.boundary.map(p=>`${p.x} ${p.y}`).join('L')+'Z';
 return `<defs><clipPath id="${id}" clipPathUnits="userSpaceOnUse"><path d="${boundary}"/></clipPath></defs><g data-fluid-effects="" data-wave-amplitude="${fluid?.waveAmplitude||0}" visibility="${fluid?'visible':'hidden'}" clip-path="url(#${id})" pointer-events="none" aria-hidden="true"><path data-fluid-foam="" d="${escape(fluid?.foamPath||'')}" fill="none" stroke="#e1fff2" stroke-width="2" stroke-linecap="round" opacity=".85"/><path data-fluid-splashes="" d="${escape(fluid?.splashPath||'')}" fill="#d4fff4" stroke="#86d6e2" stroke-width=".65" opacity=".9"/></g>`;
}
function fluidView(frame,actor,pack,spatial){
 const fluid=frame.fluid?.actor===actor.id?frame.fluid:null;if(!fluid)return null;
 let descendants=new Set();const ship=fluid.ship;
 if(ship&&spatial){let cached=fluidDescendants.get(pack);if(!cached){cached=new Map();fluidDescendants.set(pack,cached);}descendants=cached.get(ship.joint);if(!descendants){descendants=new Set([ship.joint]);for(let changed=true;changed;){changed=false;for(const j of pack.joints)if(descendants.has(j.parent)&&!descendants.has(j.id)){descendants.add(j.id);changed=true;}}cached.set(ship.joint,descendants);}}
 const pivot=ship&&spatial?.world[ship.joint],scale=pivot?`translate(${pivot.x} ${pivot.y}) scale(${ship.scale}) translate(${-pivot.x} ${-pivot.y}) `:'';
 return {paths:fluid.paths||{},hidden:new Set(fluid.hidden||[]),joint:(joint,base)=>descendants.has(joint)?scale+base:base,part:(part,base)=>Object.hasOwn(fluid.paths||{},part.id)?'matrix(1 0 0 1 0 0)':descendants.has(part.joint)?scale+base:base};
}
function cameraTransform(c,bounds){
 if(![c.x,c.y,c.rotation,c.zoom,c.width,c.height].every(Number.isFinite)||c.zoom<=0||c.width<=0||c.height<=0)throw new Error('Invalid camera.');
 return `translate(${c.width/2} ${c.height/2}) scale(${c.width/bounds.width*c.zoom}) rotate(${-c.rotation}) translate(${-c.x} ${-c.y})`;
}
function limitArc(joint, rotation) {
  const r = 18, angle = deg => deg * Math.PI / 180;
  const from = angle(joint.min - rotation), to = angle(joint.max - rotation), span = joint.max - joint.min;
  if (span >= 359) return 'M18 0 A18 18 0 1 0 -18 0 A18 18 0 1 0 18 0';
  return `M0 0 L${r*Math.cos(from)} ${r*Math.sin(from)} A${r} ${r} 0 ${span>180?1:0} 1 ${r*Math.cos(to)} ${r*Math.sin(to)} Z`;
}
function physicsOverlay(frame,document){return frame.actors.filter(a=>a.physics&&(!document||nodeVisible(document,document.actors.find(node=>node.id===a.id)))).map(a=>{
 const p=a.physics,c=p.center,n=value=>Number(value).toFixed(2);
 return p.contacts.map(v=>`<circle cx="${n(v.x)}" cy="${n(v.y)}" r="3" fill="#df7951"/>`).join('')+`<circle cx="${n(c.x)}" cy="${n(c.y)}" r="3" fill="#418ea1"/><path d="M${n(c.x)} ${n(c.y)}l${n(p.velocity.x*.15)} ${n(p.velocity.y*.15)}" stroke="#418ea1" stroke-width="1.5"/>`;
}).join('');}
const particlePath=kind=>kind==='flame'?'M0 0C-.56-.11-.61-.39-.14-1C-.22-.69.64-.47.28-.03Q.11.07 0 0Z':kind==='smoke'?'M-1 0C-1.4-.6-.6-1.2 0-.8C.5-1.2 1.3-.5 1 0C1.2.7.3 1-.2.6C-.8 1-1.5.4-1 0Z':'M-1 0A1 1 0 1 0 1 0A1 1 0 1 0-1 0Z';
const particleTransform=p=>`translate(${p.x} ${p.y}) rotate(${p.rotation}) scale(${p.scaleX} ${p.scaleY})`;
function emitterPlacement(document,frame,emitter){const actor=emitter.actor&&document.actors.find(a=>a.id===emitter.actor);return actor?placement(frame.actors.find(a=>a.id===actor.id)?.placement||actor.transform):'';}
function emitterVisible(document,emitter){const actor=emitter.actor&&document.actors.find(a=>a.id===emitter.actor);return emitter.enabled&&nodeVisible(document,emitter)&&(!emitter.actor||actor&&nodeVisible(document,actor));}
function emitterSVG(document,frame,sample){const {emitter,particles}=sample,interactive=emitter.type==='flame'&&emitter.actor&&document.interactions?.some(b=>b.actor===emitter.actor&&b.gesture==='click'&&!b.joint&&!b.part);return `<g data-emitter="${emitter.id}" data-emitter-type="${emitter.type}" transform="${emitterPlacement(document,frame,emitter)}" visibility="${emitterVisible(document,emitter)?'visible':'hidden'}" display="${emitterVisible(document,emitter)?'inline':'none'}" ${interactive?`data-emitter-actor="${emitter.actor}"`:''} pointer-events="${interactive?'visiblePainted':'none'}" aria-hidden="true">${particles.map(p=>`<path data-particle="${p.slot}" d="${particlePath(p.kind)}" transform="${particleTransform(p)}" fill="${p.color}" opacity="${p.opacity}"/>`).join('')}</g>`;}
export function renderSVG(document, frame, { label = document.name, bones = false, limits = false, selectedActor, selectedJoint,physicsDebug=false,colliders=false,selectedProp,camera=frame.camera } = {}) {
  assertDocument(document);
  const prefix='pc-view-'+(++spatialInstance),light=sampleLighting(lightingConfig(document,frame),frame.effectsTime??frame.localTime??frame.time),emitterSamples=sampleEmitters(document,frame.effectsTime??frame.localTime??frame.time,frame);
  const effects=light.enabled?`<rect data-light-wash="" width="${document.bounds.width}" height="${document.bounds.height}" fill="url(#${prefix}-wash)" pointer-events="none"/>`+document.actors.filter(a=>!a.unlit).map(actor=>{
   const evaluated=frame.actors.find(a=>a.id===actor.id),receiver={...light,floorY:evaluated.groundY??actor.groundY??light.floorY};
   const p=placement(evaluated.placement||actor.transform),href=`#${prefix}-${actor.id}-artwork`,contact=contactShadow(actor,document.packs[actor.pack],evaluated,receiver),anchor=actorAnchor(actor,evaluated),wall=wallProjection(receiver,anchor);
   return `<g data-light-effects="${actor.id}" visibility="${nodeVisible(document,actor)?'visible':'hidden'}" display="${nodeVisible(document,actor)?'inline':'none'}" pointer-events="none" aria-hidden="true">${(receiver.wallShadow||light.emitter)&&receiver.receiver==='corner'?`<g data-wall-strength="" clip-path="url(#${prefix}-wall)" opacity="${receiver.wallShadow}"><g data-wall-shadow="" visibility="${wall?'visible':'hidden'}" transform="${wall||''}" filter="url(#${prefix}-shadow)"><use data-light-placement="" href="${href}" transform="${p}"/></g></g>`:''}${receiver.floorShadow||light.emitter?`<g data-floor-strength="" clip-path="url(#${prefix}-floor)" opacity="${receiver.floorShadow}"><g filter="url(#${prefix}-shadow)"><g data-floor-shadow="" transform="${shadowProjection(receiver,anchor)}"><use data-light-placement="" href="${href}" transform="${p}"/></g></g></g><ellipse data-contact="${actor.id}" cx="${contact.cx}" cy="${receiver.floorY}" rx="${contact.rx}" ry="5" fill="${receiver.shadowColor}" opacity="${contact.opacity}" filter="url(#${prefix}-shadow)"/>`:''}${receiver.reflection?`<g data-reflection="" mask="url(#${prefix}-mirror-mask)" opacity="${receiver.reflection}"><g transform="translate(0 ${2*light.floorY}) scale(1 -1)"><use data-light-placement="" href="${href}" transform="${p}"/></g></g>`:''}</g>`;
  }).join(''):'';
  const renderProp=p=>{const c=p.collider;return `<g data-prop="${p.id}" visibility="${nodeVisible(document,p)?'visible':'hidden'}" display="${nodeVisible(document,p)?'inline':'none'}" transform="${transform(p)}"><title>${escape(p.name)}</title><rect x="${-p.width/2}" y="${-p.height/2}" width="${p.width}" height="${p.height}" rx="3" fill="${escape(p.fill)}" stroke="${p.id===selectedProp?'#7351bd':'#797481'}" stroke-width="${p.id===selectedProp?2:1}"/>${colliders||physicsDebug||p.id===selectedProp?`<rect data-collider="${p.id}" x="${c.x-c.width/2}" y="${c.y-c.height/2}" width="${c.width}" height="${c.height}" fill="none" stroke="${c.enabled?'#df7951':'#999999'}" stroke-width="1.5" stroke-dasharray="5 3" pointer-events="none"/>`:''}</g>`;};
  const attachments=new Map(),actorDepths=new Map();
  const renderActor=actor=>{
    const pack = document.packs[actor.pack], evaluated = frame.actors.find(a => a.id === actor.id);
    if (!evaluated) throw new Error(`Missing evaluated actor ${actor.id}`);
    const {spatial,fragments}=evaluateActorDrawing(pack,actor,evaluated),depth=sceneDepth(actor.depth,actor,evaluated,spatial),groups=scenePartGroups(pack);actorDepths.set(actor.id,depth);
    const fluid=fluidView(frame,actor,pack,spatial);
    const masks=spatial?[...new Set(pack.parts.map(p=>p.spatial?.mask).filter(Boolean))]:[];
    const gradients=light.enabled&&!actor.unlit?pack.parts.map(part=>{const paint=appearance(part,actor,evaluated),surfaceLight=partLighting(light,actor,evaluated,part,spatial),ramp=surfaceRamp(paint.fill,surfaceLight);if(!ramp)return '';const focus=surfaceFocus(surfaceLight,(evaluated.placement||actor.transform).rotation,`${spatial?.parts.get(part.id).transform||transform(evaluated.world[part.joint])} ${paint.transform}`);return `<radialGradient data-surface="${part.id}" data-shading="${light.shading}" id="${prefix}-${actor.id}-${part.id}-surface" ${spatial?.parts.get(part.id).mesh?meshGradient(spatial.parts.get(part.id).mesh.bounds,focus):`cx="${focus.cx}" cy="${focus.cy}" r=".85"`}>${surfaceStops(ramp,surfaceLight)}</radialGradient>`;}).join(''):'';
    const definitions=gradients+masks.map(id=>{const p=pack.parts.find(p=>p.id===id),paint=appearance(p,actor,evaluated);return `<clipPath id="${prefix}-${actor.id}-${id}" clipPathUnits="userSpaceOnUse"><path data-mask-part="${id}" d="${escape(spatial.parts.get(id).d??paint.d)}" transform="${spatial.parts.get(id).transform} ${escape(paint.transform)}"/></clipPath>`;}).join('');
    const fragmentMasks=fragments.filter(f=>f.view?.clipD).map(f=>`<clipPath id="${prefix}-${actor.id}-${f.id}-segment" clipPathUnits="userSpaceOnUse"><path data-fragment-mask="${f.id}" d="${escape(f.view.clipD)}" transform="${f.view.transform}"/></clipPath>`).join('');
    const slot=({id,part,view})=>{const paint=appearance(part,actor,evaluated,pack,spatial),mask=part.spatial?.mask;
      // Joined base triangles share pixel edges. Expanding their strokes would paint
      // skin over neighboring clothing; only material overlays get seam overlap.
      const markup=`<g id="${prefix}-${actor.id}-slot-${id}" data-slot="${id}" ${view?.clipD?`clip-path="url(#${prefix}-${actor.id}-${id}-segment)"`:''}><g ${mask?`clip-path="url(#${prefix}-${actor.id}-${mask})"`:''}><g data-joint="${part.joint}" data-fragment="${id}" data-selected="${actor.id===selectedActor&&part.joint===selectedJoint}" transform="${fluid?.part(part,view?.transform||transform(evaluated.world[part.joint]))??(view?.transform||transform(evaluated.world[part.joint]))}"><path data-source-part="${part.id}" data-fragment-path="${id}" opacity="${(part.opacityChannel?evaluated.pose[part.opacityChannel]??1:1)*(view?.opacity??1)*paint.opacity}" ${!view?.kind||view.kind==='part'||view.kind==='upper'||view.primary?`data-part="${part.id}"`:''} d="${escape(fluid?.paths[part.id]??view?.d??paint.d)}" fill="${view?.kind==='mesh-edge'?'none':light.enabled&&!actor.unlit&&surfaceRamp(paint.fill,light)?`url(#${prefix}-${actor.id}-${part.id}-surface)`:escape(paint.fill)}" stroke="${view?.kind==='mesh-face'?(light.enabled&&!actor.unlit&&surfaceRamp(paint.fill,light)?`url(#${prefix}-${actor.id}-${part.id}-surface)`:escape(paint.fill)):escape(part.stroke||'none')}" stroke-width="${view?.kind==='mesh-face'?(part.spatial?.surfaceOf ? .8 : 0):part.strokeWidth||0}" ${view?.kind==='mesh-face'?'shape-rendering="crispEdges"':''} stroke-linejoin="round" stroke-linecap="round" transform="${escape(fluid&&Object.hasOwn(fluid.paths,part.id)?'':paint.transform)}" visibility="${paint.visible&&view?.visible!==false&&!fluid?.hidden.has(part.id)?'visible':'hidden'}"/></g></g></g>`;
      if(view?.kind?.startsWith('mesh-')&&!mask&&!view.clipD&&!fluid){const path=markup.slice(markup.indexOf('<path '),markup.indexOf('/>')+2);return path.replace('<path ',`<path id="${prefix}-${actor.id}-slot-${id}" data-slot="${id}" data-joint="${part.joint}" data-fragment="${id}" data-mesh-path="" data-selected="${actor.id===selectedActor&&part.joint===selectedJoint}" `);}
      return markup;
    };
    const detached=new Set();attachments.set(actor.id,groups.map(group=>{const value=sceneDepth(group.depth,actor,evaluated,spatial),fused=sameDepth(value,depth),members=fragments.filter(f=>group.parts.includes(f.part.id));if(!fused)members.forEach(f=>detached.add(f.id));return {id:`part:${actor.id}:${group.id}`,depth:value,markup:`<g data-scene-unit="part:${actor.id}:${group.id}" data-scene-actor="${actor.id}" data-scene-group="${group.id}" transform="${placement(evaluated.placement||actor.transform)}" display="${!fused&&nodeVisible(document,actor)?'inline':'none'}">${members.map(f=>`<use data-fragment-use="${f.id}" data-scene-part="${f.part.id}" data-scene-joint="${f.part.joint}" href="#${prefix}-${actor.id}-slot-${f.id}"/>`).join('')}</g>`};}));
    return `<g data-actor="${actor.id}" visibility="${nodeVisible(document,actor)?'visible':'hidden'}" display="${nodeVisible(document,actor)?'inline':'none'}" data-activity="${escape(evaluated.activity||'')}" data-response="${escape(evaluated.response||'calm')}" data-emotion="${escape(evaluated.inputs?.emotion||'neutral')}" transform="${placement(evaluated.placement||actor.transform)}"><defs>${definitions}${fragmentMasks}<g data-detached-slots="">${fragments.filter(f=>detached.has(f.id)).map(slot).join('')}</g></defs><g data-artwork="" id="${prefix}-${actor.id}-artwork">${fragments.filter(f=>!detached.has(f.id)).map(slot).join('')}</g>${fluidEffects(document,frame,actor,prefix)}${bones ? pack.joints.map(j => `<g data-bone="${j.id}" transform="${fluid?.joint(j.id,spatial?spatialBone(spatial.world[j.id]):transform(evaluated.world[j.id]))??(spatial?spatialBone(spatial.world[j.id]):transform(evaluated.world[j.id]))}">${limits && j.id===selectedJoint && actor.id===selectedActor ? `<path data-limit="${j.id}" d="${limitArc(j,evaluated.pose[j.id+'.rotation'])}" fill="#9c71ff22" stroke="#7955be" stroke-width=".6" pointer-events="none"/>`:''}<path d="M0 0H${j.length || 12}" stroke="#7751bd" stroke-width="1.1" pointer-events="none"/><circle r="3" fill="${j.id===selectedJoint&&actor.id===selectedActor?'#7253bc':'#fff'}" stroke="#7253bc" stroke-width="1"/><circle data-handle="${j.id}" cx="${j.length || 12}" r="2.2" fill="#7253bc" stroke="#fff" stroke-width=".6"/></g>`).join('') : ''}</g>`;

  };
  const actorMarkup=new Map(document.actors.map(actor=>[actor.id,renderActor(actor)]));
  const renderLayer=layer=>{const entries=[];for(const actor of document.actors.filter(a=>(a.layer||'characters')===layer)){entries.push({depth:actorDepths.get(actor.id),markup:`<g data-scene-unit="actor:${actor.id}">${actorMarkup.get(actor.id)}${emitterSamples.filter(s=>s.emitter.actor===actor.id).map(s=>emitterSVG(document,frame,s)).join('')}</g>`},...attachments.get(actor.id));}for(const prop of (document.props||[]).filter(p=>(p.layer||'background')===layer))entries.push({depth:prop.depth?.value??null,markup:`<g data-scene-unit="prop:${prop.id}">${renderProp(prop)}</g>`});if(layer==='characters')for(const object of evaluatedObjects(document,frame))entries.push({depth:object.depth??object.y,markup:objectSVG(object)});return `<g data-scene-layer="${layer}">${sortSceneDepth(entries).map(e=>e.markup).join('')}${emitterSamples.filter(s=>!s.emitter.actor&&(s.emitter.layer||'characters')===layer).map(s=>emitterSVG(document,frame,s)).join('')}</g>`;};
  return `<svg data-scene-time="${frame.time}" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${camera?.width||document.bounds.width} ${camera?.height||document.bounds.height}" role="img" aria-label="${escape(label)}" width="100%" height="100%">${camera?`<g data-camera="" transform="${cameraTransform(camera,document.bounds)}">`:''}${lightingDefinitions(light,document.bounds,prefix)}${renderLayer('background')}${effects}${renderLayer('characters')}${renderLayer('foreground')}${light.enabled&&light.type==='point'&&(light.showSource||light.emitter&&document.lighting?.showSource)?`<g visibility="${light.showSource?'visible':'hidden'}" data-light-source="" transform="translate(${light.pointX} ${light.pointY})" pointer-events="none"><circle r="10" fill="${light.color}" stroke="#fff"/><circle r="18" fill="none" stroke="${light.color}" stroke-dasharray="2 4"/></g>`:''}${physicsDebug?`<g data-physics-debug="" pointer-events="none">${physicsOverlay(frame,document)}</g>`:''}${camera?'</g>':''}</svg>`;
}
export function mountSVG(element, document, frame, options) {
  element.innerHTML = renderSVG(document, frame, options);
  let previous;const baseLight=lightingConfig(document,frame);
  const emitterBindings=new Map((document.emitters||[]).map(e=>{const node=element.querySelector(`[data-emitter="${e.id}"]`);return [e.id,{node,particles:node?[...node.querySelectorAll('[data-particle]')]:[]}];}));
  const layerBindings=[...element.querySelectorAll('[data-scene-layer]')].map(node=>{const layer=node.dataset.sceneLayer,keys=document.actors.filter(a=>(a.layer||'characters')===layer).flatMap(a=>['actor:'+a.id,...scenePartGroups(document.packs[a.pack]).map(g=>`part:${a.id}:${g.id}`)]).concat((document.props||[]).filter(p=>(p.layer||'background')===layer).map(p=>'prop:'+p.id),layer==='characters'?(document.objects||[]).map(p=>'object:'+p.id):[]),nodes=new Map([...node.children].filter(n=>n.dataset.sceneUnit).map(n=>[n.dataset.sceneUnit,n]));return {node,units:new Map(keys.map(key=>[key,nodes.get(key)]))};});
  const propBindings=(document.props||[]).map(p=>({prop:p,node:element.querySelector(`[data-prop="${p.id}"]`)}));
  const objectBindings=new Map((document.objects||[]).map(p=>[p.id,element.querySelector(`[data-object="${p.id}"]`)]));
  const attribute=(node,key,value)=>{if(node.getAttribute(key)!==String(value))node.setAttribute(key,value);};
  const bindings = document.actors.map(actor => {
    const root = element.querySelector(`[data-actor="${actor.id}"]`),effects=element.querySelector(`[data-light-effects="${actor.id}"]`);
    const pack=document.packs[actor.pack],groups=scenePartGroups(pack).map(group=>({...group,node:element.querySelector(`[data-scene-unit="part:${actor.id}:${group.id}"]`)}));
    return { actor, root, effects,groups,detachedSlots:root.querySelector('[data-detached-slots]'),fragmentMasks:[...root.querySelectorAll('[data-fragment-mask]')],masks:[...root.querySelectorAll('[data-mask-part]')],fluidEffects:root.querySelector('[data-fluid-effects]'),fluidFoam:root.querySelector('[data-fluid-foam]'),fluidSplashes:root.querySelector('[data-fluid-splashes]'),partsById:new Map(document.packs[actor.pack].parts.map(p=>[p.id,p])),lightPlacements:effects?[...effects.querySelectorAll('[data-light-placement]')]:[],contact:effects?.querySelector('[data-contact]'),floor:effects?.querySelector('[data-floor-shadow]'),wall:effects?.querySelector('[data-wall-shadow]'),surfaces:[...root.querySelectorAll("[data-surface]")].map(node=>({node,part:document.packs[actor.pack].parts.find(p=>p.id===node.dataset.surface)})), artwork:root.querySelector('[data-artwork]'),slots:new Map([...root.querySelectorAll('[data-slot]')].map(node=>[node.dataset.slot,node])), joints: [...root.querySelectorAll('[data-joint], [data-bone]')], paths:[...root.querySelectorAll('[data-fragment-path]')].map(node=>({node,id:node.dataset.fragmentPath,part:pack.parts.find(p=>p.id===(node.dataset.sourcePart||node.dataset.part))})), limits:[...root.querySelectorAll('[data-limit]')] };
  });
  return {
    update(next) {
      if(next===previous)return;previous=next;attribute(element.firstElementChild,'data-scene-time',next.time);const light=sampleLighting(document.lighting?.emitter?lightingConfig(document,next):baseLight,next.effectsTime??next.localTime??next.time);
      for(const {emitter,particles} of sampleEmitters(document,next.effectsTime??next.localTime??next.time,next)){const binding=emitterBindings.get(emitter.id);if(!binding?.node)continue;attribute(binding.node,'transform',emitterPlacement(document,next,emitter));attribute(binding.node,'visibility',emitterVisible(document,emitter)?'visible':'hidden');attribute(binding.node,'display',emitterVisible(document,emitter)?'inline':'none');for(let i=0;i<binding.particles.length;i++){const p=particles[i],node=binding.particles[i];attribute(node,'opacity',p?.opacity||0);if(p){attribute(node,'transform',particleTransform(p));attribute(node,'fill',p.color);}}}
      for(const {prop,node} of propBindings){attribute(node,'visibility',nodeVisible(document,prop)?'visible':'hidden');attribute(node,'display',nodeVisible(document,prop)?'inline':'none');}
      if(next.camera){const node=element.querySelector('[data-camera]');if(node)attribute(node,'transform',cameraTransform(next.camera,document.bounds));}
      const depths=new Map(propBindings.map(({prop})=>['prop:'+prop.id,prop.depth?.value??null]));
      for(const object of evaluatedObjects(document,next)){const node=objectBindings.get(object.id);if(!node)continue;depths.set('object:'+object.id,object.depth??object.y);attribute(node,'transform',transform(object));attribute(node,'display',object.visible?'inline':'none');const shape=node.lastElementChild;attribute(shape,'fill',object.fill);if(object.shape==='circle')attribute(shape,'r',object.radius);else for(const [key,value]of Object.entries({x:-object.width/2,y:-object.height/2,width:object.width,height:object.height}))attribute(shape,key,value);}
      for (const b of bindings) {
        const visible=nodeVisible(document,b.actor);attribute(b.root,'visibility',visible?'visible':'hidden');attribute(b.root,'display',visible?'inline':'none');if(b.effects){attribute(b.effects,'visibility',visible?'visible':'hidden');attribute(b.effects,'display',visible?'inline':'none');}
        const evaluated = next.actors.find(a => a.id === b.actor.id),pack=document.packs[b.actor.pack],spatial=spatialParts(pack,evaluated),fluid=fluidView(next,b.actor,pack,spatial);
        const depth=sceneDepth(b.actor.depth,b.actor,evaluated,spatial),detached=new Set();depths.set('actor:'+b.actor.id,depth);
        for(const group of b.groups){const value=sceneDepth(group.depth,b.actor,evaluated,spatial),fused=sameDepth(depth,value);depths.set(`part:${b.actor.id}:${group.id}`,value);attribute(group.node,'display',visible&&!fused?'inline':'none');attribute(group.node,'transform',placement(evaluated.placement||b.actor.transform));if(!fused)for(const {id,part}of b.paths)if(group.parts.includes(part.id))detached.add(id);}
        attribute(b.root,'transform',placement(evaluated.placement||b.actor.transform));
        if(b.effects){for(const [selector,opacity] of [['[data-floor-strength]',light.floorShadow],['[data-wall-strength]',light.wallShadow]]){const strength=b.effects.querySelector(selector);if(strength)attribute(strength,'opacity',opacity);}const receiver={...light,floorY:evaluated.groundY??b.actor.groundY??light.floorY},anchor=actorAnchor(b.actor,evaluated),wall=wallProjection(receiver,anchor);if(b.floor)attribute(b.floor,'transform',shadowProjection(receiver,anchor));if(b.wall){attribute(b.wall,'transform',wall||'');attribute(b.wall,'visibility',wall?'visible':'hidden');}for(const node of b.lightPlacements)attribute(node,'transform',placement(evaluated.placement||b.actor.transform));const node=b.contact;if(node){const contact=contactShadow(b.actor,pack,evaluated,receiver);attribute(node,'cy',receiver.floorY);for(const [key,value] of Object.entries(contact))attribute(node,key,value);}
         for(const {node,part} of b.surfaces){const surfaceLight=partLighting(light,b.actor,evaluated,part,spatial),focus=surfaceFocus(surfaceLight,(evaluated.placement||b.actor.transform).rotation,`${spatial?.parts.get(part.id).transform||transform(evaluated.world[part.joint])} ${appearance(part,b.actor,evaluated).transform}`);const bounds=spatial?.parts.get(part.id).mesh?.bounds;if(bounds){attribute(node,'cx',bounds.minX+(bounds.maxX-bounds.minX)*focus.cx);attribute(node,'cy',bounds.minY+(bounds.maxY-bounds.minY)*focus.cy);attribute(node,'r',Math.max(bounds.maxX-bounds.minX,bounds.maxY-bounds.minY)*.85);}else{attribute(node,'cx',focus.cx);attribute(node,'cy',focus.cy);}const key=surfaceLight.intensity+':'+surfaceLight.celThickness;if(node._lightIntensity!==key){node._lightIntensity=key;const ramp=surfaceRamp(appearance(part,b.actor,evaluated).fill,surfaceLight);surfaceStopValues(ramp,surfaceLight).forEach(([offset,color],i)=>{attribute(node.children[i],'offset',offset);attribute(node.children[i],'stop-color',color);});}}
        }
        attribute(b.root,'data-activity',evaluated.activity||'');attribute(b.root,'data-recovery',evaluated.recovery?.phase||'none');attribute(b.root,'data-response',evaluated.response||'calm');attribute(b.root,'data-emotion',evaluated.inputs?.emotion||'neutral');attribute(b.root,'data-motion-mode',evaluated.physics?.mode||'animated');
        for (const node of b.joints) {
          if(node.hasAttribute('data-mesh-path'))continue;
          const partId=node.firstElementChild?.dataset.sourcePart||node.firstElementChild?.dataset.part,part=b.partsById.get(partId),view=spatial?.fragments?.get(node.dataset.fragment)||spatial?.parts.get(partId),joint=node.dataset.joint||node.dataset.bone,base=view?.transform||(spatial&&node.dataset.bone?spatialBone(spatial.world[node.dataset.bone]):transform(evaluated.world[joint]));attribute(node,'transform',part?(fluid?.part(part,base)??base):(fluid?.joint(joint,base)??base));
        }
        const ids=spatial?.fragmentOrder||spatial?.order||pack.parts.map(p=>p.id),order=ids.join('|')+';'+[...detached].sort().join('|');
        if(order!==b.order){orderChildren(b.artwork,ids.filter(id=>!detached.has(id)).map(id=>b.slots.get(id)));orderChildren(b.detachedSlots,ids.filter(id=>detached.has(id)).map(id=>b.slots.get(id)));for(const group of b.groups){const uses=new Map([...group.node.children].map(n=>[n.dataset.fragmentUse,n]));orderChildren(group.node,ids.filter(id=>uses.has(id)).map(id=>uses.get(id)));}b.order=order;}
        if(spatial){
          for(const mask of b.masks){const part=b.partsById.get(mask.dataset.maskPart),view=spatial.parts.get(part.id),paint=appearance(part,b.actor,evaluated);attribute(mask,'transform',view.transform+' '+paint.transform);attribute(mask,'d',view.d??paint.d);}
          for(const mask of b.fragmentMasks){const view=spatial.fragments.get(mask.dataset.fragmentMask);attribute(mask,'d',view.clipD);attribute(mask,'transform',view.transform);}
        }
        const inputKey=JSON.stringify(evaluated.inputs);
        if(spatial||fluid||b.hadFluid||inputKey!==b.inputKey){b.inputKey=inputKey;for (const {part,node,id} of b.paths) if (spatial||fluid||b.hadFluid||part.variants || part.showWhen) { const paint=appearance(part,b.actor,evaluated,pack,spatial),view=spatial?.fragments?.get(id)||spatial?.parts.get(part.id);attribute(node,'d',fluid?.paths[part.id]??view?.d??paint.d);attribute(node,'transform',fluid&&Object.hasOwn(fluid.paths,part.id)?'':paint.transform);attribute(node,'visibility',paint.visible&&view?.visible!==false&&!fluid?.hidden.has(part.id)?'visible':'hidden'); }}
        if(b.fluidEffects){const liquid=next.fluid?.actor===b.actor.id?next.fluid:null;attribute(b.fluidEffects,'visibility',liquid?'visible':'hidden');attribute(b.fluidEffects,'data-wave-amplitude',liquid?.waveAmplitude||0);attribute(b.fluidFoam,'d',liquid?.foamPath||'');attribute(b.fluidSplashes,'d',liquid?.splashPath||'');}
        b.hadFluid=!!fluid;
        for(const {part,node} of b.paths)if(part.opacityChannel||part.spatial?.facingFade||part.spatial?.surfaceOf)attribute(node,'opacity',(part.opacityChannel?evaluated.pose[part.opacityChannel]??1:1)*(spatial?.parts.get(part.id).opacity??1)*appearance(part,b.actor,evaluated,pack,spatial).opacity);
        for (const node of b.limits) { const j=document.packs[b.actor.pack].joints.find(j=>j.id===node.dataset.limit);node.setAttribute('d',limitArc(j,evaluated.pose[j.id+'.rotation'])); }
      }
      for(const layer of layerBindings){const entries=[...layer.units].map(([id,node])=>({id,node,depth:depths.get(id)??null})),ordered=sortSceneDepth(entries),key=ordered.map(e=>e.id).join('|');if(key!==layer.order){const tail=[...layer.node.children].find(n=>!n.dataset.sceneUnit);for(const entry of ordered)layer.node.insertBefore(entry.node,tail||null);layer.order=key;}}
      const source=element.querySelector('[data-light-source]');if(source){attribute(source,'transform',`translate(${light.pointX} ${light.pointY})`);attribute(source,'visibility',light.enabled&&light.showSource?'visible':'hidden');}const wash=element.querySelector('[data-light-wash-gradient]');if(wash&&light.type==='point'){attribute(wash,'cx',light.pointX/document.bounds.width);attribute(wash,'cy',light.pointY/document.bounds.height);attribute(wash.firstElementChild,'stop-opacity',light.intensity*.2);}
      const overlay=element.querySelector('[data-physics-debug]');if(overlay)overlay.innerHTML=physicsOverlay(next,document);
    },
    dispose() { element.replaceChildren(); }
  };
}
