import type {Rig3D,Pose3D,Placement3D,World3D,Vector3D,Quaternion3D} from './rig-3d.js';
import type {GripFrame3D} from './grip-3d.js';
import type {BenchActionRoles,BenchActionContact} from './bench-action-3d.js';
import type {WorkoutProject3D} from './workout-project-3d.js';
export type WorkoutAction3D='pullup'|'bench'|'rest'|'drink';
export interface WorkoutEvent3D {sequence:number;type:'actor.action.completed'|'actor.action.failed'|'actor.command.cancelled';actor:'atlas';request:string;action:WorkoutAction3D;time:number;error?:string}
export interface WorkoutStats3D {fatigue:number;dehydration:number;sets:number;reps:number;successes:number;failures:number;mechanicalFailures:number;drinks:number}
export interface WorkoutSnapshot3D {activity:WorkoutAction3D|'walk'|'stopped';target:WorkoutAction3D|null;stats:WorkoutStats3D;events:WorkoutEvent3D[];lastOutcome:null|{action:WorkoutAction3D;type:'mechanical-invalid'|'exercise-failure'|'success'|'cancelled';error?:string;reps?:number};stopped:boolean;queued:null|{action:WorkoutAction3D;request:string};request:string|null;time:number}
export interface WorkoutFrame3D {face:Record<'blink'|'strain'|'happy'|'tired'|'surprise'|'breath',number>;time:number;activityTime:number;duration:number;phase:string;rep:number|null;effort:number;pose:Pose3D;placement:Placement3D;world:World3D;contacts:BenchActionContact[];diagnostics:BenchActionContact[];valid:boolean;support:{seat:boolean;feet:Vector3D[]};bar:{position:Vector3D;rotation:Quaternion3D;scale:number;length:number};bottle:{position:Vector3D;rotation:Quaternion3D;visible:boolean;owner?:'atlas'|null};workout:WorkoutSnapshot3D;[key:string]:unknown}
export interface Workout3D {readonly duration:number;readonly beats:Array<{id:string;label:string;start:number;end:number}>;sample(time:number):WorkoutFrame3D;snapshot():WorkoutSnapshot3D;describe():{actors:Array<{id:'atlas';actions:WorkoutAction3D[]}>;anchors:string[];variables:Record<string,{min:number;max:number}>};setVariable(name:'fatigue'|'dehydration',value:number):void;request(action:WorkoutAction3D,options?:{request?:string;target?:'bench'|'pullup'|'bottle'}):string;cancel(request:string):void;interrupt(time?:number):{supported:true};reset():WorkoutFrame3D}
export function createWorkout3D(options:{rig:Rig3D;roles:BenchActionRoles;grips?:Partial<Record<'left'|'right',GripFrame3D>>;project:WorkoutProject3D}):Workout3D;
